### ISSUE TITLE
Select fields values not visible

### ISSUE THREAD

**Issue by vmanthos** [elegantthemes/Divi-Beta#10]
### Problem:

The values of select fields are not visible in the builder or any module settings. I can click on the field and select a value, but the actual value is not visible, when the select field is not active.

The problem seems to be the:
`body.wp-admin select {
    height: 1.9em;
}`

### Steps To Reproduce:
1. Open builder or module settings
2. The select fields are too narrow and the vales not visible

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Linux Mint

**Browser**: Chrome 49.0.2623.87 (64-bit)

**Screen Resolution**: 1920x1080
![edit page divi wordpress](https://cloud.githubusercontent.com/assets/193660/13911829/8adf8352-ef3e-11e5-93dc-4cc1aa9c9168.png)

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by ThierryA** [comment]
Hi @vmanthos, could you kindly advise which version of WordPress your are using?

I cannot reproduce the issue and can't see `body.wp-admin select { height: 1.9em; }` set on the admin select. Could you take a print screen of your browser inspector where you see this CSS line too?

Thanks,

**Comment by vmanthos** [comment]
I checked it again and found out that the piklist plugin, I have installed, is "injecting" the css selector. This was not happening with Divi 2.6.4.4 though.

![desctop screenshot](https://cloud.githubusercontent.com/assets/193660/13922790/94c11488-ef86-11e5-827b-1fd272531ef1.png)

**Comment by ThierryA** [comment]
@vmanthos plugins should not set global styling but should rather have it prefixed, especially `body.wp-admin select` such selectors which affects all the admin selects.

@timayhelen would you like me to add more specificity or ignore?

**Comment by vmanthos** [comment]
I'm with you, but the question is why wasn't this happening on Divi 2.6.4.4? Maybe removed specific selectors in the beta?

**Comment by ThierryA** [comment]
I just tried with the current version and it happens too, the only select which would not be affected is `#et_pb_select_category` because the ID overrides `body.wp-admin select`.

**Comment by timayhelen** [comment]
@ThierryA sure let's add more specificity here.
