### ISSUE TITLE
Uncaught Error: Minified exception occurred

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1001]
While testing builder sync on our SiteGround hosting account, the following error occurred during VB sync:

![screen shot 2017-02-22 at 3 07 55 pm](https://cloud.githubusercontent.com/assets/3333028/23237096/c0432d6e-f910-11e6-8ba2-ceb6c6d7b6eb.png)

Here are the steps I took:

1. Open up an existing page in the VB.
2. Open the same page in the BB to initiate builder sync. 
3. Create a split testing the BB.
4. Switch to the VB and let it sync. 
5. On-focus the browser window and open up a different ap. After a heartbeat or two, the error appeared.

**Comment by timayhelen** [comment]
note, this can currently be replicated by editing the following page in the BB, and then opening the same page in ta new tab in the VB:

http://elegantthemessiteground.com/wp-admin/post.php?post=1102&action=edit

One weird thing I notice is that, in the processes of switching between the VB and BB, even when no edits are made, browser backups are initiated by WP in the BB. So even just by opening the BB and VB, once you refresh the page you will get a browser backup notification even though nothing was changed. Something is being changed in the process of syncing nothing.

**Comment by fikrirasyid** [comment]
@timayhelen @Jronk I've checked this issue and it appears that this ticket is basically https://github.com/elegantthemes/Divi-Beta/issues/1007 but happens on minified file. @lots0logs has submitted a fix for it https://github.com/elegantthemes/submodule-builder/pull/1757 which I have checked and reviewed at https://github.com/elegantthemes/submodule-builder/pull/1757#pullrequestreview-23434690. Take a look at the following:

![1001-divi-beta](https://cloud.githubusercontent.com/assets/916442/23255952/10ac8ebe-f9f0-11e6-89c2-bb83a7565350.jpg)

It's pretty much the same. I successfully replicated the issue on the localhost as well. To do so, on submodule-builder's `master`,  run `grunt zip` on `/Divi` dir (Note: the compressing part takes quite sometime). It'll overwrite bundle.js with the one used for the zip file. To replicate the issue, try the following:

1. Create new page, load a layout consist of two section > row > column > any module 
2. Publish the page
3. Open the VB on new window. Open dev tool > console
4. Activate split testing. Set the first section as subject and the second section as goal
5. Once the split test done being configured, switch window to VB and click anywhere to force focus which triggers the force check. As the incoming heartbeat arrives, you'll see the error displayed on elegantthemes/Divi-Beta#1007 appears

Here's how the issue looks like on my local site:

![screen shot 2017-02-23 at 5 26 06 pm](https://cloud.githubusercontent.com/assets/916442/23256026/5ab65b48-f9f0-11e6-8aff-c5e3c04207dd.png)

To make sure that https://github.com/elegantthemes/Divi-Beta/issues/1007 branch fixes this ticket's issue, switch submodule-builder to https://github.com/elegantthemes/submodule-builder/pull/1757 (`1007-dont-dispatch-buildr-actions-from-within-componentDidUpdate`) then run `grunt zip` again on `/Divi` dir. you'll see that the issue disappears.

***

With that being said, there is still one issue left on this ticket which was mentioned by @timayhelen:

>  in the processes of switching between the VB and BB, even when no edits are made, browser backups are initiated by WP in the BB. So even just by opening the BB and VB, once you refresh the page you will get a browser backup notification even though nothing was changed. Something is being changed in the process of syncing nothing.

I'll fix this aspect of this issue on this ticket. I have a feeling that this is related to https://github.com/elegantthemes/Divi-Beta/issues/1006 tho.

**Comment by Jronk** [comment]
I moved the "one issue left" from this issue to its own issue: https://github.com/elegantthemes/Divi-Beta/issues/1009
