### ISSUE TITLE
Uncaught TypeError: Cannot read property '_onClick' of undefined

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1005]
I received this error while testing Split Testing and builder sync. All I did was:

1. Create a new page.
2. Enable the Divi Builder.
3. Load the Homepage Basic layout.
4. Publish the page. 
5. Enable Split testing and select the Slider as your subject and the Call To Action module as your goal. 
6. Open the VB in a new tab.

and the following error occurred in the VB:

![screen shot 2017-02-22 at 4 14 11 pm](https://cloud.githubusercontent.com/assets/3333028/23239110/2031c812-f91a-11e6-9871-ec448fa04023.png)

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1759

**Comment by lots0logs** [comment]
@timayhelen I'm not able to reproduce this :thinking:

**Comment by timayhelen** [comment]
@lots0logs it happens quite randomly, as do most of these errors.

**Comment by lots0logs** [comment]
Noted. :dizzy_face:

**Comment by timayhelen** [comment]
@lots0logs I was on siteground hosting when I encountered the error.
