### ISSUE TITLE
"An Autosave Exists" When I Have Never Edited The Page Before

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1006]
This happens to me quite often on master. On a completely new post that has just been saved and never been edited in the Visual Builder, the first time I open it in the Visual Builder I get asked to restore an Auto Save that should not exist. These are my steps:

1. Create a new page.
2. Enable the Divi Builder.
3. Load the Homepage Basic Layout 
4. Publish the page. 
5. Click the "Use Visual Builder" button. 
(when the Visual Builder loads for the first time, an auto-save popup appears)

The above steps do not consistently replicate the problem. I assume it has to do with the heartbeat running at a certain time or in a certain way while completing steps 1-4 above. 

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1766

**Comment by timayhelen** [comment]
I am able to replicate this quite often on the SiteGround account. Almost every time I open the VB for the first time I get greeted with the auto-save popup. Here is an example of me testing AB testing when it occurs on a new page:

![auto-save](https://cloud.githubusercontent.com/assets/3333028/23246460/90f68906-f948-11e6-88e1-09c65927b68f.gif)

**Comment by Jronk** [comment]
I was able to replicate consistently using @timayhelen steps above, and now with the fix in PR it no longer occurs.

**Comment by aszx** [comment]
Hey, sometimes I get this message at the very bottom of the page, when editing a page in Visual Builder.:
.....................................
An Autosave Exists
A recent autosave exists for this post that is newer than the version you are currently viewing. This autosave was captured during your previous editing session, but you never saved it. Would you like to restore this autosave and continue editing where you left off?

Don't Restore Restore
.....................................
(the above links "Don't Restore Restore" don't work)

The workaround was to live the VB of page 'A' by clicking on page 'B' on the website menu, activate VB there and clicking on the page 'A' again. Now, activating the VB wont show the message... Strange eh.. Cheers
