### ISSUE TITLE
Blurb modules icons change everytime

### ISSUE THREAD

**Issue by FourFeathers** [elegantthemes/Divi-Beta#101]
Situation: 
I made a Divi library item with 4 columns with 4 the blurbs modules with the same icons that I want to use on a page. (I am currently working with safari, chrome and MAMP)

The bug(s): When I add this library item to the page via the visual builder everything is correct. However when I go to the page again the blurb icons are changed to a different icon. When I enter visual builder not only do the blurbs change again, the blurbs icons are also multiplied in each column.

The library item:
<img width="695" alt="screenshot_288" src="https://cloud.githubusercontent.com/assets/21121491/17804663/f4a0d054-65fc-11e6-8a7e-9766e028f191.png">

When you revisit the page again:
<img width="1098" alt="blurbs revisit" src="https://cloud.githubusercontent.com/assets/21121491/17804993/96ba1788-65fd-11e6-8567-691872fa3f78.png">

When you enter the visual editor:
<img width="1196" alt="blurbs visual editor" src="https://cloud.githubusercontent.com/assets/21121491/17805000/a1fef44c-65fd-11e6-8c6b-355ca8a7dcaa.png">

**Comment by monowebdesign** [comment]
This seems to happen on the Fullwidth header 'scroll down' icons as well

**Comment by fikrirasyid** [comment]
@FourFeathers @monowebdesign can you create a screencast or step-by-step screenshots to replicate the issue? I've tried replicating the issue based on the description you gave above, but the icon still appear correctly in FB and actual page in my case. I think I missed something. Visual cue will definitely help.

**Comment by FourFeathers** [comment]
@fikrirasyid First of all: this bug also happens when I save the blurbs as 'a row', with different columns (1/2 and 1/2, 3/4 and 1/4 etc.) and so on. So the steps below apply to them too.

The steps I take are the following:

1. First I make a new section in the Divi library with 4 columns with 4 blurbs modules in them. 

<img width="928" alt="section" src="https://cloud.githubusercontent.com/assets/21121491/17886053/5e50ea7c-6920-11e6-8e61-34fb06d06d48.png">

2. I save this section to the Divi Library

3. Then I add it to a new/existing page (via add section (blue plus icon) / from library / section)

4. The blurbs icons are correctly displayed after adding the new section to the page. See:
<img width="695" alt="blurbs library item" src="https://cloud.githubusercontent.com/assets/21121491/17886065/6a6d1538-6920-11e6-970c-553236aae76f.png">

5. When I save the page, everything still looks right. 

6. HOWEVER: when I refresh the saved page (or if I open the saved page by going to it via the main navigation / or just via a hyperlink) all of the sudden the blurb icons that I have added to the new created section (see screenshot step 1) change. Instead of the blurb icons I selected for all 4 blurbs modules (see screenshot step 3) the modules choose 4 different blurb icons. On top of that- it replicate it many times when I am in the 'visual editor mode'. 

Resulting visual into:

_When not in the 'visual editor mode':_
<img width="1098" alt="blurbs revisit" src="https://cloud.githubusercontent.com/assets/21121491/17886081/769d96d4-6920-11e6-8c46-e633e1af849d.png">

_When in the 'visual editor mode':_
<img width="1196" alt="blurbs visual editor" src="https://cloud.githubusercontent.com/assets/21121491/17886082/76a295bc-6920-11e6-9c2a-15c62320bdf8.png">

**Comment by fikrirasyid** [comment]
@FourFeathers Thank you for your detailed step by step! I've successfully replicated the issue and currently looking for a way to fix it. I'll keep you updated.

**Comment by fikrirasyid** [comment]
@FourFeathers I've submitted a patch for this issue. The issue occurs due to the use of `sanitize_text_field()` to sanitize all values which will be saved. If the saved font icon uses `%%number%%` format, it will be sanitized improperly thus the issue (hence the issue actually happens to all font icon picker).

The patch is currently under review now. Once it passes the review, it should be merged into next beta release. Thank you for reporting the bug! 😄
