### ISSUE TITLE
Initial Split Test Syncing Does Not Work (Sometimes)

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1011]
1. Create a new page. 
2. Enable the Divi Builder. 
3. Load the Homepage Basic layout. 
4. Publish the page. 
5. Enable a split test with the Slider as the subject and Fullwidth Header as the goal. 
6. Right click "Use Visual Builder" and open in a new tab. 
7. The split test is not initiated in the Visual Builder. 
8. Return to the BB tab to see the split test subject disappear, at this point things are quite bugged (a split test is running but the goal and subject are gone.)

Sometimes it works, sometimes it doesn't. I am on the siteground hosting environment.

**Comment by lots0logs** [comment]
I'm unable to reproduce this (so far).

**Comment by fikrirasyid** [comment]
The steps to replicate this issue is almost exactly like https://github.com/elegantthemes/Divi-Beta/issues/932#issuecomment-281683476 which should've been fixed. I'll take a look on this
