### ISSUE TITLE
Editing Page In Backend Builder Causes Browser Backup Notification Mid-Sessions

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1012]
When editing a page in the Backend Builder, browser backup notifications always appear after ~30 seconds of editing. You must first publish the page. 

1. Create a new page. 
2. Enable the Divi Builder. 
3. Load the Homepage Basic Layout. 
4. Publish the Page. 
5. Continually duplicate, edit and delete a module until the browser backup notification appears. 

![browser-backup](https://cloud.githubusercontent.com/assets/3333028/23279806/8f0e65cc-f9cb-11e6-8046-12a15b6cc55f.gif)

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1768

**Comment by timayhelen** [comment]
Turns out this is unrelated to split testing. It occurs often when editing the page in the BB after builder sync has been used during the current editing session:

![browser-backup](https://cloud.githubusercontent.com/assets/3333028/23279484/4fa0be68-f9ca-11e6-8726-78137c06db78.gif)

**Comment by timayhelen** [comment]
Turns out initiating builder sync is not necessary to replicate this. Simply editing a page in the BB long enough will trigger a browser backup notification. Un-focusing the tab may still be involved.

**Comment by lots0logs** [comment]
@timayhelen Can you reproduce it on my test site?

**Comment by timayhelen** [comment]
@lots0logs It's quite easy to replicate. You can use these steps:

1. Create a new page. 
2. Publish the page. 
3. Edit some text on the page (such as a blurb title)
4. Leave the browser tab and come back to force a heartbeat. 
5. Edit some text on the page again.

**Comment by lots0logs** [comment]
@timayhelen Followed those steps on the Siteground site and the issue did not occur :confused:

**Comment by Jronk** [comment]
I approve, see my comment on PR: https://github.com/elegantthemes/submodule-builder/pull/1768#issuecomment-282223320
