### ISSUE TITLE
Siteground :: VB :: Section, Row Settings discrepancies

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#1015]
### Problem:

There are some discrepancies between how the VB and the frontend render the video background.

This video will show more information:

https://drive.google.com/open?id=0B8PjD3Z_XQvua3NXVUlabkNMdTg

**Comment by SlavaET** [comment]
@eduard-ungureanu can you please check it in the latest version of master? It seems to work fine for me. If you still see the issue - please share the page layout you're testing and I'll take a look. Probably I'm missing some settings.

**Comment by eduard-ungureanu** [comment]
@SlavaET the test was done on the sharing account on siteground, I can use the latest master on my local server, but I think we should update the siteground account with that latest master, to make sure we do a proper check, what do you think?

**Comment by SlavaET** [comment]
Hm, so you cannot reproduce the issue on your localhost?

**Comment by lots0logs** [comment]
That behavior is to be expected. You have two disabled modules in that section. The VB displays disabled modules while the frontend does not (for obvious reasons). The disabled modules being displayed in the VB make the height of the section much greater than it actually is on the frontend.
