### ISSUE TITLE
Siteground :: FB :: Tabs Module :: Tab Item (child items) :: Font Options

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#1017]
### Problem:

Editing the font style options: Bold, Italic, Underline, Uppercase, in FB doesn't show which option is enabled and which is disabled, but saving the module, and checking in BB (the settings are synced and show properly.

https://drive.google.com/open?id=0B8PjD3Z_XQvuR0cyT3FHWDRMZWc

Same thing happens for the Body Font Options.

MacOs - Browsers:
- Chrome - latest version
- Safari - latest version
- Firefox - latest version

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1795

**Comment by timayhelen** [comment]
Note: this only occurs for child items (the individual tabs)

**Comment by SlavaET** [comment]
I cannot reproduce this issue in the latest master. I can see it on siteground website, but looks like it's not the latest version of master installed there.
@lots0logs can we update the theme on siteground to make sure it works there as well?

**Comment by lots0logs** [comment]
@SlavaET I can still reproduce it on `master`. Check out the tabs module on the homepage of my test site: http://et.falgout.us/divi

**Comment by SlavaET** [comment]
Was able to reproduce the issue locally and found the root cause.
Btw, it happens with any setting ( except for the Content of tab ) not only with font options.

**Comment by lots0logs** [comment]
The font styles for individual tabs get overridden by the styles set in the parent module. I don't think its directly related to this fix so I created #1070 for it.
