### ISSUE TITLE
Toggling Tabs Initiates Heartbeat Even When Builder Sync Is Not Active

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1019]
We only need to force heartbeat when switching tabs if builder sync is active, otherwise it is not necessary. 

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1767

**Comment by lots0logs** [comment]
@Jronk Here's the steps I took to test this:

1. Clear browser cache and cookies.
2. Create a new page with the Homepage Basic Layout in the BB.
3. Open the VB in a new tab.
4. Delete one of the Blurb Modules.
5. Switch back to the BB's tab.

I get a spinner on the BB for what feels like longer than normal. Once the spinner is removed, I see that the change I made in the VB did not sync to the BB (the Blurb Module is still there). If I switch back to the VB I can still see the change I made.

During this, I noticed that when I switched back to the BB after making the change, two ajax requests were made. Here are the details:

**Request 1**
```
data[wp-refresh-post-lock][post_id]:29224
data[wp-refresh-post-lock][lock]:1488209699:1
data[et][last_post_modified]:2017-02-27 09:34:53
data[et][built_by]:bb
data[et][post_id]:29224
data[et][force_check]:false
data[et][force_autosave]:false
interval:15
_nonce:2941b2f354
action:heartbeat
screen_id:page
has_focus:true
```

**Response 1**
```
{"wp-refresh-post-lock":{"new_lock":"1488209715:1"},"wp-auth-check":true,"et":{"received":true,"force_check":false,"force_autosave":false,"action":"No actions since this editor has focus"},"server_time":1488209715}
```

**Request 2**
```
data[wp-refresh-post-lock][post_id]:29224
data[wp-refresh-post-lock][lock]:1488209715:1
data[et][last_post_modified]:2017-02-27 09:34:53
data[et][built_by]:bb
data[et][post_id]:29224
data[et][force_check]:true
data[et][force_autosave]:false
interval:15
_nonce:2941b2f354
action:heartbeat
screen_id:page
has_focus:true
```

**Response 2**
```
{"wp-refresh-post-lock":{"new_lock":"1488209728:1"},"wp-auth-check":true,"et":{"received":true,"force_check":true,"force_autosave":false,"post_post_modified":"2017-02-27 09:34:53","autosave_exists":false,"used_autosave":false,"post_id":29224,"last_post_modified":"2017-02-27 09:34:53","post_modified":"2017-02-27 09:34:53","post_not_modified":true,"action":"post content not modified externally"},"server_time":1488209728}
```

**Comment by Jronk** [comment]
@lots0logs fixed. The normal syncing works, and the preventing of syncing works. There was a typo in the cookie name :man_facepalming:
