### ISSUE TITLE
Section Layouts when loading from library in Visual Editor are mixed up

### ISSUE THREAD

**Issue by heart347** [elegantthemes/Divi-Beta#102]
### Problem:

When i'm in the Visual Editor and I try to add a new section and Load from Library, the layout packs we got during the Divi 100 are all mixed up. If you select a layout, you don't get the layout you selected. However if you are in the Divi builder and select a layout and then preview it or go to Visual Editor after, the correct layout will come. So the it is only a problem when adding a new section and loading from library from the Visual Editor that they get mixed up.

Steps To Reproduce:
1. Go to Visual Editor
2. Select the plus button to add a section
3. Select Email Optin 4 as an example
4. You get a section on products.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac

**Operating System**:

**Browser**: Chrome

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by heart347** [comment]
It still is mixed up when I select a layout from a new section in Visual Editor.

**Comment by SlavaET** [comment]
Yes, the fix is ready but is not published yet. You'll be notified when new version of beta will be available :)

**Comment by heart347** [comment]
Oh, okay! :) Thanks! I'm about to post another bug.
