### ISSUE TITLE
VB :: Full Width Section :: Video Background

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#1027]
### Problem:

Setting up a video background doesn't properly fill the whole section:
https://drive.google.com/open?id=0B8PjD3Z_XQvuX09rbTI1VGVsbDQ

Exiting the VB the video will properly get applied filling the whole section.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1798

**Comment by lots0logs** [comment]
@fikrirasyid Please see my review. Thanks!

**Comment by fikrirasyid** [comment]
@lots0logs replied. Thanks!
