### ISSUE TITLE
VB :: Specialty Section

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#1028]
### Problem:

Setting up a custom padding, for the second column in a specialty section only works for desktop, on tablets and mobile the custom padding doesn't get applied.

Layout:
[specialty-section.json.zip](https://github.com/elegantthemes/Divi-Beta/files/798804/specialty-section.json.zip)

Video:
https://drive.google.com/open?id=0B8PjD3Z_XQvuVlBVVnRudzF5MUk

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1808

**Comment by lceberg** [comment]
The issue affects BB as well, the tablet/phone padding settings did not get included in the generated CSS.
