### ISSUE TITLE
1&1 :: VB :: Gallery Module :: Issue when switching between slider and grid

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#1029]
### Problem:

1 Add a gallery module.
2 Switch from grid to slider (works fine).
3 Switch back to grid (it doesn't change).

![116](https://cloud.githubusercontent.com/assets/16414613/23303151/59f6ef02-fa8a-11e6-9680-4acf4ef5332a.gif)

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1771

**Comment by FaycalBoutam** [comment]
Actually all options are not changing in the module configuration panel. They apply though.

**Comment by lots0logs** [comment]
@Jronk This issue is fixed by your PR. But please see my comment here: https://github.com/elegantthemes/Divi-Beta/issues/1039#issuecomment-282444556

**Comment by Jronk** [comment]
Saw the comment, fixed in https://github.com/elegantthemes/submodule-builder/pull/1771, thx
