### ISSUE TITLE
Visual editor hangs while trying to load page for editing

### ISSUE THREAD

**Issue by adlambros** [elegantthemes/Divi-Beta#103]
### Problem: If you try to run the visual editor on a page with many section, it just looks like it tries to load but goes nowhere.  For example, I tried adding a page layout from the library called 'Our Team', and when I go to edit it in the visual editor it just hangs and hangs.  If I remove some of the sections then it will load fine

Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.

### Steps To Reproduce:
1. Install a layout from the library (i.e. Our Team)
2. Try to use visual editor
3. It just keeps trying to load and load and goes nowhere.
4.If you remove sections then it will work, but pages with big sections cause hanging problems

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac

**Operating System**: 10.11

**Browser**: Chrome

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@adlambros Can you try right clicking in Chrome and choosing "Inspect Element", refreshing the page and reproducing the error again?
Please see if any messages appear in the "Console" tab. Please paste the messages here if anything shows up.

**Comment by bhalsekhar** [comment]
I can reproduce this error in post. The error is  **Uncaught TypeError: this.state.sections.map is not a function**  in Divi/includes/builder/frontend-builder/app/bundle.js?ver=2.9.9

**Comment by adlambros** [comment]
Looks like you were able to fix it! :)
