### ISSUE TITLE
Builder Sync :: Sync Does Not Work After Saving And Refreshing VB Page

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1034]
### Problem:
To reproduce the problem open two tabs: BB and VB. Then:
1. Go to VB and add some changes. 
2. Save and refresh the page.
3. Go to BB tab.

You'll see the Sync in not functioning. It will work after you add new portion of changes. 

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1770

**Comment by timayhelen** [comment]
@Jronk This doesn't seem to work for me, following Karen's steps. Does this fix a different issue?

![sync](https://cloud.githubusercontent.com/assets/3333028/23374746/757ebc08-fcda-11e6-9cc4-7dd582886c88.gif)

**Comment by Jronk** [comment]
@timayhelen I am able to reproduce my fix over and over, so i'm not sure how you are able to get your results in above gif. (I literally copied your exact moves, including using keyboard commands to save and refresh, and used same layout, made same changes etc.) I updated the PR branch to include latest master as well, and re-pushed, so give it another try? :shrug:

branch: `1034-builder-sync-sync-does-not-work-after-saving-and-refreshing-vb-page`

![builder sync sync does not work after saving and refreshing vb page - 1770](https://cloud.githubusercontent.com/assets/1163441/23394256/f65dfa20-fd3c-11e6-8ff8-e989d1aa0c6b.gif)

**Comment by timayhelen** [comment]
Seems to be working for me now.
