### ISSUE TITLE
BlueHost :: Bar Counter :: Window Closes After Text Selection

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1037]
### Problem:

This happens only when you try to select text using mouse (and you move arrow out of the module window settings). Screen cast:
http://youtu.be/S8iVfXXwX_U?hd=1

Test page:
http://elegantthemesbluehost.com/accordion/?et_fb=1

**Comment by timayhelen** [comment]
@kary4 Can you replicate this consistently? I can't seem to.

**Comment by kary4** [comment]
@timayhelen Yes, I can, at least on the test page I posted above. Here is it again:
http://elegantthemesbluehost.com/accordion/?et_fb=1

Just open the first tab in the Bar Counter module settings try to select select a value (even it's empty) in the percentage module. Here is one more screen cast if you need:
http://youtu.be/RpOD6XZLkkI?hd=1

Though you are correct, if I now try to create a new page and reproduce the problem I cannot get that anymore. It should be something wrong in the specific page I posted above. I'm not exactly sure how I was able to create the problem :)
