### ISSUE TITLE
DreamHost :: VB :: Post Navigation :: Module settings do not work after enabling Hide Next Post Link

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#1039]
### Problem:

After enabling the **Hide Next Post Link** setting the settings window does not respond.
![screen](https://cloud.githubusercontent.com/assets/20072036/23320456/e8c032fa-faeb-11e6-8a62-6674795ad27e.gif)

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1790

**Comment by Jronk** [comment]
This is fixed via: https://github.com/elegantthemes/submodule-builder/pull/1771

**Comment by lots0logs** [comment]
@Jronk After adding a Post Nav Module to the layout the entire tab hangs indefinitely.

**Comment by Jronk** [comment]
Thanks @lots0logs, fixed. See new PR
