### ISSUE TITLE
VB :: Bar Counter :: Some Values Don't Get Applied

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1041]
### Problem:
I cannot apply some simple values (one digit, for ex.: 5 or 7) to the Percent field option. Though sometimes it work. In the screen cast below you can see that the Percent value reverts to 0 immediately after Mouse-down event when you try to save the changes.

Screen cast:
http://youtu.be/UaYYj57xSMI?hd=1

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1791

**Comment by timayhelen** [comment]
I notice this too, and I don't notice it on the last Divi release. 

![bar-counter](https://cloud.githubusercontent.com/assets/3333028/23321304/c0a66dbe-fa93-11e6-94bc-97eebb33b9d1.gif)

**Comment by kary4** [comment]
@timayhelen are you sure you did not mean this issue instead: https://github.com/elegantthemes/Divi-Beta/issues/1037

**Comment by SlavaET** [comment]
It should be fixed in scope of this ticket - https://github.com/elegantthemes/Divi-Beta/issues/1040
