### ISSUE TITLE
VB :: Bar Counter :: Double Animation

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1045]
### Problem:

When you refresh the VB page the Bar Counter animation initializes two times. 

To reproduce the problem:
1. Add a Bar Counter module and add some changes.
2. Wait for wordpress heartbeat to get an autosave.
3. Refresh the page. 
4. When the page loads select Restore.

Screen cast:
http://youtu.be/4ad6Ms5sqyA?hd=1

**Comment by kary4** [comment]
Same for Blog Module here:
http://elegantthemesbluehost.com/blog-page/?et_fb=1

**Comment by timayhelen** [comment]
@kary4 Does this only occur when restoring a backup?

**Comment by kary4** [comment]
@timayhelen Yeah, that's correct. It's important to select Restore when you refresh the page.

**Comment by kary4** [comment]
Here is another way to replicate similar problem: Just play with the top-padding in Visual builder and quickly hover over the bar counter module.
Screen cast:
http://youtu.be/qj6MHWwslL0?hd=1
