### ISSUE TITLE
DreamHost :: VB :: Responsive settings toggle issue

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#1047]
### Problem:

It's hard to explain. The issue occurs especially trying to switch between device layouts on neighboring settings like Maring/Paading and so on.
The screencast has recorded using Post Slider Module.
![screen](https://cloud.githubusercontent.com/assets/20072036/23324421/bb3bd27c-fafe-11e6-8e45-8ab704721f75.gif)

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1780

**Comment by SlavaET** [comment]
Fixed. The simple way to reproduce the issue:
1) Open module settings which contains Text or Range option with Responsive settings ( like `Post Slider` from above example );
2) Activate the Responsive option ( it can be either Text option like Top Padding or Range option, like font-size );
3) Use the main switcher in VB App ( the one in the left bottom corner of the screen ) to toggle the preview mode;
4) Note that option tab is not correctly switched to the new mode until you hover over the Settings modal.
