### ISSUE TITLE
Move button

### ISSUE THREAD

**Issue by ferreirex** [elegantthemes/Divi-Beta#105]
### Problem:

When i try to move some stuff like Button to another place, i can reach to the move icon.
![screen shot 2016-08-19 at 11 13 38](https://cloud.githubusercontent.com/assets/5623963/17806804/a428e3da-65fe-11e6-89c4-8172439e8945.png)

**Comment by timayhelen** [comment]
This issue has been reported, so I am closing this duplicate ticket. Thanks!
