### ISSUE TITLE
VB :: Post Nav Module :: PHP Notice: Trying to get property of non-object

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1052]
### Problem:

```
[25-Feb-2017 00:48:15 UTC] PHP Notice:  Trying to get property of non-object in et.falgout.us/wp-content/themes/Divi/includes/builder/main-modules.php on line 15596
```

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1774

**Comment by fikrirasyid** [comment]
Steps to replicate the issue:

Add new page, activate builder
Add post navigation module
Right click + open new page on Use Visual Builder button.
The error occurs

**Comment by Jronk** [comment]
I fixed this in a different way, didnt see this ticket... See https://github.com/elegantthemes/submodule-builder/pull/1790/commits/495ddc1a32ae6e1fad2bde8d56bd37727c39cd30
