### ISSUE TITLE
VB :: Cannot Remove Padding Values In Mobile/Tablet View

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1054]
### Problem:

The padding value always reappear itself or when you try to modify for ex. left-padding it remove all other padding. All fields are buggy. 

Screen cast:
http://youtu.be/ARQvy2ObTq8?hd=1

### Steps To Reproduce:
1.  Define left and right padding to a row module by dragging the row lines using Visual Builder.
2. Switch to Mobile View.
3. Now open the Row Settings and try to redefine the mobile padding fields.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1792

**Comment by timayhelen** [comment]
@fikrirasyid FYI this is not a new bug. It probably dates back to when we worked on all the padding stuff.

**Comment by fikrirasyid** [comment]
@timayhelen @kary4 I've fixed the issue at https://github.com/elegantthemes/submodule-builder/pull/1792.

I'm copying the PR message below for reference:

> What is being referred as the bug on the issue above is actually intentional due to how the newly introduced responsive behaviour at https://github.com/elegantthemes/submodule-builder/pull/1345 which basically works as follow: 
> 
> 1. if responsive mode isn't activated (indicated by opened responsive tab), tablet and phone breakpoint use desktop value. 
> 2. Consequently, upon responsive activation and no value is saved, tablet inputs use desktop's value and phone fields uses tablet or desktop value until these fields are updated.
> 3. Thus the "cannot remove value" behaviour. Basically when the value is empty in tablet/phone view, it'll fetch its fallback value because that is how the setting works on the layout
> 
> Nevertheless, I agree that this *feels* buggy, and it feels that  it isn't right. Thus, what this commit does is enhancing its UX:
> 
> 1. Instead of automatically apply wider breakpoint's inputs value as default value, apply them as placeholder instead.
> 2. Apply softer color for placeholder so placeholder and value are properly distinctive.
> 
> Now the responsive inputs' value can be removed, but the sense of wider breakpoints value used as fallback value still can be noticed.
> 
> ![1054](https://cloud.githubusercontent.com/assets/916442/23395817/33232a44-fdc3-11e6-8c97-a956d92fb73c.gif)
