### ISSUE TITLE
VB :: Padding Disappears 

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1055]
### Problem:

In the following situation Padding Row padding disappears.
Screen cast:
http://youtu.be/SwkinMuWmq0?hd=1

### Steps To Reproduce:
1.  Add a row under VB and define some padding (in my case left and right padding).
2. Open Row module settings.
3. And close the settings right away by clicking the Red (Disregard all changes) button.
4. The padding disappears even though you did not add any changes under Row Settings window.

Possible related to:
 https://github.com/elegantthemes/Divi-Beta/issues/1054

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1785

**Comment by SlavaET** [comment]
This issue is similar to https://github.com/elegantthemes/Divi-Beta/issues/1059
But I fixed it in a new PR because this code is located in a different place.

**Comment by lots0logs** [comment]
@SlavaET Could you fix merge conflicts? Thanks!

**Comment by lots0logs** [comment]
@SlavaET Could you fix merge conflicts? Thanks!

**Comment by SlavaET** [comment]
@lots0logs done.

**Comment by lots0logs** [comment]
@SlavaET Could you check this again. Looks like you applied the change to the wrong place. That code block was moved recently, it starts on [this line](https://github.com/elegantthemes/submodule-builder/pull/1785/files#diff-3d118346b9153b174ee444572afed18dR3783) now.

**Comment by SlavaET** [comment]
@lots0logs yes, you're right. Corrected it now.
