### ISSUE TITLE
VB :: Button Module :: Hover Letter Spacing

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1056]
### Problem:
It's small problem actually. Hover Letter Spacing option behaves a bit incorrectly. If you don't touch the option it display that you can change the option from 0 (zero). But once you try to increase the value by moving the slider you cannot get 0 (zero) value again. It goes to 1px minimum. To fix it you have to define 0px manually and then it starts working correctly. 

To see what exactly I mean please refer to this screen cast:
http://youtu.be/b8lmLpGyjSo?hd=1

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1786

**Comment by lceberg** [comment]
This seems to affect all the range sliders in FB that don't have their default settings explicitly set.
