### ISSUE TITLE
VB :: Button Modules :: Cannot save changes

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1057]
### Problem:
It's a big problem with button modules. Actually no matter if I add any changes or not.. It goes wrong once you close Button Settings window (no matter what you click Disregard Changes or Save). Also, if you save the page and preview you can see nothing.

Screen cast:
http://youtu.be/pjLWjamDvPQ?hd=1

### Steps To Reproduce:
1.  Just add a button module and close the settings window.

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1783

**Comment by timayhelen** [comment]
I notice another weird thing.

1. Add a new button module. 
2. Change the Button URL to http://google.com and do nothing else. 
3. Click the green checkmark. 
4. Save the page. 
5. View on the front-end. 

The button text becomes the button URL. If you go back and apply custom button text, then it fixes it.

**Comment by SlavaET** [comment]
Fixed. I removed default values which were wrongly applied in VB for the button module and now it behaves exactly as on Frontend, i.e.:
1) There is no default values for URL and Text in the Button module;
2) If you define no URL and no Text - button won't appear;
3) If you define URL and no Text - button will appear and Text of the button equals to URL;
4) If you define URL and Text - button will appear with defined Text and URL.

It's the way button module always behave on frontend.
@timayhelen let me know if we need to apply the default values ( i.e. Text = "Button", URL = "#" ), please note if we change it on frontend, then it potentially may change the appearance of module for users who defined URL only and don't want to show custom text.
