### ISSUE TITLE
VB :: CTA :: Text Reappears After You Remove It

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1059]
### Problem:

I'm assuming this is not only in CTA module. When you add some changes to the text in a text editor directly (don't use Module Settings Window) it works good. But once you open Module Settings and click the Discard Changes it also affects the text you changed earlier. It seems the events should not be related.

Screen cast:
http://youtu.be/O2PEzHqnWQk?hd=1

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1784

**Comment by kary4** [comment]
I just noticed that this also happens even you apply some padding and then Open>Close any module it removes all the changes (padding).
Screen cast:
http://youtu.be/nckQFGqxyYM?hd=1

**Comment by lots0logs** [comment]
@SlavaET Could you fix merge conflicts? Thanks!
