### ISSUE TITLE
VB :: Locked Module :: Does Not Lock under VB

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1063]
### Problem:
If I understand correctly this exact problem was fixed and merged recently (https://github.com/elegantthemes/submodule-builder/pull/1746). I just checked this feature again. It still does not work correctly. For example for Blog module it works good but for Button module it does not work.  

And some questions if you don't mind:
1. Why some Locked module icons are Red and some Green? (You can see in screen cast);
2. Is it supposed that when you double click the locked modules you still can add any changes and save it? If I understand the concept of the locked content it should not be possible.

Screen cast:
http://youtu.be/6ZfsZOEe-ws?hd=1

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1787

**Comment by timayhelen** [comment]
@lceberg I thought of something else, we need to disable some keyboard shortcuts as well. For example, it's still possible to copy a module from one row into a locked row.

**Comment by lceberg** [comment]
@timayhelen The latest few commits address that - locked modules can no longer be cut/copied/pasted and any modules can no longer be cut/copied/pasted from and into locked modules.

**Comment by lots0logs** [comment]
@lceberg Could you fix merge conflicts? Also regarding this:
>* locked modules could be cut/copied/pasted [BB, VB]
>* locked rows could have their elements cut/copied/pasted [VB]

I think **Copy/Paste** is fine (so long as it's pasted into a non-locked module). We should prevent **Cut** though.

**Comment by lceberg** [comment]
@lots0logs Merge conflicts are resolved. Locked modules can now be copied (not cut) and pasted in non-locked sections.

**Comment by lots0logs** [comment]
@lceberg 

**BB:**
* Copy/Paste doesn't work using keyboard shortcuts.

**VB:**
* Copy/Paste doesn't work using keyboard shortcuts.
* Copy option isn't presented in the right-click menu either.

**Comment by lots0logs** [comment]
@lceberg There's just one thing I noticed which is that after copying a locked module in the VB, the new module is locked while in the BB the new module is not locked. I think the BB's behavior is preferred. Let's make it the same in the VB.

**Comment by lceberg** [comment]
@lots0logs Done, just a note -- this worked in BB only on newly created and locked modules, so latest commit tweaks BB logic a bit as well.
