### ISSUE TITLE
DreamHost :: VB :: Sudden layout disappearing

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#1065]
### Problem:

I've noticed the sudden layout disappearing when creating page from scratch. The issue appears while adding columns or/and module without touching any settings. Just wait a few seconds and layout disappears by itself.
http://screencast-o-matic.com/watch/cbnT0V6YsD

**Comment by dm-chechik** [comment]
It seems the issue occurs even while adjusting module settings. I've successfully reproduced it while editing Shop Module.
http://screencast-o-matic.com/watch/cbnT0y6YMo

**Comment by timayhelen** [comment]
This has already been fixe don the latest version.
