### ISSUE TITLE
DreamHost :: VB :: Slider :: Controls disappearing after adding video to a slide 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#1066]
### Problem:

Syncronizing feature works well, on front end I see the video on the slide, however VB don't show any slider controls.
![screen](https://cloud.githubusercontent.com/assets/20072036/23343044/d7381670-fc75-11e6-91b5-16358af9c90f.gif)

**Comment by lots0logs** [comment]
@dm-chechik The controls should show once you save/close the settings modal and hover over the slider. Let us know if that's not the case.
