### ISSUE TITLE
Cannot add section in visual builder

### ISSUE THREAD

**Issue by bhalsekhar** [elegantthemes/Divi-Beta#107]
### Problem:
When I use visual builder I cannot add a new section because of the blue round button which show the save button hide that button .   

### Steps To Reproduce:
1. Go to the visual editor.
2. then try to add a new section.

**Screenshots**:
![section](https://cloud.githubusercontent.com/assets/8648513/17808181/446366e0-662c-11e6-8f56-d18577bd9fa0.png)

**Comment by timayhelen** [comment]
Thanks for the input. There is already an issue opened for this bug, so I am closing this duplicate.
