### ISSUE TITLE
Builder :: Tabs Module :: Font Style Settings For All Tabs Overrides Individual Tab Settings

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1070]
@lots0logs commented on [Fri Jan 27 2017](https://github.com/elegantthemes/Divi/issues/2783)

### Problem:

The font style settings for individual tabs (child modules) should override the font style settings applied to all tabs in the parent module.

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1797

**Comment by SlavaET** [comment]
Corrected the selectors for individual tabs font options.
As for the `Underline`, `Uppercase`, `Italic`, `Bold` - these can be overriden only if disabled in parent module, i.e. once you enable one of those options for parent there is no way to disable it for child module. It's a general issue with all modules in Divi and right now there is no mechanism to override enabled font option from above list for child module. 
If remember correctly there was a discussion about this a while back but I don't remember what was the final decision on this.
