### ISSUE TITLE
Tabs Small Column Styles Broken

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1071]
The tab's size and content padding is off when tabs are placed inside of a 1_3 or 1_4 column.

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1796

**Comment by lots0logs** [comment]
**Note:** I had to manually remove the stylesheet to get webpack to include the changes in this PR: 

`frontend-builder/assets/css/style.css`
