### ISSUE TITLE
Buttons With No Border Have Borders

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1080]
#It doesn't look like border widths are rendering correctly in the Visual Builder for custom buttons styles.

What it looks like on the front end:

![screen shot 2017-03-06 at 3 40 47 pm](https://cloud.githubusercontent.com/assets/3333028/23635218/4d9e5636-0283-11e7-87f4-6b8a8050c47f.png)

What is looks like in the Visual Builder:

![screen shot 2017-03-06 at 3 41 07 pm](https://cloud.githubusercontent.com/assets/3333028/23635231/5a3ccef4-0283-11e7-8780-b6b30076ceaa.png)

Border border width is showing up as "2" in the Visual Builder even though it is set to "0" in the shortcode. It works in the BB and on the front end, but not in the Visual Builder.

![screen shot 2017-03-06 at 3 41 45 pm](https://cloud.githubusercontent.com/assets/3333028/23635250/6d9dae28-0283-11e7-910d-050bbecc4351.png)

The following button options are used:

`custom_button=\"on\" button_letter_spacing=\"0\" button_use_icon=\"default\" button_icon_placement=\"right\" button_on_hover=\"on\" button_letter_spacing_hover=\"1px\" auto_ignore_hover=\"off\" header_font=\"|on|||\" header_font_size=\"48\" button_text_size=\"22\" button_bg_color=\"#8300e9\" button_border_width=\"0\" button_border_radius=\"38\" button_font=\"|on||on|\"`

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1812

**Comment by timayhelen** [comment]
Update: Looks like this is due the "border width" settings not working in the Visual Builder. If you check the BB, the border width is correctly set to 0. If you check the Visual Builder, it shows up as "2" which is the default width.

**Comment by fikrirasyid** [comment]
@timayhelen can you share the layout you used for this page? I've tried to replicate the issue, but still no luck. VB still appears as it is shown on the actual front page 🤔

**Comment by fikrirasyid** [comment]
Nevermind, I've finally found a way to replicate the issue 👌 The issue wouldn't occur if the slider is created on VB, but it appears if the slider is made on BB.
