### ISSUE TITLE
ID & Class Removed From Modules With Child Elements In Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1083]
This is likely related to shortcode trimming:

1. Create a new page.
2. Enable the BB.
3. Load the Homepage Basic layout.
4. Apply an ID and Class to the Slider modules via the CSS tab.
5. Publish the page. You will notice the ID and Class you added are still there. 
6. Click "Use Visual Builder"
7. Open the slider settings to see that the ID and class has been removed. 

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1820

**Comment by SlavaET** [comment]
Fixed.
It's not related to shortcode trimming btw, it's a bug in Custom CSS fields rendering function.
