### ISSUE TITLE
Image Animations Removed After Saving In The Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1086]
This problem is being reported often in the forum for Divi 3.0.35. However, I can't seem to replicate it:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664150
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=663884

The reports all state the following:

1. Create a page and add an Image Module.
2. Change the image animation to "No Animation."
3. Save the Page.
4. Open the page in the Visual Builder.
5. Do nothing and save the page. 
6. The animation style reverts to default.

There must be something else going on though, sine I can't replicate it. It's definitely a real issue though, we have many reports. 

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1822

**Comment by SlavaET** [comment]
I cannot reproduce this issue as well. I checked all the module settings and defaults of the module. Tested various scenarios I can think of and it works fine. I asked @abhi-sharm to let me know when he receive a reply to take a look at customer's website.

The only possible situtation I can think of is following:
1) Create and save a layout with image module in BB;
2) Open the VB in a new tab leaving the BB opened;
3) Change the animation or whatever option in VB;
4) Switch back to BB and press save button before the sync process finished.
As a result old layout will override the new one and it will be saved with old settings. But it's a general issue not related to image or any other module and I think we should disable save functionality while sync process is in progress to not allow users to accidentally override the changes.
@timayhelen what do you think? Probably it's not a high priority issue, but I think we need to implement it.

@Jronk @fikrirasyid btw, is it possible that WordPress autosaves may conflict with our autosave and override it somehow? I can dig into the code and figure it out, but you guys know this thing much better, so I decided to ask and not spend the time on it right now.

**Comment by timayhelen** [comment]
@SlavaET The way people describe it, I don't think that's what's happening. For some people, for whatever reason, animations are being reset every time they save in the VB.

I don't think the issue you described is high priority enough for us to worry about at the moment. Hopefully we can find out more about the original issue.

**Comment by SlavaET** [comment]
@timayhelen yeah, I see that my case is different, just wanted to mention so we can consider it for future updates.
I don't know what else to try right now though, we can request token from the customer or at least layout to see what's going on there. I can't see any errors in code or conflict of default values, so looks like it's something specific to user layout/settings.

**Comment by SlavaET** [comment]
I got it. As always, when you say there is nothing to try you find it, lol.
It has to do with the Customizer settings.
In the `Module customizer` -> `Image` set the animation to `No Animation` and then you'll be able to replicate the issue.
Working on it.

**Comment by SlavaET** [comment]
Fixed. Also found and fixed similar issue with divider module.
