### ISSUE TITLE
Unsaved Page Warning Always Appears In VB and BB

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1087]
## Unwanted Save Warning

Related Topics:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664554
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=663468
https://www.facebook.com/groups/DiviThemeUsers/permalink/1092801010849494/

> Prior to the current update on or before 3/10/2017 I have had to update the page twice in order to go view the page. It would ask "Stay on Page" or "Leave Page" unless I saved it again. Now after the update, I can't even leave the page without just leaving as if not saving. Even after saving/updating twice. It does save the page it seems but something is wrong.

I have seen this reported for both the BB and the VB separately. Since 3.0.35, many people are reporting that even after a successful manual save, when they try to leave the BB or the VB they still get greeted with the save warning:

![screen shot 2017-03-12 at 11 13 00 am](https://cloud.githubusercontent.com/assets/3333028/23834512/e34f5b18-0714-11e7-8716-4f4562289d3e.png)

<img width="432" alt="screen shot 2017-03-08 at 11 02 50 pm" src="https://cloud.githubusercontent.com/assets/3333028/23834503/cca3877c-0714-11e7-8c7a-58541660fa56.png">

It seems to be a common and frustrating issue since people have to keep exiting this dialog after editing their page. Saving seems to work fine, so it must have something to do with autosaves. 

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1826

**Comment by timayhelen** [comment]
An update on this. It looks like Auto Saves are created on every heartbeat, even if no changes have been made. Try this in the BB:

1. Enable the Divi Builder
2. Load a layout
3. Publish the page
4. Switch to a different tab in your browser and then come back to force a heartbeat
5. Refresh the page. 
6. You will get an Auto Saves notification and when you look at the diff you see that nothing changed:

![screen shot 2017-03-13 at 8 54 23 am](https://cloud.githubusercontent.com/assets/3333028/23862876/6ac7823a-07cb-11e7-9c7c-124041b782a2.png)

**Comment by lots0logs** [comment]
@Jronk 

- [ ] If the page is saved in one tab, the other tab will still show "Are you sure" message when trying to navigate away.
  1. Edit a page in one builder.
  2. Edit the same page in the other builder in a new tab.
  3. Make a change and save the page.
  4. Switch to the other builder.
  5. Try to close tab or navigate away from builder.
