### ISSUE TITLE
Call to undefined function et_fb_enabled()

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1089]
I have seen a few reports of this, after upgrading to Divi 3.0.35:

> Fatal error: Call to undefined function et_fb_enabled() in /public_html/wp-content/themes/Divi/includes/builder/ab-testing.php on line 659"

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664892
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664294
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664724
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664424
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664070

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1823

**Comment by SlavaET** [comment]
You may notice this error in debug log with 1hr interval. It happens because we're calling `et_fb_enabled()` in function which was called by cron. `et_fb_enabled()` is undefined at this point and it causes the error.

**Comment by FaycalBoutam** [comment]
@SlavaET Some customers still reporting this error after the update to 3.0.37. One of them created a staging site (revert back to 3.0.34 on the main site). Error appears on this page alone:
http://deaportal.dreamhosters.com/?page=gf_activation&key=47b76eec17c5b06e 
All other pages looks okay. 
Would you want me to request token+FTP info for this? Cause I have no idea how to fix it!

**Comment by SlavaET** [comment]
@FaycalBoutam It's the same issue, but root cause is different. I'll open a new ticket and submit a fix. No need to request token, I see what's wrong.

**Comment by SlavaET** [comment]
@FaycalBoutam here is the ticket with attached solution - https://github.com/elegantthemes/Divi-Beta/issues/1099
