### ISSUE TITLE
Imposible to reach text module menu

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#109]
### Problem:

When text in Text Moduel is too short it's impossible to click on module menu. So I can't delete it, move etc. 

### Steps To Reproduce:
1. Insert text module
2. Input short text, for example **Short text**

**Comment by dm-chechik** [comment]
Also I faced this problem with button module

**Comment by timayhelen** [comment]
Thanks for the report. There is another issue that reported this, so I am closing this as a duplicate.
