### ISSUE TITLE
Failed Save Modal Fires Even When Save Is Successful

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1091]
There have been a few reports of this, but I am unsure how to replicate it:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=665269
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=662857

![4dc28572-e318-11e6-8a84-11df03c0340b](https://cloud.githubusercontent.com/assets/3333028/23863698/9eb12e1e-07cd-11e7-9ed8-413cac7724c6.gif)

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1851

**Comment by fikrirasyid** [comment]
@lots0logs I've checked the forum and once you get the token from the user, can you inform it to me as well? My best guess of the cause of the issue is something (possibly plugin) causes an error and pollutes the returned AJAX request 🤔

**Comment by fikrirasyid** [comment]
The site mentioned on the thread uses caching plugin so it's pretty hard to deduct the plugin they're using. I think there's no way except for waiting for the customer token. 🤔

**Comment by timayhelen** [comment]
Looks like this definitely occurs in the BB when the page contains a global row or section.

**Comment by FaycalBoutam** [comment]
@fikrirasyid The site in the second ticket is using some js code that causes this problem. You'll find that on the very end of the source code page. It's related to: https://github.com/elegantthemes/Divi/issues/2880 meaning that a custom code is what's causing this problem. This is the code in question: `<script type="text/javascript">(function($) {
      
    function setup_collapsible_submenus() {
        var $menu = $('#mobile_menu'),
            top_level_link = '#mobile_menu .menu-item-has-children > a';
             
        $menu.find('a').each(function() {
            $(this).off('click');
              
            if ( $(this).is(top_level_link) ) {
                $(this).attr('href', '#');
            }
              
            if ( ! $(this).siblings('.sub-menu').length ) {
                $(this).on('click', function(event) {
                    $(this).parents('.mobile_nav').trigger('click');
                });
            } else {
                $(this).on('click', function(event) {
                    event.preventDefault();
                    $(this).parent().toggleClass('visible');
                });
            }
        });
    }
      
    $(window).load(function() {
        setTimeout(function() {
            setup_collapsible_submenus();
        }, 700);
    });
 
})(jQuery);</script> <script type='text/javascript'>/*  */
var _wpcf7 = {"recaptcha":{"messages":{"empty":"Please verify that you are not a robot."}},"cached":"1"};
/*  */</script> <script type='text/javascript'>/*  */
var et_pb_custom = {"ajaxurl":"https:\/\/www.yogameditation.com\/wp-admin\/admin-ajax.php","images_uri":"https:\/\/www.yogameditation.com\/wp-content\/themes\/Divi\/images","builder_images_uri":"https:\/\/www.yogameditation.com\/wp-content\/themes\/Divi\/includes\/builder\/images","et_frontend_nonce":"0f3f309a3a","subscription_failed":"Please, check the fields below to make sure you entered the correct information.","et_ab_log_nonce":"baaec54d59","fill_message":"Please, fill in the following fields:","contact_error_message":"Please, fix the following errors:","invalid":"Invalid email","captcha":"Captcha","prev":"Prev","previous":"Previous","next":"Next","wrong_captcha":"You entered the wrong number in captcha.","is_builder_plugin_used":"","ignore_waypoints":"no","is_divi_theme_used":"1","widget_search_selector":".widget_search","is_ab_testing_active":"","page_id":"842","unique_test_id":"","ab_bounce_rate":"5","is_cache_plugin_active":"yes","is_shortcode_tracking":""};
/*  */</script> <script type="text/javascript" id="slb_context">/*  */if ( !!window.jQuery ) {(function($){$(document).ready(function(){if ( !!window.SLB ) { {$.extend(SLB, {"context":["public","user_guest"]});} }})})(jQuery);}/*  */</script>`

**Comment by fikrirasyid** [comment]
@faycalBoutam thank you for providing the steps to replicate the issue! I successfully replicate the issue and notice what's wrong. I've submitted a PR to fix the issue.
