### ISSUE TITLE
All Values Replaced With "px" Units

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1092]
This is a rather important issues. In the past, the Divi Builder has accepted various units of measurement, depending on the field. "px" is used by default, but users can input %,em,rem,vw,vh, etc. In the latest version of Divi, all units are saved as "px" no matter what. If someone has customized their page using custom units in the past, saving the page will break their design. 

### Attached PR
* https://github.com/elegantthemes/submodule-builder/pull/1828

**Comment by timayhelen** [comment]
Noe this only happens in the BB.

**Comment by lots0logs** [comment]
@timayhelen Could you post exact steps to reproduce?

**Comment by lots0logs** [comment]
@Jronk The units are being stripped off of Mobile and Tablet range slider values upon saving.
