### ISSUE TITLE
Multiple Instances Of Global Modules Don't Sync In VB

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1093]
If you have multiple copies of the same global module, row or section on the same page, and you make a change to one of the instances in the VB, the rest of the copies should update to reflect the change. @fikrirasyid worked on this for a while and it was working great, but most likely shortcode trimming caused some issues. 

## Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1831

**Comment by timayhelen** [comment]
Here is the original PR that is no longer working: https://github.com/elegantthemes/Divi-Beta/issues/773

**Comment by lots0logs** [comment]
Identified the issue. PR coming shortly....
