### ISSUE TITLE
Save Warning Appears When Leaving BB When It Contains Global Section Or Row

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1094]
1. Create a page in the BB.
2. Add a Global Section.
3. Publish The page. 
4. Leave The Page
5. You will get a warning that unsaved changes will be lost, but you have no intended unsaved changes. 

<img width="360" alt="cca3877c-0714-11e7-8c7a-58541660fa56_720" src="https://cloud.githubusercontent.com/assets/3333028/23926847/cbd9b4c2-08d3-11e7-91e7-7f08438b6366.png">

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1833

**Comment by Jronk** [comment]
The TL;DR is `global_parent=##` attr gets added to the content, so that dirties the editor causing the issue..

**Comment by SlavaET** [comment]
Reopening this. Some more cases were encountered which should be fixed.
