### ISSUE TITLE
Prevent clicking on links

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#110]
### Problem:

When you click on an image or a blurb with a link, it takes you straight to the URL without showing a confirmation message. I find myself loosing my work with no way of getting it back. We should disable links like we have with the backend-editor.

**Comment by andyhqtran** [comment]
@timayhelen I think that all links should open in a new tab. That's what a lot of Visual Builders do.

**Comment by timayhelen** [comment]
Yeah that sounds fine to me.
