### ISSUE TITLE
Error When Restoring Auto Save

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1104]
I get the following error when attempt to restore an auto save when editing the homepage of our Divi Demo

https://www.elegantthemes.com/preview/Divi/

![screen shot 2017-03-23 at 4 57 26 pm](https://cloud.githubusercontent.com/assets/3333028/24275079/12964d9a-0fea-11e7-912d-1970e9c10344.png)

I figured it was due to the content on the page, so I tried export the layout and impoting it on localhost and performing the same auto save actions, however, no error occurs on localhost.

To reproduce this on the Divi Demo homepage, I simply did the following:

1. Open the page in the VB.
2. Delete on blurb module. 
3. Open the VB in a new tab to get the Auto Save prompt. 
4. Restore auto save, which generates the error above. 

Other pages in the demo work fine. It seems isolated to the homepage.

**Comment by timayhelen** [comment]
Updated, this seems to be caused by the Fullwidth Slider at the top of the page. When restore an Auto Save that does not contain this particular slider, it works fine. However, when testing this same slider exported to localhost I do not get any errors.

**Comment by lots0logs** [comment]
@timayhelen There's an A/B test running on that slider, right?

**Comment by timayhelen** [comment]
@lots0logs Not anymore, but there was at one time.
