### ISSUE TITLE
Divi Builder Email Sign Up + Mailchimp API Key not working

### ISSUE THREAD

**Issue by mmkdigital** [elegantthemes/Divi-Beta#1106]
Hey, I can't figure this one out. The API key connection to Divi seems to be set up and working properly, but when I try to test on the front end the form just gives me an internal server error. No new signups are coming through. Help?

It's the embedded sign up form on this page: http://quinmaxmedia.com/

![screen shot 2017-04-20 at 10 33 56 am](https://cloud.githubusercontent.com/assets/19536137/25239918/18b64b52-25b7-11e7-91c5-da357b609b93.png)

**Comment by lots0logs** [comment]
Hi, if you could, please open a ticket over in our [Support Forum](https://www.elegantthemes.com/forum) so that our team can take a look at this for you. Thanks for your cooperation :smiley:
