### ISSUE TITLE
Slide In Navigation issue in RTL version

### ISSUE THREAD

**Issue by veeren** [elegantthemes/Divi-Beta#1108]
### Problem:

Slide In navigation goes off in RTL version, menu close is not visible and when menu is opened page is getting scroll from left.

### Steps To Reproduce:
1.  Goto Appearance
2. Theme Customisation
3. Header & Navigation
4. Header Format
5. Header Style - > Slide In

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

** Macbook Air**:

**Mac OS 10.12.3**:

**Chrome**:

**11440x900**:

**Screenshot**:
[Screenshot - 1](http://prntscr.com/f5ddv1)
[Screenshot - 2](http://prntscr.com/f5djch)

**Comment by lots0logs** [comment]
Hi! Sorry for the delayed response. This Github repo is only used during Divi beta testing. If you still need assistance, please open a ticket in our [Support Forum](https://www.elegantthemes.com/forum). Thanks for your cooperation :smiley:
