### ISSUE TITLE
Global attributes

### ISSUE THREAD

**Issue by ilianiv** [elegantthemes/Divi-Beta#1109]
### Problem:

Please add some of the global HTML attributes to divi modules settings like:
 - title - very often used for on page SEO
 - tabindex - someone may need to configure tab key focus queue
 - data-* - useful for passing custom data to js script for example
 - ... any other global attribute ([see full list](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)) that you think may be useful

For example I need to add `title` attribute to my buttons and buttons in call-to-action module but there is no such an option at this point.

### Steps To Reproduce:
1. Add new button module
2. Open button settings
3. Try to set title attribute

### Additional Information:
Full list of global HTML attributes: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) or [w3schools](https://www.w3schools.com/tags/ref_standardattributes.asp)

**Comment by lots0logs** [comment]
Hi! Sorry for the delayed response. This Github repo is only used during Divi beta testing. If you could, please post your feature request in the [Theme Suggestions](https://www.elegantthemes.com/forum/viewforum.php?f=22) section of our Support Forum. Thanks for your cooperation :smiley:
