### ISSUE TITLE
Fixed menu overlaps text module settings menu

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#111]
### Problem:

When the text module is on top of the page the gray popup menu is under a fixed main menu.

### Steps To Reproduce:
1. Create a multi column row
2. Insert a text module. Use the second or third etc column not first
3. Make mouse over and menu appears under the fixed menu

### Screenshot:
![capture](https://cloud.githubusercontent.com/assets/20072036/17809053/96f217c2-661c-11e6-9862-15f9b0fe2282.jpg)

**Comment by uportnykh** [comment]
This will be fixed in https://github.com/elegantthemes/Divi-Beta/issues/120
