### ISSUE TITLE
Conversion Outline :: Unable to use convertFontIcon on conversion-outline.ts

### ISSUE THREAD

**Issue by carlfromfelton** [elegantthemes/Divi-Beta#111]
### Problem Description
Added to my conversion-outline.ts file the following code to handle the conversion of the icon font selection field 

```ts
import {ModuleConversionOutline} from '@divi/types';
import {convertFontIcon} from "@divi/conversion";


export const conversionOutline: ModuleConversionOutline = {
...
valueExpansionFunctionMap: {
       prev_icon: convertFontIcon,
        next_icon: convertFontIcon,
        overlay_icon: convertFontIcon,
    },
...
}
```

Describe what you expected to happen
Expect the D4 module to load the correct value for the icon selection when open for the first time on D5

Describe what actually happened
After saving the change on my conversion-outline.ts file, I get the following error in the console 

```
ERROR in ./src/components/dynamic-gallery/conversion-outline.ts 1:0-51
Module not found: Error: Can't resolve '@divi/conversion' in '/Users/carlos/Local Sites/dividev/app/public/wp-content/plugins/dp-divi-dynamic-gallery/src/components/dynamic-gallery'
```

### Related Links or Information
* Discord Discussion: [link](https://discord.com/channels/1041765492907589683/1303038805992800356)

### Screenshot and/or gif
![Screenshot 2024-11-05 at 7 45 07 AM](https://github.com/user-attachments/assets/22663f13-e249-428d-8b87-ad5a0ca0d0ce)
![Screenshot 2024-11-05 at 7 49 27 AM](https://github.com/user-attachments/assets/7aaa822c-7756-488e-9af5-0907d93ce445)
![Screenshot 2024-11-05 at 7 51 20 AM](https://github.com/user-attachments/assets/56df854b-70f4-42b5-b653-7c5bded1841a)

### System Information
* Divi version: 5.0.0-dev-alpha.2
* Operating System: macOS 14.15
* Browser: Chrome 130.0.6723.92
* PHP version: 8.3.11
* MySQL version: 8.0.16
* Web Server: Apache
* WordPress version: 6.6.2

**Comment by carlfromfelton** [comment]
It works if I use 

```ts
// @ts-ignore
const {convertFontIcon} = window?.divi?.conversion;
```

Instead of 
```ts
import {convertFontIcon} from "@divi/conversion";
```

**Comment by robicse11127** [comment]
As the issue gets resolved I am closing this one. 
Thanks.
