### ISSUE TITLE
Counter Module - Change comma to dot

### ISSUE THREAD

**Issue by andersonchagas** [elegantthemes/Divi-Beta#1110]
Various countries (including Brazil) uses dot (.) in place of comma (,) for big numbers.

We need some way to choose what to use.

**Comment by lots0logs** [comment]
Hi! If you could, please post your feature request in the [Theme Suggestions](https://www.elegantthemes.com/forum/viewforum.php?f=22) section of our Support Forum. Thanks for your cooperation :smiley:
