### ISSUE TITLE
Divi builder scripts on frontend site

### ISSUE THREAD

**Issue by backspinn** [elegantthemes/Divi-Beta#1111]
Just upgraded 2.0.13 to 2.0.28 and the WP site stopped working. I see that the frontpage adds script divi-builder.min.js (which none of my older sites with WP + DIVI does) and this gives error on $.browser.msie undefined in the console, I am using jquery 2.2.4 for the site which then of cause halts the scripts.

**Comment by lots0logs** [comment]
Hi, this repo is only used during official Divi beta tests. Please open a ticket in our [Support Forum](https://www.elegantthemes.com/forum) for assistance. Thanks for your cooperation :smiley:
