### ISSUE TITLE
Shop Module Limited Categories

### ISSUE THREAD

**Issue by bradleyputters** [elegantthemes/Divi-Beta#1112]
### Problem:

The Shop Module only displays 29 categories when I have the type set to Product Categories, even though I have more categories than that.

### Steps To Reproduce:
1.  Add new page
2. Add column
3. Add shop module
4. Type: Product Categories

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 200+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Clarifications requested from reporter or design team if needed
- [ ] PR(s) link added in main issue description area of issue
- [ ] Steps to reproduce proven solved
- [ ] Estimated points
- [ ] Proper code documentation 
- [ ] PR description has layman's description of problem and solution
- [ ] PR description has "Areas Affected" listed/explained 
- [ ] Test included and coverage acceptable
- [ ] Tests passed
- [ ] Ajax/Form used?
  - [ ] Nonce used
  - [ ] Perms checked 
  - [ ] Input sanitized
  - [ ] Input validated
- [ ] Database saved/updated?
  - [ ] Data sanitized
  - [ ] Data validated 
- [ ] Variable output
  - [ ] Properly escaped
  - [ ] Validated if applicable 
- [ ] i18n used

<strong>Quality Assurance</strong>
- [ ] PR(s) link added in main issue description area of issue
- [ ] PR description has layman's description of problem and solution
- [ ] PR description has "Areas Affected" listed/explained 
- [ ] Steps to reproduce passed
- [ ] No errors in console or output 
- [ ] Affected areas still functioning same
- [ ] Estimated points included

<strong>Design Review</strong>
- [ ] UI/design is to spec and/or acceptable 
- [ ] UX is to spec and/or acceptable 

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used?
  - [ ] Nonce used
  - [ ] Perms checked 
  - [ ] Input sanitized
  - [ ] Input validated
- [ ] Database saved/updated?
  - [ ] Data sanitized
  - [ ] Data validated 
- [ ] Variable output
  - [ ] Properly escaped
  - [ ] Validated if applicable 
- [ ] i18n used
- [ ] DRY
- [ ] Implementation acceptable
  - [ ] Scaleable solution, future safe
- [ ] Best practices used
  - [ ] Cleverness and grokage
  - [ ] ES6 use

**Comment by lots0logs** [comment]
Hi, please open a support ticket in [our forum](https://www.elegantthemes.com/forum). This repo is only used during Dive beta tests. Thanks for your cooperation :smiley:
