### ISSUE TITLE
Portfolio module causes Segmentation Fault

### ISSUE THREAD

**Issue by saiqulhaq** [elegantthemes/Divi-Beta#1113]
We have a page that use portfolio module

the page contains hundred projects

previously it was working fine, but now we added more projects, and only that page who not working, the others are fine

when I activated the WP_DEBUG, I found that there is a problem in this file Divi/includes/builder/class-et-builder-element.php

inside _shortcode_callback function,

```
$output = $this->{$shortcode_callback}( $atts, $content, $function_name, $parent_address, $global_parent, $global_parent_type );
```

I guess it's trying to load all contents into php buffer, but the memory is not enough, right?

**Comment by etstaging** [comment]
### QA Checklist
<strong>Reporter</strong>
- [ ] Helpful title used &nbsp;<img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Helpful title format:*** `Scope(s) :: One Sentence To Describe The Issue`
  * ***Example:*** `VB :: Floating Toolbar :: Jumps To Top Of Page`
- [ ] Detailed description <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
  * ***Description should usually be 150+ characters.***
- [ ] Steps to reproduce included <img src="https://assets-cdn.github.com/images/icons/emoji/unicode/274c.png" width="16" height="16"/>
- [ ] Image and/or gif

<strong>Developer</strong>
- [ ] Clarifications requested from reporter or design team if needed
- [ ] PR(s) link added in main issue description area of issue
- [ ] Steps to reproduce proven solved
- [ ] Estimated points
- [ ] Proper code documentation 
- [ ] PR description has layman's description of problem and solution
- [ ] PR description has "Areas Affected" listed/explained 
- [ ] Test included and coverage acceptable
- [ ] Tests passed
- [ ] Ajax/Form used?
  - [ ] Nonce used
  - [ ] Perms checked 
  - [ ] Input sanitized
  - [ ] Input validated
- [ ] Database saved/updated?
  - [ ] Data sanitized
  - [ ] Data validated 
- [ ] Variable output
  - [ ] Properly escaped
  - [ ] Validated if applicable 
- [ ] Proper RTL appearance
- [ ] i18n used

<strong>Quality Assurance</strong>
- [ ] PR(s) link added in main issue description area of issue
- [ ] PR description has layman's description of problem and solution
- [ ] PR description has "Areas Affected" listed/explained 
- [ ] Steps to reproduce passed
- [ ] No errors in console or output 
- [ ] Affected areas still functioning same
- [ ] Proper RTL appearance
- [ ] Estimated points included

<strong>Design Review</strong>
- [ ] UI/design is to spec and/or acceptable 
- [ ] UX is to spec and/or acceptable 

<strong>Dev Review</strong>
- [ ] Test(s) included and coverage acceptable
- [ ] Ajax/Form used?
  - [ ] Nonce used
  - [ ] Perms checked 
  - [ ] Input sanitized
  - [ ] Input validated
- [ ] Database saved/updated?
  - [ ] Data sanitized
  - [ ] Data validated 
- [ ] Variable output
  - [ ] Properly escaped
  - [ ] Validated if applicable 
- [ ] i18n used
- [ ] DRY
- [ ] Implementation acceptable
  - [ ] Scaleable solution, future safe
- [ ] Best practices used
  - [ ] Cleverness and grokage
  - [ ] ES6 use

**Comment by lots0logs** [comment]
Hi, please open a support ticket in [our forum](https://www.elegantthemes.com/forum). This repo is only used during Dive beta tests. Thanks for your cooperation :smiley:
