### ISSUE TITLE
Visual editor not visible and various formatting issues in WordPress 4.6

### ISSUE THREAD

**Issue by nicheprofitwebsites** [elegantthemes/Divi-Beta#113]
### Problem:

Opening a page created a few days ago using one of the Dvi 100 homepage templates and then clicking on the visual editor renders a page without any visible way to change text, add columns or sections. It also removed text formatting, colours, padding, background images, button styles and unhides sections. This was on the newest version of WordPress 4.6 which just released

### Steps To Reproduce:
1. Update WordPress to version 4.6
2. Open a pre-existing page created using the default Divi editor and click the Visual editor button

### Additional Information:

**Device**: Desktop computer

**Operating System**: Windows 10
 
**Browser**: Chrome Version 52.0.2743.116

**Screen Resolution**: 2560 x 1440

**40 second video of the issue**: [https://youtu.be/dg6Diej-ZYE](url) (Copy and paste the url if it does not open in Github)

**Screenshots**:
What the page should look like: [https://drive.google.com/open?id=0B7C0zbyJSPOWVDBxU0lHWXp3UEU](url) (Copy and paste the url if it does not open in Github)

What the page looks like in the Visual Builder: [https://drive.google.com/open?id=0B7C0zbyJSPOWV1pfZHlMaHdNYzA](url) (Copy and paste the url if it does not open in Github)

What the page looks like in the Default editor: [https://drive.google.com/open?id=0B7C0zbyJSPOWQnVVQzQyUThNREE](url) (Copy and paste the url if it does not open in Github)

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Can you export the layout and post a download link to the JSON file here? I am not able to replicate this problem, so it could be due to specific things in your layout. 

Do you have any Child Theme enabled? Try disabling that as well.

**Comment by nicheprofitwebsites** [comment]
No CSS or child themes used. It's pretty much a clean install of WordPress, Divi and basic plugins I use on all sites. 

However, after I submitted the issue I tried to use Visual Editor on some newly created pages but without any luck, I then started to disable plugins in case there was was a conflict somewhere. As it turns out (and you might be able to replicate it this time) that when the Yoast SEO plugin is enabled the visual editor won't load and the issue occurs, but with the plugin disabled the visual editor loads and functions as expected. 

The plugin is the Yoast SEO plugin in the WordPress directory and I have tried uninstalling it and re-installing Toast but there just seems to be some sort of conflict with this plugin _(and unfortunately it's quite a popular one)_ 
![image](https://cloud.githubusercontent.com/assets/21123117/17828530/c0b9729c-66d7-11e6-9c23-c136e2d02990.png)

**With the plugin de-activated...**
![image](https://cloud.githubusercontent.com/assets/21123117/17828542/ff8aacca-66d7-11e6-840d-74f7942ee865.png)

**no issue...**
![image](https://cloud.githubusercontent.com/assets/21123117/17828583/7ab1888c-66d9-11e6-9131-78eec20f8160.png)

**Comment by BrittanyAK** [comment]
I to am having the same problem - it does not load at all.  I only have Askmet, Divi Updater (I deactivate) and hello Dolly plugins installed.  I did update to Wordpress 4.6 BEFORE adding the divi Beta.  It just gets stuck on the four dots rotating

**Comment by BrittanyAK** [comment]
Also on a Windows 10, PC system

**Comment by timayhelen** [comment]
Thanks, we have a fix for this and it will be available in the next beta version.
