### ISSUE TITLE
Page Settings :: Custom CSS field font is not visible on focus

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#114]
### Problem:

![homepage portfolio elegantthemes](https://cloud.githubusercontent.com/assets/16414613/17811205/5d2e7830-6619-11e6-8718-438c21c3284b.png)

**Comment by FaycalBoutam** [comment]
Actually the issue is on every section, row module's custom CSS tab.

**Comment by timayhelen** [comment]
What browser are you using? Please use the Github issue template as it will help us identify the issue for easily.

**Comment by FaycalBoutam** [comment]
All of my browsers. I'm using the latest version of Chrome (52)/Firefox (48)/Edge (25.10) with Windows 10

**Comment by timayhelen** [comment]
Hmm it must be related to a customizer setting. Thanks, we will look into it.
