### ISSUE TITLE
Cntrl + Z Not working in Visual Editor

### ISSUE THREAD

**Issue by Dmobley317** [elegantthemes/Divi-Beta#115]
### Problem:

The option to use Cntrl+Z shortcuts from the keyboard is non-existent. This is a problem power users and developers that rely on shortcuts when building.

### Steps To Reproduce:
1. Go to any page in Visual Editor
2. Modify page
3. Use Crtl+Z
4. Nothing Happens

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac Desktop

**Operating System**: EL Cap 10.11.5

**Browser**: Chrome v52.x

**Screen Resolution**: 2560x1440

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄
