### ISSUE TITLE
Copy of Element in Visual Editor

### ISSUE THREAD

**Issue by Dmobley317** [elegantthemes/Divi-Beta#116]
### Problem:

There is no notice of element having been duplicated in Visual Editor. 

If you duplicate any section or element in the VE and it drops below your viewable window area, there is no warning of it happening. 

There should at least be the little green check mark that appears, but a modal window with a response would be better.
### Steps To Reproduce:

1.
2.
3.
4.
### Additional Information:

_Please include any of the following details that are relevant to the issue you are reporting._

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:
## 
#### Before submitting your issue, please ensure the following:
- You searched this Github repo for the issue and found no open reports of the issue.
- You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- You have provided a detailed description of the issue.
- You have provided any/all relevant information: screenshot, screencast, page URL.
- You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
I think this can be addressed by adding a fade/scale in animation for modules when:

1. New modules are added.
2. Modules are duplicated
3. Modules are pasted.

**Comment by Dmobley317** [comment]
That sounds great!

**Comment by SlavaET** [comment]
@timayhelen I added the same effect as we use when module dropped into new location. Please let me know if we need to use a different effect for this.
