### ISSUE TITLE
Visual Builder : Editing Difficult For Closely Placed Elements

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#117]
### Problem:

When the elements are too closed , it created trouble editing them and there is some hover issue as well. it is difficult to explain the issue fully with snapshot or licecap , please follow below on how to replicate

### Steps To Reproduce:
1. Load Home Extended layout on any page 
2. Try editing the text as shown in image below
3. you will not be able to edit it at all due to hover issue and location of edit toolbar
![home extended](https://cloud.githubusercontent.com/assets/13402626/17812247/da0c7382-6643-11e6-845f-3e1dceb7cbe4.PNG)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
There is already an issue open for this, so I am going to close this duplicate. Thanks!
