### ISSUE TITLE
Settings Panel in Visual Editor

### ISSUE THREAD

**Issue by Dmobley317** [elegantthemes/Divi-Beta#119]
### Problem:

There should be an option to place the settings panel on the right and underneath everything as well. You have the button available for placing it on the left, but I would like the ability to snap it to a location based on what I'm doing and not having to drag it, though I could. 

If it could snap to the bottom as full-width that would also be pretty cool. 

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by andyhqtran** [comment]
@Dmobley317 you have the options to snap it to either left or right.

![image](http://g.recordit.co/hAeNGR9xPA.gif)
