### ISSUE TITLE
Divi Libary not loading on custom post types

### ISSUE THREAD

**Issue by LeadWP** [elegantthemes/Divi-Beta#12]
Some people have activated the page builder on custom post types and since the last few updates, the library does not seem to be loading on custom post types anymore.

For instance, if you created an email signup from pages and try to add it WooCommerce product page it will not display that module in your library.

This is not exactly Divi 2.7 related but it something that should be fixed in the Divi core.

**Comment by SlavaET** [comment]
Do you mean Global Modules not loading on front-end if you add it on the Product post type?
If not, please provide more details, so we can better understand the issue.

**Comment by LeadWP** [comment]
None of the stuff that had been created on pages, post or projects and saved to the library show on any custom post types creation page, when I try you try to add from the library.

**Comment by SlavaET** [comment]
Ah, that's correct. Any library items you save into library are assigned to the post type you created it from, so if you Saved the item from `Page`, then it'll not be visible on `Product` post type, but will be visible for `Project` and `Post`, because `Post`, `Page` and `Project` post types considered as Standard by Divi theme and share the same layouts. 
There is a filter which allows you to modify the list of Standard post types. So you can use the `et_pb_standard_post_types` filter to add your custom post types into list of Standard post types.

**Comment by sonicviz** [comment]
Hi,
"There is a filter which allows you to modify the list of Standard post types. So you can use the et_pb_standard_post_types filter to add your custom post types into list of Standard post types."

Could you elaborate on this with an example?
I can add divi builder to a pods custom post type, but also have issues getting saved layouts to show up when trying to add them when creating.

**Comment by theeternalsw0rd** [comment]
I don't see any layouts let alone saved ones.

**Comment by theeternalsw0rd** [comment]
Seems like et_pb_standard_post_types doesn't even exist anymore. I've seen to use et_pb_show_all_layouts_built_for_post_type but that is not working for me.

**Comment by theeternalsw0rd** [comment]
et_pb_show_all_layouts_build_for_post_type did work. Just had a browser glitch that the options were not visible.

```
function myprefix_et_pb_show_all_layouts_built_for_post_type($post_type) {
    $similar_post_types = array( // list of all post types to support
        'post',
        'page',
        'chapel_menu',
    );

    if ( in_array( $post_type, $similar_post_types ) ) {
        return $similar_post_types;
    }

    return $post_type;
}
add_filter('et_pb_show_all_layouts_built_for_post_type', 'myprefix_et_pb_show_all_layouts_built_for_post_type');
```

**Comment by swinterroth** [comment]
@theeternalsw0rd Thanks for sharing this snippet. SAVED me hours!
