### ISSUE TITLE
Row Settings, Custom Margin and Custom Padding "titles" missing ... top bottom left right

### ISSUE THREAD

**Issue by TAGdigitalDesign** [elegantthemes/Divi-Beta#121]
### Problem:

When going to adjust custom padding on row settings , would be nice if there was the top left bottom right description under gray shaded px boxes.

### Steps To Reproduce:
1. new row
2. insert text
3. design
4. no descriptions under custom margin and custom padding

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: n/a

**Operating System**: n/a

**Browser**: n/a

**Screen Resolution**: n/a 

**Screenshots**:

![image](https://cloud.githubusercontent.com/assets/21128505/17817103/af98f62c-660a-11e6-8097-3bacdac59d01.png)

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
@TAGdigitalDesign We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄
