### ISSUE TITLE
Google PageSpeed Insights *IMPORTANT*

### ISSUE THREAD

**Issue by Chris-netleaf** [elegantthemes/Divi-Beta#125]
**Problem:**

The theme still has several JavaScript and CSS issues that aren't Google friendly. This has never been addressed in any updates since the very first day Divi was born. I totally understand that you must prioritize lots of things before this, but you should REALLY consider fixing this before release or asap. As Google starts to rely more and more on speed factors, this gives Divi a disadvantage right off the bat over other great themes currently on the market.

Current desktop score with Divi : 86
Current desktop score with Divi : 75

Both scores could be way above 90 if this gets fixed.

**Steps To Reproduce:**
1. Install Divi on your website.
2. Design anything on any page.
3. Run a test here : https://developers.google.com/speed/pagespeed/insights/

**Additional Information:**

Here are the current issues that we get right from the start both on mobile and desktop : 

**Remove render-blocking JavaScript:**
…-includes/js/jquery/jquery.js?ver=1.12.4
…s/jquery/jquery-migrate.min.js?ver=1.4.1

**Optimize CSS Delivery of the following:**
http://fonts.googleapis.com/…0,300,600,700,800&subset=latin,latin-ext
…-content/themes/Divi/style.css?ver=2.9.9
…/shortcodes/css/shortcodes.css?ver=2.9.9
…/css/shortcodes_responsive.css?ver=2.9.9
…lder/styles/magnific_popup.css?ver=2.9.9

**Minify JavaScript
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 9.6KiB (27% reduction).**
Minifying …lder/scripts/frontend-builder-scripts.js could save 6.4KiB (26% reduction) after compression.
Minifying wp-content/themes/Divi/js/custom.js could save 3.1KiB (33% reduction) after compression.

**Minify CSS for the following resources to reduce their size by 4.9KiB (11% reduction).**
Minifying wp-content/themes/Divi/style.css could save 4.9KiB (11% reduction) after compression.

**Device**: Not relevant to this issue.

**Operating System**: Not relevant to this issue.

**Browser**: Not relevant to this issue.

**Screen Resolution**: Not relevant to this issue.

**Screenshots**: Not relevant to this issue.

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the input Chris. This update is 100% focused on the new visual builder, and it doesn't address anything related to what's loaded on the page. We have an upcoming Developer release where we will be looking to performance issues. That being said, the best way to deal with render blocking JS and CSS/JS minification is via a plugin, since it will work outside the scope of the theme and combine and minify assets that are enqueued by WordPress and by other plugins.

**Comment by Chris-netleaf** [comment]
This is what we currently do and it works well (even tho we had some issues in the past). Still, not everyone has the knowledge about the existence of this issue.

May I ask if you guys have any plan to fix it in your Developer release?

**Comment by timayhelen** [comment]
We can fix some of it, but like I said it's better to use a plugin that also addresses scripts enqueued by WordPress, such as jQuery. We will be exploring all performance-enhancing avenues in Divi 3.1.
