### ISSUE TITLE
Jetpack Compatibility Issue

### ISSUE THREAD

**Issue by sosensible** [elegantthemes/Divi-Beta#126]
### Problem:

I went to an existing page on the front end. After two attempts the admin button is gone, and going to the edit page we see the page was converted to a divi page. Clicking the Use Visual Builder button did not get us working either.

### Steps To Reproduce:
1. Go to an existing page
2. Click the "Enable Visual Builder"
3. Seeing no edit features, click the button again.
4. Still no edit features, and now no button.

### Additional Information:

I found similar issues with two sites. On my roundliving.com site (work in progress), some pages worked and it shows a spinner type thing when page is loading. On my www.lvq.today site, nothing seems to be working right with the new editor.

**Comment by timayhelen** [comment]
Can you try clicking Inspect Element in Chrome, and then enabling the builder and let us know if you see any messages in the console log?

**Comment by sosensible** [comment]
I got this response.

bundle.js?ver=2.9.9:7 Uncaught Invariant Violation: Minified React error
#37; visit
http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for
the full message or use the non-minified dev environment for full errors
and additional helpful warnings.

but that was clicking through from the post editor. The button produced
this error...

bundle.js?ver=2.9.9:7 Uncaught Invariant Violation: Minified React error
#37; visit
http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for
the full message or use the non-minified dev environment for full errors
and additional helpful warnings.

So same results from both sides.

**Comment by jamesrayth** [comment]
I'm seeing the same issue. I started with a blank page went straight to the visual editor but it loaded a preview of the new page, nothing was clickable. I then loaded a page template from the library, saved as draft, and tried the visual editor again, still no dice.

I'm seeing two errors in the console:

bundle.js?ver=2.9.9:7 Uncaught Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

I'm attaching the HAR export as txt.
[d3-frontend-error.txt](https://github.com/elegantthemes/Divi-Beta/files/428049/d3-frontend-error.txt)

**Comment by VerbalCA** [comment]
Just a note that I am experiencing the same problem. Running site on Wordpress 4.6 if that helps. Chrome  51.0.2704.103 on Mac OS X Yosemite. 

Error messages are the same with an additional one:

bundle.js?ver=2.9.9:7 Uncaught Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
n 

@ bundle.js?ver=2.9.9:7_renderNewRootComponent @ bundle.js?ver=2.9.9:32_renderSubtreeIntoContainer @ bundle.js?ver=2.9.9:32render @ bundle.js?ver=2.9.9:32(anonymous function) @ bundle.js?ver=2.9.9:2t @ bundle.js?ver=2.9.9:2(anonymous function) @ bundle.js?ver=2.9.9:2(anonymous function) @ bundle.js?ver=2.9.9:2

util.js:207 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

util.js:207 Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key

**Comment by SlavaET** [comment]
Do you guys have Yoast SEO plugin activated? Try disabling it if yes.

**Comment by VerbalCA** [comment]
I don't have Yoast on this website but I do have iThemes security activated, wonder if that could be causing an issue?

**Comment by SlavaET** [comment]
Please try disabling all plugins and check.

**Comment by sosensible** [comment]
OK, it works right when I toggle Yoast SEO to inactive. This is a serious
conflict because many of my sites, users sites are using Yoast. Hope this
fix is easy to come by.

**Comment by SlavaET** [comment]
Don't worry, the fix is ready, so it'll be included into next beta version :)

**Comment by jamesrayth** [comment]
I have Yoast, but disabling it didn't fix the issue. 

I have the following plugins:

1. All In One SEO Pack
2. Bloom
3. Elegant Themes Divi Beta Tester
4. ET Anticipate Maintenance Plugin
5. Jetpack for WordPress.com
6. Monarch Plugin
7. WooCommerce
8. WooCommerce Amazon Payments Advanced Gateway
9. WooCommerce PayPal Powered by Braintree Gateway
10. WP Super Cache
11. Yoast SEO

I disabled Yoast first, still didn't load the front end.
Next I disabled All In One SEO Pack, still didn't load.
Then WP Super Cache, then the WooCommerce gateways, then WooCommerce, interface still didn't load. 
That left only Jetpack and Elegant Themes plugins.
It was Jetpack.
I'm sure it goes without saying, that's a big deal.

Once it was narrowed down to Jetpack I added back WooCommerce, the payment gateways, all in one seo pack, and wp super cache and it still worked.

I then tried Yoast, and it surely broke again.

So there's two plugins causing it: Yoast and Jetpack.

**Comment by SlavaET** [comment]
@jamesrayth which modules in Jetpack do you use?

**Comment by jamesrayth** [comment]
@SlavaET Sorry for delay in response, got slammed. 

I just used the default JetPack "Jump Start" settings (it gives you a button upon installing saying "lets jump start your site!" or something to that effect). It activates the following modules:

- Beautiful Math
- Carousel
- Contact Form
- Custom CSS
- Custom Content Types
- Enhanced Distribution
- Extra Sidebar Widgets
- Gravatar Hovercards
- JSON API
- Notifications
- Omnisearch
- Photon
- Post by Email
- Protect
- Publicize
- Related Posts
- Sharing
- Shortcode Embeds
- Single Sign On
- Site Stats
- Spelling and Grammar
- Subscriptions
- WP.me Shortlinks
- Widget Visibility

**Comment by jamesrayth** [comment]
I went through and tested each module that activates with the "Jump Start" to see where it breaks, there's two that break divi visual builder:
Publicize
Sharing

I then went and added all the other modules just to see if any other ones broke, and the rest worked fine. So its just Publicize and Sharing that are breaking it.

**Comment by SlavaET** [comment]
@jamesrayth can you please confirm that the issue with jetpack modules exist in the latest version of Beta?
I checked the Sharing ( and all other modules available in Development mode of Jetpack ) and it works fine.
I cannot check the Publicize module on localhost though.

**Comment by jamesrayth** [comment]
@SlavaET Both Publicize and Sharing can be activated without breaking the visual builder now. Looks like this is resolved.

**Comment by SlavaET** [comment]
Great! Closing this issue then.
@jamesrayth thanks for confirming. Feel free to open a new ticket if you find conflicts with any other plugins.

**Comment by VerbalCA** [comment]
Can confirm this is now working for me too. Going to get stuck in now!

**Comment by WarenGonzaga** [comment]
jetpack plugin looks like conflict with divi builder

**Comment by WarenGonzaga** [comment]
I'm getting this error:

Failed to load resource: the server responded with a status of 502 () --> /wp-admin/admin-ajax.php

The Divi Builder is loading forever!

**Comment by lots0logs** [comment]
Hi, please open a support ticket in [our forum](https://www.elegantthemes.com/forum). This repo is only used during Dive beta tests. Thanks for your cooperation :smiley:
