### ISSUE TITLE
FB :: Performance :: Modal slows overall performance

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#127]
### Problem:
When the `Modal` component is opened, it causes some performance issues with the page setting bar toggle. From the looks of it, the `Modal` component is getting re-rendered every time you toggle the page settings bar.

### Steps To Reproduce:
1. Open any Modal that uses `modal/index.js`
2. Open React Dev Tools and check **Trace React Updates**
3. Toggle the Page Settings

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Macbook Pro 15" Retina

**Operating System**: macOS

**Browser**: Chrome

**Screen Resolution**: 1440x900

**Screenshots**:
![image](http://g.recordit.co/m9idfLhkef.gif)

**Comment by andyhqtran** [comment]
It seems that having the modal also effects performance for any animation related content. 
- Inline Editor has a slight lag when popping up.
- Clunky animation when resizing screen using the responsive toggles.
- React Ink abruptly stops midway when clicking on it.

**Comment by Jronk** [comment]
- [ ] Clicking save hangs up, doesn't ever complete (unless you toggle off/on the page settings bar again)

**Comment by timayhelen** [comment]
This is still happening for me:

- [ ] Typing inside of modal inputs is very glitchy, and it doesn't recognize every ~4th letter while I am typing. So if I type at a semi-fast speed, all of my words are missing letters. UPDATE - looks like this is an issue in the main branch as well actually.

Also:

- [ ] Looks like there is an issue with the new page settings snap feature. You can not drag the page settings bar to the top of the page. It works in this branch, but the purple circle does not follow your cursor as it does in the main branch. 

- [ ]  The [X] cancel button in page settings modal doesn't work. It doesn't correctly cancel the changes made. It cancels some of the changes, but not all of them.

**Comment by Jronk** [comment]
@timayhelen those latest 3 issues are addressed

**Comment by timayhelen** [comment]
Re-opening this since the PR was not merged.
