### ISSUE TITLE
Firefox Visual Editor Shows Blank Page

### ISSUE THREAD

**Issue by VirtualVisionary** [elegantthemes/Divi-Beta#128]
# Problem:

When I try to use the Visual Editor using the latest version of Firefox, I get a completely blank page. Reload does not work either. 

### Steps To Reproduce:
1. Go to Edit on any page in Dashboard
2. Click Use Visual Editor, next to Use Divi Builder
3. Fades to blank page
4. Reload also shows blank page

### Additional Information:
Inspect Element Console in Firefox shows this Error message in the Server tab:

Error: Permission denied to access property "apply"

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC Laptop

**Operating System**: Windows 10

**Browser**: Firefox 47.0

**Screen Resolution**: 1920x1080

**Screenshots**:
See attached
![beta test visual editor blank page](https://cloud.githubusercontent.com/assets/21133555/17826532/976b4b38-663f-11e6-9d50-aae380775fb8.PNG)
![beta test page builder view](https://cloud.githubusercontent.com/assets/21133555/17826533/9777507c-663f-11e6-9370-737e5144e40e.PNG)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
Hi @VirtualVisionary , the latest version of Firefox is actually 48. Could you try installing the latest update? If the issue persists, please try it while in Private Browsing Mode. Let us know the result. Thanks!

**Comment by jamesrayth** [comment]
Yoast was breaking the visual builder until the update that was released today. Try it again after getting the newest update.
