### ISSUE TITLE
Cannot Load Layout 

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#129]
### Problem:

Predefined layouts on page bar hangs on loading state.

### Steps To Reproduce:
1. Create new page, open in VB
2. Toggle page settings bar
3. Click load layout icon (the leftest icon)
4. The tooltip hangs in loading state.

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Screen-shot or Screen-cast**:
![hangs on loading state](https://cloud.githubusercontent.com/assets/916442/17827130/7c9a94c2-66a2-11e6-9c11-8afcc2e2cb95.gif)

**Link To Download Layout JOSN File**:
This happens on any layout

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@fikrirasyid it works for me although it does take quite a while. Also the Ajax request is supposed to happen in the background when the app launches, and I am not sure if that's happening anymore.

**Comment by fikrirasyid** [comment]
@timayhelen ah I see. with this length of loading time (it's still not loading the layout list on my FB), I think it'll be perceived as bug tho. We need to speed the loading time up 🤔

**Comment by timayhelen** [comment]
Yeah, we need to do it a different way I think.

**Comment by websbyjd** [comment]
For what it's worth, it does load instantly on windows box

**Comment by SlavaET** [comment]
I tested and it works instantly for me. I can see the loading icon for 1-2 seconds only if I immediately click `Load Layouts` button after page refresh. In all other cases I don't see the loading at all.
@fikrirasyid do the predefined layouts work fine in BB for you?

**Comment by fikrirasyid** [comment]
It works fine in BB for me. I checked the network tab and found this tho:

![allowed memory size](https://cloud.githubusercontent.com/assets/916442/17893916/a777affa-6971-11e6-9002-78b072a37631.jpg)

**Comment by SlavaET** [comment]
@fikrirasyid how many layouts do you have beside the predefined? Can you export them and send to me for testing? Also, try clearing your browser cache and cookies, just in case. Do you have any plugins?

**Comment by fikrirasyid** [comment]
@SlavaET I have 111 items on my library. I've sent the exported XML file to you via Slack.

I've tried clearing browser data, but still no luck. I have 13 active plugins. I've deactivated them all, but it still doesn't work. Probably has something to dow with the number of items I have on the library 🤔

**Comment by SlavaET** [comment]
@fikrirasyid thank you for provided details and layouts pack! Finally was able to reproduce the issue, looks like 111 layouts is too many to retrieve in a single request. Working on fix.

**Comment by SlavaET** [comment]
@fikrirasyid can you please check whether your library items are loading with my PR or not?

**Comment by fikrirasyid** [comment]
@slavaET I've tested it and I can confirm that your PR works. Thanks!

**Comment by SlavaET** [comment]
Great. Frontend Builder will retrieve the library items by small portions of 50 items and should work fine with any library size.
