### ISSUE TITLE
Missing RangeContainer Properties

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#13]
### Background:
In Divi 4.0, the `range` field accepted the `fixed_unit` and `unitless` properties. The `fixed_unit` property ensured that only one unit type could ever be entered into a range field. The `unitless` property allowed the range field to function without any units.

### Problem:
Both these properties seem to be missing in the current implementation of `<RangeContainer>`.

**Comment by dtcblyth** [comment]
I should add that it **is** currently possible to emulate these behaviours in D5.

The `unitless` behaviour can be achieved like this:
```
<RangeContainer
    min={1}
    minLimit={1}
    max={10}
    step={1}
    allowEmpty={false}
    allowedUnits={['']}
    defaultUnit=""
    validateUnit
/>
```
The `fixed_unit` behaviour can be achieved like this:
```
<RangeContainer
    min={1}
    minLimit={1}
    max={100}
    step={1}
    allowEmpty={false}
    allowedUnits={['px']}
    defaultUnit="px"
    validateUnit
/>
```
So, I guess the real question is whether it’s necessary to make these behaviours explicitly set with `unitless` and `fixedUnit` attributes.

**Comment by lanresmith** [comment]
Thanks @dtcblyth for the observation. After some consideration, we decided that since it can be achieved [the way you've described](https://github.com/elegantthemes/Divi-Beta/issues/13#issuecomment-1500031793), then that's fine.
