### ISSUE TITLE
Question about "copy" and "paste after" functionality…

### ISSUE THREAD

**Issue by rtwintp** [elegantthemes/Divi-Beta#13]
### Problem:

Lots of cool new features… But, when I right click on a section, I no longer see the "copy" or the "paste after" items, which I use frequently. Has this functionality been altered?

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
This functionality has not been removed or altered. Can you provide us with the missing information in your ticket and also make sure you disable all plugins and child themes?

**Comment by rtwintp** [comment]
Okay, I have disabled plugins and child theme temporarily to test. But, when I right click on a section I still see the menu items, including the new "Split Test" but not "Copy" or "Paste." Sorry if I am missing something obvious; I was unable to label the issue as a question, as opposed to a bug.
![previous version](https://cloud.githubusercontent.com/assets/17971106/13913617/de04b2a2-ef05-11e5-82a1-cc6bb021fb1f.png)
![current beta version](https://cloud.githubusercontent.com/assets/17971106/13913624/e61f94a2-ef05-11e5-946e-082a88f9cbf7.png)

WEBSITE: http://www.winerybrochures.com/

OS X 10.11.3
Chrome (current)

**Comment by SlavaET** [comment]
@timayhelen I can reproduce the issue and I see where it comes from. I can take a look into it.
