### ISSUE TITLE
Can't use ampersand in title fields

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#133]
### Problem:

Using non ASCII in title field is converted to html & amp ; on save.  Tested in Blurb, Circle Counter, Tabs, Accordions, and in Testimonials (author name)    

Updated this after testing with several other non ASCII characters
 
### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. We already have an issue open for this, so I am closing this duplicate.
