### ISSUE TITLE
Create a functionality to edit the footer credit

### ISSUE THREAD

**Issue by adilsoncosta** [elegantthemes/Divi-Beta#134]
### Problem:

Not a problem but an improvement that would like it to be implemented.

It would be interesting to create a function so we could edit the footer credits without the need to edit the default theme code.

Could maintain the credits editing option and another allowing the Elegant Theme credit information, something very subtle, as an icon (logo) or something like that!

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the suggestion. This beta test is focused on testing new Divi 3.0 functionality only, so I am closing this ticket for now.
