### ISSUE TITLE
Menu and Footer not shown in Visual Builder if not in Full Screen Mode

### ISSUE THREAD

**Issue by kingdomstudios** [elegantthemes/Divi-Beta#135]
### Problem:

When editing a page in Visual Editor in other than Full Screen Mode, the Menu and Footer do not render. They do render on the actual device, however. This means that the editor is not reflecting that which will be displayed.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Laptop**:

**Windows 10**:

**Chrome**:

![screenshot](https://cloud.githubusercontent.com/assets/16942309/17828349/84b2068e-6654-11e6-91a9-6154a49513e6.png)

**Comment by lots0logs** [comment]
@kingdomstudios Thanks for the report. Currently the Visual Builder supports desktops only (screen resolutions of 1366px and up). We'll consider adding support for tablets in a future release though! :smiley:
