### ISSUE TITLE
Two Modals Open; None Will Close

### ISSUE THREAD

**Issue by mwsmedia** [elegantthemes/Divi-Beta#136]
### Problem:
When Full Width Header Settings modal is open and pinned to the side, if the bottom ellipses menu is opened and Load Layout is selected, both modals cannot be closed (their close buttons no longer work

**Device**: Desktop Computer

**Operating System**: Windows 10

**Browser**: Chrome

**Screen Resolution**: 2560 x 1080

**Server**: Local WAMP installation

**Comment by timayhelen** [comment]
Thanks for the input. We already have an issue opened for this bug, so I am closing this duplicate.
