### ISSUE TITLE
Custom CSS in modules not applying in Visual Builder after upgrade

### ISSUE THREAD

**Issue by Kaessa** [elegantthemes/Divi-Beta#137]
### Problem:

Replace this section with a description of the issue you are reporting. Be sure to explain the expected results vs. actual results when it might not be obvious to those who will read your report. 

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  Load site with custom CSS in individual modules
2. Enable Visual Builder
3. Observe that site CSS doesn't load.

Before enabled
![home andrea gatley about me before](https://cloud.githubusercontent.com/assets/400823/17828694/06532e14-6657-11e6-8bed-1780a4380926.png)

After enabled
![home andrea gatley about me after](https://cloud.githubusercontent.com/assets/400823/17828695/098b6876-6657-11e6-8d64-5363a76e6afe.png)

### Additional Information:

See before and after shots

*Please include any of the following details that are relevant to the issue you are reporting.*

PC
Windows 10 w/latest updates
Chrome
3440x1440

Layout JSON File:

https://www.dropbox.com/s/dbv0m17bn5xucuy/Divi%20Builder%20Layout.json?dl=0

**Comment by SlavaET** [comment]
@Kaessa I checked your layout and it works perfectly in Visual Builder. 
I noticed that you have Yoast plugin enabled on your website and it may cause the issue. Please try disabling this plugin and check again. 
The issue with Yoast plugin will be fixed in next beta version.

**Comment by Kaessa** [comment]
That worked! Disabled Yoast and everything works fine now.
