### ISSUE TITLE
CSS Syntax Highlighting (And contrast issue) 

### ISSUE THREAD

**Issue by muffinjello** [elegantthemes/Divi-Beta#138]
This is more of a bunch of suggestions on my part, apologies if it's already been suggested and I missed it in my searching.

- [ ] Text color when input selected has very poor contrast (Dark on dark) ![Screenshot](https://cdn.pbrd.co/images/aMVBmDd3v.png)
- [ ] When editing a module (i.e. Text settings), place CSS ID and CSS Class on the same line. While extra margins help with a 'minimal look', a lot of the time I'm using the tiny editor box: Meaning every time I want to edit the main css, I can't do so without scrolling a fair amount. ( :arrow_up: usability)
- [ ] Better code module/custom css writing. Allow for tabs and indentation, even if syntax colouring is  out of the picture. Sorely lacking (and missed). I love how we can easily add CSS to any module/row/section, but the current implementation makes me want to resort to an external code editor for all of three lines of CSS (or custom JS that I add)

**Comment by timayhelen** [comment]
Thanks for the input. There is already an issue opened for this bug, so I am closing this duplicate.
