### ISSUE TITLE
Difficulty selecting edit button for modules (Disappears on hover)

### ISSUE THREAD

**Issue by muffinjello** [elegantthemes/Divi-Beta#139]
### Problem:

The edit tools for modules hangs slightly out of the hover "activation" area, with the end result being the controls disappearing when trying to use them, due to the system registering the user as no longer being focused on that module (and consequently, hiding the controls).

### Steps To Reproduce:
1.  Create a new page with Divi
2.  Enter the visual editor
3.  Add a Section -> Row -> Module (in my case, Code module). Leave row/section paddings the default
4.  Try to select the edit controls (from hover). Sometimes this doesn't happen.

### Additional Information:

Might be related to https://github.com/elegantthemes/Divi-Beta/issues/83
There's also a side issue shown here.. with the blank template, sometimes these edit controls will be off the screen (or in this case, hiding under the wordpress admin bar :-1:)

**Browser**: Chrome on windows 10, at WHD (2560 x 1080)

![Demo](https://cdn.pbrd.co/images/aNclvAw0m.gif)

**Comment by timayhelen** [comment]
Thanks for the input. We already have an issue open for this, so I am closing this as a duplicate.
