### ISSUE TITLE
Page Settings in Chrome showing different and useless

### ISSUE THREAD

**Issue by witkinss** [elegantthemes/Divi-Beta#14]
### Problem:

Page Settings in Chrome showing different and useless (see image attached).  It is working and different in Firefox.

### Steps To Reproduce:
1.Nothing to add
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Windows 7

**Browser**: Chrome-version is 49.0.2623.87

**Screen Resolution**:n/a

**Screenshots**:

-
![css-not-working](https://cloud.githubusercontent.com/assets/12988697/13919125/5f03d3c6-ef4a-11e5-9baf-dc2b7b4ff992.jpg)

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@witkinss looks like the cache issue. Can you please clear the cache in your Chrome browser and check again?

**Comment by witkinss** [comment]
You're right Slava, cache issue!  It works now. Tks.
