### ISSUE TITLE
Missing ButtonOptionsContainer Properties

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#14]
### Background:
In Divi 4.0, the `multiple_buttons` field accepted the `toggleable` property. This property prevented the user from deselecting all buttons, and ensured that at least one button was selected at all times. When a user attempted to deselect all buttons, the `default` button was automatically re-selected.

### Problem:
This property seem to be missing in the current implementation of `<ButtonOptionsContainer>`. If this functionality is not implemented it will lead to unpredictable behaviour and potential fatal errors in existing modules which expect to always receive a value from a `multiple_buttons` field.

This may well be the cause of the `Heading Level` bug [described here](https://github.com/elegantthemes/Divi-Beta/issues/4).

**Comment by lanresmith** [comment]
Kindly see [this comment](https://github.com/elegantthemes/Divi-Beta/issues/13#issuecomment-1544420347).
