### ISSUE TITLE
Shop Module :: Include Categories option missing

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#145]
### Problem:

When you display the products by categories, the option to select the categories is missing:

![sans titre 2](https://cloud.githubusercontent.com/assets/16414613/17834372/83e95004-6735-11e6-8068-e313d1f7d5ad.jpg)

![sans titre 6](https://cloud.githubusercontent.com/assets/16414613/17834388/28d51102-6736-11e6-9884-d9929794fec4.jpg)

**Comment by timayhelen** [comment]
@SlavaET I tested this, but I don't see any category options. I ensured that cached was cleared and that I was on the right branch. I am testing on Homepage Extended with the addition of a Shop module in the first standard section.

**Comment by SlavaET** [comment]
@timayhelen make sure you selected `Product Category` in the `type` option if Shop module:
![product-cat-option](https://cloud.githubusercontent.com/assets/3446682/17850280/4b78cf34-687e-11e6-87cc-fe0c89df3778.gif)

**Comment by timayhelen** [comment]
@SlavaET Ah right, thanks.
