### ISSUE TITLE
Custom widget areas are missing

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#146]
### Problem:

I created some custom sidebars and now they are gone. I can't see them on the front page or in Appearance => Widgets.

I can only see them when I role back to 2.7

![widgets elegantthemes wordpress](https://cloud.githubusercontent.com/assets/16414613/17834457/d91881c8-6738-11e6-8840-29bb89de6c05.png)

![widgets elegantthemes wordpressd](https://cloud.githubusercontent.com/assets/16414613/17834459/dd346588-6738-11e6-9f34-e41cd2509cda.png)

**Comment by SlavaET** [comment]
@FaycalBoutam I cannot reproduce this issue. I can see the widget areas created a while ago after upgrade to Divi Beta. 
Did you rename your Divi theme? Did you create these widget areas when child theme was activated?

**Comment by timayhelen** [comment]
@FaycalBoutam This happens if you disabled Divi during the upgrade process, or changed to a theme other than Divi.
