### ISSUE TITLE
Contact form module drop-down options jump to admin dashboard

### ISSUE THREAD

**Issue by gahawkey** [elegantthemes/Divi-Beta#147]
### Problem:

When using Visual Builder to create form with Contact Form module, selecting input field type jumps to admin dashboard, loosing all unsaved changes.

### Steps To Reproduce:
1. Open page in visual builder
2. Insert new contact form module
3. Create new field
4. Change type to email for example
5. Landing in admin dashboard, and going back with browser back button loads page in visual builder without any unsaved changes.

### Additional Information:

**Surface Pro 4**:

**Windows 10 1607 (build 14393.82)**:

**Chrome 52.0.2743.116 m (64-bit)**:

**2736x1824 (200%)**:

-

**Comment by SlavaET** [comment]
@gahawkey I cannot reproduce this issue. Could you please post the video screencast showing it?

**Comment by timayhelen** [comment]
@gahawkey I can't seem to replicate this either. Have you tried disabling all of your plugins?
