### ISSUE TITLE
Closing or escaping the Visual Builder

### ISSUE THREAD

**Issue by ayanize** [elegantthemes/Divi-Beta#148]
## Problem:

There is no button or at least we are not seeing a way to close or escape the Visual Builder when done. The save button does save the changes but what we need to do to get out of the visual builder still being logged in. Reloading the page works but we think there should be  way to get out of this when done.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Desktop**:

**Windows 7**:

**Chrome**:

**1920x1200**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. There is another issue open for this, so I am closing this duplicate.
