### ISSUE TITLE
Unable to choose colours using Hex codes

### ISSUE THREAD

**Issue by avo108** [elegantthemes/Divi-Beta#149]
### Problem:

When changing the background colour of a section, the Hex value cannot be manually adjusted. Only 1 character can be typed in & the box turns red. Colours can only be chosen using the picker.

### Steps To Reproduce:
1.  Add a section
2. Section Settings
3. Background Color
4. Try to type in a Hex code

### Additional Information:

**Device**: iMac

**Operating System**: El Capitan 10.11.6

**Browser**: Chrome

**Screen Resolution**: 2560 x 1440

**Screenshot or Screencast**: 

<img width="676" alt="screen shot 2016-08-21 at 12 16 03" src="https://cloud.githubusercontent.com/assets/13122732/17836631/1d004316-6799-11e6-827d-38435fbf48b1.png">

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
