### ISSUE TITLE
JS Error When Right Clicking Outside Divi Builder Area

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#15]
### Problem:

When you right click in certain areas on the page, the following error is produced:

![screen shot 2016-03-23 at 4 30 21 am](https://cloud.githubusercontent.com/assets/3333028/13983918/15a7dc1a-f0b0-11e5-8f44-522396cb997e.png)

### Steps To Reproduce:
1. Load the builder
2. Right click outside on the "Save To Library" link, and other areas around the builder.

**Comment by fikrirasyid** [comment]
@timayhelen can you take a look at https://github.com/elegantthemes/submodule-builder/pull/607 and see whether it fixes the issue or not?
