### ISSUE TITLE
Over 48 Hours & Still No Update Available

### ISSUE THREAD

**Issue by jdjmedia** [elegantthemes/Divi-Beta#151]
### Problem:

How long should I have to wait for the beta update to become available? I have tried both methods listed in the documentation on multiple installs and different WordPress versions and none seem to work.

**Comment by timayhelen** [comment]
Do you have the Divi theme activated? Also try disabling all of your plugins so that you only have the beta tester plugin enabled.

**Comment by jdjmedia** [comment]
Yes. Divi is activated. Not a child theme. All plugins disabled except beta plugin. Still not working.

**Comment by lots0logs** [comment]
Hmm..could you confirm that Divi's directory on your server has not been renamed? It must be eaxactly `Divi` (its case sensitive).

**Comment by jdjmedia** [comment]
Yah this is crazy. It is Divi and 755 security.

**Comment by lots0logs** [comment]
Have you experienced any issues with automatic updates prior to this? Could you check that your ET username and API key is properly saved in **Divi>>Theme Options>>Updates?**

**Comment by jdjmedia** [comment]
Never had an issue like this ever. Not a novice Wordpress user either. :) Re-enter API key and saved fine. Still no go. I am not sure what to even try next.

**Comment by lots0logs** [comment]
Next step would be to enable debug logging and then check the log after forcing it to check for updates a few times. Just add the following to your `wp-config.php` (remove your current WP_DEBUG line if it exists so that it is only defined once). 
```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);
```

**Comment by GWS14** [comment]
Hi there,

It's been 24 hours since install and unfortunately still no sign of version 3.

Installed on wampserver 3.04
PHP 5.6.19 / MysQL: 5.6.30 / Apache 2.4.18

Correct API and username - Theme options-update tab

Dashboard > Updates  - clicked the "Check Again" button several times. 
Appearances > Editor - changed Divi version number in style.css from 2.7.10 to 2.9.1

Directory named - Divi
Divi theme - activated.
Beta tester plugin active
All other plugins deactivated

**Comment by lots0logs** [comment]
Hi @GWS14 , the version for the 3.0 beta will always be in the `2.9.x` series. That way there wont be any issues upgrading from the beta to the official 3.0 release :wink:

**Comment by GWS14** [comment]
Hi
Thanks for the tip but not sure how that help me with current issue.

**Comment by lots0logs** [comment]
Sorry, I do not understand. You said:
>It's been 24 hours since install and unfortunately still no sign of version 3.
I explained that you should not be expecting to see version 3.0 yet. The beta versions will all be versioned as `2.9.x`  where `x` will increase for each beta leading up to the release of 3.0.

**Comment by jdjmedia** [comment]
After debugging this is all I got.
[23-Aug-2016 15:13:37 UTC] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/httpd/html/wowyourugly.com/public_html/wp-content/themes/Divi/functions.php on line 8027
[23-Aug-2016 15:13:37 UTC] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/httpd/html/wowyourugly.com/public_html/wp-content/themes/Divi/functions.php on line 8029
[23-Aug-2016 15:13:37 UTC] PHP Notice:  Undefined index: HTTP_USER_AGENT in /home/httpd/html/wowyourugly.com/public_html/wp-content/themes/Divi/functions.php on line 8031

**Comment by GWS14** [comment]
My misunderstanding Ok. Not version 3.... 
to clarify then..what I should have said is that has been no update from 2.7.10-no front page edditing

**Comment by GWS14** [comment]
Given up trying to get Divi to update on home server. Update worked first time on live server.
