### ISSUE TITLE
Fullwidth Scrolldown Button Not Working On Firefox

### ISSUE THREAD

**Issue by mwsmedia** [elegantthemes/Divi-Beta#153]
### Problem:

The scrolldown button does nothing in Firefox. After clicking, the browser bar URL adds a /.

### Steps To Reproduce:
1.  Install fullwidth module
2.  Activate scrolldown button
3.  Test in Firefox
4.  Scratch head

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop computer

**Operating System**: Windows 10

**Browser**: Firefox

**Screen Resolution**: 2560 x 1080

**Comment by fikrirasyid** [comment]
We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄
