### ISSUE TITLE
Text Module flyover toolbar disappears on mouseover

### ISSUE THREAD

**Issue by jfsturtz** [elegantthemes/Divi-Beta#154]
### Problem:

When I mouse over a Text Module, the flyover toolbar appears.  In some (but not all) cases, when I mouse over the toolbar, it disappears before I can select anything.

### Steps To Reproduce:
1.  Activate the Visual Builder
2. Mouse over a Text Module to display the toolbar
3. Try to select an item in the toolbar.  In some cases, it disappears on mouseover.
This seems random; I have not been able to discern any obvious differences between the Text Modules for which this happens and the ones for which it doesn't.  The screencast shows a page with two Text Modules near the top of the page that work fine.  But when I try to access the toolbar for the Text Module further down (below the blurbs), it vanishes.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:  Windows PC (Dell XPS 13)

**Operating System**:  Windows 10

**Browser**:  Firefox 47.0

**Screen Resolution**:  1920 x 1080

**Screenshot or Screencast**:  https://www.dropbox.com/s/a60eurn67ic0xyk/screencast.mp4?dl=0

**Link To Download Layout JSON File**:  https://www.dropbox.com/s/v0dufh2dbahrlcn/Divi%20Builder%20Layouts.json?dl=0

**Comment by timayhelen** [comment]
Thanks for the report. We have an issue open for this problem already, so I am closing this duplicate.
