### ISSUE TITLE
Change API Key button in Map module opens ePanel not in new tab

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#159]
### Problem:

If you click `Change API Key` button from the Map module settings it'll open the ePanel settings in the same tab which means that you'll lose everything you built with the Visual Builder.
That button should open ePanel settings in a new tab.

### Steps To Reproduce:
1.  Open Map module settings in Visual Builder
2. Click `Change API Key` button

**Comment by fikrirasyid** [comment]
@SlavaET I should've think of this :facepalm: I'll add target blank on the button.
