### ISSUE TITLE
Image not showing in certain position

### ISSUE THREAD

**Issue by jcolome** [elegantthemes/Divi-Beta#16]
### Problem:  http://infoseektechnologies.com/welcome/

Image works above sidebar location but no below when moved doen

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: Mac os

**Browser**: chrome

**Screen Resolution**: 1900 x 2400

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@jcolome did you add an image below your sidebar? Currently I see only image above the sidebar and no image module below.

**Comment by jcolome** [comment]
I did add it to sb - it's only when I move the module to the bottom it won't show.  there should now be two images one on top and one on bottom.  do you see the bottom one ?

here's admin credentials 

demo

wrzMOJN7*kVwPR&zSkvy&#I!

**Comment by SlavaET** [comment]
I see, thanks, looks like the issue with waypoints not triggered properly at the bottom of page. Did you see the same issue in previous version of Divi?

**Comment by jcolome** [comment]
Sorry did not try with older version.
