### ISSUE TITLE
Person modules duplicated in visual editor (Visual Bug)

### ISSUE THREAD

**Issue by tcshad** [elegantthemes/Divi-Beta#160]
### Problem:
Visual Bug
When manipulating the location of person modules a visual bug occurred where a module appeared to be duplicated.  No control elements appeared and on saving the module was not present.  Appears to be a visual bug only.

### Steps To Reproduce:
1.  unable to replicate
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: cloud linux 6 cPanel php 5.6 

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**: screenshot 
![dupe](https://cloud.githubusercontent.com/assets/11753618/17888655/4d338fc0-696f-11e6-8ab5-693fd9efde5a.JPG)
attached

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report, I believe this will be fixed in an updating PR.
