### ISSUE TITLE
Inline Editor Text Side Glitch

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#161]
Text size becomes un-editable in the following scenario:

1. Open up the visual editor on the Homepage Extended layout. 
2. Double click the word "Vestibulum" in the first blurb.
3. Set the text to bold.
3. Change font to Arvo. 
4. Attempt to adjust font size.

**Comment by timayhelen** [comment]
@SlavaET This is still happening for me in this PR. It happens when you double click to select the first word in a text block, adjust the style, and then try to slide the text size.

![text-size](https://cloud.githubusercontent.com/assets/3333028/17981315/098012e0-6ab8-11e6-8cd0-bd44277f581b.gif)

**Comment by SlavaET** [comment]
@timayhelen please check this new PR - https://github.com/elegantthemes/submodule-builder/pull/993
I improved the logic of this option so It should fix the issue.
