### ISSUE TITLE
Cannot type anything into the Code module

### ISSUE THREAD

**Issue by avo108** [elegantthemes/Divi-Beta#162]
### Problem:

The "code" module is not working. I was unable to type in or copy+paste any code, eg. shortcodes - nothing happens.

### Steps To Reproduce:
1.  Insert a section / row
2. Insert a module
3. Select "Code" module
4. Try to type in or copy+paste any code

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac

**Operating System**: El Capitan 10.11.6

**Browser**: Chrome

**Comment by timayhelen** [comment]
This affects the Custom CSS inputs as well.
