### ISSUE TITLE
"Preview Changes" button does not show changes

### ISSUE THREAD

**Issue by witkinss** [elegantthemes/Divi-Beta#163]
### Problem: "Preview Changes" button does not show changes

NOT in Visual Builder Mode (blue button), but the former Visual Editor, "Preview Changes" button  does not reflect changes if not Updated first.

### Steps To Reproduce:
1.  Make any change to page
2. Click on "Preview Changes"
3. **No changes reflected**
4. Click on "Update"
5. Click on "Preview Changes"
6. **Changes reflected now**

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Windows 10

**Browser**: Chrome

**Screen Resolution**: 

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
I cannot reproduce the issue. Preview changes button works as expected even with unpublished pages. 
@witkinss does that button work fine if another theme activated? Does it work fine with the latest Divi theme ( not Beta ) ?

![preview-works](https://cloud.githubusercontent.com/assets/3446682/17923076/1a07c5e0-6a04-11e6-845b-6d99ed739ac5.gif)

**Comment by timayhelen** [comment]
I can't seem to replicate this either. @witkinss Are you still experiencing the issue on the latest beta version? It sounds like maybe you clicked preview too quickly and the page didn't have time to update.

**Comment by witkinss** [comment]
Hi SlavaET and timayhelen, sorry for the delay I wanted to check and recheck before replying.   I just updated to the latest version of the Beta and it seems it is working Ok now on my side too.  Tks and rgds.
