### ISSUE TITLE
Updating directly from Appearance>>Themes or Plugins>>All Plugins Fails (new feature in 4.6) 

### ISSUE THREAD

**Issue by sosensible** [elegantthemes/Divi-Beta#165]
### Problem:

I tried to run my update and on a multi-site and on a single site it failed to update.

### Steps To Reproduce:
1.  run update of theme
2. paste in this notice: "Update Failed: The theme is at the latest version."
3. file this bug report and ( smile, knowing it will get there )

### Additional Information:

I did not see what was updated in the notifications.

**Comment by sosensible** [comment]
Had my host, WPEngine, try a file permissions reset. That did not allow either site to update.

**Comment by christopherbsantos** [comment]
It was great chatting with your sosensible. Let me know if you need me to do anything else on your sites to assist with this process.

**Comment by lots0logs** [comment]
Hi @sosensible could you try installing the update from the Updates page in your Dashboard instead of from the **Appearance>>Themes** page? You can access the Updates page under **Dashboard>>Updates**

**Comment by sosensible** [comment]
Yes, this worked on both sites. :)
