### ISSUE TITLE
New section button at the bottom

### ISSUE THREAD

**Issue by webjac** [elegantthemes/Divi-Beta#166]
### Problem:

When you create a few sections and you want to create a new one, the button for the new section at the bottom of the page is hidden behind the purple "main settings" button making it unreachable.

Here's a screenshot: http://jmp.sh/OgIwmy5 

### Steps To Reproduce:
1.  Create a few sections
2. Try to create a new one at the bottom of the page
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: MacBook Pro 15

**Operating System**: OSX El Capitan

**Browser**: Chrome

**Screen Resolution**: 1440x900 (Retina)

**Screenshot or Screencast**: http://jmp.sh/OgIwmy5

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
