### ISSUE TITLE
Text is hidden

### ISSUE THREAD

**Issue by webjac** [elegantthemes/Divi-Beta#167]
### Problem:

Text is hidden behind the settings panel of the section. Screenshot: http://jmp.sh/MvAzHME 

### Steps To Reproduce:
1.  Add a text module in any section
2. 
3. 
4. 

### Additional Information:

**Device**: MacBook Pro

**Operating System**: OSX El Cap

**Browser**: Chrome

**Screen Resolution**: 1440x900

**Screenshot or Screencast**: http://jmp.sh/MvAzHME

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
