### ISSUE TITLE
Divi Library shows incorrect count

### ISSUE THREAD

**Issue by jonathanbossenger** [elegantthemes/Divi-Beta#17]
### Problem:

When viewing Divi Library items, the count for 'Mine' shows 34 layouts (I'm assuming that's the pre built layouts).

### Steps To Reproduce:
1. Divi Library
2. See count next to 'Mine'

**Comment by fikrirasyid** [comment]
Hi @jonathanbossenger, thank you for reporting the issue. We've submitted a patch for this issue and it is currently under review process. Once it passes the review process, it should be available on the next beta release.
