### ISSUE TITLE
Hide justified option from textAlignment element

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#17]
### Request:

Related thread: https://discord.com/channels/1041765492907589683/1090466903396466698

In D4 we could hide individual alignment options from the advanced `fonts` field and custom `text_align` field.

Like this:
```
// Advanced field:
$fields['fonts']['my_fonts'] = array(
  ...
  'text_align' => array(
    'options'  => et_builder_get_text_orientation_options( ['justified'] ),
  ),
);

// Custom field:
$fields['my_field'] => array(
  ...
  'type' => 'text_align',
  'options' => et_builder_get_text_orientation_options( ['justified'] )
);
```
There is currently no way to do this in D5. I have several existing D4 modules which rely on this feature and without it could lead to undesirable UX and styling problems.

**Comment by fikrirasyid** [comment]
This has been addressed in dev-beta release. See: https://devalpha.elegantthemes.com/blog/release-dev-beta#group-component-refactor
