### ISSUE TITLE
Ampersands appearing as html entity (& appearing as &amp;)

### ISSUE THREAD

**Issue by jamesrayth** [elegantthemes/Divi-Beta#170]
### Problem:
Symptom: Ampersands in title and subheading fields are being replaced with the html entity `&amp;`

Issue: This appears to be happening any time the page is loaded in the back-end editor. If you load the page you're working on using the divi visual builder and add an ampersand to a title or subheading field, save the page using the visual builder, and close out of the back-end page without making any updates to the back-end, than the ampersands remain ampersands even when the page you edited is loaded. However, if you edit and save the page using the visual builder and then, through WP > Pages > All Pages, click Edit on that page again so it loads into the back-end editor, at that point the ampersands get replaced with the web entity. This also happens if you add ampersands using the divi builder in the back-end, as soon as you save a title or subheading field using the old divi builder they get replaced with the web entity.

### Steps To Reproduce (Visual Builder):
1.  On a new or existing page, add a module that displays a title or subheading, and put an ampersand in the text.
2. Save the page and close the visual editor.
3. View the page, notice the ampersands remain ampersands.
4. From WP > Pages > All Pages, click "Edit" (or by using the Edit Page in the admin bar while viewing the page).
5. The ampersands at this time have been converted to `&amp;`, you can verify by either opening the module in the divi builder, or by loading the visual builder.

### Steps To Reproduce (Divi Builder):
1.  On a new or existing page, add a module that displays a title or subheading, and put an ampersand in the text.
2.  Save the module changes and close the module.
5.  Open the module again and notice the ampersands have been replaced with `&amp;`

### Additional Information:

**Device**: Macbook Pro Retina

**Operating System**: OSX El Capitan

**Browser**: Tested and verified in Chrome, Firefox, and Safari

**Screen Resolution**: Tested on 1920 x 1200, and 1920 x 1080

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.

**Comment by jamesrayth** [comment]
Which issue was the duplicate? I searched for ampersand and nothing came up
