### ISSUE TITLE
Device preview icon color not changing on click (Bug)

### ISSUE THREAD

**Issue by TrevorGreenfield** [elegantthemes/Divi-Beta#171]
### Problem:

If I click the purple ellipsis icon at the bottom of the VB, then change the device view, the highlighted icon does not reflect the newly selected view unless I click the purple X, then it will be shown correctly.  Obviously, visually I can tell which is which in terms of page width, but ideally the icon should change color to highlighted green on click.  This would be even more important if you are quickly trying to switch between devices for adjustments.

### Steps To Reproduce:
1.  In VB, click the purple ellipsis icon.
2.  Click any device icon on left side.
3.  Note it does not highlight the chosen icon/device.

### Additional Information:

**Device**: PC

**Operating System**: Win 7 x64

**Browser**: I have tested both firefox 48.0.1 and Chrome 52.0.2743.116

**Screen Resolution**: 2560x1080

**Screenshot or Screencast**:
![iconbug](https://cloud.githubusercontent.com/assets/16709732/17899958/076b5a7a-6912-11e6-8ab4-c493817e0f45.JPG)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Hi @TrevorGreenfield, 

I am not able to re-create this bug. Could you try clicking Right Click > Inspect Element in Chrome and then run the previewer again? When the bug occurs, check the Console log and let me know if you see any errors.

**Comment by andyhqtran** [comment]
Hey @TrevorGreenfield,

I was also unable to reproduce the issue.
![image](http://g.recordit.co/YRCGtqLTkP.gif)

**Comment by TrevorGreenfield** [comment]
@timayhelen @andyhqtran Thank you for investigating.  I've disabled all extensions in both FF and Chrome, but I am still having the issue.  Here's video

![record_2016_08_23_12_03_40_314](https://cloud.githubusercontent.com/assets/16709732/17905973/0ac44156-692a-11e6-9a39-118d69d1c1c4.gif)

**Comment by andyhqtran** [comment]
Hey @TrevorGreenfield,

It looks like I was on an old version of the Visual Builder. After investigating it once more, I have confirmed that this is a bug.

Some notes for dev:
- Buttons update it's color once you toggle the page settings bar.
- Buttons can be changed once when you reopen the page settings bar. Afterwards, it returns to glitching out.
- No console errors were logged.

![image](http://g.recordit.co/LVIbxnanKH.gif)
