### ISSUE TITLE
third party module plugin not working in Visual

### ISSUE THREAD

**Issue by jking2076** [elegantthemes/Divi-Beta#172]
### Problem:

My KK Divi Mods plugin and modules therein work in "legacy" mode but hang in the Visual Editor. I can find the KK modules in the insert module modal, but when selected, the Visual Editor hangs.  It does not present a display for that KK module nor the Settings modal.  I am unable to open the Add modal again in that column.  I can, however, open the insert module modal in another column after that occurrence and insert a Divi module.

When I disable the Visual Editor and open the page in WP editor, there is no module present. I did not attempt to save while still in VE.

**Comment by mindsize** [comment]
This isn't surprising given that KK is currently using undocumented features to hook into Divi. I wouldn't expect anything that isn't a core part of Divi to work right now. I would imagine this will all be fixed soon when ET releases official documentation on extending Divi.

**Comment by jking2076** [comment]
Forgive me, mindsize, but are you speaking for ET or just making a comment?

**Comment by mindsize** [comment]
I'm a tester, just like you, though I can nearly guarantee this will be the answer from ET.

**Comment by jking2076** [comment]
That would be sad if they don't show a little interest before official documentation.  Maybe my problem is not cause for alarm for the launch date, but at least tell me where to start looking for the root cause.  Else, I'll just figure it out like I did before.

**Comment by timayhelen** [comment]
Can you send us a copy of the plugin? We will take a look and provide guidance if it's not something we can address on our end.

**Comment by jking2076** [comment]
Sure. Let me know if this doesn't attach.
[kk-divi-mods073.zip](https://github.com/elegantthemes/Divi-Beta/files/433230/kk-divi-mods073.zip)

**Comment by jking2076** [comment]
In my original problem description, I failed to mention that there were no JS console errors.  Else, it might would have tipped me off.

**Comment by jking2076** [comment]
mindsize, you've baited me into responding, but, you're right. Nick has no obligation to me or any other third party.  Yet, when I was upfront in signing up to beta test, Nick must have thought it was worthwhile. You're also half right about what I reported as being a bug.  Surely he would want to know that something works in legacy mode but not in VB mode, third party or not.

**Comment by jking2076** [comment]
On further testing...  After a module is selected, the column hangs, but other cols can be exercised. Other rows can be added, etc.  However, if the page is saved and then reopened in WP editor/Divi Builder, ALL modules that were added in VB are visible and functioning.

Also, if KK modules are added with Divi Builder, these render in VB and can be manipulated.

**Comment by mindsize** [comment]
No baiting involved, and I saw the value of reporting the issue. When I responded to your initial post, I was not aware you were the developer. As the developer, I can see the reason behind reporting the issue. 

Building something against an unsupported interface is always risky. You now have to protect your customers, who are also ET's customers, against the potential that new builds will break your code. And that will happen even more frequently when it's being built against code that doesn't have to stay backwards compatible. That was my last point. I'm glad you're in the beta so you can get a head start on making sure you're compatible with the sweeping changes that come with adding a whole new interface to the Divi we know and love.

Please don't misunderstand me, I find value in what you've created. I didn't intend to undervalue your work in any way, if that's the way you've taken it. I have plans for my own modules, but they're on hold until there is an official path for extending Divi for this very reason.

**Comment by jking2076** [comment]
mindsize, somehow, I DO believe we think alike.  It's just that I've been a member of ET so long now, I've never felt the need that an official path was necessary considering how ET had written their code and licensed it.  All the relevant php functions could be overwritten, hooks and filters were easy to spot, etc.  I created my first module nearly a year ago and the "documentation" was fairly straightforward.  Even through Divi 2.7.10, if a conflict arose, it was relative easy to rectify.  But now in the age of apps and sophisticated browsers, there may be a need for dev documentation and a new division at ET to keep it up-to-date as the race keeps heating up ;^)

**Comment by SlavaET** [comment]
@jking2076 thank you for providing your plugin it really helped to see the issues with similar plugins and develop a solution.
First of all, there is an error in your plugin which breaks the Visual Builder ( and probably some other aspects of Divi ). Please check the following functions in your plugin:
- `et_builder_include_library_modules()`
- `et_builder_include_library_layouts()`
- `et_builder_include_library_sections()`
- `et_builder_include_library_rows()`

You perform the `WP_Query` there and don't reset post data after that - it affects the main WP query, which breaks some stuff Divi rely on. You need to add the `wp_reset_postdata();` before `return` in the functions I mentioned. Keep in mind to always reset the postdata if you use `WP_Query`.

As for the Support of 3rd party plugins in Visual Builder - in the 3.0 version it'll be limited and only following options will be available for 3rd party plugins:
- `move`
- `copy`, `paste`, `duplicate`
- `remove`
- `save to library`

You will be able to add full support of your custom modules in Visual Builder when we release the Developers update where we'll work on all the required hooks and filters and create some documentation to help 3rd party developers properly add their modules into Divi.

@timayhelen I'm adding the PR to Design review, you can test it with the plugin provided by @jking2076 but don't forget to apply the fix I described to make it work.

**Comment by jking2076** [comment]
SlavaET, thanks for the update. I was beginning to lose hope. I take it then that you temporarily have made the corrections in your copy of the plugin.  However, I'll make the corrections and re-upload here.

From my analysis, I understand there wouldn't be full compliance by my modules because the app appears to be hardcoded for only Divi modules.  That's understandable considering you don't know what plugin a particular user would employ.

@timayhelen, et al, I appreciate your indulging me.  There is a reason I've been a member of ET since early 2011.

**Comment by jking2076** [comment]
I've made the corrections you outlined in my Divi3 test bed and there is no improvement.  Also, these functions are only used in two modules.  I can only assume that there is an updated theme package that hasn't been released.

As a side-note, if a third party module will not be allowed to be added in VB, then would it make sense to not have it in the insert list?

**Comment by lots0logs** [comment]
@jking2076 Once the changes have been reviewed and approved they'll be merged and included in an update to the beta. I'm afraid you wont be able to test it on your end until that happens :grimacing:

**Comment by SlavaET** [comment]
And yes, 3rd party modules won't be included into list of modules when you're adding new module. You'll be able to insert 3rd party modules from the library though.

**Comment by jking2076** [comment]
@lots0logs Yep, I realized that after my zeal led me back into test mode ;^)

@SlavaET Excellent!  We all think alike ;^)

**Comment by Jronk** [comment]
@jking2076 can you attach an updated copy of your plugin after the changes @SlavaET requested are implemented? Thanks!

**Comment by jking2076** [comment]
attached is the plugin with the edits per @SlavaET:

[kk-divi-mods073.zip](https://github.com/elegantthemes/Divi-Beta/files/443582/kk-divi-mods073.zip)

**Comment by jking2076** [comment]
I'm thinking not, but does Beta2.9.13 address any of these issues?  I've updated in my test bed.

ISSUE: the PB has a filter (et_builder_main_tabs) that I have recently taken advantage of to add a tab (Extended Settings) to the Module Settings modal. This is good to differentiate certain controls from the other three tabs. Will this filter be honored in the VB?

**Comment by Jronk** [comment]
@jking2076: 
1. The issues in this issue have not been addressed in 2.9.13, but will be in the next beta release.
2. At this time the tabs of the Module Settings Modal are not extensible. The best option at this point, that is supported, is to continue to locate your controls in the General tab.

**Comment by jking2076** [comment]
I've done some further testing with 2.9.14.  I hope this gets to someone now that it is closed.  Please confirm.

I've noticed that child modules as content in KK parent modules are lost when a page/post is saved in VB.

**Comment by lots0logs** [comment]
@jking2076 If you dont mind, could you create a new issue for that and include a reference back to this issue (you can simply references by its number (#172) Thanks! :smiley:
