### ISSUE TITLE
Visual builder displays featured image as meta background differently than website (Bug)

### ISSUE THREAD

**Issue by TrevorGreenfield** [elegantthemes/Divi-Beta#173]
### Problem:

1. In VB (Visual Builder) When using a Post Title module on a standard row, and selecting use featured image as background, and CSS Parallax, VB does not show the featured image at the same height in the background as the rendered page, and
2. does not display the parallax either. 
3. The desired height for the image is as shown in the rendered page.
4.  I hadn't noticed before but it appears even the meta information displayed is somehow different.   The spacing in the byline is different, and the comment style is different (No vs. 0). 

This also brings to light that the modal settings do not include any way to adjust the height of the featured image, or rather, the container that the image is the background image of.  Perhaps this would be an improvement feature for the modal across Divi versions.

Examining in developer tools it appears the height is achieved with a .et_pb_post_title.et_pb_featured_bg { padding: 16% 8% } on line 10473.

If I plug these into the VB in the padding for the module, it then correctly emulates what the rendered page does.  Again, if somehow this was already present and in some way called out in the settings modal, it would allow for actual adjustment of this height (as well as adjusting the text position which would be desired for granular control).

### Steps To Reproduce:
1.  In the standard editor or standard builder screen, add a featured image to a post, page or project
2.  In builder, add a Post Title module to a standard row
3. Set the featured image as meta background with CSS parallax (shown in screenshot)
4.   Observe difference between rendered page and VB page, in terms of padding applied to the container which affects the height of the image displayed.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**:  Win 7 x64

**Browser**:  Firefox 48.0.1 and Chrome 52.0.2743.116

**Screen Resolution**: 2560 x 1080

**Screenshot or Screencast**:
As shown in VB:
![divi3betatest-featuredimagebackgroundmetavb](https://cloud.githubusercontent.com/assets/16709732/17900423/254c6582-6914-11e6-8747-0be2058aa909.JPG)

As shown on rendered page on website:
![divi3betatest-featuredimagebackgroundmetaview](https://cloud.githubusercontent.com/assets/16709732/17900425/2555fd40-6914-11e6-99bd-fdd45a1da529.JPG)

Modal settings
![divi3betatest-featuredimagebackgroundsettings](https://cloud.githubusercontent.com/assets/16709732/17900424/254d24a4-6914-11e6-8c71-512179b981cd.JPG)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.

**Comment by TrevorGreenfield** [comment]
@timayhelen I've reviewed all of the open issues and the only one I can find that mentions something similar is https://github.com/elegantthemes/Divi-Beta/issues/78 but that is confined to just the Parallax/CSS issue.  My issue is more related to padding of Post Titles not being displayed in the settings modal properly (regardless of whether you turn on parallax) and it not previewing properly in VB,  compared to the rendered page, probably due to incorrect default padding being applied.  But I guess I'll just wait until the release to see if its fixed or not.

**Comment by TrevorGreenfield** [comment]
@timayhelen I've determined the problem with the padding is caused because the container div does not have the class "et_pb_featured_bg" applied.  If I manually insert this into inspector, VB now shows correctly compared to the rendered page.

Here's the affected line, you can see I've added the "et_pb_featured_bg".

![divi3betatest-featuredimagebackgroundcodefix](https://cloud.githubusercontent.com/assets/16709732/17905293/45c76484-6927-11e6-972a-558fbcf92bf0.JPG)


- I would still like to see this padding adjustable or called out somewhere in the modal.  Since Post Title module already has padding fields, these fields should at a minimum be populated with the correct padding % ( 16% 8%) .  I would say it is a bug that the padding is not correlated properly into the modal at this point.
