### ISSUE TITLE
Visual Editor Save button just spins after saving... 

### ISSUE THREAD

**Issue by elephantik** [elegantthemes/Divi-Beta#174]
### Problem:

I'll have to fill this out completely later but in simple reaction the saving process appears to be saving but the spinning symbol goes forever. I'll update this in a few hours. 

### Steps To Reproduce:
1.  Build a page layout that is large, save it in VE and the spinning button appears to keep spinning.
2. I haven't isolated anything yet so I'll do so in a later update.
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:
Os 10.9

**Browser**:
Chrome 

**Screen Resolution**:
2560x1440

**Screenshot or Screencast**:
https://www.dropbox.com/s/quh5408utmnyz2k/Spinning.png?dl=0
**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.

**Comment by elephantik** [comment]
Whoops thanks!
