### ISSUE TITLE
Inline Editor Strips Custom HTML Added From Settings Modal

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#175]
### Problem:

Third party icon code stripped from text module when saved in VB

### Steps To Reproduce:
1.  create a text module
2. add icon code such as this from fontawesome<i class="fa fa-envelope-o" aria-hidden="true"></i>
3. save and fontawesome code is stripped
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Can you paste the exact code you are adding? When you open up the module after saving, has the code been altered?

**Comment by websbyjd** [comment]
Here is the exact code that I had in the text module

`<i class="fa fa-envelope-o" aria-hidden="true"></i> CONTACT US`

**Comment by timayhelen** [comment]
I can't seem to replicate this issue. The code remains intact once I save via the VB and refresh the page. 

Are you using "Visual" mode in the text editor? Try using "Text" mode instead.

**Comment by websbyjd** [comment]
Ok here's an update.  I didn't give a very accurate description of this bug the first time.  After trying it a few more times, here's a new description:

FontAwesome icons are stripped from the text in a text module after editing in the front end editor (not in module mode).  

Steps to reproduce:

1. create a text module in Visual Builder and add the code:
`<i class="fa fa-envelope-o" aria-hidden="true"></i> CONTACT US`
2. save the page
3. load page in browser to see that icon is visible (provided that fontawesome has been integrated)
4. reload the Visual Builder
5. go back and edit text on page without opening module (for me the icon disappears as soon as I begin to change the text.
6. save the page and reload in browser and see that icon is gone.

**Comment by timayhelen** [comment]
I see, thanks. So basically the inline editor in particular is stripping out custom HTML.

**Comment by websbyjd** [comment]
lol...yep, I guess I could have said it like that.
