### ISSUE TITLE
Visual Editor Hangs when trying to save page

### ISSUE THREAD

**Issue by support-websavvy** [elegantthemes/Divi-Beta#179]
### Problem:

I made changes to a page with the visual editor.When I tried saving it took a long time and then just hung

### Steps To Reproduce:
1.  Create the whole page
2. Click Save at the bottom of the page

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop

**Operating System**:Windows 10

**Browser**:Chrome

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. This has already been reported, so I am closing this duplicate. It has been fixed in Divi 2.9.11.

**Comment by support-websavvy** [comment]
I still have divi 2.9.10. How do I get divi 2.9.11?
