### ISSUE TITLE
Off Screen: Font Family Off Screen in Top Row

### ISSUE THREAD

**Issue by GWS14** [elegantthemes/Divi-Beta#180]
### Problem:

Font Family window off screen when editing title in top row.

### Steps To Reproduce:
1.  Pages -Add New from Dashboard > Select Use Divi Builder > Select Use Visual Editor
2. Create row > I column > Text Module > Create H1 Text - Save
3. Select Text > Select Font Family Icon

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop PC

**Operating System**: Windows 10

**Browser**: Firefox

**Screen Resolution**:  1920 x 1200

**Screenshot or Screencast**:

![font-family](https://cloud.githubusercontent.com/assets/6307774/17920200/98151e3c-6a05-11e6-9955-bc44495df9b5.png)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Fixed.
Also improved the positioning of Inline editor on left/right edge of the screen to make sure it always fully visible.

**Comment by dm-chechik** [comment]
Also I've noticed that the row settings panel overlaps the content text.
![capture](https://cloud.githubusercontent.com/assets/20072036/18389838/5f36c7f2-76b0-11e6-847f-241d29ffbced.jpg)

**Comment by Jronk** [comment]
@dm-chechik go ahead and submit a new issue for that new issue you mentioned:
> Also I've noticed that the row settings panel overlaps the content text.
