### ISSUE TITLE
Font Formatting: Formatting options missing in Visual Editor

### ISSUE THREAD

**Issue by GWS14** [elegantthemes/Divi-Beta#181]
### Problem:

No header formating or text size in Visual Editor tool bar

### Steps To Reproduce:

1.  Use Visual Editor > Insert 1 row / 1 column
2.  Insert Text Module > add h1 text > save
3.  Try to change H1 to H2 or other size

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop PC

**Operating System**: Windows 10

**Browser**: Firefox

**Screen Resolution**: 1920 x 1200

**Screenshot or Screencast**:

![formatting](https://cloud.githubusercontent.com/assets/6307774/17921051/93c4244a-6a0a-11e6-8004-ea2868631ffe.png)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Text size and headers are accessed via the "Aa" icon.
