### ISSUE TITLE
Text Module Settings:  Unable to Click to Open

### ISSUE THREAD

**Issue by GWS14** [elegantthemes/Divi-Beta#182]
### Problem:

Toolbar for text settings disappears when mouse cursor moves towards it.

### Steps To Reproduce:

1. Use Visual Editor > Insert 1 row / 1 column
2. Insert Text Module > add h1 text > save
3. Try to edit text module settings

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop PC

**Operating System**:

**Browser**: Firefox

**Screen Resolution**: 1920 x 1200

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.

**Comment by GWS14** [comment]
oops aplogies
