### ISSUE TITLE
Divider redundant option (hide on mobile)

### ISSUE THREAD

**Issue by novalore** [elegantthemes/Divi-Beta#183]
The option is present in divider module's design settings and it feels counterintuitive and redundant since we already have the option for disabling the module on a per-device basis in general settings.

This issue is not limited to the beta, it exists since the release of the responsive editing controls.

(I understand that the priority of this one is probably the lowest possible...)

**Comment by timayhelen** [comment]
Thanks for the suggestion! We are going to use this repo for Divi 3.0 related bugs only, so I am going to close this report and keep a reference of it internally.

**Comment by timayhelen** [comment]
It's the same issue reported here: https://github.com/elegantthemes/Divi-Beta/issues/123
