### ISSUE TITLE
Fullwidth Row Buttons Overlap Section Buttons

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#184]
Section settings button cannot be accessed when:

1. Section padding-top reduced to 0. 
2. The first row in the section has it's padding-top reduce to 0. 
3. The first row in the section is set to "fullwidth row."
4. The first row in the section has it's gutters set to "0."

In this case, the row buttons overlap the section buttons.

**Comment by Anny85** [comment]
@timayhelen We could only replicate "Section padding-top reduced to 0."
Could you check to see if other points are still relevant?

**Comment by timayhelen** [comment]
This fix doesn't really work because it causes the row to overlap the next module. 

I think a better fix would be to move the row buttons to the right instead of downward whenever the row and section buttons are in danger of overlapping. Ideally this would only occur when the row and section buttons are about to touch, instead of always being applied with section padding = 0.

**Comment by Anny85** [comment]
@timayhelen I added the code to move row settings to the right, it applies `et-fb-small-top-padding` class to a section, when padding top is less than 40. Do we need to add different values "margin left" values for each breakpoint or it is ok to use `112px` to account for all situations?
