### ISSUE TITLE
in VB, module control menu does not stay visible to access

### ISSUE THREAD

**Issue by jking2076** [elegantthemes/Divi-Beta#187]
in the attached video capture, a Divider module is used as example.  this anomaly may be prevalent in any module without sufficient height. using Divi2.9.11
[divicap1.zip](https://github.com/elegantthemes/Divi-Beta/files/435842/divicap1.zip)

**Comment by timayhelen** [comment]
Thanks for the report. We already have an issue open for this, so I am closing this duplicate.

**Comment by jking2076** [comment]
do you think everything has been covered?  Can you suggest any area I may contribute further?
