### ISSUE TITLE
Dragging Sections Causes TinyMCE Formatting To Be Lost

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#188]
When you drag and drop a section, it causes some TinyMCE inline styles to be lost. Text Color in particular.

**Comment by SlavaET** [comment]
@timayhelen I can't replicate this issue in the latest version of `1848-front-end-builder branch` though I could replicated it in yesterday's version. 
Can you please check whether you still see the issue in the latest version or not?

**Comment by timayhelen** [comment]
@SlavaET I can't seem to replicate it now either.
