### ISSUE TITLE
What are all the little red flame/building(?) things when I go to the themes screen in the dashboard? 

### ISSUE THREAD

**Issue by SheriLossing** [elegantthemes/Divi-Beta#19]
### Problem:

Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.

### Steps To Reproduce:
1.To reproduce you would need to go to my dashboard
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac (Retina 5K, 27-inch, Late 2015)

**Operating System**: OS X El Captain (van.10.11.3)

**Browser**: Chrome

**Screen Resolution**: Retina 5K

**Screenshots**: 
<img width="2560" alt="screen shot 2016-03-23 at 5 52 09 pm" src="https://cloud.githubusercontent.com/assets/18037922/14002305/7f7aaea8-f121-11e5-9131-9589aa6c4a51.png">
<img width="2560" alt="screen shot 2016-03-23 at 6 08 31 pm" src="https://cloud.githubusercontent.com/assets/18037922/14002457/88420396-f122-11e5-86ab-951be8a20149.png">
<img width="2560" alt="screen shot 2016-03-23 at 6 11 51 pm" src="https://cloud.githubusercontent.com/assets/18037922/14002520/eaaf3f12-f122-11e5-96f7-fafb945463ba.png">

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
Hi,

I'm not sure but it's most likely one of the following:

* A browser extension that you have installed and activated (Try disabling your extensions)
* A WordPress plugin that you have installed on your site (Try disabling plugins).

**Comment by timayhelen** [comment]
I think it's your video tutorials plugin.

**Comment by SheriLossing** [comment]
@timayhelen Nick... you're right. When I deactivated & removed them it went away. Regardless... It is apparently a case of them not playing well with the beta version, as I have them on my own site (not this beta site), and these 'flame'-looking things do not pot up with the current version of Divi (the non-beta one).
