### ISSUE TITLE
Spinning Gear Icon

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#191]
This is totally not priority, but I think if the gear icon spins on `:active` or `:hover` state, It'll make the interaction more livelier. By `gear icon`, I mean these icons:

### Module item settings
![screen shot 2016-08-25 at 5 48 58 pm](https://cloud.githubusercontent.com/assets/916442/17966535/480eac2c-6aec-11e6-8f20-6ee726fbee27.png)

### Module, row, and section setting popovers
![screen shot 2016-08-25 at 5 49 44 pm](https://cloud.githubusercontent.com/assets/916442/17966560/700b4d66-6aec-11e6-8553-f66840d3b075.png)

### Page settings
![screen shot 2016-08-25 at 5 50 45 pm](https://cloud.githubusercontent.com/assets/916442/17966576/7eeda20c-6aec-11e6-8dbc-b2d90167ec51.png)

**Comment by timayhelen** [comment]
I think animations might be distracting, but maybe we can do a more subtle hover state, like a simple color change or BG color change. I will think about it :)

**Comment by fikrirasyid** [comment]
@timayhelen yeah, it can be distracting if it's too much 😁  What I mean by the issue is some icons don't have ripple effect like many buttons do, so it feels like little bit "cold" on `:active` state due to no direct feedback toward click event.

Anyway, another possible  animation idea:

![screen shot 2016-08-26 at 9 30 54 am](https://cloud.githubusercontent.com/assets/916442/17992233/d2986094-6b6f-11e6-9497-4457bba78708.png)

I think it'll be pretty cool if it can do the lid-open-then-close-effect on `:active` event:

![photo on 8-26-16 at 9 33 am](https://cloud.githubusercontent.com/assets/916442/17992297/4432c118-6b70-11e6-875e-f17134b91147.jpg)
