### ISSUE TITLE
Visual builder: Can't click on first module settings

### ISSUE THREAD

**Issue by OlgaT** [elegantthemes/Divi-Beta#193]
### Problem:

Can't click on first module settings if eader is transparent. Settings tab is under the header

1.  Set transparent background color in Customizer > header&Navigation > Primary menu bar
2. Enable visual editor
3. Try to click on the settings panel (it disappears)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
