### ISSUE TITLE
Visual builder: Portability popup position issue

### ISSUE THREAD

**Issue by voceadinumbra** [elegantthemes/Divi-Beta#194]
### Problem:

At some smaller browser resolutions, like 1250 * 550 - the Portability popup is causing some layout problems when opened

### Steps To Reproduce:
Browser: Chrome
OS: Windows 10

### Additional Information:

https://www.youtube.com/watch?v=Rx3osibeyf0&feature=youtu.be&hd=1

**Comment by SlavaET** [comment]
@voceadinumbra can you still reproduce this issue in the latest version of Divi? 
I cannot reproduce it.

**Comment by voceadinumbra** [comment]
Hi, 
I have just tested this again and now it seems ok; I can't replicate the problem
