### ISSUE TITLE
Default row gutter width is not displayed

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#196]
### Problem:

When enable row Use Custom Gutter Width option the defalt value "3" is not displayed. Also reset setting button set value to "14".

## Steps To Reproduce:
1.  Create new row
2. Enable Use Custom Gutter Width option and value field will be empty.
3. Set any value
4. Click on reset button and value will be "14"

**Comment by fikrirasyid** [comment]
@dm-chechik We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄
