### ISSUE TITLE
Module settings window popups twice

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#197]
### Problem:

After closing settings window on new module without any adjustments the window displays second time if you move mouse over new module. 

### Steps To Reproduce:
1. Create any new module
2. Close settings window without any adjustments.
3. Move mouse over that module.
4. Settings window appears second time

**Comment by timayhelen** [comment]
Thanks for the report. We found this bug internally and fixed it already, and it will be fixed in beta 2.9.13.
