### ISSUE TITLE
Color palette selector showing all 8 transparent

### ISSUE THREAD

**Issue by agirlandhermac** [elegantthemes/Divi-Beta#20]
### Problem:

Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.

### Steps To Reproduce:
1. added new section
2. added new single full row and text module
3. inserted sample text, set to light and center
4. went to set background color in section settings and saw all 8 palettes seem to be set to transparent/white. When picking a color inside the gradient and then clicking a palette the selected hex stays in the field but does not show in palette square.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: MacBook Pro 17" 

**Operating System**: OSX Yosemite 10.10.5

**Browser**: Chrome Version 48.0.2564.116 (64-bit)

**Screen Resolution**: 1850 x 1040

**Screenshots**:
![screen shot 2016-03-23 at 7 00 12 pm](https://cloud.githubusercontent.com/assets/16481723/14004740/79898f9c-f12a-11e5-89fb-2c22350be285.png)
![screen shot 2016-03-23 at 7 09 06 pm](https://cloud.githubusercontent.com/assets/16481723/14004781/cf33c796-f12a-11e5-98ad-87b0ffe35e54.png)

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Fixed. The fix is in 2 branches:
submodule-epanel - https://github.com/elegantthemes/submodule-epanel/issues/26
submodule-builder - https://github.com/elegantthemes/submodule-builder/issues/610
