### ISSUE TITLE
Module Duplication During Drag & Drop

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#201]
If you drop and drop a module, then drag and drop the same module back to it's original location, the module is duplicated:

![module-duplicate](https://cloud.githubusercontent.com/assets/3333028/17983302/b990f87c-6ac0-11e6-8424-a80a35158d1d.gif)

I also see the following error during module drag and drop:

![screen shot 2016-08-25 at 12 38 26 pm](https://cloud.githubusercontent.com/assets/3333028/17983328/de0160c0-6ac0-11e6-88c6-85c6048921e5.png)

**Comment by Jronk** [comment]
@timayhelen I am unable to reproduce, I tried exactly what I see above, in my case I am using homepage extended trying the section that looks identical to above, no dup no errors.

![drag-n-drop-no-dup](https://cloud.githubusercontent.com/assets/1163441/17988493/7bc73770-6adb-11e6-8bfd-855885d42b9a.gif)

**Comment by timayhelen** [comment]
@Jronk I am closing this issue and opening a new one that details the actual issue, which is unrelated to the bug I documented here. https://github.com/elegantthemes/Divi-Beta/issues/207
