### ISSUE TITLE
Hover Buttons Should Be Disabled While Tooltips & Modals Are Open

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#205]
It used to work like this in the past, so I am not sure what changed, but we should prevent hover buttons from appearing while tooltips and modals are open. This will also fix https://github.com/elegantthemes/Divi-Beta/issues/48

![hover-tooltip](https://cloud.githubusercontent.com/assets/3333028/17987758/a9ff2986-6ad6-11e6-8f49-0dc23872a6a1.gif)

When a tooltip is active, the current module and parent row/section buttons remain active, but hovering should not trigger new buttons to appear.

**Comment by SlavaET** [comment]
@timayhelen btw, this will fix the https://github.com/elegantthemes/Divi-Beta/issues/48 only partially, because you can still open the tooltips and modals from Page Settings bar.
