### ISSUE TITLE
Ensure ES5 Is Being Used For Production - ES6 Related Errors Are Occuring

### ISSUE THREAD

**Issue by azgithub6** [elegantthemes/Divi-Beta#206]
### Problem:

The Visual Builder popup toolbars for sections, rows, and modules disappear when clicking the gear wheel to open the option panels in Chrome 44 on OSX 10.6.8. 

SCREENCAST:
[Chrome-Issue-mp4.zip](https://github.com/elegantthemes/Divi-Beta/files/438681/Chrome-Issue-mp4.zip)

### Steps To Reproduce:
1.  Click Use Visual Builder in Chrome OSX
2.  Click the gear icon on any popup toolbar (section, row, or module)
3.  The toolbar disappears. The options panel does not open. The developer console fires errors for Object.assign is not a function, and Uncaught Invariant Violation: Minified React error #121 (see screencast)
4. Reloading the page restores the vanished popup toolbar, but the same thing happens again

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
Macbook Pro 17

**Operating System**:
OSX 10.6.8

WP 4.6 Clean install, only Elegant Themes Divi Beta Tester plugin active.

DIVI 2.9.9

**Browser**:
Chrome Version 44.0.2403.155 (64-bit)

**Screen Resolution**:
1920 X 1200

**Screenshot or Screencast**:
See attached

URL: http://milagroman.com/

Issue does not occur in FireFox 48 OSX. 

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Chrome version 44 is over a year old and doesn't support ES6 syntax, which is why the builder fails. Upgrading to the latest version should solve the issue for you. 

@Jronk Should we be using a polyfill for help with old browsers? 

http://babeljs.io/docs/usage/polyfill/

**Comment by azgithub6** [comment]
True. But Google Chrome updates are no longer available for 10.6.8. I have other Macs running the latest OSX/Chrome, but my production machine (MBP 17 8,3 16GB, dual SSDs) has remained on Snow Leopard because not only is SL glitch free and runs MUCH faster than El Crapitan, I can still run the handful of legacy rosetta applications that have become core to my workflow. I've been holding out as long as I can to avoid being sucked into to Apple's hasty OS release cycle. I've had a good run - six years and counting. I never would have guessed that of all things, using DIVI 3 in Chrome would make the first compelling case for upgrading my OS. But for now I'll move from Chrome to Firefox for DIVI 3 dev work, even though FF is an unstable criminal in terms of system resource theft (I can leave Chrome running for weeks with 100+ tabs open, but I have to relaunch FF every hour, if it doesn't crash first on its own. Meanwhile, DIVI 3 is shaping up to be freaking awesome and worth some suffering. Thanks for letting me complain a little ; )

**Comment by timayhelen** [comment]
Looks like we are using ES6 for dev, but we should be compiling to ES5. So it's possible something is still using ES6 by mistake. We need to look into it.

**Comment by Jronk** [comment]
@azgithub6 I have found some stray uses of `Object.assign`, and converted them to our more consistently used lodash 4 `_.assign()` counterpart which is compatible with older browsers. Thanks for submitting the detailed bug report.
