### ISSUE TITLE
Cannot access the Visual Editor Options

### ISSUE THREAD

**Issue by jumborexTest** [elegantthemes/Divi-Beta#208]
### Problem:

While clicking upon a text not ever appears the black tag for options. In the attached image you can see how the text in evidence doesn't wake up any tag related to text.

### Steps To Reproduce:
1.  Enter Visual Builder
2. Click on text
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: Windows 10

**Browser**: Firefox

**Screen Resolution**: 1440 x 900

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

![visual_editor](https://cloud.githubusercontent.com/assets/21120636/18002371/a6a9a304-6b87-11e6-9b39-514cb31344c6.jpg)

**Comment by SlavaET** [comment]
@jumborexTest Can you try clicking Inspect Element in Chrome and let us know if you see any messages in the console log when you try working with the Builder?
Also, can you please try disabling all active plugins and check whether the Builder works without plugins or not?

**Comment by jumborexTest** [comment]
Ok, I don't see any difference with, or without plugins running.
Errors, only this warning: KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
An one error: http://fonts.googleapis.com/css?family=Georgia:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&cyrillic,greek,latin
Failed to load resource: the server responded with a status of 403 (Forbidden)

By the way, I don't use any cyrillic!

**Comment by timayhelen** [comment]
@jumborexTest Can you try again? I just tested your site after upgrading the Divi Beta and the In-Line editor seems to be working for me. If not, can you try using a different browser, such as Chrome, to see if it makes a difference?

**Comment by jumborexTest** [comment]
Ok: if I click upon a text the "tools" for changing it (color, type, etc) appear in a part outside the screen, and I must scroll down to find it. But it's true: now it's working.
Thank you.

**Comment by timayhelen** [comment]
Ok great, the issue you describe has been reported in a different ticket, so I am going to close this one :)
