### ISSUE TITLE
Cannot save

### ISSUE THREAD

**Issue by jumborexTest** [elegantthemes/Divi-Beta#209]
### Problem:

After using Visual Buiding, if I click teh "Save" button this goes in a continuous rotation and never exits. The only way I found for saving is returning to the Post Normal Vision (where the mods are mantained) and save it thru WordPress.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: Windows 10

**Browser**: Firefox, Chrome

**Screen Resolution**: 1440 x 900
![saving](https://cloud.githubusercontent.com/assets/21120636/18002860/c6b67e62-6b8a-11e6-9100-e6bd9fba9348.jpg)

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@jumborexTest Can you try clicking Inspect Element in Chrome, and then enabling the builder and let us know if you see any messages in the console log after you clicking `save`?

**Comment by timayhelen** [comment]
@jumborexTest Would you be able to install the Elegant Themes Support Plugin and then email me your support token and website URL to nick@elegantthemes.com so that I can log in a take a look?

http://www.elegantthemes.com/downloads/elegant-themes-support.zip

Please activate the plugin and generate a new token via the "Tools > Elegant Themes Support Account" page and email it to nick@elegantthemes.com. Include your website URL as well.

**Comment by jumborexTest** [comment]
Ok! I've' sent a token via email.

**Comment by timayhelen** [comment]
@jumborexTest I updated your Divi Beta to the latest version, 2.9.12, and it looks like saving is working now :)

**Comment by jumborexTest** [comment]
Right: ok. It's working.
