### ISSUE TITLE
Incorrect popover buttons size on responsive mode

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#210]
### Problem:

Popover buttons size on responsive mode at latest `master` branch looks like this:

![screen shot 2016-08-26 at 6 17 14 pm](https://cloud.githubusercontent.com/assets/916442/18003668/616e5ed8-6bb9-11e6-8028-9718a76da95f.png)

![screen shot 2016-08-26 at 6 16 09 pm](https://cloud.githubusercontent.com/assets/916442/18003669/616f4bb8-6bb9-11e6-9b1b-e75d464fd592.png)

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Comment by SlavaET** [comment]
@fikrirasyid this one probably related - https://github.com/elegantthemes/Divi-Beta/issues/211
Can you please check?

**Comment by fikrirasyid** [comment]
@SlavaET yeah, the styling is caused by the same class name. https://github.com/elegantthemes/submodule-builder/issues/1003 should fix it. However, I'm not sure why changing gutter adds `et_fb_hidden_header` class on `<body>` tag tho. There must be a leak somewhere.
