### ISSUE TITLE
Hover buttons become very big if Gutter Width adjusted in Page Settings

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#211]
### Problem:

If you adjust the Gutter Width in Page Settings, then Hover buttons become very big

![giant-buttons](https://cloud.githubusercontent.com/assets/3446682/18005284/efc99002-6bba-11e6-854e-c583a4650ae4.gif)

### Steps To Reproduce:
1. Open Page settings in Frontend Builder  
2. Modify the Gutter Width setting
3. Hover over any module on page

**Comment by timayhelen** [comment]
@SlavaET I am not able to replicate this. Perhaps the it's related to something else and not the gutter width adjustment. Perhaps the "no header" class got stuck on somehow, and in that case Fikri's new branch will fix that.

**Comment by SlavaET** [comment]
I cannot reproduce it in the latest branch either. Looks like it's not an issue anymore.
