### ISSUE TITLE
Ensure Unfiltered HTML Cannot Be Processed By Non Admins

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#214]
We need to make sure that unfiltered HTML cannot be saved into the post by non-admins. And we should double check the code module, since this was an issue we addressed in the past in the BB and needs to be re-validated in the FB.

**Comment by SlavaET** [comment]
@timayhelen I checked and FB saves the content with respect to `unfiltered_html` role. If user doesn't have that role than content will be filtered. Our filters for code module also applied and work fine with Frontend Builder.

**Comment by timayhelen** [comment]
@SlavaET Ok great.
