### ISSUE TITLE
Visual builder doesn't work with Divi 100 Article Cards add-on

### ISSUE THREAD

**Issue by fionchadd** [elegantthemes/Divi-Beta#215]
### Problem:

The Visual Builder doesn't work correctly with the Article Cards add-on - it doesn't correctly preview or save the changes (see screenshot and further information below)

### Steps To Reproduce:
1.  Install and activate Divi Article Cards plugin
2. Enter Visual Editor on page containing blog module - displays correctly
3. Bring up settings for blog module in Visual Editor
4. Toggling options i.e. 'show categories', 'show comments' changes the display back to normal blog mode but with the columns squashed. Saving the settings and exiting the visual builder puts the display back to normal but the changes haven't been applied. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac

**Operating System**: El Capitan

**Browser**: Chrome

**Screen Resolution**: 

**Screenshot or Screencast**: 
![image](https://cloud.githubusercontent.com/assets/17981211/18027260/237cee70-6c57-11e6-9783-7b3d66d52e24.png)
![image](https://cloud.githubusercontent.com/assets/17981211/18027272/8cc54788-6c57-11e6-89f9-e6b018048e6b.png)

**Link To Download Layout JSON File**:

[Divi Builder Layout - blog module with article cards enabled.json.zip](https://github.com/elegantthemes/Divi-Beta/files/440632/Divi.Builder.Layout.-.blog.module.with.article.cards.enabled.json.zip)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@fionchadd These settings aren't intended to work the the article card layout. It's a bit of an all or nothing plugin, sorry for the confusion!

**Comment by fionchadd** [comment]
Ah fair enough - no worries! :)
