### ISSUE TITLE
WPMU Dev Pro Sites + DIVI 3.0 Integration

### ISSUE THREAD

**Issue by mshigekawa** [elegantthemes/Divi-Beta#217]
### Problem:
I have a business use-case in which I'm looking to integrate WPMU Dev Pro Sites with DIVI 3.0. Think large-scale wordpress.com with the power of the client friendly DIVI 3.0 editor targeting a niche market. Before I go down into the weeds, I wanted to see if there were any major blockers anyone can think of with this implementation. 

### Steps To Reproduce:
1.  Install DIVI 3.0 beta
2.  Install WPMU Dev Pro Sites

### Additional Information:

**Link To Download Layout JSON File**:
https://premium.wpmudev.org/project/pro-sites

**Comment by timayhelen** [comment]
@mshigekawa Is there a bug in particular that you are experiencing?

**Comment by mshigekawa** [comment]
Hey Nick - No bugs in particular at the moment as I'm looking to begin integration testing this week. Just wanted to see if anyone had experience with this integration or knew of any potential showstoppers.

**Comment by timayhelen** [comment]
Ok, let us know if you run into any problems. I am going to close this issue for now, but it can be re-opened later. Right now we need to focus on fixing known issue.
