### ISSUE TITLE
UX: Must Check "show toolbar when viewing site" in user profile.

### ISSUE THREAD

**Issue by sasserc** [elegantthemes/Divi-Beta#218]
You will need documentation or note somewhere explaining that the browser editing will not work unless  "show toolbar when viewing site" is check in WP User Profile.

**Comment by timayhelen** [comment]
The visual builder can be enabled when editing a post by clicking the "Use Visual Builder" button. The button is also available in the admin toolbar for convenience if the toolbar is enabled.
