### ISSUE TITLE
In dashboard fullwidth header has some text that is not showing

### ISSUE THREAD

**Issue by SheriLossing** [elegantthemes/Divi-Beta#22]
### Problem:

In my dashboard the fullwidth header appears to have duplicate text: 'Enter the text for the Button",
"Enter the URL for the Button".... but when I pasted it into this message, this text also appeared "Button #1 URL: ".... So.... I am assuming that the text that id's the boxes as labels for button #1 and button #2 is what is not showing, and that is is actually there, but now showing because the font is white? Also, please note in the screenshot that the 'save' button texts are also not showing. This has actually been happening for me a lot on the current Divi version (not beta) buttons in the Divi builder. It is actually quite inconvenient at times.

Actually, I just checked the dashboard and there are other boxes in that header module that also do not have their label showing (in the same manner as in the 'button #1' and 'button #2').

### Steps To Reproduce:
1. In dashboard
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:  iMac (Retina 5K, 27-inch, Late 2015)
**Operating System**: OS X El Captain (van.10.11.3)
**Browser**: Chrome
**Screen Resolution**:Retna 5K
**Screenshots**:
![screen-shot-fullwidth-header](https://cloud.githubusercontent.com/assets/18037922/14006230/ad5fcd74-f141-11e5-91a9-3e898eba8485.jpg)

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
Could you check it while all plugins are disabled? It looks like something is conflicting with the builder's styles. This is what it should look like:

![2016-03-23_09-24-33-pm](https://cloud.githubusercontent.com/assets/4675662/14006665/b8810230-f13d-11e5-8bd4-69ea50ea8717.png)

**Comment by SheriLossing** [comment]
The only plugins I have are the install and update for this Beta version.

**Comment by SheriLossing** [comment]
Nevermind... Now I see the text. Wow. Sorry.
