### ISSUE TITLE
Can't save what was created in visual editor

### ISSUE THREAD

**Issue by blondejon** [elegantthemes/Divi-Beta#221]
### Problem:

It may just be that I'm missing something, but I can't save what I created in the visual editor.  It doesn't go live, I can't save it to the library.... nothing.

No plugins are installed so it isn't a plugin that is interfering.  

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. Can you be a bit more specific about the issue, with exact steps used to replicate it? 

Where you able to find and click the save button? Does the page appear to save successfully, or does the saving animation continue without ever confirming the save? If you right click and "Inspect Element" in Chrome, and click the save button, do any errors show up in the console log?

It would also be helpful if you filled out the missing info in your ticket, since this is all very useful to us. Thanks!

**Comment by blondejon** [comment]
Steps to reproduce error:
I just realized it works in IE, but not Chrome.  Here are the steps in Chrome:
Build a page using visual editor.
Click save
Nothing happens

Errors in console log:

1. Failed to load resource: the server responded with a status of 500 (Internal Server Error)
content-script.js:274 
2. Uncaught TypeError: Cannot read property 'webkitBackingStorePixelRatio' of undefined
3. bundle.js?ver=2.9.11:30 Uncaught TypeError: Cannot read property 'length' of undefined
4. portability.js?ver=2.9.11:279 Uncaught TypeError: Cannot read property 'timestamp' of undefined

Device: laptop
Operating system: windows 10
Browser Chrome
screen resolution 1280x720

**Comment by timayhelen** [comment]
@blondejon Are you using a child theme or do you have any custom code input via ePanel, or by other means? The very first error the causes the failure isn't part of Divi (content-script.js). 

Do you have any Chrome extensions installed? Try disabling them all.

**Comment by blondejon** [comment]
I turned off the Chrome extensions and now it works.  Would you like me to go through the process of elimination to figure out which one is causing the visual editor not to work?

**Comment by timayhelen** [comment]
@blondejon Sure that would be great.

**Comment by lbjohnson01** [comment]
I'm in the same boat. I cannot get the VB to save changes in any browser.

Device: MBP 17"
Operating system: OSX 10.11
Browser Safari v. 9.0 (11601.1.56)
screen resolution 1920 x 1200

Only extension running is the ET Divi Beta Tester

**Comment by timayhelen** [comment]
@lbjohnson01 Can you load the builder in Chrome, right click and "Inspect Element" and then try saving the page? After that, check the Console tab in the inspector and let me know if you see any errors.

**Comment by lbjohnson01** [comment]
@timayhelen I figured out what I was doing wrong - "Expand settings" wasn't expanding properly. I am now using the beta in Chrome Canary and I am able to save now. Thank you, Nick!
