### ISSUE TITLE
Editing Content of Opened Toggle reverses open and closed state background and font colors

### ISSUE THREAD

**Issue by sasserc** [elegantthemes/Divi-Beta#222]
### Problem:

When editing a page that contains a toggle module (that is normally closed) and has a closed state background of blue with light text, when opening/expanding the toggle module as soon as the cursor selects something to change and the text edit bar pops up everything is ok until you move the cursor and then the open state color of the toggle module changes to the background color of closed state and then the visual editor seems to get confused. 

### Steps To Reproduce:
1. Normal closed state ready to open toggle.
![image](https://cloud.githubusercontent.com/assets/21265604/18035123/dbb801e4-6d1c-11e6-808b-99959e7b91d6.png)
 
2. Normal open state ready to edit text.
![image](https://cloud.githubusercontent.com/assets/21265604/18035133/09a4d7da-6d1d-11e6-90bf-2d284dbc0684.png)

3. Screen result after selecting text to change.  As soon as cursor is moved to text edit bar, the open dark blue background of the closed toggle state covers the screen.
![image](https://cloud.githubusercontent.com/assets/21265604/18035166/a3938a08-6d1d-11e6-8653-571665cfad7b.png)

### Additional Information:

- Laptop running Windows 7 professional
- Latest version of Google Chrome 
- 1366 x 768
- WPEngine is web host

**PS:**  **How do I get to Trello board?**

**Comment by sasserc** [comment]
Additional Information you may need:

The site is a staging copy of my production site at WPEngine.  It is running WP 4.6, Divi 2.9.12 (Beta) which was upgraded from 2.7.8.  WPEngine is running php 5.5.9 . 

You can access the production site is at http://remason.com/careers/.  It is running WP 4.6, Divi 2.7.10 and php 5.5.9

Hope this helps.

If you can't easily reproduce would be glad to privately give you admin access.

**Comment by SlavaET** [comment]
@sasserc I cannot reproduce this issue on my localhost. Could you please try updating your Divi Beta to the latest version ( 2.9.**13** at the moment ) and check again?
Please let us know if you still see the issue in the latest version of Beta.

**Comment by timayhelen** [comment]
@SlavaET I can replicate this. Try loading the "Sale Page" layout. Open one of the closed toggled, and then hover over the newly opened toggle. The background color will change from white to gray.

**Comment by SlavaET** [comment]
@timayhelen Ah, I see. Thanks!
