### ISSUE TITLE
REQUEST: Divi 3.0 New Feature Overview / List

### ISSUE THREAD

**Issue by heretiq** [elegantthemes/Divi-Beta#223]
I've just downloaded and installed the 3.0 Beta and am now ready to begin testing and reporting findings. However, I would like to go about this in a systematic manner vs randomly trying and reporting on things. I've read the beta testing post, searched the ET blog posts and the Github issues queue for an overview/list of the new 3.0 features; but I've not found one. The best I can discern is that Divi 3.0 is exclusively focused on the new visual/front-end editor. I would appreciate some insight into whether this is the case. If there are other new features I would appreciate a brief summary to orient myself. 

Thanks ET for your consistent efforts to make Divi even better!

**Comment by timayhelen** [comment]
The update is focused entirely on the new Visual Builder. So we are just asking people to launch the new builder and test absolutely everything :) I wish I could give you more direction, but it's such a big update that every part of the new builder would benefit from some heavy testing.

**Comment by heretiq** [comment]
Thanks Nick. That's exactly what I needed to know. I will run it through it paces and report and issues I encounter. Thank you. Keep up the great work!
