### ISSUE TITLE
Save button visual issues in FireFox

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#224]
### Problem:

I noticed some visual issues with the `save` button in FireFox browser:
- [x] spinning circle misaligned during the saving process ( it should be centered like in Chrome ):

![image](https://cloud.githubusercontent.com/assets/3446682/18041969/7dcdca32-6ddf-11e6-8708-ec4890a752ef.png)
- [ ] text becomes misaligned after saving the **Post**, but looks fine on Pages:

![image](https://cloud.githubusercontent.com/assets/3446682/18041996/b32408ae-6ddf-11e6-9af7-8e62427609e7.png)

### Steps To Reproduce:
1. Enable Visual Builder on **Post** using FireFox browser
2. Click `save` button
3. Check the spinning circle alignment during save
4. Check the text alignment on the button after save

**Comment by andyhqtran** [comment]
The text seems find on my end, but the icon is misaligned.
