### ISSUE TITLE
VB should display warning on attempt to exit

### ISSUE THREAD

**Issue by TrevorGreenfield** [elegantthemes/Divi-Beta#227]
### Problem:

Visual builder should, consistent with standard builder and modern UX, display a dialog warning on page exit if there are unsaved changes to the node.  Currently, there is nothing to stop you from losing great amounts of unsaved info if you accidentally click on a page link or really, anything.

### Steps To Reproduce:
1.  Work on anything in VB.  Make a change.
2.  Click on any link on the page that would take you out of editor.
3.   Note there is no dialog to prevent lost work from not saving changes.
4.  Repeatedly bang head against desk for lost productivity.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: W7x64

**Browser**: Chrome or FF

**Screen Resolution**: 2560 x 1080

**Comment by timayhelen** [comment]
Thanks for the suggestion. We already have an issue ope for this, so I am closing this duplicate.
