### ISSUE TITLE
End split test popup when changing page setting  

### ISSUE THREAD

**Issue by DiviThemeExamples** [elegantthemes/Divi-Beta#23]
### Problem:

end split test message appearing after split testing has ended

### Steps To Reproduce:
1. new page, new section, new row, new text module
2. right click and enable split testing on the text module
3. right click and end split testing. select the module to keep.
4. goto page settings and try and change one of the colour palettes and it is showing the popup for end split test....which was already ended.

### Additional Information:
video available if ^ doesn't make sense...
*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
laptop
**Operating System**:
windows
**Browser**:
chrome latest
**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
Hi @DiviThemeExamples, thank you for reporting the issue. Your reproducing steps is already clear, but can you send us the screencast too? It'll help us ensuring that the fix we're working fixes your issue :)

**Comment by fikrirasyid** [comment]
Hi @DiviThemeExamples, thank you for reporting the issue. We've submitted a patch that should've fixed this issue and the patch is currently under review process right now. Once it passes the review process, it will be merged on the next release.

**Comment by DiviThemeExamples** [comment]
ok, thanks. was just about to send the screencast...but guess its not needed now.

cheers. 

2.7 looks very cool !

**Comment by fikrirasyid** [comment]
@DiviThemeExamples yeah, you don't need to send the screencast. After multiple and consistent bug replication, I'm quite sure that the bug we're addressing is similar to the one you're having. Sorry for that earlier.

> 2.7 looks very cool !

Thanks! I hope it will enable you to do more cool things! :D
