### ISSUE TITLE
Cannot update Divi to 2.9.13 - Update Failed

### ISSUE THREAD

**Issue by DebLJones** [elegantthemes/Divi-Beta#231]
### Problem:

I am not able to update Divi to the latest version. I have installed the Beta Updater Plugin and authenticated my account. On Appearance > Themes, I click on Theme Details and see this message:
There is a new version of Divi available. View version 2.9.13 details or update now.
I click on Update Now. The little icon spins, then I receive this error in red and pink: 
Update Failed: The theme is at the latest version.

The little icon continues to spin until I refresh the page and it returns to saying there is an update available.

**Comment by timayhelen** [comment]
I think this just means the update notification got cached, but you have successfully updated. If you give it a little time it should go away.

**Comment by DebLJones** [comment]
No, I don't think it is a cache issue--I am still not able to update from 2.9.12. Theme is now at version 2.9.17 and I have attempted to update repeatedly - all unsuccessful with the same error: 

Update Failed: The theme is at the latest version.

I downloaded my current changelog.txt and the last entry is "version 2.7.10 ( updated 08-18-2016 )".
