### ISSUE TITLE
Visual builder doesn't work on home page

### ISSUE THREAD

**Issue by sweetsop** [elegantthemes/Divi-Beta#232]
### Problem:

I can use the visual builder on my other pages but when I try to use it on the home page, the 4 dots just spin and spin. Also, I couldn't export the Layout JSON for the home page, works fine on other pages.

### Steps To Reproduce:
1.  Go to the home page while logged in
2. Click Enable Visual Builder

OR

1. From the Edit Page screen inside the dashboard while editing the home page click Use Visual Builder. (neither method works)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
HP Laptop

**Operating System**:
Windows 10

**Browser**:
Chrome

**Screen Resolution**:
1600x900

**Screenshot or Screencast**:
http://adobe.ly/2bxE2Db

**Link To Download Layout JSON File**:
Could not export Layout JSON.  Progress froze at 1%.
http://adobe.ly/2c5Sf7n

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@sweetsop Can you please try disabling all of your plugins and let us know if the builder still fails to load?
