### ISSUE TITLE
Prevent text selection when snapping modal

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#237]
### Problem:

When modal is being dragged to be snapped, it tends to accidentally perform unwanted text selection:

![prevent-text-selection-when-snapping-modal](https://cloud.githubusercontent.com/assets/916442/18089893/3eadc696-6eec-11e6-87a5-90c0cd04ba50.gif)

### Steps To Reproduce:
1. Open any module / page settings 
2. Try snapping it to the left or right

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Comment by timayhelen** [comment]
This causes quite a bit of lag when first dragging the modal. Basically it takes .2s or so to start moving after you start dragging, likely because things are re-rendering. I don't think it's worth it, unless there is a better solution.

**Comment by fikrirasyid** [comment]
@timayhelen hmm.. I hardly noticed the lag 🤔 I closed the previous PR and open new one at https://github.com/elegantthemes/submodule-builder/pull/1035. This PR only disable the text selection when it enters snap area (so no action that can possibly lag the modal dragging is occurred when the modal is being dragged)
