### ISSUE TITLE
Disabled Sections 'ghosting' in the VB Frontend

### ISSUE THREAD

**Issue by DeerMtn** [elegantthemes/Divi-Beta#239]
### Problem:

Should it be normal when editing pages in Visual Builder, and you have disabled sections on that page, the sections show up in low opacity? It makes it much more difficult to edit the page on the front end with disabled sections showing.

### Steps To Reproduce:
1.  Edit desired page in backend
2. Disable one or two of the sections for all screen types
3. Save the page and view
4. Enable the "Visual Builder" 
5. Notice that the sections you've disabled in the backend now show on the frontend in lower transparency

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Dell Laptop

**Operating System**: Win 10

**Browser**: Latest version of Chrome

**Screen Resolution**:

**Screenshot or Screencast**: ![visualbuilder_ss1](https://cloud.githubusercontent.com/assets/21114520/18093691/fa928d42-6e8d-11e6-8f12-3b9082b5cc36.jpg)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
This is intentional because and completely hidden section would be impossible to update in the visual builder. We want the visual builder to be completely functional, and we don't want there to be a reason for people to jump back and fourth between the BB and VB for certain features.
