### ISSUE TITLE
fullwidth header the image loads larger, then 'pops' into place/shrinks (resizes)

### ISSUE THREAD

**Issue by SheriLossing** [elegantthemes/Divi-Beta#24]
### Problem:
I am using no plugins, other than the two to install/update for the beta version, and with my fullwidth header the image loads larger, then 'pops' into place/shrinks (resizes). http://fa4.690.myftpupload.com/

### Steps To Reproduce:
1. Load this page. It is the full-width header at the top: http://fa4.690.myftpupload.com/
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: iMac (Retina 5K, 27-inch, Late 2015)
**Operating System**: OS X El Captain (van.10.11.3)
**Browser**: Chrome
**Screen Resolution**: 5K
**Screenshots**: Video/screencast: http://youtu.be/0Isj9X7nvQw?hd=1

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
That's just because you have parallax enabled. Javascript calculates the correct size of the image based on the size of the section, but it needs time to load. You can disable parallax mode or use CSS parallax as an alternative.

**Comment by SheriLossing** [comment]
@SlavaET I just got on and saw that it is marked 'ready for review'. Not sure if this means you want me to check if it is still happening, but I just checked in Chrome and in Firefox and still see the issue on my end.

**Comment by SlavaET** [comment]
@SheriLossing you don't need to check anything yet. It's our internal review process and the fix is not available for you yet. It'll be included into next version of theme.
