### ISSUE TITLE
Unable to add rows to new unsaved page or project

### ISSUE THREAD

**Issue by TrevorGreenfield** [elegantthemes/Divi-Beta#240]
### Problem:

If you start a new page, and don't add a section before you click on Enable VB, you cannot add the first row in VB, instead, it takes you to the home page.  After deleting the header in developer tools, it appears this problem is caused because of a conflict in positioning of the teal row addition icon and the header logo.  It also appears the default section that is added does not have enough padding or margin applied to avoid this issue.

If instead, you add a row in the standard builder and then enable VB, the page functions as intended.

Also, this behavior is not seen in Posts.

### Steps To Reproduce:
1.  Start new page, don't add a section
2.  Start Builder then, VB
3. Note if you click to add a row to the page it instead sends you to the front page.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Win7x64

**Browser**: FF & Chrome

**Screen Resolution**: 2560x1080

**Screenshot or Screencast**: 
![record_2016_08_30_08_08_05_47](https://cloud.githubusercontent.com/assets/16709732/18095271/4a219b58-6e8b-11e6-90e6-e53ce8a33741.gif)

**Comment by timayhelen** [comment]
Thanks for the report. This issue has already been opened and fixed here: https://github.com/elegantthemes/Divi-Beta/issues/83 It will be available in the next beta update.
