### ISSUE TITLE
Custom Margin and Custom Padding Labels Missing

### ISSUE THREAD

**Issue by stearmanbc** [elegantthemes/Divi-Beta#243]
### Problem: UX issue with Custom Margin and Custom Padding.

On visual builder the custom padding and custom margin fields are not labeled so the user would know what margin or padding they are adjusting. Should be labeled Top, Left, Bottom, Right. This is on all levels (section, row, text, image, etc.)

### Steps To Reproduce:
1.  Settings
2. General or Design
3. Margin or Custom Padding
4.

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
