### ISSUE TITLE
Add Input Field For Inline Editor Color Picker

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#244]
There should be a way to input hex or rgba values.

**Comment by timayhelen** [comment]
@fikrirasyid Can we have the input field appear in the top part of the inline editor, similar to the input field of the "link" option:

![screen shot 2016-08-31 at 11 16 45 am](https://cloud.githubusercontent.com/assets/3333028/18140947/7b15f06a-6f6c-11e6-95c4-2aec2b6c1b5f.png)

We can use the same styles too.

**Comment by fikrirasyid** [comment]
@timayhelen I've adjusted the position. I've adjusted the styling to match url's input as well (I'm not 100% sure about the styling tho):

![screen shot 2016-09-01 at 6 35 27 am](https://cloud.githubusercontent.com/assets/916442/18150087/86a69bd0-700e-11e6-9701-036d547cb968.png)
