### ISSUE TITLE
Call To Action text uneditable 

### ISSUE THREAD

**Issue by mshigekawa** [elegantthemes/Divi-Beta#247]
### Problem:

In the Visual Editor, when you scroll over text on a Call to Action component, it is not possible to edit the text unless you manually go into the Call to Action Settings.

### Steps To Reproduce:
1.  Load the Header #4 layout from the Ultimate Layout Pack 
2. Enable Visual Builder 
3. Scroll over Header #4 / Call To Action text and attempt to inline edit

### Additional Information:

**Device**: iMac

**Operating System**: OS X El Capitan 10.11.6 

**Browser**: Chrome Version 52.0.2743.116 (64-bit)

**Screen Resolution**: 2560 x 1440

**Comment by timayhelen** [comment]
@mshigekawa At this time only body content is editable, not the title. However we are hoping to adding inline editor support for other areas as well. There is already a ticket open for this, so I am closing this duplicate.
