### ISSUE TITLE
Portability :: Export button text misaligned

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#25]
### Problem:

See the screenshot for details. It's the same on Divi library page, Single Page, Customizer and ePanel

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Macbook Pro + Thunderbolt Display

**Operating System**: OSX El Capitan

**Browser**: Chrome 49

**Screen Resolution**: 2560x1440

**Screenshots**:
![image](https://cloud.githubusercontent.com/assets/3446682/14018142/34a05326-f1f6-11e5-9878-9bd1155f1863.png)
-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
I'll fix it.
