### ISSUE TITLE
I put some buttons on my website using Chrome but it is not showing up in Explorer www.nørrelyndelsekirke.dk

### ISSUE THREAD

**Issue by viamedia** [elegantthemes/Divi-Beta#252]
### Problem:

Replace this section with a description of the issue you are reporting. Be sure to explain the expected results vs. actual results when it might not be obvious to those who will read your report. 

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@viamedia Would you mind filling out the issue template with the details requested? We would love to look into this, but it's difficult to figure out from the title alone what exactly is happening.

**Comment by viamedia** [comment]
hi, 
Steps To Reproduce:
1.  go to http://www.nørrelyndelsekirke.dk using chrome webbrowser
2. go to same adress using Explorer webbrowser 
3. 
4. 

Additional Information: With the Chrome webbrowser you can se the 3 Pictures (buttons) on the FrontPage

With the explorer webbrowser you can se the 3 Pictures (buttons) on the frontpage


Please include any of the following details that are relevant to the issue you are reporting.

Device:

Operating System:

Browser:

Screen Resolution:

Screenshot or Screencast:
