### ISSUE TITLE
Duplicate Modules Causes Ajax Loading Bar & Breaks HTML

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#253]
Looks like there is a strange issue with module duplication. The preloader renders and the content often breaks after duplicating.

**Comment by timayhelen** [comment]
Also, moving modules is not rather glitchy. The animations are not longer smooth because the re-render seems to interrupt them. It's not something that happened in previous beta versions.

**Comment by SlavaET** [comment]
I fixed the issue with duplicating of Rows and Sections in my PR.
As for the modules moving issue, it seems to be fixed in this Fikri's PR - https://github.com/elegantthemes/Divi-Beta/issues/251
