### ISSUE TITLE
Accordion module :: Color settings

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#254]
### Problem:

The color options shows previous color after you change the color and open module settings again.

![accordion](https://cloud.githubusercontent.com/assets/9657712/18124194/06fd6cc2-6f93-11e6-8cce-e99ee23e77db.gif)

### Steps To Reproduce:
1.  Open toggle settings
2.  Change color
3.  Close module settings
4.  Open toggle settings. The text color option shows previous color

Same issue with icon color and background color.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: Windows7

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by eduard-ungureanu** [comment]
The same issue happens in Chrome - mac OS X.
