### ISSUE TITLE
Position of Right Click menu and Inline editor popover incorrect on Posts

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#255]
### Problem:

Position of Right Click menu and Inline editor popover incorrect on Posts and pages with sidebar.
O fixed this issue a while ago for the tooltips modals. Need to apply similar fix for these elements.

### Steps To Reproduce:
1. Open Post with the sidebar
2. Enable Visual Builder
3. Right click inside the app
4. Check the position of Right Click Menu

**Comment by timayhelen** [comment]
@SlavaET It looks like the very first time you click and open the inlined editor, it appears in the wrong location. After that, all subsequent clicks work correctly.

**Comment by SlavaET** [comment]
@timayhelen I cannot reproduce this issue. It works correctly from the very first click on my end. Could you please record a screencast? probably I could understand what's wrong from there

**Comment by timayhelen** [comment]
@SlavaET I can't replicate it now, but I think it had something to do with comments. We can look at it again if the bug re-surfaces.
