### ISSUE TITLE
Comment module :: doesn't show up

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#256]
### Problem:

![commentmodule](https://cloud.githubusercontent.com/assets/9657712/18125319/86a91e72-6f97-11e6-9c9d-bd50730943a5.gif)

### Steps To Reproduce:
1.  Add comment module

It will show up if you save and update the page

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**: w7

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

**Comment by SlavaET** [comment]
@Jronk please check my answer https://github.com/elegantthemes/submodule-builder/pull/1047#issuecomment-244264824.
