### ISSUE TITLE
Coming soon module

### ISSUE THREAD

**Issue by jcolome** [elegantthemes/Divi-Beta#26]
http://infoseektechnologies.com/splash

### Problem:

dates won't update

Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@jcolome which date did you set in the Countdown Module? I tested it locally and it works fine.

**Comment by jcolome** [comment]
You are correct.  My bad.  I had 2014 as date set.

thanks
