### ISSUE TITLE
Cannot Edit Child Module After Adding

### ISSUE THREAD

**Issue by jking2076** [elegantthemes/Divi-Beta#26]
I have a "partial"  (Unsupported) Module/Child Module extension that I have offered since D1.  I have discovered that although I can add a child to the parent, no fields or attributes display for editing.  This holds true for children added in D4. The infamous "Panel" tab shows up.
![d5_unsupported_child2](https://github.com/elegantthemes/Divi-Beta/assets/21201937/cde1145c-a2c2-411b-a38c-790f9e90146c)
![d5_unsupported_child](https://github.com/elegantthemes/Divi-Beta/assets/21201937/d083bf93-c5da-4620-8b75-45826b88af4a)

**Comment by Lovely-Fellow** [comment]
@jking2076 Mostly because of JS error. Please check console error.

**Comment by jking2076** [comment]
@Lovely-Fellow Yeah, this is old stuff.  Check the date of my filing  ;^)  They told me to pen this issue but there was never any discussion.

**Comment by Lovely-Fellow** [comment]
@jking2076 Ok, so you can close this issue?

**Comment by jking2076** [comment]
@Lovely-Fellow not to be flippant and I don't mean to be, but you are asking why?  I'll probably need to recheck to see what this looks like now and to determine if it could be an issue to a public user.

**Comment by Lovely-Fellow** [comment]
@jking2076 I'm checking all opened issues and not seeing this issue from my side. That's why.

**Comment by jking2076** [comment]
@Lovely-Fellow I assumed as much.  Thnx for recalling my attention to it.  I had figured it had disappeared and I didn't press it.  It was in the early days of dev-alpha.

**Comment by shohel** [comment]
Closing this issue in favor of - https://discord.com/channels/1041765492907589683/1105867503097368681/1322116471219949590
