### ISSUE TITLE
Cannot open settings of module items

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#260]
### Problem:

If I click to open settings of the item in modules like Slider or Pricing table - nothing happens. I can duplicate, move, remove or add items, though

### Steps To Reproduce:
1. Open settings of any module with sub items ( slider for example )
2. Try editing its sub items

**Comment by fikrirasyid** [comment]
Note: also fixing an issue where closing module item's setting directly closes its parent instead of closing itself + back to parent
