### ISSUE TITLE
Accordion Animation :: Doesn't work

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#261]
### Problem:

Using VB, when 2 or more rows contains the accordion module, the animation (open - close) only works for the accordion in the first row

### Steps To Reproduce:
1.  add at least 2 rows ( I did used 4 columns for the first row with 3 columns in the second row)
2.  in each row add multiple accordion modules
3. the open close animation on accordions from the second row doesn't work

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: MAC OS X
 
**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**: https://drive.google.com/file/d/0B8PjD3Z_XQvuWEJBTW1GY045SkU/view?usp=sharing

**Comment by fikrirasyid** [comment]
@eduard-ungureanu have you checked this on latest `1848-front-end- builder`? I checked this on latest commit and it works as expected:

![animation works as expected](https://cloud.githubusercontent.com/assets/916442/18197526/cbc60c5a-7121-11e6-940d-44e7885d3240.gif)

**Comment by eduard-ungureanu** [comment]
@fikrirasyid no yet, but I will try it later to day and update this!

**Comment by SlavaET** [comment]
I remember fixing this issue in one of my PRs, looks like it was already merged.
anyway, let's wait for the @eduard-ungureanu

**Comment by eduard-ungureanu** [comment]
@fikrirasyid and @SlavaET using #1848 is now working as it should 💃
