### ISSUE TITLE
Slider Module :: Custom Styles for Button

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#262]
### Problem:

Once the custom Styles For Button is enable, the hover icon is misplaced.

### Steps To Reproduce:
1.  add the slider module
2. add a slide
3. enable Use Custom Styles for Button

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop

**Operating System**: Mac OS X

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
![screen shot 2016-08-31 at 5 12 07 pm](https://cloud.githubusercontent.com/assets/1719735/18132117/13b795d6-6f9e-11e6-8ccf-e7580ceb5959.png)

**Comment by timayhelen** [comment]
Thanks for the report. There is already an issue open for this, so I am closing this duplicate.
