### ISSUE TITLE
Text Module ::Unable to move if it contains short text

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#264]
### Problem:

In a totally random layout I'm unable to move the text module, the options dissapper

### Steps To Reproduce:
1.  Add a text module and enter a short text something like: "Audio Module"
2. Try to move the text module

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: dekstop

**Operating System**: mac os x

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuOE1GamVTX3l3RDg/view?usp=sharing

**Comment by timayhelen** [comment]
@fikrirasyid The issue here is that it makes it impossible to trigger the inline editor in most situations. Is there something we can do about that?

**Comment by fikrirasyid** [comment]
@timayhelen ah I see. I was wondering what is the intent of `pointer-events: none;` you added. I'll take a look at it and figure out a way to allow access to inline editor and mousetrap. For the time being, it is limited to short and really short module only so it is better than previous approach (although it isn't good enough tho). I'll keep you notified.

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed https://github.com/elegantthemes/submodule-builder/commit/c2d876b59a2789791ef8cd27ec35c864fd3856dd which should've fixed the issue. It allows mousetrap's area to have `pointer-event: auto` and make inline editor area accessible.

**Comment by eduard-ungureanu** [comment]
@fikrirasyid same goes for the code module:https://drive.google.com/file/d/0B8PjD3Z_XQvuamlYdTY1OE9nMXM/view?usp=sharing

**Comment by fikrirasyid** [comment]
@eduard-ungureanu it has been fixed as well, and the patch has been merged to the latest `1848-front-end-builder`:

![short module](https://cloud.githubusercontent.com/assets/916442/18216959/332219f4-7184-11e6-8465-bd556a4ceb5a.gif)
