### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by eileenlonergan** [elegantthemes/Divi-Beta#265]
### Problem:

Hey guys, thanks for all of this hard work, really impressive.  

I have hit a bump in Chrome (on a Mac, 21").  My test site doesn't seem to span the full width of the browser window.

Beta testing url: http://www.eileenlonergan.com/test/

![screen shot 2016-08-31 at 12 17 22 pm](https://cloud.githubusercontent.com/assets/6805934/18137093/11ca53e0-6f75-11e6-8da8-d7be68e027e2.png)

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@eileenlonergan Can you try disabling all plugins and child themes and see if it makes a difference?

**Comment by timayhelen** [comment]
I believe this is a known issue with the KK Modules plugin, and I assume the developer will be looking into it.
