### ISSUE TITLE
row tool tip and menu visibility sticks + tooltip inconsistencies in section and module's popover + add new button

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#266]
### Problem:

Row tooltip and menu appear to stick after mouseout.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Win10

**Browser**: Chrome

**Screen Resolution**: 1366 x 768

**Screenshot or Screencast**: http://youtu.be/PZ3d7ZF-hZE?hd=1

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
@websbyjd thank you for reporting the issue! I'm able to replicate the issue on another situation, but to make sure, can you export the layout you're using on the video above so I can debug the issue on that particular layout? You can export the layout using portability feature, zip it, then attach it to this issue's comment. Thanks.

**Comment by websbyjd** [comment]
[Divi Builder Layout.zip](https://github.com/elegantthemes/Divi-Beta/files/448629/Divi.Builder.Layout.zip)

**Comment by fikrirasyid** [comment]
@websbyjd thank you for the layout! I'm now able to replicate the issue exactly like how you captured on the screencast. We'll further investigate the issue and we'll keep you notified.

**Comment by fikrirasyid** [comment]
@websbyjd We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄
