### ISSUE TITLE
Visual builder phone size differs from real phone size

### ISSUE THREAD

**Issue by ChrisMechanic** [elegantthemes/Divi-Beta#268]
Hey!

So I made new page in Visual Builder and than changed view to phone and made fine tuning to adjust height of the rows, size of the text etc.
All good.
Than saved and opened that page in my phone (Honor 7, HD display 1080 x 1920) and it looks different.
I'm not sure if it is a bug or just differences in sizes, but...

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
PC, Honor 7 phone

**Operating System**:
Windows 10, Android 6.0

**Browser**:
Chrome and Chrome

**Screen Resolution**:
PC" 1920 x 1200
phone: 1080 x 1920
![screenshot_2016-08-31-23-22-45](https://cloud.githubusercontent.com/assets/21371893/18147236/00f099da-6fd4-11e6-8ad6-717daea03747.png)

I attache print screens for both devices
![divi_3 0](https://cloud.githubusercontent.com/assets/21371893/18147173/b36f4198-6fd3-11e6-9b9a-1b902bc35d03.PNG)

**Comment by timayhelen** [comment]
I don't think this is avoidable. Different browsers will end up rendering things slightly differently. The best we can do in our preview is adjust the width of the content and trigger the breakpoints.
