### ISSUE TITLE
Visual Builder :: Add New Section button :: hardly visible

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#270]
### Problem:

Some times it's tricky to find the Add New Section Button.

![divi](https://cloud.githubusercontent.com/assets/3352130/18151302/e2bbce76-6ff6-11e6-91d2-9e6d6c2a45ec.gif)

### Additional Information:

**Device**:
Desktop
**Operating System**:
Win 10
**Browser**:
FireFox
**Screen Resolution**:
1920x1080

**Comment by timayhelen** [comment]
Thanks for the report. There is another issue open for this, so I am closing this duplicate.
