### ISSUE TITLE
Visual Builder:Responsive layout simulation issue

### ISSUE THREAD

**Issue by garglingfish** [elegantthemes/Divi-Beta#276]
### Visual Builder:Responsive layout simulation issue:

Create a Blog page with a grid layout of posts (3 columns for example). When using the visual builder to simulate phone and tablet views, it simply compresses the 3 columns instead of responding as it would in real use. On actual devices, the computer gives 3 columns, a tablet switches to 2 columns, and the phone has 1 column. You also get this result with the developer tools in Google chrome.

I would expect the Divi visual builder to simulate mobile device views the same way the Google developer tools do.

I have tested this on windows 10 - Chrome and Explorer, and Mac OS 10 - Chrome and Safari

**Comment by timayhelen** [comment]
@garglingfish Are you referring to the responsive testing buttons provided by the visual builder? It correctly breaks down the columns for me. Are you using a child theme or any third party plugins? Try disabling them all to see if it helps.

**Comment by garglingfish** [comment]
Yes, that’s what I’m referring to, I’m testing this in a new barebones install. Yes, I was using a child theme but I get the same results with the parent. I now find that I can force the transition by horizontally squeezing the browser window size, but it seems like that defeats the purpose of the testing buttons. Below are screen shots of the results I’m talking about.

Monitor selected
[cid:3FA4B486-1C3E-463C-A9E8-992CEC33D2E4@hsd1.or.comcast.net.]

Tablet selected
[cid:47F05076-6829-448B-ADD4-FA8437B7EB4F@hsd1.or.comcast.net.]

Phone selected
[cid:3B476C1F-910C-4B0D-B573-42179651D00D@hsd1.or.comcast.net.]

On Sep 1, 2016, at 1:40 PM, Nick Roach <notifications@github.com<mailto:notifications@github.com>> wrote:


@garglingfish<https://github.com/garglingfish> Are you referring to the responsive testing buttons provided by the visual builder? It correctly breaks down the columns for me. Are you using a child theme or any third party plugins? Try disabling them all to see if it helps.

**Comment by timayhelen** [comment]
@garglingfish I see, this is isolated to Blog module when it Grid mode. Thanks! @SlavaET Looks like we need to add responsive styles for the blog module.
