### ISSUE TITLE
Bloom edit optin presents blank screen

### ISSUE THREAD

**Issue by agirlandhermac** [elegantthemes/Divi-Beta#28]
### Problem:
Created a new popup optin and returned to edit settings and got a blank screen. Also tried to edit an inline optin that had previously been created and again a blank screen.

### Steps To Reproduce:
1. Bloom optin forms > edit optin

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: MacBook Pro 17"

**Operating System**: OSX El Capitan 10.11.4

**Browser**: Chrome 49.0.2623.87

**Screen Resolution**: 1850 x 1050

**Screenshots**:
![screen shot 2016-03-26 at 4 44 13 pm](https://cloud.githubusercontent.com/assets/16481723/14062600/b58d6514-f372-11e5-882e-3afe444d32b6.png)
-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by agirlandhermac** [comment]
Updating to say the options came back. It wasn't after a cache clear or anything, not sure what brought it back, but now I can edit settings for the optins.

**Comment by lots0logs** [comment]
Okay, thanks for the update. If it happens again, please let us know!
