### ISSUE TITLE
SoundCloud audio player doesn't load in blogroll

### ISSUE THREAD

**Issue by MyInternetScout** [elegantthemes/Divi-Beta#280]
### Problem:

SoundCloud audio player doesn't load in blogroll excerpt.  Visitors should be able to play the sound cloud player straight from the blogroll.  Now, users only see shortcode where the player is suppose to be.  Please refer to my two enclosed screenshots.  - Peter
![20160901 how soundcloud is suppose to show in blog roll](https://cloud.githubusercontent.com/assets/21134596/18172487/9b5739fc-7033-11e6-90af-f0fbdba6e5fa.jpg)
![20160901 soundcloud not showing in blog roll](https://cloud.githubusercontent.com/assets/21134596/18172491/9e0b9df0-7033-11e6-93de-93bb20cd1b80.jpg)

**Comment by SlavaET** [comment]
@MyInternetScout I cannot reproduce the issue, Soundcloud embed shortcode works fine inside the Blog module in both Visual Builder and Front end. Can you please check it in the latest version of Divi ( it's 3.0.5 ) at the moment.
