### ISSUE TITLE
Bar Module :: Cannot change item title

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#281]
### Problem:

If the bar module's items are cloned, you cannot change their titles anymore

### Steps To Reproduce:
1.  add the bar module
2. add a bar item
3. duplicate the item
4. change it's title

### Additional Information:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuUzBLQ3YtWUUzUGM/view?usp=sharing

**Comment by fikrirasyid** [comment]
@SlavaET I've checked https://github.com/elegantthemes/submodule-builder/pull/1056 on various situation, including several other modules such as code, etc and it doesn't cause any side effect, as long as i can see. Nevertheless, can you take a look at it and see whether it will impacting anything that you anticipate at https://github.com/elegantthemes/submodule-builder/commit/edeb1a4f8d3487acb513bbf26af87596ae607e06#diff-b1d71f459e338ab33b5b5db74dc6c5c6R210 (I noticed that you added it previously)?
