### ISSUE TITLE
Blog Module :: Fails to load

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#282]
### Problem:

Building a layout in FB using Blog Module, after exiting the Builder, when trying to enter the builder again the blog module fails to load, if a post has the Gallery Format, and in dev console the  et_pb_slider_init is not defined shows

### Steps To Reproduce:
1.  add a blog module
2. exit the FB
3. enter again
4. blog module doesn't load

### Update:
Once you leave the FB everytime you want to return the FB will not load while the above error is still present.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuM0dlM3JxRXBOLXM/view?usp=sharing

**Comment by fikrirasyid** [comment]
This issue is also fixed at https://github.com/elegantthemes/submodule-builder/pull/1054 because it prevents https://github.com/elegantthemes/Divi-Beta/issues/258 from being fixed.
