### ISSUE TITLE
Circle Counter :: Clone No animation and no text

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#283]
### Problem:

In FB after creating a Circle counter, once it is cloned the animation doesn't happen, and also the number and the % sign doesn't appear.

### Steps To Reproduce:
1.  add a circle counter
2. clone it

### Update

When cloning a row that has already 1 or more Circle counters, the animation of the counter start, but then it dissapper.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: chrome 

**Screen Resolution**:

**Screenshot or Screencast**:
Video 1: https://drive.google.com/file/d/0B8PjD3Z_XQvuLW56RVBSMzJzUkE/view?usp=sharing

Video update: https://drive.google.com/file/d/0B8PjD3Z_XQvuQkNhaXpIOFV1TEU/view?usp=sharing

![screenshot-et dev 2016-09-01 19-50-13](https://cloud.githubusercontent.com/assets/1719735/18176252/7fd707e4-707d-11e6-8052-e6d4794cb8cb.jpeg)

**Comment by timayhelen** [comment]
@Anny85 It also looks like the work you did to have Circle Counters resize correctly on browser resize isn't working anymore.

**Comment by kary4** [comment]
It happens also for Number Counter module.

**Comment by who519** [comment]
Has this issue ever been resolved? I am experiencing it with any page that has more than one set of animation. eg I have a row with three circle counters that work great, a few sections below, I have a number counter and it doesn't trigger until after I scroll past it.

**Comment by lots0logs** [comment]
Hi, if you could please open a ticket in our [Support Forum](https://www.elegantthemes.com/forum) so that our staff can assist you. Thanks for your cooperation :smiley:
