### ISSUE TITLE
third party module plugin not working in Visual Rnd 2

### ISSUE THREAD

**Issue by jking2076** [elegantthemes/Divi-Beta#284]
I've done some further testing with 2.9.14 and KK Divi Mods. Please, see beta issue #172.  The "fix" discussed there seems to be working as it was described but a new problem has surfaced.

I've noticed that child modules as content in KK parent modules are lost when a page/post is saved in VB.

### Steps To Reproduce:
1.  use KK Horizontal Tabs and/or KK Vertical Tabs Ext PB
2. creat two tabs and use tiny-mce
3. publish
4. use VB and do something
5. Save
6. use PB and note if child tabs saved in step 3 are gone

### Additional Information:

There are other KK modules that use child modules.  I've not verified this anomaly with those, but will check and identify here.

**Comment by jking2076** [comment]
UPDATE: for all of the various parent modules in KK, all child modules are lost whether Save Draft or Publish within VB.

**Comment by SlavaET** [comment]
Fixed. Now the content of 3rd party modules will not be broken during save.
Also fixed the issue with loading 3rd party items from library and duplicating of 3rd party modules.

@jking2076 thank you for providing the detailed description of the issue. The fix will be included into next Beta version.

**Comment by jking2076** [comment]
@SlavaET I'm more than happy to contribute even though it's mostly in my best interest ;^)  However, there are more devs than myself who have jumped on the Divi train.  I hope that anything we've done here will help others.

**Comment by Jronk** [comment]
@jking2076 we are thankful for your contributions and beta testing from the 3rd party dev perspective, thanks!
