### ISSUE TITLE
Can't modify Divider Module

### ISSUE THREAD

**Issue by lmilesw** [elegantthemes/Divi-Beta#285]
### Problem:

After adding a divider module via the Visual Builder I am unable to modify the Divider.

### Steps To Reproduce:
1.  Add new Divider Module
2. Click the check to save
3. Try to edit the module
4. The box for selecting edit keeps going away when I move the cursor to click on edit

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. We have an issue open for this already, so I am closing this duplicate.
