### ISSUE TITLE
Image module - near impossible to click settings etc

### ISSUE THREAD

**Issue by gelbin** [elegantthemes/Divi-Beta#286]
### Problem:

it is nearly impossible to mouse over the settings etc. without them disappearing

### Steps To Reproduce:
1.  try to edit image module in visual builder
2. move mouse
3.  settings, etc. disappear as soon as you move the mouse

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:
safari

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. This issue is already listed so I am closing this duplicate.
