### ISSUE TITLE
Add fullwidth module button tooltip wrong

### ISSUE THREAD

**Issue by danmossop** [elegantthemes/Divi-Beta#288]
When adding a full-width section, the grey "Add module" button brings up the Insert module modal as expected. However, if you hover over this button the tooltip says "Add New Row", which seems to be wrong. I would expect the tooltip to be "Add New Module".

![image](https://cloud.githubusercontent.com/assets/17969935/18193237/eb1f9812-711e-11e6-96fe-145e9dc7ed88.png)

**Comment by SlavaET** [comment]
Fixed. Also corrected tooltips for Inner Rows inside the Specialty sections.
