### ISSUE TITLE
Font Awesome code disappears from all text modules when editor toggled to Visual on any text module

### ISSUE THREAD

**Issue by heretiq** [elegantthemes/Divi-Beta#289]
### Problem:
Font Awesome code in all text modules on a page disappears when the editor toggled from Text to Visual in any text module.

### Steps To Reproduce:
1. Create a page with several sections -- with each section containing two columns with text modules 
2. Add Font Awesome icon code in half of the text modules in Text mode
3. Switch from Text mode to Visual mode and update/publish the page
4. View page and see that all FA icons are missing
5. Edit the page and confirm that all FA code is missing from text modules where FA code was added

Please see attached screencast and JSON layout file.

### Additional Information:
*Please include any of the following details that are relevant to the issue you are reporting.*
**Device**: Retina MacBook Pro
**Operating System**: MacOS Sierra Beta 8
**Browser**: Safari Technology Preview Release 12 (Safari 10.0, WebKit 12603.1.3)
**Screen Resolution**: Retina Scaled 1680x1050
**Screenshot or Screencast**: https://www.dropbox.com/s/i4lt0bfs68koilp/Divi%203%20Beta%20Text%20Module%20Editor%20Problem.mov?dl=0
**Link To Download Layout JSON File**: https://www.dropbox.com/s/jeh7ii1xov0afby/Divi%20Builder%20Layouts-9-2-16.json?dl=0

**Comment by timayhelen** [comment]
This is pretty common when switching between text and visual mode. It will strip away and re-formatting your HTML when you enter visual mode, so it's best to stay in Text mode if you are using custom code.

**Comment by heretiq** [comment]
Hi Nick,

I think this may be a different case than the common one you cited — or perhaps this is the first time I’m encountering it. 

The problem I’m observing is that the FA code is lost in ALL text modules whenever ANY text module on the same page is switched to visual mode.  

In this case, editing a text module that does not contain ANY FA code causes ALL text modules with FA code to lose their code.

Is this the same common issue you are referring to? 

Thanks,

Donovan

xCentric Support ::::  www.getxCentric.com <https://getxcentric.com/>
The information in this email may be confidential and/or privileged. This email is intended to be reviewed by only the individual or organization named above. If you are not the intended recipient or an authorized representative of the intended recipient, you are hereby notified that any review, dissemination or copying of this email and its attachments, if any, or the information contained herein is prohibited. If you have received this email in error, please immediately notify the sender by return email and delete this email from your system.
