### ISSUE TITLE
Split Testing :: Select Goal Screen Not Visible Fully on Lower Resolution Monitors

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#29]
### Problem:

The last step in setting up split test is **Select Goal Screen** but the pop up for this does not seems to fit well on screen , anything below 1366 x 768 screen resolution , we are not able to click on OK button , we need to zoom out (CTRL - ) so see the pop message and button properly. Many customers may report this .

### Steps To Reproduce:
1. Set up a Split Test
2. Go up to last screen where it says **Select Your Goal**
3. Need to do the above steps on screen resolution 1366 x 768 or lesser.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Window Laptop 

**Operating System**: Win 7

**Browser**: Firefox, Chrome 

**Screen Resolution**:1366 x 768 

**Screenshots**:
![screen](https://cloud.githubusercontent.com/assets/13402626/14065692/a6172d60-f451-11e5-8a5e-4fe2b65a5430.PNG)
-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
@abhi-sharm can you take a look at https://github.com/elegantthemes/submodule-builder/pull/628 and see whether it fixes the issue or not?

**Comment by abhi-sharm** [comment]
@fikrirasyid - Yes it works fine now.

**Comment by timayhelen** [comment]
@fikrirasyid I don't think it makes sense to apply vertical centering to only a single instance of the small modal. We should apply this everywhere for consistency. For example, to:

* All Split Testing prompt modals
* Clear Layout modal
* Save To Library (layout) modal
* Right Click > Rename modal

**Comment by fikrirasyid** [comment]
@timayhelen I see, I selectively applied the centerize mechanism to prevent unwanted backward compatibility. I'll apply it to all modal then.

**Comment by fikrirasyid** [comment]
@timayhelen I've incorporated your feedback at https://github.com/elegantthemes/submodule-builder/pull/628 and https://github.com/elegantthemes/submodule-core/pull/9 (to auto centerize core's modal). Previously, only auto centerize split test's alert modals. Now it auto centerize all modals which have no `bottom` data (which indicates it doesn't appropriately vertically centered)
