### ISSUE TITLE
Audio Player Loses Custom Appearance When Duplicating Module Or Moving Module

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#291]
![screen shot 2016-09-02 at 12 45 20 am](https://cloud.githubusercontent.com/assets/3333028/18196514/aa0ceece-70a6-11e6-8de6-3d91f28f05f9.png)

**Comment by SlavaET** [comment]
@timayhelen this issue should be fixed here - https://github.com/elegantthemes/submodule-builder/pull/1059
Do you see the same issue in my PR?

**Comment by timayhelen** [comment]
@SlavaET Yeah I actually saw it while testing your PR.

**Comment by timayhelen** [comment]
@SlavaET Maybe it was a cache issue because now I can't replicate it. Nevermind!

**Comment by SlavaET** [comment]
Yeah, looks like it was a cache, because this is one of the issues I fixed in the PR.
