### ISSUE TITLE
Visual Builder :: Expand Settings stuck on drag when clicked

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#297]
### Problem:
It appears that the problem is caused by the minify process. If you unminify the ``bundle.js`` file it works as expected. The problem should be obvious in the screenscast bellow.

### Steps To Reproduce:
Create a new page and enable the Visual Editor and then try to expand the setting.

### Additional Information:

**Browser**: Firefox 48.0.2

**Screenshot or Screencast**: http://screencast-o-matic.com/watch/cDQnXojfgz

**Comment by kary4** [comment]
Exactly the same problem here.
