### ISSUE TITLE
Code Module :: Cannot be view/edited in FB when contents doesn't have explicit height value.

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#298]
### Problem:

When in a code module, is only css code present that module, cannot be seen / edited / deleted from FB

### Steps To Reproduce:
1.  add 2 code modules
2. add a simple html code in one of those 2 CM
3. add a css code in the second module (I used `<style></style>` to wrap my css code)

Although the css style gets applied, I cannot edit that code module using FB.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:
![screen shot 2016-09-02 at 3 32 18 pm](https://cloud.githubusercontent.com/assets/1719735/18203977/dffef618-7122-11e6-8435-754d636216ff.png)
![screen shot 2016-09-02 at 3 32 23 pm](https://cloud.githubusercontent.com/assets/1719735/18203978/e246b474-7122-11e6-8bbe-f854834dfc4d.png)
![screen shot 2016-09-02 at 3 32 36 pm](https://cloud.githubusercontent.com/assets/1719735/18203979/e46ccfc2-7122-11e6-835c-88e05c4318a4.png)

I did show the content of the modules from backend, just to see the code used.

**Comment by SlavaET** [comment]
Looks like we need to add min-height to code module, to make it possible to edit in case when it doesn't output any HTML. It'll also make possible to edit empty code module, which is not possible right now.

**Comment by andyhqtran** [comment]
There's already a minimum height put in place.

**Comment by lots0logs** [comment]
Just tested this on the current `master` and the code module becomes completely inaccessible if its contents doesnt have explicit height. You cant even tell that the module is there at all really. You can use the following HTML to reproduce the issue:
```
<div class="row-1">
<div class="col-1"></div>
<div class="col-1"></div>
<div class="col-1"></div>
</div>
```

**Comment by lots0logs** [comment]
@SlavaET Can we fix it so that they aren't overlapping?

![2016-10- 5_11-55-45-am](https://cloud.githubusercontent.com/assets/4675662/19123065/d7e85aa2-8af2-11e6-8625-2df008854beb.png)

**Comment by SlavaET** [comment]
@lots0logs It'll happen with any module which has `height = 0` so it's not related to the Code module nor to the issue I fixed. It's more related to this - https://github.com/elegantthemes/Divi-Beta/issues/550
Just include this issue into the description so it won't get lost when I'll work on it.
