### ISSUE TITLE
Bloom settings do not include custom palette colors

### ISSUE THREAD

**Issue by agirlandhermac** [elegantthemes/Divi-Beta#30]
### Problem:

The edit optin settings don't include the custom colors that are picked in divi options and it seems like it should. If Bloom wasn't an ET product it would make sense that it didn't but...

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: MacBook Pro 17"

**Operating System**:  OSX El Capitan 10.11.4

**Browser**: Chrome 49.0.2623.87

**Screen Resolution**: 1850 x 1050

**Screenshots**: 
![screen shot 2016-03-27 at 10 35 25 pm](https://cloud.githubusercontent.com/assets/16481723/14070480/a4023d6a-f46c-11e5-9c9e-8a0185b3ae23.png)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
This option supposed to work only in Divi theme, since it can be configured in Divi settings only.
@timayhelen so we need to integrate support of this option into our plugins? There is no place where to configure it in plugins, but we can use the Divi settings if defined in ePanel. It will require updating of Bloom and Monarch plugins.

**Comment by timayhelen** [comment]
@SlavaET I think we should keep the color palette Divi-specific for now.
