### ISSUE TITLE
Comments module :: Doesn't appear when you first add it

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#300]
### Problem:

Try to add a comment module into your layout, it doesn't show, you need to exit the FB and then enter again to see it in action.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvub0dwc1V3ak1ZNTA/view?usp=sharing

**Comment by SlavaET** [comment]
Duplicate of https://github.com/elegantthemes/Divi-Beta/issues/256
