### ISSUE TITLE
Contact Form Module :: Submit leaves the FB

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#301]
### Problem:

After customize everything on the contact From Module, if I hit Submit, without saving the page, it leaves the FB and the Contact Form (since it was saved ) is not present anymore.

Maybe a message to inform the user that he first must update / publish the page, or simply deactivate the submit button while in FB might help.

**Comment by SlavaET** [comment]
We already added warning when you try to leave the page and have unsaved changes. It's in the latest `1848-front-end-builder` branch already.
