### ISSUE TITLE
Ability to Disable Front End Builder button in Divi Role Editor or Theme Options

### ISSUE THREAD

**Issue by SRHDesign** [elegantthemes/Divi-Beta#304]
@lots0logs  @timayhelen ### Problem:

Is there going to be an option to either disable the Front End Builder button completely via the Theme Options? Or an option to disable the Front End Builder button using the Divi Role Editor?

The Front End Builder is amazing! However, having tested it, I would not want **some** of my clients accessing a frontend builder as they would very easily break their sites. Some clients would be very capable of using the frontend builder but, definitely **not** all of them.

**Comment by SRHDesign** [comment]
@timayhelen Thanks for upgrading this from a Question to Feature. I see there is no Milestone or Assignee yet...does that mean this feature will not make the launch of Divi 3.0?

**Comment by SlavaET** [comment]
Added `Use Visual Builder` role into the `Builder Interface` section of Role Settings:
![image](https://cloud.githubusercontent.com/assets/3446682/18255133/dd65464e-73c7-11e6-9e75-ea49cf638e4b.png)

**Comment by SRHDesign** [comment]
That's very exciting. Can't believe the fast turnaround on this...hoping it makes it into the launch version of 3.0!

**Comment by Jronk** [comment]
@SRHDesign this will make it into 3.0, thanks for suggesting the idea
