### ISSUE TITLE
FB :: Page settings - undo/redo - color controls "color swatch" values don't undo/redo

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#311]
### Problem:

When you click undo/redo in the page settings modal, the changes to the page roll back/forward, but the current values in the color controls themselves do not rollback.

### Steps To Reproduce:
1.  Toggle page settings bar
2. Open page setting modal
3. Change the dark text color
4. Click undo in settings modal
5. You will see the changes reflected on the page, but the color swatch in the control will remain the previous value, and if you open the value you will see the text input is correct

### Additional Information:
**Screenshot or Screencast**:
![color-swatch-not-up-to-date-on-redo](https://cloud.githubusercontent.com/assets/1163441/18215175/cfb181b8-7104-11e6-8163-f6ac2d095300.gif)

**Comment by SlavaET** [comment]
@Jronk looks like it's the same issue - https://github.com/elegantthemes/Divi-Beta/issues/299

**Comment by SlavaET** [comment]
Or do you see the issue with color pickers only? Do the other controls reflect changes correctly?

**Comment by Jronk** [comment]
I noticed it in the color swatches only, if you look at the gif above, you can see in the end its showing #666666 while still purple in the swatch, so it looks to be an issue specific to the color control. So it might not be the same as #299. At any rate, Ill be fixing both of these so we'll see what they have in common....

**Comment by timayhelen** [comment]
@Jronk Also why are all your buttons turning blue on hover! Has it always been that way for you?

**Comment by uportnykh** [comment]
@Jronk These issues are unrelated. I fixed the issue with undo/redo settings, you can branch off of `299-fix-undo-redo-settings` to fix color swatches issues: https://github.com/elegantthemes/submodule-builder/pull/1076

**Comment by Jronk** [comment]
@timayhelen I just checked again, and none of those buttons are turning blue on hover.. Not even the one shown doing it in the gif... Weird. :shrug:

**Comment by Jronk** [comment]
This has been resolved, probably due some recent other fixes to the color controls
