### ISSUE TITLE
Don't Fail Silently When Its Not Appropriate To Do So

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#314]
### Problem:
Review features/functionality that directly depend on data retrieved via AJAX and ensure they don't fail silently when its not appropriate to do so (eg. loading premade/saved layouts, saving the page, etc).

**Comment by SlavaET** [comment]
Improved errors handling in following ajax requests:
- Saving the page. Saving will fail as it should if error in ajax request will happen
- Loading of library items/saving of library items. This operations will be failed with correct response.
- Updating computed properties. This operation will be failed without hanging the module.
