### ISSUE TITLE
Add Grunt Zip Tasks For Extra and Divi Builder Plugin

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#317]
^^

**Comment by timayhelen** [comment]
@Anny85 It doesn't look like the new Extra grunt file takes into consideration any of the new FB dev files. They are not excluded.

**Comment by Anny85** [comment]
@timayhelen Josh added it here: https://github.com/elegantthemes/Extra/blob/30c06bfd5ac05c4bd8f810e20f04effb7236331a/Gruntfile.js#L693-L730
