### ISSUE TITLE
FB :: Page settings :: color controls appear incorrectly

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#319]
### Problem:
1. Wrong position for color controls.
2. Also can't save Content Area Background Color value.
![divi](https://cloud.githubusercontent.com/assets/3352130/18221476/5fa26248-7186-11e6-95ad-54a8a6cb4e79.gif)

**Comment by SlavaET** [comment]
@kary4 which browser do you use? I cannot replicate the issue with misaligned controls.

**Comment by kary4** [comment]
@SlavaET I can see this issue on both Chrome and Firefox. I'm on Win10, 1920x1080px screen res., new wordpress installation, no plugins, no child theme, nothing else except for divi :)

**Comment by lots0logs** [comment]
@kary4 Are there any errors in your console?

**Comment by kary4** [comment]
@lots0logs no, only google maps API warning: http://youtu.be/3rhuzV9BMO8?hd=1

**Comment by SlavaET** [comment]
@kary4 I cannot reproduce the issue with wrong alignment.. I tested in Browser stack on Win10 using the Firefox, Chrome and IE - everything look fine.
As for the issue with Content Area Background - it works, you just need to adjust transparency, which is set to 0 by default :)

**Comment by kary4** [comment]
@SlavaET not sure what Im missing. Maybe you can record a screen cast so I can take a look?

**Comment by SlavaET** [comment]
Sure: 
![content-bg-option](https://cloud.githubusercontent.com/assets/3446682/18230586/c4a2d272-72c1-11e6-90d8-dc3c83554867.gif)

**Comment by kary4** [comment]
Am I on the latest beta version (Version: 2.9.15) ? Because in your screen cast I can see you are able to click the Expand Settings button. But it does not for me. So, probably we are testing different versions..

**Comment by lots0logs** [comment]
@kary4 Could you try adding a domain entry to your hosts file so that you can access your test site using a normal address? Its just a hunch but I think the issue could be caused by javascript quirkiness when on localhost address.

**Comment by kary4** [comment]
I just tried it on real server, not on localhost. Expand Settings button works, but it's the same problem with color controls: http://youtu.be/Q1BKfLjMsN0?hd=1

**Comment by lots0logs** [comment]
@kary4 What happens if you increase the width of the settings modal? I assume it resolves the issue?

**Comment by kary4** [comment]
No, it does not. You can see the result in the screen cast I posted right above.

**Comment by lots0logs** [comment]
Can you reproduce it on my site? I'll send you the details on Slack..

**Comment by kary4** [comment]
Sure, I can give it a try.

**Comment by kary4** [comment]
Okay, it works good on the testing page here http://et.falgout.us/divi/
