### ISSUE TITLE
Spinning wheel is back but only when trying to edit a section

### ISSUE THREAD

**Issue by osicam** [elegantthemes/Divi-Beta#32]
### Problem:

The spinning wheel problem is well disapeared on divi builder except that I still have the problem when trying tro eedit a section (example : Make a standard section full-width)

### Steps To Reproduce:
1. open any page
2.try to edit a section
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: laptop 

**Operating System**: windows 8

**Browser**: chrome

**Screen Resolution**: 15"

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@osicam Could you provide us with a support token and the URL of your website so we can take a look?

Please download and install the following plugin:

http://www.elegantthemes.com/downloads/elegant-themes-support.zip

Next navigation to Tools > Elegant Themes Support Account and create a new token. Don't paste it here as this is a public repo. 

You can send me a new PM on the support forum containing your login URL and the support token:

https://www.elegantthemes.com/forum/ucp.php?i=pm&mode=compose&u=2

It would also be beneficial if you could create a screencast of the issue and post it here.

**Comment by timayhelen** [comment]
@osicam I do see some strange activity when loading the builder on your site. Admin-ajax is failing, and local-storage is being filled with malformed builder templates. 

Would you be able to temporarily disable all plugins on this website to see if it fixes the issue?

**Comment by osicam** [comment]
hello

I just disabled all plugin and proiblem still there. The only way to fox this error is to delete divi, resinstall a version divi 2.5 and the update the problem is fixed for some time

**Comment by osicam** [comment]
i keep plugin disabled so you can have a look yourself. Let me know when I can enable plugins

**Comment by timayhelen** [comment]
@osicam We haven't been able to identify the problem unfortunately. It's most likely due to your server settings. Would you be able to PM me your FTP login details as well so we can investigate further?

**Comment by timayhelen** [comment]
@osicam It looks like some files in your Divi theme did not update. After uploading a fresh version it seemed to work fine. 2.7 has been released today. I would suggest delete your current version of Divi and download a fresh version manually (instead of using the updater) to see if it helps. It could be a file permissions issue.

**Comment by osicam** [comment]
thanks. Just reloaded divi 2.7 and indeed it works :-)

**Comment by osicam** [comment]
FYI I found he reson as I could reprodice the problem. It is when I try to change file class-et-builder-element to change screen value so function hide tablet works on ipad that the problem occurs.
