### ISSUE TITLE
Add Slight Delay To Dragging When Not Clicking On Move Icon

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#323]
I think we should add a slight delay to when module move is triggered. We actually have something similar in the BB. It prevents modules from being dragged by mistake when you click on other settings icons, for example. I find myself triggering the move event when I click other buttons because my cursor has not stopped moving completely.

**Comment by SlavaET** [comment]
Added 100ms delay. The same as in BB.
