### ISSUE TITLE
FB :: Screen size resizes automatically when you add changes.

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#328]
### Problem:

I'm not sure if it's a real issue, anyway in some cases the option Desktop/Tablet/module view resizes automatically.
![divi](https://cloud.githubusercontent.com/assets/3352130/18228211/8efaab98-724b-11e6-855f-d713006a448b.gif)

### Steps To Reproduce:
1.  Add any layout you want.
2. Select Mobile view.
3. Open Row module settings select "Keep Custom Padding on Mobile".
4.  And add top padding.

You will see it resizes automatically  to the Desktop view even though you selected "Keep Custom Padding on Mobile". 

I think when you open the row settings (or any other settings) it should open the settings for the selected view port (Tablet/Mobile). Right now it always opens it for Desktop. This might be inconvenient.

**Comment by SlavaET** [comment]
It works as expected. When you adjust the option with responsive settings - Divi automatically adjusts the preview mode.
