### ISSUE TITLE
Visual Builder :: Insert Section - css problems

### ISSUE THREAD

**Issue by voceadinumbra** [elegantthemes/Divi-Beta#329]
### Problem:

Insert Section is not properly styled

Browser: Chrome
OS: Win 10

![1](https://cloud.githubusercontent.com/assets/2896715/18233295/e79d32de-72eb-11e6-8276-be486b7b6ec0.png)
![2](https://cloud.githubusercontent.com/assets/2896715/18233296/e79dac46-72eb-11e6-9bd4-d3b638dad313.jpg)

Browser: Firefox
OS: Win 10

https://www.youtube.com/watch?v=pBTntr2i57Q

**Comment by timayhelen** [comment]
@voceadinumbra Are you zoomed in or out in your browser? Try clicking Ctrl+ and Ctrl- to make sure you are at 100%.

**Comment by voceadinumbra** [comment]
-yes, I am at 100% browser zoom

**Comment by SlavaET** [comment]
@timayhelen I can reproduce the issue. It appears only on posts with sidebar.
