### ISSUE TITLE
Responsive settings still not working on ipad lanscape view

### ISSUE THREAD

**Issue by osicam** [elegantthemes/Divi-Beta#33]
Not a real bug but I am just surpised thay known bug is not fixed in this latest version as here is answer I got weeks ago from suipport :+1: 
Hi there,

My apologies for the delay.
Yes, we are aware of this problem and it has been fixed. It will probably be pushed in the next update.

I'm sorry for any inconvenience.

If you wish, you can fix this yourself. Open //includes/builder/class-et-builder-element.php.

@media only screen and ( max-width: 980px ) {

And replace it with:

@media only screen and ( min-width: 768px ) and ( max-width: 1024px ) {

Also increase viewport min width for desktop to 1025px.

Iw as just wondering why you don't fix ipad responsive design issue

Regards

**Comment by timayhelen** [comment]
( min-width: 768px ) and ( max-width: 1024px ) also affects Desktop computers, so I am not sure it's the best solution for all users. We have this issue logged already in the main Divi repo, so I am going to close this so we can keep this area for Divi 2.7 Beta related issues only.

**Comment by osicam** [comment]
yes sure ok 
thanks


Date: Tue, 29 Mar 2016 03:12:38 -0700
