### ISSUE TITLE
Allow Modules To Be Pasted It Empty Columns

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#334]
Currently you cannot paste a module into an empty column because right click triggers the row menu instead of the module menu. This used to work, so it may just be a z-index issue. Same goes for pasting rows into empty sections, although that scenario is a bit more rare.

**Comment by SlavaET** [comment]
Turned out that mechanism for pasting into empty Rows, Columns and Sections was totally removed from the FB due to changed logic in some functions, so I added it from scratch to follow new logic.

**Comment by Jronk** [comment]
@SlavaET I added some comments onto the PR, but since the branch is already merged, a follow-up branch and PR can be done for the fixes.

**Comment by SlavaET** [comment]
@Jronk fixed in this PR - https://github.com/elegantthemes/submodule-builder/pull/1098
