### ISSUE TITLE
RTL Issues

### ISSUE THREAD

**Issue by eran-katz** [elegantthemes/Divi-Beta#335]
### Problem: RTL Display Issues

Working with RTL mess things up in the new builder. I disabled the translation option in the Divi panel in order to understand and read. Some of the issues are hard to describe, so I've prepared a small video to see... https://vimeo.com/simplysocial/review/181451864/66bd1e8600

### Steps To Reproduce:
1.  just use RTL 

### Additional Information:

**Operating System**: windows 10

**Browser**: Chrome

**Screen Resolution**: 1920 ✖ 1080

**Screenshot**: https://vimeo.com/simplysocial/review/181451864/66bd1e8600

-

**Comment by fikrirasyid** [comment]
@eran-katz We've submitted a patch for this and it is currently under review process. Once the patch passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄 

A glimpse of the fixed issue:

![fixed rtl issues](https://cloud.githubusercontent.com/assets/916442/18262601/5414176a-742d-11e6-82ad-d126c86be20c.gif)

**Comment by Jronk** [comment]
See my comment on PR

**Comment by fikrirasyid** [comment]
@Jronk I've submitted new PR which replaces all isRtl() method with `Utils`' method: https://github.com/elegantthemes/submodule-builder/pull/1123
