### ISSUE TITLE
When New Modules Re-render, TinyMCE Formatting And Text Is Removed

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#336]
Add a new text module and then add some content and style it with the inline editor. Then move the module, or cause the module to re-render by adjusting the parent row or section. Text and formatting disappears and the following error occurs:

![screen shot 2016-09-04 at 11 54 16 pm](https://cloud.githubusercontent.com/assets/3333028/18239566/e7bdf0c8-72fa-11e6-81dc-f3fbaeb3dbda.png)

**Comment by SlavaET** [comment]
@timayhelen I fixed the issue you described, but I couldn't reproduce the error you see in console. Can you please check whether or not you see this error with my PR?
