### ISSUE TITLE
js warning appears because of wrong propTypes validation in page-settings-bar

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#337]
### Problem:

It's hard to catch this error, but I saw it several times. The error appears because in the 
`/includes/builder/frontend-builder/app/components/page-settings-bar/page-settings-bar.jsx`
we defined `PropTypes.string` for the `modalSnapLocation` prop, but it can be `boolean` sometimes.

I usually see this error after playing around with the settings modal - moving, snapping, centering, closing, opening. I didn't figure out exacts steps to reproduce it, but I know how to fix it.

**Comment by timayhelen** [comment]
Is it supposed to fix this warning? It happens for me every time I snap modal to the side in this branch:

![screen shot 2016-09-05 at 2 46 54 pm](https://cloud.githubusercontent.com/assets/3333028/18257387/c88196ce-7377-11e6-95a1-9c6e51fb774d.png)

**Comment by SlavaET** [comment]
@timayhelen I believe I fixed that warning in this PR - https://github.com/elegantthemes/Divi-Beta/issues/333

**Comment by timayhelen** [comment]
Ok, great. I will check again when both are merged.
