### ISSUE TITLE
Question : New Divi Builder Layout Export & Import : not importing settings of New Divi Builder Settings

### ISSUE THREAD

**Issue by rijendra** [elegantthemes/Divi-Beta#34]
Not a problem but its a question
New Divi Builder Layout Export & Import : not importing settings of New Divi Builder Settings of that page to a new page

### Steps To Reproduce:
1. create a normal divi builder page
2. give some effects using the New Divi Builder Settings
3. Process to export
4. Process to import on a new fresh page

Question:
Is it intentional to not export the page settings?

Thank you for your time.

**Comment by timayhelen** [comment]
@ThierryA I think these should be exported with individual divi layouts. This will be especially useful with the new Custom CSS setting.

**Comment by DiviThemeExamples** [comment]
is this something that will be added? would make layouts much more flexible to be able to attach custom css to a page layout ;)
