### ISSUE TITLE
Video Slider :: loading speed when using youtube/vimeo

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#342]
### Problem:

When you have the video slider on the page and you trying to add one more video slider the first module will re-render. It slowing down the performance. If you have a lot of the slider modules it's quite noticeable.

![animation](https://cloud.githubusercontent.com/assets/9657712/18250231/6ee3a38c-73a4-11e6-8fb0-6a979526239c.gif)

### Steps To Reproduce:
1.  Create the slider module with youtube/vimeo
2.  Create another slider module or load it from the library
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
I dont think there is much we can do about this unfortunately.
