### ISSUE TITLE
Map Module :: Google map gets trimmed out after clone

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#344]
### Problem:

On a radom layout (2 column) - each column with it's own map module, upon clone and column layout change the map module get trimmed out:

https://drive.google.com/file/d/0B8PjD3Z_XQvuZ2lBUjlrcWtkVUU/view?usp=sharing

https://drive.google.com/file/d/0B8PjD3Z_XQvuclE4WmJUUnZRQWs/view?usp=sharing

**Comment by SlavaET** [comment]
Fixed. Also fixed the issue when it was impossible to navigate inside the map module because it was triggering the Module Move.
