### ISSUE TITLE
Person Module :: Body Color

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#345]
### Problem:

Body Color, override the social Icon color, and the social icons hover color

### Steps To Reproduce:
1.  add the person module
2.  set the color for the social icons
3.  set the color for hover on social icons
4.  set the color for the body text

Social Icons and hover color:
![screen shot 2016-09-05 at 6 52 26 pm](https://cloud.githubusercontent.com/assets/1719735/18252953/eb14e714-7399-11e6-8c6a-822d1ed0d7fc.png)

Body font color:
![screen shot 2016-09-05 at 6 52 30 pm](https://cloud.githubusercontent.com/assets/1719735/18252963/fadd77e2-7399-11e6-84dc-bea4b0190813.png)

**Comment by SlavaET** [comment]
It's no something what introduced in 3.0. This issue exists in current version of Divi as well. 
Fixed it anyway.
