### ISSUE TITLE
Visual Builder doesn't work for library items

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#346]
### Problem:

404 page opened instead of Visual Builder If I click `Use Visual Builder` on library item.

### Steps To Reproduce:
1. Open Divi Library
2. Open any module in library
3. Click `Use Visual Builder` button

**Comment by timayhelen** [comment]
This has been broken and fixed a few times. @Anny85 can you take a look?

**Comment by lbjohnson01** [comment]
@SlavaET @timayhelen when would you all like us to start reporting on the divi-100 layouts? I can get the VB to show up on them, but am finding buggy behavior.

**Comment by timayhelen** [comment]
@lbjohnson01 Feel free to report any bugs you find.

**Comment by Anny85** [comment]
@timayhelen I will take a look.
