### ISSUE TITLE
Implement Support For Auto Save & Post Locking While Editing

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#349]
WP Core handles this for us in the backend. We'll have to do it ourselves on the frontend. 

## Attached PRs
- https://github.com/elegantthemes/submodule-builder/pull/1267
- https://github.com/elegantthemes/submodule-core/pull/43

**Comment by fikrirasyid** [comment]
👍  👍  👍  for this. I experienced this myself yesterday. I edited a long layout for quite sometime, and the builder suddenly no longer working and I have to refresh the builder and loosing several changes I made the last. It turns out that something is failing and throwing bunch of js errors and after that everything stops working (I can't trace it too since it's been way too much changes when I notice it).

I can imagine customer can be enraged by this. If we can do proactive save to localStorage on several interval just like backend does it, it can be a total deal breaker. So if builder is suddenly froze and user refreshes their page, we can give a notice that there are unsaved changes and provide then an option to roll-front (or rollback?) to their latest unsaved state.

**Comment by fikrirasyid** [comment]
This reminds me on how enraged I am at the collage when I work on paper and suddenly Ms word stops working and I haven't saved any of it.

:rage:

**Comment by Jronk** [comment]
@timayhelen @mariomaruffi I need some UI specs for 3 items please:

1. Notification of a newer autosave in browser, subtle notification and asking for user optional action
WP version:
![screen shot 2016-10-28 at 10 04 50 am](https://cloud.githubusercontent.com/assets/1163441/19815746/21bef128-9cf9-11e6-8ca8-ce86ae646958.png)

2. Notification of a newer autosave on server,  subtle notification and asking for user optional action
WP version:
![screen shot 2016-10-28 at 10 06 21 am](https://cloud.githubusercontent.com/assets/1163441/19815756/2e0a54e0-9cf9-11e6-86db-ca90e1822831.png)

3. Autosave status display
WP version:
![screen shot 2016-10-28 at 10 17 26 am](https://cloud.githubusercontent.com/assets/1163441/19815767/38802b02-9cf9-11e6-9f96-d54c6c5bb283.png)
![screen shot 2016-10-28 at 10 17 19 am](https://cloud.githubusercontent.com/assets/1163441/19815766/387d4d2e-9cf9-11e6-8028-bc50bf5bd78a.png)


Possible Ideas:
![screen shot 2016-10-28 at 10 16 34 am](https://cloud.githubusercontent.com/assets/1163441/19815781/4580cc58-9cf9-11e6-94df-464da447e60b.png)
![screen shot 2016-10-28 at 10 14 58 am](https://cloud.githubusercontent.com/assets/1163441/19815782/45850304-9cf9-11e6-9bc0-cf6d7ff09662.png)

**Comment by timayhelen** [comment]
Let's use: 
![screen shot 2016-10-28 at 11 36 28 am](https://cloud.githubusercontent.com/assets/3333028/19818132/53fc2f5c-9d03-11e6-9d8c-edabaec15903.png)
![screen shot 2016-10-28 at 11 38 28 am](https://cloud.githubusercontent.com/assets/3333028/19818135/55233966-9d03-11e6-851b-0d8c023cceb3.png)

**Comment by Jronk** [comment]
![heartbeat sync flowchart](https://cloud.githubusercontent.com/assets/1163441/20019512/fafb84fc-a289-11e6-9d36-7b7aaa15bd3e.png)
![autosave flowchart 3](https://cloud.githubusercontent.com/assets/1163441/20019513/fb00c8ae-a289-11e6-890e-6b00865a8464.png)
![dual editor auto-sync ux](https://cloud.githubusercontent.com/assets/1163441/20019574/425b26f4-a28a-11e6-82ec-9fe8e3a1b47c.png)

**Comment by Jronk** [comment]
The same PR fixes #349 and #575
branch: 575-fix-heartbeat-content-smashing
PR: https://github.com/elegantthemes/submodule-builder/pull/1267

**Comment by lots0logs** [comment]
@Jronk I'm getting an error in the browser console when the heartbeat fires in the VB:
```
Uncaught ReferenceError: Utils is not defined(…)
(anonymous function) @ autosave.js:436
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
trigger @ jquery.js?ver=1.12.4:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous function) @ jquery.js?ver=1.12.4:3
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
trigger @ jquery.js?ver=1.12.4:3
connect @ heartbeat.js?ver=4.6.1:359
(anonymous function) @ heartbeat.js?ver=4.6.1:449
setTimeout (async)scheduleNextTick @ heartbeat.js?ver=4.6.1:447
(anonymous function) @ heartbeat.js?ver=4.6.1:214
i @ jquery.js?ver=1.12.4:2fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2K @ jquery.js?ver=1.12.4:2
```
Something else I noticed, if I save changes in the BB and then save different changes in the VB before the next heartbeat, it allows the VB to clobber what was saved in the BB. :notsureif: its only happening because of the above error though.

**Comment by Jronk** [comment]
Fixed the utils error, please try again, thx

**Comment by lots0logs** [comment]
@Jronk 

The VB is still clobbering changes saved in the BB. I'm getting a 500 response from the server (pasted below). Here's the steps I took:

1. I opened an existing page in BB and VB.
2. In the BB, I added a new module to the layout.
3. Then I played around for 60 or so seconds checking the ajax calls. I didn't make any further changes.
4. Next, I Saved/Published the page.
5. Waited another 60 or so seconds for the change to be picked up by the VB..
6. Change never showed up so I checked the console and found two requests to admin-ajax returned 500 status (details below). 
7. I then made a change to the font color on a different module and saved it in the VB.
8. The changed showed up in the BB after about 30 seconds and clobbered the earlier change I had saved in the BB.

Both requests sent the same form data to the server so I'm only including it once. 

### Request Headers
```
POST /divi/wp-admin/admin-ajax.php HTTP/1.1
Host: et.falgout.us
Connection: keep-alive
Content-Length: 237
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://et.falgout.us
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.90 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://et.falgout.us/divi/1home-extended/?et_fb=1
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```
### Request Form Data
```
data[et][last_post_modified]:2016-11-05 14:46:29
data[et][built_by]:fb
data[et][post_id]:16875
data[et][force_check]:false
interval:30
_nonce:1a8c7fa089
action:heartbeat
screen_id:front
has_focus:false
```
### Response Headers
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 10 Nov 2016 22:26:20 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.0.8-0ubuntu0.16.04.3
Access-Control-Allow-Origin: http://et.falgout.us
Access-Control-Allow-Credentials: true
X-Robots-Tag: noindex
X-Content-Type-Options: nosniff
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
X-Frame-Options: SAMEORIGIN
Server: cloudflare-nginx
CF-RAY: 2ffcece624271f94-DFW
```

And here's the wp debug output:
```
[10-Nov-2016 22:23:23 UTC] PHP Notice:  Undefined index: action in /srv/et.falgout.us/wp-content/themes/Divi/includes/builder/framework.php on line 29
[10-Nov-2016 22:24:19 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[10-Nov-2016 22:24:22 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[10-Nov-2016 22:24:22 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[10-Nov-2016 22:24:23 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[10-Nov-2016 22:24:24 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[10-Nov-2016 22:25:51 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function et_fb_process_shortcode() in /srv/et.falgout.us/wp-content/themes/Divi/includes/builder/core.php:992
Stack trace:
#0 /srv/et.falgout.us/wp-includes/plugin.php(235): et_pb_heartbeat_post_modified(Array)
#1 /srv/et.falgout.us/wp-admin/includes/ajax-actions.php(2776): apply_filters('heartbeat_send', Array, 'front')
#2 /srv/et.falgout.us/wp-includes/plugin.php(524): wp_ajax_heartbeat('')
#3 /srv/et.falgout.us/wp-admin/admin-ajax.php(91): do_action('wp_ajax_heartbe...')
#4 {main}
  thrown in /srv/et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 992
[10-Nov-2016 22:26:21 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function et_fb_process_shortcode() in /srv/et.falgout.us/wp-content/themes/Divi/includes/builder/core.php:992
Stack trace:
#0 /srv/et.falgout.us/wp-includes/plugin.php(235): et_pb_heartbeat_post_modified(Array)
#1 /srv/et.falgout.us/wp-admin/includes/ajax-actions.php(2776): apply_filters('heartbeat_send', Array, 'front')
#2 /srv/et.falgout.us/wp-includes/plugin.php(524): wp_ajax_heartbeat('')
#3 /srv/et.falgout.us/wp-admin/admin-ajax.php(91): do_action('wp_ajax_heartbe...')
#4 {main}
  thrown in /srv/et.falgout.us/wp-content/themes/Divi/includes/builder/core.php on line 992
```

**Comment by Jronk** [comment]
There are helpful debug logs ingrained into both FB and BB version, so it might behoove you to enable them to see what its thinking

**Comment by lots0logs** [comment]
@Jronk @timayhelen The feature is working as intended now. I have not been able to induce any further errors. That being said, I'm concerned about the 5 second minimum delay (could be longer depending on server response time) imposed when the builder regains focus. I'd feel a lot better about it if it was only imposed once we know there are multiple instances of the builder running.

As it is currently, users will see the spinner/preloader for minimum 5 seconds every time they return to the builder after checking something in another tab or application. Referencing information in other tabs or applications while created posts/pages is a very common workflow. Think about how annoying it would be if you were doing something in that workflow with the builder :thinking:

**Comment by Jronk** [comment]
good thoughts, here is some more info:
it already doesnt have to be 5 seconds, and surely, as you mentioned, I dont even have to pop the spinner at all

Here is what's literally happening:
If you arrive, after being gone for more than 5 seconds (another value I could change) then it will wait 5 seconds, then trigger heartbeat immediately, and check for external changes.

I could change if blurred > 30 seconds, then wait 3 seconds upon returning, and no spinner
the scenario I am targeting, is hitting save in BB, then flipping to FB.

But, I see the scenarios that are getting sucked in, which is what you are referencing like switching back and forth between any harmless tab and even cases where a 2nd builder is not even in use.

So, ideas:
I could require a confirmation that a 2nd editor is being used, in order for that immediate heartbeat upon arrival being triggered
confirmation = the blurred editor has to have found external changes during the normal 30 sec heartbeat

**Comment by timayhelen** [comment]
I think it's a good idea that we try to confirm that both builders are being used before we force a heartbeat check and activate the spinner. It's definitely frustrating in the current state. This, combined with the ever-present post revision popups, are going to be very annoying unless we do a good job at limiting them to when they are only most necessary. I am finding it difficult to use this branch without getting spinners and post revision popups every time I edit a page in the VB.

Here are some of the main issues: 

1. There is no way to purposefully exist the VB without saving. Even if you don't want to save, your changes always get saved and you always get a post revision or browser backup popup. If someone leaves the builder and chooses to "discard changes" then we don't need to give them a post revision or browser backup popup next time. 
 
2. Old browser backups in the VB are treated as "newer" than newly saved pages when saved from the BB. Try this: a) Create and save a new page in the BB. b) Click "use visual builder," make some changes and then exist the builder and "discard changes.". c) Open up the page again in the BB, make some changes and save the page. d) Now click "Use Visual Builder." You will get a prompt that says a newer browser backup exists, but it's actually an old browser backup. We **just** saved the page and that browser backup is old.

![backups](https://cloud.githubusercontent.com/assets/3333028/20451912/212b587a-adb4-11e6-906f-31345dd51dad.gif)

**Comment by Jronk** [comment]
I have taken all the design and qa feedback and made many modifications:
1. It will now only pop the spinner and attempt to "sync" with other editor if the other editor did actually make changes
2. If you click save on either editor, it will clear both editor's browser autosaves
3. If you intentionally exit without saving in FB, it will drop its browser autosave

**Comment by lots0logs** [comment]
@Jronk 

- [ ] Try this:
1. Open the BB and the VB for the same page.
2. In the VB, make any change to the layout.
3. Switch over to the BB, and you will see it picks up the change. Perfect.
4. Don't make any changes, now switch back to the VB. It thinks there has been a change and throws up the spinner to check. 
- [ ] [This error](http://paste2.org/Gj9thMjH) keeps showing up in the console though I'm not sure what triggers it.

**Comment by timayhelen** [comment]
@Jronk 

- [ ] Error upon browser backup restore. I was prompted to restore a browser backup in the Visual Builder. Once restored, the follow error occurred and the content was jumbled. 

![screen shot 2017-01-05 at 4 19 53 pm](https://cloud.githubusercontent.com/assets/3333028/21702857/eefa4058-d362-11e6-9ec4-772372cfa655.png)

![screen shot 2017-01-05 at 4 19 29 pm](https://cloud.githubusercontent.com/assets/3333028/21702861/f22c86d2-d362-11e6-9a31-9ae844d52ddb.png)

**Comment by timayhelen** [comment]
- [ ] No "Unsaved Changes" prompt when exiting the builder. It looks like this no longer works in the latest PR. If you make changes to the builder and then leave, you should be prompted to Save & Exit or Discard & Exit.

![save](https://cloud.githubusercontent.com/assets/3333028/21702905/3999e67c-d363-11e6-89d9-54271a17450c.gif)

**Comment by timayhelen** [comment]
@Jronk Currently we discard browser backups and autosaves when someone clicks "Discard & Exit" when leaving the builder via the save warning modal. Can we do the same thing for the javascript prompt that appears when closing a browse tab? If someone purposefully closes a browser tab, and then clicks "leave" when they are warned that they will lose their changes, I think it's save to assume  that they want to discard them and we shouldn't bother them with a popup the next time they edit the page.

**Comment by timayhelen** [comment]
I am closing this in favor of: https://github.com/elegantthemes/Divi-Beta/issues/912 

We can track issue for the newly-combined branches here.
