### ISSUE TITLE
Theme Options :: Mailchimp API Key :: Connection failed.

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#35]
### Problem:
When you try to connect to mailchimp under the theme option it displays:

```
Connection failed.
Authorization code is empty.
```
Please, check the attachment below 

![1](https://cloud.githubusercontent.com/assets/3352130/14121066/b0eff894-f617-11e5-9c2e-60d975f24ab2.png)

I just updated divi from Mater

**Comment by lots0logs** [comment]
@kary4 I don't think you need to do anything for mailchimp besides input the key. The button your pressed is for Aweber, no?
