### ISSUE TITLE
Tooltip Screen Scroll In Extra Scrolls To Wrong Position

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#350]
If you open up a tooltip in Extra, and the tooltip triggers the screen scroll to move the tooltip into the viewport, the screen scrolls to the wrong location and you have to scroll back down to find the tooltip you opened.

**Comment by SlavaET** [comment]
@timayhelen I fixed it in scope of this issue - https://github.com/elegantthemes/Extra/issues/1469
