### ISSUE TITLE
Dragging Module Inside Speciality Section Inner Row Drag Parent Row

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#355]
If you try to drag and drop a module that exists inside of an inner row in a specialty section, the entire row is dragged.

Also, the placeholder indicator for dropping does not render. 
![drag](https://cloud.githubusercontent.com/assets/3333028/18271091/32dda81a-73e5-11e6-8369-4960ddd70dfb.gif)

**Comment by SlavaET** [comment]
@timayhelen this is the issue @fikrirasyid is working on in scope of this - https://github.com/elegantthemes/Divi-Beta/issues/352

**Comment by fikrirasyid** [comment]
@SlavaET @timayhelen I've submitted patch for #352 at https://github.com/elegantthemes/submodule-builder/pull/1108
