### ISSUE TITLE
Tabs Module :: Font transform issue

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#358]
### Problem:

If the body font is set to be uppercase it also make the tab title to be uppercase, making the title font option to not take effect

### Steps To Reproduce:
1.  add a tab module
2.  add a tab element
3.  set the body font to be uppercase
4.  set the tab title to be normal case

### Additional Information:
**Screenshot or Screencast**:
![screen shot 2016-09-06 at 3 09 26 pm](https://cloud.githubusercontent.com/assets/1719735/18273035/f27df1b2-7443-11e6-8465-a4b5de739aba.png)

**Comment by SlavaET** [comment]
Fixed. It was broken before 3.0 though.
