### ISSUE TITLE
Testimonial Module :: Icon Color 

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#359]
### Problem:

If setting the custom color for the quote icon, the icon will lose it's default background color, and in case the user set a testimonial to have a border, is visible trough icon.

![screen shot 2016-09-06 at 3 22 22 pm](https://cloud.githubusercontent.com/assets/1719735/18273402/bd03af3e-7445-11e6-9aa8-ea38a9fac509.png)

Instead of:
![screen shot 2016-09-06 at 3 23 20 pm](https://cloud.githubusercontent.com/assets/1719735/18273424/ddea5e64-7445-11e6-834e-f3300423dbac.png)

**Comment by uportnykh** [comment]
I can't replicate the issue, but I see another problem. 

It doesn’t seem to render a border, once I save and re-load the page ( border width should be set to 1px ). I'll work on it.
