### ISSUE TITLE
500 internal error when Enabling Visual Builder

### ISSUE THREAD

**Issue by melissalove** [elegantthemes/Divi-Beta#360]
### Problem:

Since yesterday, I've not been able to use the Visual Builder either be enabling it from the page edit screen or the front end of the site. When I try to enable, I'm getting a 500 error.

### Steps To Reproduce:
1.  Enable Visual from front of back end

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

Running Divi 2.9.17 with WordPress 4.6. 
I've also checked my hosting account for issues.

**MacBook Pro**:

**Chrome**:

**Screenshot or Screencast**:

![screenshot-thedesignspacedemo co 2016-09-06 13-34-11](https://cloud.githubusercontent.com/assets/17326331/18273817/2d24668c-7437-11e6-803a-535cf6299fb6.jpg)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@melissalove Can you check your error log, or ask your host to check it, so that we know what the actually error is? 

Also be sure to disable all of your plugins.
