### ISSUE TITLE
Toggle Module :: Clone :: Edit Settings

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#361]
### Problem:

This might be related to #322.

### Steps To Reproduce:
1. add a toggle module  
2. clone it 
3. try to edit the settings of the clone one
4. the options disappears when the mouse pointer leaves the toggle area

Update:
Same thing happens, if after the toggle is added to the layout you close it's settings and try to edit it again!

### Additional Information:
**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuT3UwMnJVQVNKaU0/view?usp=sharing

**Comment by eduard-ungureanu** [comment]
[Toggles Layout - Cannot edit settings.json.zip](https://github.com/elegantthemes/Divi-Beta/files/458504/Toggles.Layout.-.Cannot.edit.settings.json.zip)

@fikrirasyid There you go, just for reference I'm using the 2.9.13 version, I cannot update to any other version - no update available for me!

**Comment by fikrirasyid** [comment]
@eduard-ungureanu I've exported your layout and still can't replicate your issue (the layout of the exported site looks different than the one you screencasted too tho). I recall similar issue I've fixed regarding mousetrap, so this might have been fixed along the way.

Let's close this issue for the time being. Once you're able to update to the latest version and still encounter this issue, we can reopen it.

**Comment by eduard-ungureanu** [comment]
@fikrirasyid That's strange since it's exactly the same layout from my screenshot (only 2 default toggle modules) nothing else. anyway, do you know from where I can download the latest version, since I cannot see any updates in my dashboard, and I want to make sure that i have the latest version so my tests will be done correctly? Is there to much to ask to email me the latest version at hello@wordpress-corner.com?

**Comment by fikrirasyid** [comment]
@eduard-ungureanu the toggles that appear on these video you posted https://drive.google.com/file/d/0B8PjD3Z_XQvuT3UwMnJVQVNKaU0/view aren't default toggle tho. It at least has custom color on it 🤔

I have my dev version on my local installation, but it probably way too big to be sent and you might need to build it. Have you tried force update check it using https://wordpress.org/plugins/force-plugin-updates-check/?

**Comment by eduard-ungureanu** [comment]
@fikrirasyid :facepalm: it looks like I send initaly post another video. 

Here is the video using the exact modules from the previous .json file:
https://drive.google.com/file/d/0B8PjD3Z_XQvuci1MTkxDX0xFS00/view?usp=sharing

Did try that plugin, but I wasn't able to update to the latest Divi beta version! 😢

**Comment by fikrirasyid** [comment]
@eduard-ungureanu yeah, I remember we've fixed an issue like that.

I've sent you latest version of Divi beta to the email address you mentioned above. Please check and confirm whether the issue remains or not :)

**Comment by eduard-ungureanu** [comment]
@fikrirasyid outstanding, now it's all working as it should! Thank you!

https://drive.google.com/file/d/0B8PjD3Z_XQvuaHFWWkNubHBWb0E/view?usp=sharing

**Comment by fikrirasyid** [comment]
Awesome :D
