### ISSUE TITLE
Text Module :: Disabled on option

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#363]
### Problem:

When a text module is marked to be Disabled on: Desktop, even if the tablet view is loaded the Module still show as gray out. Exiting the FB and check this in the real browser works as intended.

### Steps To Reproduce:
1.  add a row with 3 column layout
2. each column add a text module
3. each text module set it to be disabled on: each of those devices
4. using the FB device options, check the layout on desktop, tablet phone
5. the module set to be disabled on desktop also shows gray out when checking the tablet and / or mobile version

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os X

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuRFEyMGFjYjM4UkE/view?usp=sharing

**Comment by timayhelen** [comment]
@eduard-ungureanu This is intended, because we need a way for users to access the module settings. We may find a better way to do it in the future.

**Comment by eduard-ungureanu** [comment]
@timayhelen I know this is not an actually bug but more a usability improvements, the modules set to not display gets gray out to indicate that it is disabled on that particular devices, but it shouldn't be gray out, if the device changes, for example when it is set to not be displayed on tablet it only becomes gray out on that particular devices, so in case of desktop I think it should be gray out on desktop, but not on tablets and / or mobile - this can create confusion.
