### ISSUE TITLE
Testimonial Module :: Mobile test

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#364]
### Problem:

There is a strange issue with the Testimonial Text when testing for responsive layout, the text gets scrambled and it does fix it self if the user hovers over a testimonial module

### Steps To Reproduce:
1.  add at least 3 testimonials module in different layout
2. use the responsive option from the FB
3. or resizing the text of the testimonial module get scrambled 

### Additional Information:
**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuZmxBdXIxTks1MWc/view?usp=sharing

**Comment by timayhelen** [comment]
@fikrirasyid This is likely due to the JS we are using, and I believe it's something you worked on back in the day so maybe you can take a look at this.

**Comment by fikrirasyid** [comment]
@eduard-ungureanu @timayhelen I've submitted a patch for this issue at https://github.com/elegantthemes/submodule-builder/pull/1125
