### ISSUE TITLE
Slider Module :: Responsive

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#365]
### Problem:

I've notice that the responsive settings for the Top/Bottom Custom Padding are missing. Also when the option Hide Content On Mobile is enabled, the slider title is still showing up. Also if the content has background set, that looks strange:

![screen shot 2016-09-06 at 4 49 46 pm](https://cloud.githubusercontent.com/assets/1719735/18276005/edc627ee-7451-11e6-9ace-485e060363a9.png)

**Comment by fikrirasyid** [comment]
@eduard-ungureanu can you elaborate more what do you mean by `responsive settings` on `I've notice that the responsive settings for the Top/Bottom Custom Padding are missing`? I've checked how it appears in FB and BB and both of them appears to be similar. This is how top/bottom paddings appear in FB:

<img width="432" alt="screen shot 2016-09-07 at 8 31 36 pm" src="https://cloud.githubusercontent.com/assets/916442/18313695/1a1db364-753a-11e6-913c-16def819d916.png">

This is how they look on BB:

<img width="1099" alt="screen shot 2016-09-07 at 8 32 05 pm" src="https://cloud.githubusercontent.com/assets/916442/18313717/2d23b4ea-753a-11e6-8c73-bdae73adea3c.png">

This appears to be how it works as well:

> when the option Hide Content On Mobile is enabled, the slider title is still showing up

This is how slider module looks like if `hide content on mobile` is activated on actual front end:

<img width="492" alt="screen shot 2016-09-07 at 9 01 16 pm" src="https://cloud.githubusercontent.com/assets/916442/18314688/524cba06-753e-11e6-9a0c-200478863b54.png">

This is how it looks like on FB:

<img width="567" alt="screen shot 2016-09-07 at 9 02 50 pm" src="https://cloud.githubusercontent.com/assets/916442/18314734/75a996cc-753e-11e6-9eb0-eafe030bbbbb.png">

Regarding this:

> Also if the content has background set, that looks strange

I think what you mean is this:

1. slider module sets min-height for its content container. This content-container min-height is adjusted when the window is being resized
2. However, on FB, when the preview mode is changed, the content-container min-height remains and not being adjusted

To fix it, I've submitted this patch: https://github.com/elegantthemes/submodule-builder/pull/1133

**Comment by eduard-ungureanu** [comment]
@fikrirasyid here is how it looks before Divi beta:
![screen shot 2016-09-07 at 6 10 14 pm](https://cloud.githubusercontent.com/assets/1719735/18317401/ae9f097a-7526-11e6-94a9-6ae1b22d1651.png)

When custom values were entered for custom top/bottom padding, the responsive settings (I hope I named those right) appears, giving us the option to set custom top / bottom padding based on the devices.

Those settings are now missing from the Advanced Design Settings (or Design Tab):
![screen shot 2016-09-07 at 6 11 12 pm](https://cloud.githubusercontent.com/assets/1719735/18317438/d93c8dc4-7526-11e6-8142-a750790f6d65.png)
