### ISSUE TITLE
Background settings and others

### ISSUE THREAD

**Issue by zolwito** [elegantthemes/Divi-Beta#366]
### Problem:

When changing background settings like Color, if you click on a color you can see the changes. But if you click the "Clear" button it should be back to the original settings. Or if you click another color then it should show it, but that is not allways the case.

Sometimes you have to close the dialog on the modal window, return and then you can change it back to "Clear" or other color.

### Steps To Reproduce:
1.  Click on a tab section on the engine icon to enter the settings
2.  On any tab click the engin icon, go to the Design tab
3. Go to the end of the settings and change the "Background Color" - you will see the changes on the tabs on the preview window.
4. Click the "Clear" button or change it to other color - Sometimes it works but now allways, you still see the background on the color you picked on (3).

### Additional Information:

Windows 10
Chrome Versión 52.0.2743.116 m (64-bit)

-

![tabs color settings](https://cloud.githubusercontent.com/assets/1943754/18277380/e160e036-7413-11e6-83bc-9fd05d18d15c.gif)

**Comment by lots0logs** [comment]
@zolwito Could you confirm that the issue still exists with the latest version (3.0.2)?

**Comment by zolwito** [comment]
It´s fixed now!!!
Thank you!!!
Great work!!
