### ISSUE TITLE
Improve Divi Layouts Ajax Requests

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#367]
1. Only pre-load "Pre-Made Layouts" when the app launches. These are the unchanging layouts that come with Divi. 
2. Cache the layouts in local storage and don't process the ajax request again if the items exist. If items do not exist, pre-load them with an ajax request again and re-store them. 
3. Do not pre-load divi layout library items saved by the user, since these cannot be cached. Start to load these items once the (+) button inside the page settings bar is clicked.

**Comment by SlavaET** [comment]
Looks like localStorage cannot fit both predefined layouts and backbone templates, so FB will not use the localstorage and will preload all predefined layouts on page load via Ajax.

**Comment by lots0logs** [comment]
@SlavaET What about HTML5 offline storage? This is the docs for chrome but its an HTML5 spec so all modern browsers support it: https://developer.chrome.com/apps/offline_storage
