### ISSUE TITLE
Enable Visual Builder Doesn't Work With Go Portfolio Plugin Enabled

### ISSUE THREAD

**Issue by jdjmedia** [elegantthemes/Divi-Beta#368]
### Problem:

Divi Visual Builder will not activate when Go Portfolio plugin is enabled.

**Comment by timayhelen** [comment]
@jdjmedia Can you please check this with Divi 3.0.3? We fixed various issues with third party shortcodes.

**Comment by jdjmedia** [comment]
Visual Builder now loads, but the layout of the plugin becomes corrupt. The layout is a horizontal list of images, but once Visual Builder loads the list becomes vertical.

**Comment by uportnykh** [comment]
@jdjmedia Can you email me a copy of the plugin at uportnykh@gmail.com?
