### ISSUE TITLE
Bundled Files and Assets

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#371]
We should have our `bundle.css`, `bundle.js` and other assets in the root folder `frontend-builder` instead of the the `app` folder.

**Comment by timayhelen** [comment]
I am going to close this for now. I think it would be better to do this at the start of 3.1 instead of in the middle of bug fixes.

**Comment by timayhelen** [comment]
this will be addressed in the builder plugin issue.
