### ISSUE TITLE
Duplicating Module Causes Design Settings To Be Lost

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#372]
![design](https://cloud.githubusercontent.com/assets/3333028/18294025/303eccc2-744b-11e6-80af-39fa798fb9c2.gif)

Also, any subsequent design changes to the duplicate module do not take affect.

**Comment by timayhelen** [comment]
@fikrirasyid Also applies to new modules. Basically anything new on the page doesn't have design settings applied correctly. Probably due to wrong CSS class or something.

**Comment by fikrirasyid** [comment]
@timayhelen i have found the issue. I'm still validating the solution tho :fikrisuccess:
