### ISSUE TITLE
Incorrect Styling Assigned For Moved Module If There is Third Party Module Used

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#373]
### Problem:
If there is a third party module and a module is moved to another column BEFORE a module which has custom styling, the custom styling is applied to the moved module. This is blurb - blurb - 3rd party module (KK Divi Mods) layout:

![incorrect-styling-assigned-for-moved-module-has-3rd-party-module](https://cloud.githubusercontent.com/assets/916442/18295849/1e0c0f9a-74cf-11e6-8552-0cd6b21293f2.gif)

This is what happened if the 3rd party module is removed first:

![incorrect-styling-assigned-for-moved-module](https://cloud.githubusercontent.com/assets/916442/18295860/3de19ab0-74cf-11e6-9979-155ab3dcd57e.gif)

### Steps To Reproduce:
1.  Add 3rd party module to a layout
2. Add 2 module in different column. Customize the look of one of the modules
3. Moved the uncustomized module above the customized module

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Comment by SlavaET** [comment]
@fikri that's because we cannot generate CSS styles for 3rd party modules on the fly for custom options. So once the module moved its index changed but FB doesn't generate new styles correctly ( because of index mismatch in back end and front-end). I can't think of an easy fix until the module will be fully integrated into FB. It behaves more as a placeholder right now.

**Comment by SlavaET** [comment]
Ah, it's an issue with Divi modules, disregard my previous comment then :)

**Comment by SlavaET** [comment]
@fikrirasyid I cannot reproduce the issue. It works fine for me on the latest branch:
![moving-modules](https://cloud.githubusercontent.com/assets/3446682/18301185/4ebb01e2-74f1-11e6-86c2-a0b9085c8bf8.gif)


Can you still reproduce the issue? Can you share the layout you're using there?

**Comment by fikrirasyid** [comment]
@SlavaET I still can reproduce the issue on the latest branch using the following layout:

[373 Issue.json.zip](https://github.com/elegantthemes/Divi-Beta/files/458391/373.Issue.json.zip)

What third party module do you use? I'm using KK plugin and have its styling customized

**Comment by timayhelen** [comment]
@SlavaET Maybe you are using a different version? Did the developer send you an updated one?

**Comment by SlavaET** [comment]
I was able to reproduce the issue with Fikri's layout. Fixed it in my PR.
