### ISSUE TITLE
Divi 100 Small Biz Layout Incompatible with 2.9.18

### ISSUE THREAD

**Issue by cap220** [elegantthemes/Divi-Beta#376]
### Problem: Divi 100 Small Biz Layout Incompatible with 2.9.18

This is not a huge problem, just a quirk.

The 'Home' and 'Services' pages of the Small Business Layout Pack (9/2/2016) don't allow the Visual Builder to load. The other pages, as well as all other Divi pages (built with pre 2.9 Divi) load the Visual Builder correctly.

### Steps To Reproduce:
1.  Import Small Business Pack (Divi 100 Day 95)
2. Create new page - import SBP 'home page layout' and save as draft OR publish same.
3. Start the Visual Builder
4. Receive 'Divi Builder Timeout' warning suggesting disabling plugins.

### Additional Information:

Cleared cache, disabled plugins and the VB continues to fail to load the 'Home Page' and "Contact" page of the Small Business Layout pack.

**Device**: Laptop & Desktop

**Operating System**: Developing on Windows 10 Professional

**Browser**: Chrome

**Screen Resolution**: 1366x768 (laptop) 2560x1440 (Desktop)

**Screenshot or Screencast**:

**Link To Download Layout JSON File**: 

http://www.elegantthemes.com/downloads/divi-100-small-business-layout-pack-by-olga-summerhayes.zip

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by DeerMtn** [comment]
I too am having this issue; have disabled every plugin and increased PHP memory - still loads the Timeout screen on the divi-100-small-business-layout-pack... home and contact pages

**Comment by cap220** [comment]
What was the resolution to this issue? I see activity including a 'ready for review' and 'Closed' status but no explanation of how to solve this issue.

Please provide whatever solution was signed off on.

Thank you,

**Comment by lots0logs** [comment]
Hi @cap220 , this issue has been fixed. The fix will be included in the 3.0 release later this morning. You will get an update notification in your dashboard (same as always) :wink:

**Comment by cap220** [comment]
Perfect...!

Apologies, didn't understand. You guys are awesome...!

cap
