### ISSUE TITLE
Unexpected behaviour after canceling Split Test setup

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#38]
### Problem:

If you start configuring the Split Test and then cancel it at the Subject selection step then some things start behaving incorrectly. There are 2 things I noticed:
1) Clicking on portability button opens the Split Test Stats modal and generates js error in console.
2) If you enable the Split Test again then Select Subject prompt modal is not displayed.

### Steps To Reproduce:
1. Open Divi Builder settings and enable Split Test
2. Click Save
3. In the `Select Split Testing Subject` modal click `cancel` button
4. Click on the portability icon. You'll see the issue No. 1
5. Repeat steps 1 and 2. Cursor turns to yellow, but  `Select Split Testing Subject` modal doesn't appear. This is the issue No. 2

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
@SlavaET can you take a look at https://github.com/elegantthemes/submodule-builder/pull/638 and see whether it fixes the issue or not?

**Comment by SlavaET** [comment]
@fikrirasyid the fix works fine, but I see the following error while on your branch:
```
Warning: Illegal offset type in isset or empty in /Applications/MAMP/htdocs/wordpress/wp-content/themes/Divi/includes/builder/core.php on line 246
```
![image](https://cloud.githubusercontent.com/assets/3446682/14143799/e9c1d7ea-f6ae-11e5-9550-23fea7bc695a.png)

**Comment by fikrirasyid** [comment]
@SlavaET I've merged latest master back to the PR and it appears to fix the error message you're mentioning above.

**Comment by SlavaET** [comment]
@fikrirasyid yes, it seems to work without errors now.
