### ISSUE TITLE
Text Module :: Text Color set to light override the custom color

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#380]
### Problem:

When a text module as the text color set to be light in the General Settings, and then in the Advanced Design Settings you set a custom color once you leave the FB the color of the text is white.

### Steps To Reproduce:
1.  Add a text module
2. set the Text Color: Light in the General Settings
3. set a custom color in Advanced Design Settings
4. leave the FB

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuZHYtemNqUmdmWEE/view?usp=sharing

**Comment by SlavaET** [comment]
Fixed. It's not related to 3.0 though and it was broken before Divi 3.0.
