### ISSUE TITLE
Can't add image in Accordion module using "Visual Builder"

### ISSUE THREAD

**Issue by gourav-vds** [elegantthemes/Divi-Beta#382]
I can't add image in "Accordion Module" using "Visual Builder".
Tried to add image using "Add Media" button, But doesn't show in editor, Also after saving all changes it doesn't show in actual page also. Also added text in module, Text shows properly but can't see any image.

However i have tried using back-end builder, it is working fine.

I have tried it in my windows 8.

**Comment by meksone** [comment]
Found same bug here (Windows 10, Chrome 52.0.2743.116 m (64-bit)) but i've found this behavior:
If i switch che editor to "text mode" before insert a media, all is working fine; if I use the "visual" text editor and then add a media, the word "undefined" is added at the begin of the line, invalidating the HTML.
If I manually remove the word "undefined" all go smooth.

**Comment by SlavaET** [comment]
I was able to reproduce this issue that way:
1) Open any module with tinymce editor.
2) Use Add Media button and add image.
3) Close the module settings.
4) Open the same module settings.
5) Try to Insert Image using Add Media again. It won't work and error appears in console.
