### ISSUE TITLE
On the first load, add new tooltip cannot be scrolled

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#383]
### Problem:
when add new tooltip is being opened for the first time, it has no scroll bar and cannot be scrolled:

![add new tooltip canot be scrolled](https://cloud.githubusercontent.com/assets/916442/18315678/ff78d874-7541-11e6-8b86-cabe131be64e.gif)

It can be scrolled after hovering here and there

### Steps To Reproduce:
1. Add VB
2. Add new module. Try scroll the select module tooltip

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Comment by Jronk** [comment]
-
