### ISSUE TITLE
Shop Module: Best Sellers not working

### ISSUE THREAD

**Issue by bluantinoo** [elegantthemes/Divi-Beta#384]
### Problem: Shop module not working when using "best sellers"

Using the Shop module in builder to show the best sellers product does not actually show the best sellers, instead it shows just products with the default order.
Other settings for the module work ok.

Furthermore, if in my child theme (or plugin) I use the **woocommerce_shortcode_products_query** to alter the woocommerce shortcode query, the module do not respond the same way as the woocommerce shortcode does.

**This problem was not present on Divi 2,7,5, I noticed at first on Divi 2.7.10**

### Steps To Reproduce:
1.  create any page layout with builder
2.  place a Shop module in the layout
3.  setup the module to show the Best Sellers products

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC, Mac, iPhone

**Operating System**: Windows 10, OSX, iOs

**Browser**: Chrome, Firefox, Safari

**Screen Resolution**: any

-

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/Divi #2531](https://github.com/elegantthemes/Divi/issues/2531) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bluantinoo** [comment]
@lots0logs sorry to ask but I don't know how you're managing issues, do you confirm this issue or not? (because I still have this problem on v 3.07)

**Comment by lots0logs** [comment]
Hi @bluantinoo, Currently we are only tracking issues specific to the Visual Builder in this repo. So I went ahead and moved this issue into our main Divi Repo. We'll be doing another round of general bug fixes soon. I expect this issue to be addressed during that round :smile:

**Comment by bluantinoo** [comment]
Thanks for answering @lots0flogs, is there a way I can track this issue? I have several woocommerce with this bug and it's quite annoying :(

**Comment by lots0logs** [comment]
No, I'm afraid not. However, it will be listed in the change log when it is fixed. Also you should feel free to use this issue to check in on it anytime :smiley:
