### ISSUE TITLE
Audio Module :: Elements broke layout when used in Various column layout

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#385]
### Problem:

When the audio module is placed in various columns layout, the player elements, brake the layout.

Also while in the FB and checking the Tablets and / or mobile phones, the player elements, gets all scrambled. 

### Steps To Reproduce:
1.  create a page
2.  load the layout attached

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:
- While in the FB
![screenshot-et dev 2016-09-07 18-23-12](https://cloud.githubusercontent.com/assets/1719735/18318067/d342f8d4-7528-11e6-89dd-60cd741f11f1.jpeg)

- leaving the FB:
![screenshot-et dev 2016-09-07 18-28-49](https://cloud.githubusercontent.com/assets/1719735/18318097/f307dd92-7528-11e6-8bb1-4efe30746424.jpeg)

**Link To Download Layout JSON File**:
[Audio Modules Layout.json.zip](https://github.com/elegantthemes/Divi-Beta/files/459576/Audio.Modules.Layout.json.zip)

-

**Comment by fikrirasyid** [comment]
@eduard-ungureanu can you elaborate more in specific way what are the areas that gets scrambled? So far I only get the inconsistency of the player length:

![d342f8d4-7528-11e6-89dd-60cd741f11f1_jpeg__1905x5328_](https://cloud.githubusercontent.com/assets/916442/18382801/c4ec1d12-76ac-11e6-893d-a667a1db2086.jpg)

**Comment by eduard-ungureanu** [comment]
@fikrirasyid please check the 3 column layout! where the timer is on the left, the progress bar not full width and the volume is on the right. Also as you can see from my previous screenshot, the same issue happens on other column layouts.

**Comment by fikrirasyid** [comment]
@eduard-ungureanu can you take a look at https://github.com/elegantthemes/submodule-builder/pull/1155?
