### ISSUE TITLE
Divider Module :: Divider Weight doesn't work

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#388]
### Problem:

After setting a Divider Weight and leaving the FB the number entered in Divider Weight is ignored.

### Steps To Reproduce:
1. add a divider module
2. set a custom Divider Weight
3. save the page
4. exit the FB

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuZG1iMzZyTVM2YW8/view?usp=sharing
**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by andyhqtran** [comment]
The divider **height** seems to work fine, the issue I'm facing it the color not being applied.

**Comment by SlavaET** [comment]
Fixed it.
@andyhqtran Eduard is talking about `Weight` option from the Design tab ( see his video ).
As for the color - it works the same way as in BB and I don't see anything wrong with that.
