### ISSUE TITLE
Possible Issue With Contact Form 7

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#389]
We have reports that contact form 7, when enabled, causing the FB to crash when loading.

**Comment by abhi-sharm** [comment]
I saw a ticket like this and tested on my test install , with Divi 3.0 and CF7 as the only plugin and it worked fine for me.

**Comment by andyhqtran** [comment]
I checked on my end as well, I'm unable to reproduce this issue.

**Comment by SlavaET** [comment]
Cannot reproduce it either. Need to look at particular website to see what's wrong there.
@abhi-sharm can you please find that ticket and ask login details?

**Comment by abhi-sharm** [comment]
Sure , i just left a message to theme for support token.Will update here as soon as i receive.
