### ISSUE TITLE
Visual Builder :: Page Setting :: Custom CSS not editable 

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#391]
Problem:

Custom CSS section in page settings does not allow to enter anything. It is not editable at all.
Steps To Reproduce:  

1. Add a section using Visual Builder
2.GO to Page Settings
3.Try adding some custom css there

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@Jronk I notice one issue remaining with this. Once you had added text to the text area, you can't delete the first character in the field. If you keep hitting backspace it stops before the first character.

**Comment by Jronk** [comment]
@timayhelen its fixed now
