### ISSUE TITLE
Conflict With Easy Social Icons Plugin

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#393]
When enabled, the visual builder does not load

**Comment by SlavaET** [comment]
@timayhelen I cannot reproduce the issue, I installed this plugin - https://wordpress.org/plugins/easy-social-icons/
Added some icons on page and it works.
Did you change any plugin settings? am I testing the correct plugin?

**Comment by timayhelen** [comment]
This was probably related to code module / shortcode issues, since it uses shortcodes. Closing for now.
