### ISSUE TITLE
Possible Conflict With Monarch

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#394]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588898

**Comment by andyhqtran** [comment]
I was unable to reproduce the issue. I enabled the same plugins to see if it conflicted with one another my version seems to be fine. No errors, and the builder loads.

**Comment by fikrirasyid** [comment]
I've tried to replicate the issue and enabled the same plugins mentioned by thread starter, but still can't replicate it. I've asked for more information, still waiting for response now.

<img width="1440" alt="screen shot 2016-09-08 at 10 11 30 am" src="https://cloud.githubusercontent.com/assets/916442/18335890/f927a2c8-75ac-11e6-96d3-61eba71c66b0.png">
