### ISSUE TITLE
Potential Issue With Shortcodes Being Obstructed After Saving

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#397]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589033

**Comment by SlavaET** [comment]
Fixed.
This issue can be easily reproduced with contact form 7 plugin.
1) Add Contact form shortcode into text module ( I used BB for that )
2) Save the page
3) Open page in VB
4) Edit the text module with contact 7 shortcode.
5) Save the page
6) Check the content of Text module in BB.
