### ISSUE TITLE
Updating to 2.9.19  Failed

### ISSUE THREAD

**Issue by DeerMtn** [elegantthemes/Divi-Beta#398]
### Problem:

Update notice "You have version 2.9.18 installed. Update to 2.9.19." Proceeded to update and it states the file is "empty" and cannot update.

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  Click on updates
2.   Select the theme update
3.   Note error 

### Additional Information:

**Device**: Dell Inspiron Laptop i7 8g

**Operating System**: Windows 10 Latest beta build XXXXX.1902

**Browser**: Latest Chrome

**Screen Resolution**: 1920

**Screenshot or Screencast**: https://www.dropbox.com/s/x566g7dfa4iurhh/965f8888-6a98-4ec3-9a60-f132eb43af17%20-%20Copy.png?dl=0

**Link To Download Layout JSON File**: https://www.dropbox.com/s/6tpudors3pjmbyi/Divi%20Theme%20Options_090716_1%20-%20Copy.json?dl=0

**Comment by cap220** [comment]
I've got the same issue... Do I just disable the beta plugin and then install 3.0 or do I need to revert back to a pre 2.9.x backup of the site?

Thank you ahead of time.

**Comment by cap220** [comment]
Okay, as I thought, steps to resolve this issue:

1) Disable the 'Elegant Themes Divi Beta Tester'
2) Refresh 'Updates' in WordPress
3) The 'new' version of Divi to update to will change from 2.9.19 to 3.0.

Simple as can be...!
