### ISSUE TITLE
Builder Settings Modal :: Double digit bounce rate limits cropped

### ISSUE THREAD

**Issue by danmossop** [elegantthemes/Divi-Beta#4]
### Problem:

When the bounce rate limit for a split test is >= 10, part of the second digit is cut off, suggesting that the input box isn't quite wide enough. Minor visual issue only.

### Steps To Reproduce:
1. Start new page and enable Divi Builder
2. Click on page settings menu
3. Set "Enable Split Testing" = Yes
4. Increase "Bounce Rate Limit" to 10 or higher

### Additional Information:

Tested on Chrome for Windows 8.1.

Screen shot - hovering to show up down arrow, but cut off whether or not arrows are visible.

![bounce-rate-limit-value-cut-off](https://cloud.githubusercontent.com/assets/17969935/13907547/d3ddc4a0-ef44-11e5-8713-9948e368a727.png)

**Comment by fikrirasyid** [comment]
@danmossop thank you for submitting the issue. We've submitted a patch which should fix your report and it is currently in review process. Once the patch passes our review process, it should be available on the next beta release. I'll keep you notified :D

**Comment by danmossop** [comment]
Nice one. Thanks fikrirasyid :)

**Comment by fikrirasyid** [comment]
@danmossop my pleasure :)
