### ISSUE TITLE
Code Module :: HTMLEntities.decode() throws a TypeError In Some Cases Which Prevents FB From Loading

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#400]
### Problem:
`HTMLEntities.decode()` expects a string but in some cases we are passing it an array which causes a TypeError to be thrown. [Here](https://github.com/elegantthemes/submodule-builder/blob/e1ad8b1c193b9645d512ae3482a902fed96f3722/frontend-builder/app/components/modules/code/code.jsx#L85) is the line in question. I corrected the issue on the customer's site with the following:

```js
    let _content = this.props.content;

    if ( _content instanceof Array ) {
      _content = ( _content.length ) ? _content[0] : '';
    }

    const code = HtmlEntities.decode(_content);
```

**Comment by fikrirasyid** [comment]
Can you post me the layout / link to the forum which causes this issue so I can further understand the issue? If I recall correctly `props.content` will only be array if it contains react virtual DOM inside of it (which is something that can't be done by user submitted input).

**Comment by lots0logs** [comment]
@fikrirasyid I was unable to reproduce it locally. When I exported the layout to my site the issue did not occur. I patched it on the customer's site so its not occurring there anymore either :grimacing:

**Comment by SlavaET** [comment]
@fikrirasyid I think I accidentally reproduced this error. Try adding Contact Form 7 shortcode into the `code` module via BB and try to open that page in VB.

**Comment by fikrirasyid** [comment]
@lots0logs thanks for confirming it 👍 
@SlavaET thanks for noticing it! Anyway if you're up to take over this issue, please do so. I'm still figuring out a way to fix https://github.com/elegantthemes/Divi-Beta/issues/390 (basically if parsed shortcode is rendered by js, our current shortcode parsing fails)

**Comment by SlavaET** [comment]
@fikrirasyid ok, I'll take it.

**Comment by fikrirasyid** [comment]
@SlavaET thanks!
