### ISSUE TITLE
Modules Which Have Been Disabled Via The FB Aren't Styled As Disabled In the BB

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#401]
### Problem:

When you disable a module using the FB, save the page, and then edit the page with the BB the module isnt styled as disabled (however the module itself is indeed disabled when you check the settings). 

### Steps To Reproduce:
1.  Disable a module for all breakpoints using the FB
2. Save the page.
3. Edit the page in the BB
4. Module is not styled as disabled.

**Comment by SlavaET** [comment]
@lots0logs I cannot reproduce this issue. It works fine.. Can you please check it in the latest version?
![disabling-all](https://cloud.githubusercontent.com/assets/3446682/18378997/f8a47a84-7691-11e6-8842-0c0641a71567.gif)
