### ISSUE TITLE
Section Module And All Its Contents Have Incorrect Width When Viewed In The FB

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#402]
### Problem:
Hard to explain, check it out:

![image](https://cloud.githubusercontent.com/assets/4675662/18331060/e2181a80-7521-11e6-87b2-892dbcbb05de.png)

No errors of any kind showing up in console. The CSS applied to those modules (by the FB) sets the width to what it is in the screenshot. 

### Additional Information:

Ping me on Slack for the support token :smiley:

**Comment by lots0logs** [comment]
Got another report of this issue:

![image](https://cloud.githubusercontent.com/assets/4675662/18367627/bd619ca0-75e1-11e6-8de0-a20bc0a54a0e.png)

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588961

**Comment by lots0logs** [comment]
@fikrirasyid I just realized that they are using one of the footers from the Divi 100 Footer Layout Pack.

**Comment by timayhelen** [comment]
@fikrirasyid Looks like it's this layout pack, so we can test it out:

https://www.elegantthemes.com/blog/divi-resources/free-divi-footer-layout-pack-10-unique-footer-designs-to-give-your-site-a-leg-up

**Comment by fikrirasyid** [comment]
@timayhelen I've tried replicating the issue by importing footer layout pack and installing all plugin that is used by the site based on the paths on its source code. However, I still can't replicate the issue tho. I think we still need an access to the site.

@lots0logs have we received the token?

**Comment by lots0logs** [comment]
@fikrirasyid No, not yet :frowning:
