### ISSUE TITLE
Contact Form :: Not sending emails

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#406]
### Problem:

After updating to WP 4.6, and the previous Divi version before Divi 3.0 the contact form stop sending emails - it did worked before.

Now with 4.6.1 and Divi 3.0 the behavior is the same, no emails are being send. This was working find prior to wp 4.6 and Divi 3.0.

### Server Details:
Login: ####
User: ###
Pass: ####

If you need more access to the server, please let me know, also I did check the log files, there is nothing in there. Contact form 7 plugin send emails without any issue.

Thank you in advance.
Best Regards.

**Comment by Anny85** [comment]
@eduard-ungureanu I couldn't replicate the issue on our staging server. You can send me FTP login details via Slack, I will take a closer look.

**Comment by Anny85** [comment]
I was able to send an email to my gmail account. Closing it for now.

**Comment by dm-chechik** [comment]
It seems this string should be reviewed
`$headers[] = "From: \"{$contact_name}\" <mail@{$_SERVER['HTTP_HOST']}>";`
The customer reported the from field transformed to mail@**www.**mydomain.com.
Some mail servers reject emails with this address.

**Comment by timayhelen** [comment]
I thought we already stripped out the www. from the "from" address. Shouldn't we be doing that?

**Comment by Anny85** [comment]
@timayhelen It was not merged for some reason https://github.com/elegantthemes/submodule-builder/pull/682

**Comment by timayhelen** [comment]
Weird, I went ahead and merged it.
