### ISSUE TITLE
Wrong appearance of units switcher in Row Width settings

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#409]
### Problem:

This is how Units switcher looks in FB:
![image](https://cloud.githubusercontent.com/assets/3446682/18345399/1cd8f246-75dd-11e6-9009-bea4165f6943.png)

And this is how it looks in BB:
![image](https://cloud.githubusercontent.com/assets/3446682/18345415/316ab8fc-75dd-11e6-9e3c-183be9527ed9.png)

So, instead of `Yes`/`No` for this control in FB we should display `px`/`%` as we do in BB.

### Steps To Reproduce:
1. Open Row settings in FB
2. Enable `Use Custom Width` option
3. Check the appearance of `Units` option

**Comment by Jronk** [comment]
@timayhelen I re-implemented the labels for units to pull from the actual i18n (where applicable) options set in the php, example https://github.com/elegantthemes/submodule-builder/blob/master/main-structure-elements.php#L263-L265

**Comment by Jronk** [comment]
Re-opening this, with a better solution

**Comment by timayhelen** [comment]
@Jronk Re-opening this because your second PR was not merged. Just making sure you intended to merge it?

**Comment by Jronk** [comment]
thanks, its merged now, dont know how I missed that
