### ISSUE TITLE
Add Preloader To Module Ajax Calls

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#41]
Currently the pre-loader CSS animation has been added to several areas in the builder, such as launching the app and loading items from the library. We should also use it for the ajax calls that some modules make, such as Blog and Portfolio modules. Currently we just use some text that says "updating module..."

**Comment by timayhelen** [comment]
@Anny85 I think we can just replace the text on the page with the SVG loader, instead of using the body overlay.

**Comment by Anny85** [comment]
@timayhelen Should we use a white wrapper?

<img width="558" alt="screen shot 2016-08-25 at 14 49 44" src="https://cloud.githubusercontent.com/assets/3335250/17968059/6eba3fda-6ad3-11e6-8e6f-2f7a4fe7b0e4.png">

or

<img width="469" alt="screen shot 2016-08-25 at 14 48 48" src="https://cloud.githubusercontent.com/assets/3335250/17968066/76c12856-6ad3-11e6-9d1d-21dd027da532.png">

**Comment by timayhelen** [comment]
@Anny85 We can leave off the white wrapper I think.

**Comment by Anny85** [comment]
@timayhelen Cool. It is ready for review then.

**Comment by timayhelen** [comment]
@Anny85 It still has the white wrapper for me. Can we remove it?

**Comment by Anny85** [comment]
@timayhelen Sorry, it should work now.
