### ISSUE TITLE
Tab module does not work in IE11

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#410]
### Problem:

Open the following demo preview page in IE11:
https://www.elegantthemes.com/preview/Divi/tabs/

You will see the tab module does not work:
http://youtu.be/klh9JmDKen8?hd=1

**Comment by uportnykh** [comment]
@timayhelen I think all IE issues will be fixed after Fikri is done with this fix: https://github.com/elegantthemes/Divi-Beta/issues/414
