### ISSUE TITLE
Section Settings access with full width row and 0 gutter

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#411]
### Problem:

Can't get to the section settings in VB when there is a full width row with custom gutters set to 0

Layout:
[Divi Builder Layout.zip](https://github.com/elegantthemes/Divi-Beta/files/461628/Divi.Builder.Layout.zip)

Screencast:
[http://youtu.be/6vEGJqUqHkc?hd=1](url)

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks for the report. We have another issue open for this, so I am closing this duplicate.
