### ISSUE TITLE
Slider module does not work in IE11

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#414]
### Problem:

Slider module does not work in IE11. There is no left/right arrows and the navigation dots. You can reproduce the problem using demo page here:
https://www.elegantthemes.com/preview/Divi/slider/

Screen cast:
http://youtu.be/ZIiFpPMfb8o?hd=1

**Comment by dm-chechik** [comment]
The javascript error `Object doesn't support this action` in the frontend-bulider-scripts.js occurs on line 920 `document.dispatchEvent( new Event('et_pb_before_init_modules') );`
