### ISSUE TITLE
Toggle Module :: Safari Issue

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#415]
### Problem:

This issue only happens on Safari, please check our demo page: https://www.elegantthemes.com/preview/Divi/toggles/ in safari and you will see that on opening / closing any of the toggle module, there are some wired lines appearing before animation ends

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: dekstop

**Operating System**: mac os X

**Browser**: Safari

**Screen Resolution**:

**Screenshot or Screencast**:
https://youtu.be/3386pm3ePa8

**Comment by Anny85** [comment]
@eduard-ungureanu I'm not able to replicate the issue. Can you try to do it one more time?

**Comment by timayhelen** [comment]
@Anny85 I can replicate it. Just open a toggle module in Safari on OSX. You can just go here for convenience:

https://www.elegantthemes.com/preview/Divi/toggles/

**Comment by Anny85** [comment]
@timayhelen I don't see any issues in Sierra, but there are some lines when a toggle is animated in older version of Safari, when I check on BrowserStack.
