### ISSUE TITLE
Responsive Preview :: Modules' Enabled/Disabled Status Isn't Correctly Reflected In Preview

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#420]
### Problem:

Modules that have been disabled for mobile, tablet, or desktop are always shown as disabled in the responsive preview modes. For example, if you set a module to be disabled for desktop only, it will still show as disabled (faded-out) in tablet and mobile responsive previews.

**Comment by timayhelen** [comment]
@SlavaET This didn't seem to work for me. I set a Section to be disabled on Desktop and Smartphone, but not Tablet, but it removes disabled in all 3 responsive previews.

**Comment by SlavaET** [comment]
Fixed. It was an issue only with Rows and Sections.
