### ISSUE TITLE
Form ShortCode not rendering

### ISSUE THREAD

**Issue by kbdkl** [elegantthemes/Divi-Beta#426]
### Problem:

Contact Form shortcode or any such shortcodes do not render with visual builder on. In fact it does show up but when you click on this the output stops and only the naked shortcodes shows up. 

Take this plugin for an example https://wordpress.org/plugins/caldera-forms/

Replace this section with a description of the issue you are reporting. Be sure to explain the expected results vs. actual results when it might not be obvious to those who will read your report. 

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  Create a contact from 
2.  Create a page with tab module 
3.  Add the contact form shortcode and publish the page
4.  Now the form will show up in the tab module with visual builder on
5. Click on the module and you will see only the shortcode and not the form output

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop
 
**Operating System**: Windows

**Browser**: Chrome

**Screen Resolution**: 1920 x 1200

**Screenshot or Screencast**: http://i.imgur.com/sVTFxPN.png

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
That's the way it's supposed to work. It gives you the ability to edit a hortcode using the Visual Builder

**Comment by ayanize** [comment]
Thanks for the reply @SlavaET . I understand this but can the editor not parse the shortcode even viewing in Visual Editor instead of just showing the naked shortcode?

Thanks

**Comment by kbdkl** [comment]
Thanks for the reply @SlavaET  . I understand this but can the editor not parse the shortcode even viewing in Visual Editor instead of just showing the naked shortcode?

Thanks

**Comment by SlavaET** [comment]
Can you please explain a bit? I'm not sure that understand your idea. Visual example would be good

**Comment by kbdkl** [comment]
Thanks once again. Please see this screen-cast (click the zoom button to get the full screen).
When you click on the shortcode it turns into the code and not output

http://tinypic.com/r/r1mvqo/9

**Comment by SlavaET** [comment]
Yes, I know how it works now, but how do you expect it to work? :)

**Comment by ayanize** [comment]
Hello I really do not intend to hijack this thread but we are facing a similar kind of issue though not related to Divi. And I also understand that it's about a thirdparty plugin which you may not support but it uses the Divi principles and I wish you to have a look.

Not sure if you've heard of this plugin AC ShortCodes which simply converts a module into a shortcode and this can be placed in other module editor to render the output. But the cases from the OP are almost similar. Request you to spend two minutes to login to this site https://ayanize.com/dev1/wp-admin/ (UN and PW - demo) to have a look. It does show the module content but we can have helpers or allow users to edit that module as well?

Thank you very much. Once again sorry to write here. If required, I will create an issue.

**Comment by timayhelen** [comment]
Looks like things are working as intended. When you edit the a text module, it must be un-parsed so that the shortcode can be adjusted.
