### ISSUE TITLE
VB :: Conflicts with Smart Slider 3 plugin 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#428]
### Problem:

SmartSlider 3 images appear one below the other, instead of one dissolving after the other like they do when VB is not active. Customer have contacted to SS3 support and received the answer:

> The problem with Divi's new frontend visual builder is that while it's in the builder mode, it does not > call in the necessary cache files (and neither does any other frontend visual builder) simply to make their own product work correctly and avoid possible issues during the editing.
> 
> However, I noticed the problem exists in the frontend (after saving when outside of the builder), which is the same problem, that the cache files are not called in. It seems like an issue with the new Divi builder, and currently the best workaround we have found is to put the [protected] shortcode around the slider's:
> 
> [protected][smartslider3 slider=16][/protected]

**Comment by SlavaET** [comment]
Saving of shortcodes should be fixed in the recent update, please ask customer to update and check again

**Comment by dm-chechik** [comment]
@SlavaET Thanks I'll ask.

**Comment by dm-chechik** [comment]
I've received the answer from customer. Now it work better but the VB is showing a blown-up static image that's cropped off the top and bottom, and there's a small image underneath that.
I've tested on my test server and VB doesn't retain slider dimensions.
