### ISSUE TITLE
Row Padding set to 0 prevents the text module from being edited

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#429]
### Problem:

When the row Padding is set to 0 and the row only have a single text module - with a single line of text, editing the text module settings, make it very hard to work with.

### Steps To Reproduce:
1.  add a row
2. add a text module
3. enter somethign short like: Lorem is great
4. set the top row padding to be 0
5. try to edit the text module settings

### Additional Information:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuemlXTFRvblBqZjg/view?usp=sharing

**Comment by lots0logs** [comment]
@eduard-ungureanu Could you confirm that this issue still exists in the latest version?

**Comment by timayhelen** [comment]
We have another ticket open for this, so I am closing this duplicate.
