### ISSUE TITLE
Improve Typing Speed In Settings Modal

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#43]
Currently, if you are building a page of decent size, typing into the input fields in a settings modal is very laggy. Each letter re-renders the DOM, including the settings modal, which adds significant delay. We need to find a way to make typing smooth.

**Comment by fikrirasyid** [comment]
An idea for this: 

1. set props.value as initial state.value
2. control input value's is printed based on state.value
3. the typed value is being debounced for some miliseconds / seconds before dispatched via actions

If my assumption is correct about this approach:
- The typing will be really smooth, as in typing in normal HTML input
- The actual layout got a really little lag, but still tolerable
