### ISSUE TITLE
Multiple Selector Issue (Custom CSS)

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#43]
Related thread: https://discord.com/channels/1041765492907589683/1079860683623116862/threads/1184739841326469211

### Problem:
When specifying multiple Custom CSS selectors for a single element, only the first selector is prefixed with the module’s orderClass. 

For example, this:
```
...
myElement: {
  subName: 'myElement',
  selectorSuffix: ' .selector_one, .selector_two, selector_three',
},
...
```

Should output styles like this:
```
.my_module_01 .selector_one, .my_module_01 .selector_two, .my_module_01 .selector_three {
  color: #123456;
}
```

But actually outputs this :
```
.my_module_01 .selector_one, .selector_two, .selector_three {
  color: #123456;
}
```

An example of this can been seen the in the `Divi Audio Settings > Advanced > Custom CSS > Player Sliders Current` field. (See screen shot attached, below)

This is issue is closely related to another Custom CSS issue, previously described issue, here: https://github.com/elegantthemes/Divi-Beta/issues/23

<img width="608" alt="Screenshot_2023-12-14_at_2 01 54_PM" src="https://github.com/elegantthemes/Divi-Beta/assets/59285096/7c9a52f5-f3aa-4c3e-a982-d93bc1950635">

**Comment by shohel** [comment]
We've resolved your issue, here is a blog post on how you can achieve this - https://devalpha.elegantthemes.com/docs/tutorials/module/beginner/custom-css-styles
