### ISSUE TITLE
Layerslider Conflict

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#430]
### Problem:

I saw few tickets regarding layerslider conflict , different customers have different issues like builder not loading , for some save function does not work and they narrowed it down to layerslider.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Probably the same issue with FW Code Module as I fixed here - https://github.com/elegantthemes/Divi-Beta/issues/446
Asked the customer to confirm it. Waiting for reply.

Here is the link to support ticket for reference - https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=590605&p=3257671

@abhi-sharm can you please ask the customers to check my assumption about FW Code module ( see my reply in the ticket above ) in this ticket - https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588948&p=3250354

**Comment by abhi-sharm** [comment]
@SlavaET : I have update my reply on my ticket to confirm about this from customers. Will update here as soon as i hear back.

**Comment by abhi-sharm** [comment]
@SlavaET 

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588948  , it does not looks like FW code module problem for this user ,they have responded on the ticket

**Comment by SlavaET** [comment]
@timayhelen looks like our fix worked and this issue is fixed.
