### ISSUE TITLE
divider height

### ISSUE THREAD

**Issue by Jerobie** [elegantthemes/Divi-Beta#432]
### Problem:

Using the DIVIDER MODULE in the visual editor, you can set the Divider Weight with the pixel weight slider. Looks good in the builder but when viewed live, it is never more than 1px tall.

### Steps To Reproduce:
1.  go into Divider Settings > Design
2.  set the Divider Weight to 10px
3.  view live

### Additional Information:

The problem appears to be caused by a double px tag:
![image](https://cloud.githubusercontent.com/assets/22105344/18399194/ea3062c2-769d-11e6-8784-d65ea2a5368a.png)

**Comment by SlavaET** [comment]
@Jerobie it was fixed already. Please update Divi theme and check again.
