### ISSUE TITLE
Visual Builder :: Text Module :: All Options not available in editor toolbar

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#435]
### Problem:

When we add a text module using visual builder not all options are available like, text color etc , these are available while we add the text module via backend.

### Steps To Reproduce:
1.  Enable Visual Builder
2. Add a text module
3. check the toolbar
![toolbar](https://cloud.githubusercontent.com/assets/13402626/18410155/a749919c-7777-11e6-97a3-e2c9cba2ca78.PNG)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Added missing buttons. Except for the buttons generated by Wordpress which cannot be added into our editor in Visual Builder.
