### ISSUE TITLE
Essential Grid plugin Conflict

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#437]
### Problem:

Many Users reported Essential Grid conflict.

This is one of such thread if needed for taking token etc https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589146

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Probably the same issue with FW Code Module as I fixed here - https://github.com/elegantthemes/Divi-Beta/issues/446
Asked the customer to confirm it. Waiting for reply.
