### ISSUE TITLE
Visual Builder :: Incorrect behaviour under IE

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#439]
### Problem:

It seems the new VB doesn't work under IE correctly. I can't add sections, rows or modules. Settings tab is not working etc.
I've checked under IE11.

**Comment by SlavaET** [comment]
@dm-chechik Are you testing the latest ( 3.0.2 ) version of theme. We have fixed IE compatibility issues and it should work fine. Please confirm.

**Comment by dm-chechik** [comment]
@SlavaET Yes I confirm it. There is the error in the console 
> Object doesn't support property or method 'startsWith'

**Comment by SlavaET** [comment]
Looks like it's a different issue than.

**Comment by andyhqtran** [comment]
@SlavaET looks like there's a polyfill that we could add to support this ES6 feature.
http://stackoverflow.com/questions/30867172/code-not-running-in-ie-11-works-fine-in-chrome

**Comment by Jronk** [comment]
were not using lodash version again

most cases of our use of startsWith come from lodash, there are a handful that are using the 
browser version (which is not cross browser (ie) compatible)

so, easy fix, just switch to lodash version

“ES6 feature” is a broad term...

many functions *and* syntaxes are only supported in ES6

some, functions are normal for some browsers now, and some just arent implemented yet, by IE (of course, usual suspect)

so, with functions, we just need to use lodash, we have not found one instance that a cross browser function issue has not been resolved by using the lodash equivalent

**Comment by SlavaET** [comment]
Fixed.
I also noticed one js error in portability.js script which breaks the Portability in IE, fixed it in this PR - https://github.com/elegantthemes/submodule-core/issues/37
