### ISSUE TITLE
Incompatibility with Soliloquy Slider plugin

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#440]
### Problem:

Initially this comes from customer ticket https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=588952&p=3258964#p3258964. The problem was the Portfolio Module doens't react to the "Show pagination" setting. I've checked and found while saving page in new VB there is the error in a browser console: 
> Cannot create property 'attrs' on string .....

I can confirm it on my local enviro. Also the "Show pagination" setting doesn't work even set through old Divi Builder.

### Steps To Reproduce:
1.  Install [Soliloquy Lite plugin ](https://wordpress.org/plugins/soliloquy-lite/)
2. Create new slider in the Soliloquy Lite
3. Paste Soliloquy slider shortcode to an empty page into the Fullwidth Code Module
4. Add a Portfolio Module
5. Save a page and reload it to slide appeared.
6. Try to Save page again. It doesn't save with console error.

### Additional Steps:
1. Try to change pagination setting on the Portfolio Module from the old Builder
2. This setting doesn't matter. Pagination always appears.

**Comment by SlavaET** [comment]
It's an issue with saving shortcodes inside the Fullwidth Code module I fixed it in scope of this ticket - https://github.com/elegantthemes/Divi-Beta/issues/446

**Comment by dm-chechik** [comment]
@SlavaET Was this fix included into the last update (3.0.2)?

**Comment by SlavaET** [comment]
Not yet. The fix is ready but is not included into public version.
