### ISSUE TITLE
Not an issue just a question regarding one file being called

### ISSUE THREAD

**Issue by ayanize** [elegantthemes/Divi-Beta#441]
### Problem:

First this is not an issue. So you can close this ticket. I have instead a question. I can see this file frontend-builder-global-functions.js is being called even you're logged out. Is there any specific reason for this being called on the site where VB is not enabled.  Sorry I have not gone through the file completely. There are some concerns among Divi users fearing that Divi 3 is bloated with files and inline css. I am trying to explain this that it'd does not. In fact it's the same old Divi when your're logged out and it does not impact on SEO. But they have their own views.

Replace this section with a description of the issue you are reporting. Be sure to explain the expected results vs. actual results when it might not be obvious to those who will read your report. 

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@ayanize This isn't part of the Visual Builder. It's Divi Builder scripts that live on the front end of your website. They were not introduced in Divi 3.0 and they are Javascript functions required to make modules work on the front end of your site. Divi 3.0 does not introduce any new JS or CSS to your site when the Visual Builder is disabled.

**Comment by ayanize** [comment]
Thanks Nick for the clarification. I should have checked that earlier. My bad. Divi 3 is awesome and fast and it does not impact SEO at all. Kudos. :)
