### ISSUE TITLE
Visual Builder :: Tablet preview wrong layout arrangement

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#447]
### Problem:

Visual Builder in tablet view causes columns in row layouts to stack on top of each other as if they were on a smartphone.

Affected row layouts include:
4-4-4-4
2-4-4
4-4-2

**Comment by SlavaET** [comment]
@dm-chechik does it work differently if you resize the browser to the same sizes as tablet preview? 
I don't see any difference and it works as expected as far as I can tell..
Tablet preview - 793px
Phone preview - 493px
and they both trigger the `mobile` view of columns.

**Comment by dm-chechik** [comment]
@SlavaET Here is the 4/4 layout under the Chrome iPad preview
![image](https://cloud.githubusercontent.com/assets/20072036/18609237/f297e4e4-7d05-11e6-9c6b-94e181cb42d9.png)
And here the same layout under the VB tablet preview
![image](https://cloud.githubusercontent.com/assets/20072036/18609242/18f194be-7d06-11e6-9d10-3a172ec4d2a5.png)

**Comment by SlavaET** [comment]
Ah, I see now. Thanks for the clarification.
