### ISSUE TITLE
Fullwidth section :: draggable padding

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#454]
### Problem:

It's hard to adjust right, bottom and left padding.

### Steps To Reproduce:
1.  Create fullwidth section with module
2.  Try to adjust right, bottom and left padding

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
The fix is easy - display the Fullwidth Section outlines when module inside the fullwidth section is hovered. Otherwise it's nearly impossible to get the section outline and drag the padding since module covers all the space inside.
