### ISSUE TITLE
Plugin compatibility :: Jetpack

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#459]
@kary4 commented on [Tue Sep 13 2016](https://github.com/elegantthemes/Divi/issues/2536)

### Problem:

When jetpack is enabled the Divi Builder Timeout warning box appears.
![1](https://cloud.githubusercontent.com/assets/3352130/18492888/5585e5b2-7a16-11e6-8394-ef621ff4c13b.png)

Ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589544

**Comment by lots0logs** [comment]
@kary4 Could you ask them to try activating jetpack (its now required to connect it to a wordpress.com account in order to use it)

**Comment by kary4** [comment]
@lots0logs Actually it's not necessary. It's enough just activating the jetpack plugin to see the issue. Right now the plugin is enabled. If you disable jetpack the problem disappears.

**Comment by lots0logs** [comment]
@kary4 I understand that. However, I cannot reproduce the problem on my own site so it would help to know if the customer's issue persists after they connect it to their wp.com account.

**Comment by kary4** [comment]
@lots0logs I see. Already asked him to connect the plugin to a wordpress.com account.

**Comment by uportnykh** [comment]
I've figured out what is wrong. JetPack plugin adds OpenGraph tags to a post / page. ```get_the_excerpt()``` is being used for ```description```. It works ok if there is no excerpt, defined for a post / page. But if an excerpt is defined, when the content filter gets fired, it still thinks excerpt is being filtered, so it doesn't proceed with adding ```et-fb-app``` container.   

Here's the commit where it was introduced: https://github.com/elegantthemes/submodule-builder/commit/d5ec9976

@SlavaET We should fix the issue with Yoast in a different way. Here's what you can do to replicate JetPack bug locally:

- Open page.php and add:
```echo get_the_excerpt();```
right after:
```
get_header();
```

- Add some excerpt to a page and try to edit it in FB

**Comment by SlavaET** [comment]
I simplified the checks inside `et_fb_app_boot()` and removed our `$called` flag which prevented app from loading in some cases ( when get_the_excerpt() was called on the page for example ).
Looks like `is_main_query()` can guarantee that we do not perform filtering of the content when we don't need to and at the same time guarantees that we perform the filtering when we need it.
I performed some tests and it seems to work fine. It works with the Yoast SEO as well, so my previous fix is not needed at all.
@uportnykh @Jronk can you think of any situations when we really need the `$called` flag and `is_main_query()` is not enough?

**Comment by uportnykh** [comment]
@SlavaET I think ```is_main_query()``` should be enough, but we can keep using ```$called``` boolean as well just to be sure we don't add ```et-fb-app``` container more than once.

**Comment by SlavaET** [comment]
@uportnykh that's the problem. Let me explain.
`get_the_excerpt()` function triggers `the_content` filter which fires `et_fb_app_boot()` function and `$called` flag is set to true after that.
Then, when `the_content()` function executed our `et_fb_app_boot()` fired again and this time `$called` flag is set to `true`, but it's the place where we actually need to modify the content.
The problem is that we cannot determine whether the_excerpt() or the_content() function was executed since both of them uses `the_content` filter and both of them return true for `is_main_query()` check.

**Comment by uportnykh** [comment]
I see. We can remove it then.

**Comment by SlavaET** [comment]
Ok, it's ready for review then :)
