### ISSUE TITLE
Spacing Descriptions

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#46]
Related thread: https://discord.com/channels/1041765492907589683/1153901473009258497

### Problem:

Margin and Padding descriptions have the same description text: See screen shot below:

<img width="391" alt="Screenshot_2023-09-20_at_11 50 59_AM" src="https://github.com/elegantthemes/Divi-Beta/assets/59285096/a59ffb44-cc9a-4868-80e1-8268e78990d0">

**Comment by fikrirasyid** [comment]
The fix for this issue will be released in dev beta 13.
