### ISSUE TITLE
Front Builder :: Windows 7 IE 11

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#461]
### Problem:

Customers have reported that the front builder doesn't work on Windows 7, IE 11. Tried to work using the demo front builder and windows 7 IE 11 on browser stacks and the console show this error:

<img width="1920" alt="screen shot 2016-09-14 at 4 14 44 pm" src="https://cloud.githubusercontent.com/assets/1719735/18513525/7b69a298-7a96-11e6-9050-ec306e8d35c3.png">

**Comment by Jronk** [comment]
See my comments on PR

**Comment by timayhelen** [comment]
Looks like Slava's PR was not merged, but after merging it and testing it does appear that his fix works, and this doesn't seem to be required. @uportnykh Does it address any issues that I missed?

**Comment by uportnykh** [comment]
@timayhelen We didn't realize lodash wasn't used properly. It's ok to close these PRs then.
