### ISSUE TITLE
Visual Builder :: Internal Server Error With Plain Permalinks

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#463]
### Problem:

Though it is all working fine on my test install but one customer reported and i checked their site . It was fresh install with no plugin and whenever we selected the permalink as plan ( that is page url with a question mark in it ) , and then enabled visual builder , it keep showing Internal Server Error, for other permalink options it worked fine. I can't say it is a bug as it does not happen my test install. Just wanted to update you for further analysis.

### Steps To Reproduce:
I was not able to reproduce at my install , but on a fresh install of customer's site it was an issue , so may be it is related to some specific server settings.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by uportnykh** [comment]
I couldn't replicate this either. It works fine on Vagrant and our staging server.

**Comment by abhi-sharm** [comment]
@uportnykh : Hi , Sorry for the delay in update , actually my email client had some issue and i was not getting email notifications properly so i missed this message. I have to search for this ticket for getting the token as it is pretty old now, i will look for it if you need. I also think this should not bug as i have not seen even a single ticket like this since then. Let me know if you want me to search the ticket and get the token from the customer ?

**Comment by uportnykh** [comment]
Sure. Let's find out if we can help the customer.

**Comment by timayhelen** [comment]
@abhi-sharm If you hear back from the customer let us know. I am closing this issue for now.

**Comment by abhi-sharm** [comment]
This is fixed for the customer after latest theme update
