### ISSUE TITLE
Upgrade and delete theme error solution

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#465]
### Problem:

It seems last errors in WP 4.6+ related to impossibility to delete and update theme caused by naming theme folder starts with capital letter. If you rename folder to **divi** (not Divi) all works fine.

**Comment by uportnykh** [comment]
@dm-chechik It has been fixed already actually. Update should work fine in new version of Divi.

Please, let us know if it still doesn't work for you.

Closing it for now.

**Comment by dm-chechik** [comment]
@uportnykh I confirm that issue still persist in the 3.0.5. I can successfully delete default theme but not Divi

**Comment by timayhelen** [comment]
@uportnykh I think we need a new patch for Theme Deletion?

**Comment by uportnykh** [comment]
@timayhelen Looks like we can't do anything about it. It is not possible to delete an active theme, but if a theme is unactive, then we can't execute the patch to fix the issue. I was able to delete the theme though, it doesn't show correct notification, but the theme folder gets removed.
