### ISSUE TITLE
Add from library does not properly show error message received from server

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#468]
### Problem:

It displays javascript error: "TypeError: this.props.label is undefined". The problem comes from divi file: 
memberstatus.wantedlogic.net/wp-content/themes/Divi-test/includes/builder/frontend-builder/app/bundle.js?ver=3.0.4

Screen cast:
http://youtu.be/wkxq-i_ZrPk?hd=1

I cannot replicate the problem locally. 
I installed fresh Divi-test version to be sure the theme files are not customized.

website:
http://memberstatus.wantedlogic.net
lhw9IsWXLi=QRn!Oq

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=591604&start=10

**Comment by lots0logs** [comment]
### Additional Information:
The response from the server includes a proper error message to show the user but the FB throws a TypeError (cannot read property "replace" of undefined). 

Response from server:
```
{"templates_data":{"error":"You have not saved any items to your Divi Library yet. Once an item has been saved to your library, it will appear here for easy use."},"next_page":"none"}
```

**Comment by SlavaET** [comment]
This error can be reproduced locally if you don't have saved `layouts` in the library.
