### ISSUE TITLE
Save Button does not Save

### ISSUE THREAD

**Issue by NIckSharples** [elegantthemes/Divi-Beta#469]
### Problem: When I click on SAVE the green SAVE button changes to an 'X' and there is a No Entry symbol hovering over the button.

When I try to click away from the page, assuming my changes have been saved, I get the dialog box asking if I really want to navigate away and warning me that my changes may not be saved. In WP Admin that indicates that the page has not updated or been saved

![image](https://cloud.githubusercontent.com/assets/6023395/18522848/a5b27346-7aa9-11e6-976f-0842a78ae736.png)

If I do click away/leave the page then the changes are not being saved.

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@NIckSharples are you using the latest version of Divi theme ( it's a `3.0.5` at the moment ) ?
If yes - do you have any non-divi shortcodes on the page? which ones and where did you placed them?

**Comment by NIckSharples** [comment]
Hi Slava,

Thanks for the quick response.

I have a Revolution Slider at the top of the page which does not show up on the Visual Builder. It uses a shortcode within a Divi Text Module.
![image](https://cloud.githubusercontent.com/assets/6023395/18540811/1f93fa08-7b19-11e6-80c4-2e76c4f11a4f.png)

I am on 3.0.1 at the moment. I will update to 3.0.5.

Thanks,

Nick

**Comment by SlavaET** [comment]
@NIckSharples please update to 3.0.5 and check again. It should be fixed already.
Let us know the results.

**Comment by NIckSharples** [comment]
Cracked it! The update has sorted the problem. I now get a small visual indicator of the Slider in the top left hand corner and can save the changes to the rest. A brilliant enhancement to Divi!!!!
Many thanks.
