### ISSUE TITLE
Make All Text Fields Editable With Inline Editor

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#47]
Current the inline editor is only available for "text area" inputs (the main TinyMCE inputs in the settings modal). We should make all text inputs, such as Slider Titles and CTA Titles, editable using the Inline Editor.

**Comment by SlavaET** [comment]
Added inline editor to all the text fields where possible:
![inline-editor-in-action](https://cloud.githubusercontent.com/assets/3446682/18128004/75f72548-6fa5-11e6-98ae-02c581e3bf11.gif)
