### ISSUE TITLE
FW Header :: Advanced Design Settings Applied In VB Only Show While Using The VB

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#476]
#### Using the VB:
![2016-09-15_12-33-49](https://cloud.githubusercontent.com/assets/4675662/18560376/e8bfad1a-7b40-11e6-9ac3-93bcbbe89f4f.png)

#### Viewing Page Normally
![2016-09-15_12-34-19](https://cloud.githubusercontent.com/assets/4675662/18560386/f4a0a026-7b40-11e6-8dd8-94a04838b4f6.png)

### Additional Information:
**URL:** https://goo.gl/ppq9F5
Ping me on Slack for the token.

**Comment by uportnykh** [comment]
@lots0logs Are you able to replicate it on localhost? I see no issues.

**Comment by lots0logs** [comment]
@uportnykh  No, but I cant explain it either. Its a fresh install with absolutely no plugins and its running php 5.5 :confused:

**Comment by uportnykh** [comment]
The customer was using incorrect CSS code for a row, it broke styling on front-end, since it renders all styles inside of one style tag ( it works differently in FB, since there are multiple style tags for each element )
