### ISSUE TITLE
HTMLUtility::render() And Role Attribute

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#48]
Related thread: https://discord.com/channels/1041765492907589683/1163686476236738590

### Problem:
The `HTMLUtility::render()` function does not output `role` attribute. See example below:
```
$figure = HTMLUtility::render([
  'tag' => 'div',
  'attributes'. => [
    'role'      => 'figure',
    'class'     => 'my_class',
    ...
  ],
  'childrenSanitizer'  => 'et_core_esc_previously',
  'children'           => $image,
]);
```

In this example, the `role` attribute is not rendered on the front-end.

**Comment by ayubadiputra** [comment]
This issue is fixed in v5.0.0-public-alpha.1.1 and will be released soon.
