### ISSUE TITLE
Error when settings modal open, then tooltip, then trying to close tooltip

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#48]
![setings-modal-then-tooltip-close-js-error](https://cloud.githubusercontent.com/assets/1163441/17787889/fbcea4c2-653f-11e6-872c-5ec78e12412a.gif)

**Comment by SlavaET** [comment]
@timayhelen isn't it supposed to close all the opened modals when tooltip opened?
So, in the situation above Module settings should be closed once tooltip opened. Is my understanding correct?

**Comment by timayhelen** [comment]
@SlavaET Yeah that sounds good.
