### ISSUE TITLE
Button Module Appearance Discrepancy 

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#482]
If you add a new button module, enable "use custom button styles" and then set the button icon to "no icon," custom padding added via the CSS tab will not work in the Visual Builder. Adding the following, for example, will have no affect in the Visual Builder but it will work correctly on the front end:

padding-left: 100px!important;

**Comment by timayhelen** [comment]
@SlavaET This seems to cause some strange issues and break various settings. For example, "Add Button Icon" setting doesn't work correctly now when you set it to "No" and it also seems to affect other module settings. For example, try enabling this setting on a standard CTA module. It will remove padding from the parent module wrapper and also will not remove the icon from the button.

**Comment by SlavaET** [comment]
Fixed.
