### ISSUE TITLE
Broken JS When Moving Row to Another Section

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#484]
The issue is discovered on Slack discussion: https://elegantthemes.slack.com/archives/divi3-0/p1474083279000176

**Comment by fikrirasyid** [comment]
@Jronk @SlavaET @timayhelen I've been working on this issue for two days and still don't get solid solution for this. Thus, I'm pausing myself from this issue and will revisit this later after I'm done with other stuff. However, it'd be super great if someone would give this issue a try; fresh perspective is probably what is needed for this issue.

Nevertheless, this is what I know about this issue so far. First, take a look at this 11 seconds screencast on how to replicate the issue: https://www.dropbox.com/s/ul9pyj4tomrc4oo/Screeny%20Video%20Sep%2022%2C%202016%2C%209.10.48%20AM.mov?dl=0

What you need to know about replicating the issue:

1. The issue happens when you drag the only row in a section into another section.
2. This issue is rarely happen when you use touchpad. To increase the possibility of the issue to occur, use mouse and set the tracking speed to max
3. This has something to do with how fast you drag the item to the placeholder. The faster you drop the dragged item into placeholder, the higher the probability of the issue to occur
4. Most of the time, it is easier to replicate the issue if you drop the dragged item outside the placeholder. However, it sometimes easy to replicate the issue to drop row between rows

This is the layout I'm using to replicate the issue: 
[Row DnD Fail Layout.json.zip](https://github.com/elegantthemes/Divi-Beta/files/486408/Row.DnD.Fail.Layout.json.zip)

Several things I learned about the issue:

1. The JS error appears due to react try to remove the moved_from_address DOM, but somehow the moved_from_address DOM has been removed. (moved_from_address as in moved_from_address DOM and moved_to_address DOM. If we move `1.0` row to `0.2`the moved_from_address DOM is `1.0`)
2. My initial thought is the DOM is accidentally removed by sortable or our custom code, but at this point I haven't found what is exactly that removes the DOM
3. The DOM appears to vanished at `stop` event. `stop` is the last event on sortable and we assign `handleDrop` for `stop` and `receive` event. See this at `/frontend-builder/app/lib/makeSortable.js`.
4. I used interval to see when the origin DOM is vanished, my findings:
 - when the error occurs, origin DOM was vanished as soon as (around 10ms-ish) `handleDrop` is called on `stop` event. Thus, when `ETBuilderActions.endDraggingModule()` is called at https://github.com/elegantthemes/submodule-builder/blob/master/frontend-builder/app/lib/makeSortable.js#L112 (which is delayed for `250ms` due to animation duration), the `moved_from_address` DOM has vanished thus causes the issue
- when the error doesn't occur, the origin DOM exists up until `ETBuilderActions.endDraggingModule()` is called

***

## Possible fix, but still missing some points

We can accurately prevent the JS from breaking by adding conditional for `ETBuilderActions.endDraggingModule()` by detecting the `moved_from_address` DOM's existence:

```
if (jQuery(`[data-address="${moved_from_address}"]`).parent().length) {
  // DOM exists
  ETBuilderActions.endDraggingModule( moved_from_address, moved_to_address );
} else {
  // DOM doesn't exist
}
```

This prevents the `removeChild` from throws an error, but this makes the `moved_from_address` DOM disappears. Theoretically, this can be somewhat fixed by adding rerender mechanism (simply by bumping up root's version state) but the dragged-and-now-disappears row wouldn't get rerendered. Interestingly, let's assume you move 1.0 to 0.2 on the following layout when the error occurs and the conditional check prevents the error from happening:


![initial error](https://cloud.githubusercontent.com/assets/916442/18735897/c6acd7d2-80ab-11e6-956a-f7c1c5dd4c3f.jpg)

This will make:

- 1.0 DOM doesn't get rendered (checked on inspector's element tab)
- However, in inspector's react tab, all the section, row, and module component is still there

If you add a section and row below then moved it to `1`, the newly added section's row will disappear:

![replicating row dnd failure](https://cloud.githubusercontent.com/assets/916442/18735889/b34596ca-80ab-11e6-875e-8049548b1680.jpg)

***

I have around 5 WIP branches that I used for working on this issue. If you need it, let me know.

**Comment by lots0logs** [comment]
@fikrirasyid This is definitely a tough one. Any solution we come up with must ensure that the DOM is not modified by jquery sortable (nor by anything other than React for that matter). I think you're findings thus far affirm that actually.

**Comment by fikrirasyid** [comment]
@lots0logs yeah. There are two missing points tho:

1. What removes the DOM
2. What triggers this DOM removal

Once we figure this out, it'll get significantly clearer, I think

**Comment by Jronk** [comment]
Fixed. There is a jQuery UI bug where the original child get dropped out of the DOM if you drag the item out of bounds, like in your above video. I was able to replicate it consistently (works about 1 in 10-15 tries). With this fix I am no longer able to replicate the bug/js error.
