### ISSUE TITLE
Possible Issue With Sub Domains

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#487]
This is the second time I have seen someone complain about the Visual Builder "not working," and their website is using a sub domain structure like this:

http://www.carmines.vagabondvirtual.com/

People often use these sub domain setups for staging. Is there a way we can replicate this and test it?

**Comment by lbjohnson01** [comment]
@timayhelen have you gotten reports of child theme style.css not working with 3.0.x? Mine seems to have petered out. Makes no difference whether installed plugins are all off or all on.

http://bbp.lbjdigital.com

**Comment by lots0logs** [comment]
@lbjohnson01 Your stylesheet has a few syntax errors in it. Try replacing it with this copy (where I have corrected the errors): https://gist.github.com/lots0logs/acf89be501f8c109280121ff35c48b53

Let us know the result :smiley:

**Comment by lbjohnson01** [comment]
@lots0logs yeah see, this is why we use staging. :/ :)

Thanks so much for catching those! You guys are The Man.

**Comment by timayhelen** [comment]
Another person with a possible sub domain issue: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=595662

**Comment by uportnykh** [comment]
The recent update ( 3.0.8 ) fixed the issue on the customer's sites.
