### ISSUE TITLE
Visual Builder :: Module Colorpicker :: Impossible to type hex code

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#490]
### Problem:

There is impossible to erase (by backspace) or input any hex code.

### Steps To Reproduce:
1. Open color picker i any module settings
2. Try to erace by tapping on backspace 
OR
3. Try to start input any color code
4. The code field gets updated itself and it adopts random colours.

**Comment by lots0logs** [comment]
@dm-chechik Could you confirm that this occurs with the latest version? (It was recently fixed elegantthemes/submodule-builder#1168)

**Comment by dm-chechik** [comment]
@lots0logs It's not the inline editor colorpicker. It's a module settings colorpicker.
![image](https://cloud.githubusercontent.com/assets/20072036/18617677/1c175772-7dde-11e6-8418-26ae1767f4a3.png)

**Comment by fikrirasyid** [comment]
@dm-chechik a patch has been submitted for this issue. It is currently under review process now. Thank you for reporting the issue :)

Fixes https://github.com/elegantthemes/Divi-Beta/issues/490

It appears that the issue isn't user **cannot** type hex code, but the typed hexcode is automatically "corrected" by colorpicker after 3rd character into 6 characters hexcode so it's impossible for user to type the correct hexcode. This commit fixes the issue.

Before:

![490-issue](https://cloud.githubusercontent.com/assets/916442/18781937/27dd2e78-81ae-11e6-99c9-8712556e88d4.gif)

After:

![490-fixed](https://cloud.githubusercontent.com/assets/916442/18782054/a72bb712-81ae-11e6-9ee7-752b306a419a.gif)
