### ISSUE TITLE
Visual Builder :: Row :: Width misconfiguration

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#494]
### Problem:

VB editor allows to set row width in px when % units is selected and vise versa. It confusing customers when they input 70% value for example and pay no attention  that px units is selected. As a result they see a row with 70px width.

**Comment by fikrirasyid** [comment]
@dm-chechik we've submitted a patch for this issue and it is currently under review process. Once it passes review process, it should be available on the next release. Thank you for reporting the issue! :D
