### ISSUE TITLE
RTL Alignment Still Applied In VB When Translations Disabled In ePanel

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#496]
### Problem:

If a site is using a RTL language but disables translations of the theme/builder using the option in ePanel, the alignment of text/buttons in the VB remains RTL while the actual text is in English.

**Comment by timayhelen** [comment]
@lots0logs Does he have the "Disable Translations" option enabled in epanel?

**Comment by lots0logs** [comment]
@timayhelen He said he has the backend in English so I assume he must have enabled that option in ePanel.

**Comment by timayhelen** [comment]
Well I don't think Divi is translating the page then. Maybe he has a translation plugin, or perhaps it's just Chrome translating it automatically.

**Comment by timayhelen** [comment]
@Anny85 I think we should disable it for the BB and Theme Options as well.

**Comment by Anny85** [comment]
Ok

**Comment by uportnykh** [comment]
@timayhelen It looks like there's not much we can do on Theme Options and BB pages. We can apply some hacks using jQuery, but it breaks RTL page layout and it might not work in all browsers. Do you think we should still add it?
