### ISSUE TITLE
Saved Previous Modal & Page Settings Bar State

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#497]
I think we should record the current position, size and state of the Settings Modal and Page Settings bar and use those value when the builder is opened again. So if someone, for example, re-sizes their settings modal and snaps it to the left and then saves the page, the next time they open the builder the settings modal opens at that position. Some people will prefer certain arrangements, and it would be best to keep their preferred settings by default. We should record the following values:

1. Settings Modal State: Snap Left / Snap Right / Expanded / Normal
2. Settings Modal Position: x/y coordinates of the modal, where they left it previously. 
3. Settings Modal Size: height and width of the settings modal. 
4. Page Settings Bar Position: Top / Bottom
5. Page Settings Bar State: Opened / Closed

**Comment by lots0logs** [comment]
@Jronk 

1. Works great :+1: 
2. I couldnt test this completely due to #546 but I was able to at least confirm that the horizontal position is persisted. 
3. :+1: 
4. :+1: 
5. :exclamation: The open/closed state is not persistent when I tested this branch.

**Comment by Jronk** [comment]
2. Is this no longer a problem here then?
5. I meant to add a note about that. Basically I didnt include it on purpose, since you would have it open to save, and it would save the open state and you would never be able to save it in a closed state because you cant hit the save button with it closed. I could, however, make these "app preferences" save without the need of the save button, but this would generate lots of ajax calls to save to the backend ever modal change and settings bar open/close... what do you think? 
@lots0logs @timayhelen

**Comment by timayhelen** [comment]
I think we can add it as part of the "power user" features we have going.

**Comment by lots0logs** [comment]
What if we did that only for the open/close state of the settings bar and keep the rest how you have it now?

**Comment by Jronk** [comment]
This functionality is what I dubbed app preferences, so the idea that we could have some app prefs that save instantly (especially ones that you arent interacting with a ton), and then others that will save on a full save (saving the page/post via save button). I tried to keep the implementation open for future use for other "app preferences".

**Comment by timayhelen** [comment]
I think we should just not worry about the open state for page settings right now. There is one thing that should be fixed in this PR though. 

- [ ] When you click the icon to "expand" modal settings, this state should be saved as well. Currently it just captures the expanded height/width/position, but the "expanded" state is actually different. This is like "fullscreen" mode. When in this mode, there is no resize icon and the "expand" icon changes to "contract," which must be clicked to leave the expanded mode.

**Comment by lots0logs** [comment]
@timayhelen Just a reminder :sweat_smile:   https://www.elegantthemes.com/forum/viewtopic.php?f=22&t=592011

**Comment by Jronk** [comment]
> When you click the icon to "expand" modal settings, this state should be saved as well.

Actually it does already capture expanded/fullscreen mode:

![app-pref-persist-does-capture-fullscreen](https://cloud.githubusercontent.com/assets/1163441/18997978/94dd3d96-86eb-11e6-92c4-71e7435b7a11.gif)

**Comment by timayhelen** [comment]
@Jronk It doesn't seem to work that way for me for some reason. It saves the position and height of the modal, but it doesn't save the "expanded" state. So when I refresh, it's in normal mode but has been increased in height/width. You will see that the icon is not changed and the re-size anchor is active:

![expand](https://cloud.githubusercontent.com/assets/3333028/19002620/a4441f8c-8701-11e6-8fc1-90c31e4cde9a.gif)

**Comment by timayhelen** [comment]
@Jronk I see, it only works if you close the modal before saving. Can we change that?

**Comment by Jronk** [comment]
@timayhelen thanks for the clarification, I fixed it, now it will save properly
