### ISSUE TITLE
Visual Builder :: Column class disappears with Post Slider Module

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#499]
### Problem:

Column css class assignments disappear from the html code after Post Slider Module insertion.

### Steps To Reproduce:
1. Insert row with 4 columns for example. 
2. Assign css class to each column (column1, column2, ...)
3. Insert Post Slider to second column for example
4. Now 3rd and 4th columns doesn't have css classes. If you look from the row settings all classes in their places however if you exit from VB mode and look into the html code you'll see the columns doesn't have css clasess.

**Comment by Anny85** [comment]
I can't reproduce this issue using the latest version of the theme.

@dm-chechik Can you see if it is still not working properly for you?

**Comment by timayhelen** [comment]
I couldn't replicate this either. It must be a different issue.

**Comment by dm-chechik** [comment]
@Anny85 @timayhelen Hi! I'v recorded the screencast.
http://screencast-o-matic.com/watch/cDQr66jFtt

**Comment by Anny85** [comment]
We've replicated the issue. You should have at least one post, made using Builder, in the Post Slider module content.

**Comment by lots0logs** [comment]
@Anny85 I noticed that the posts shown in the VB for the blog module is different from what is shown on the actual page when one of the posts has a blog module in its content. 

### Page:
![2016-09-26_10-39-05-pm](https://cloud.githubusercontent.com/assets/4675662/18859532/a4253046-843a-11e6-8694-9cb08cf4b9c4.png)

### VB:
![2016-09-26_10-45-46-pm](https://cloud.githubusercontent.com/assets/4675662/18859577/06194eae-843b-11e6-884e-4fda9145cf55.png)

**Comment by Anny85** [comment]
@lots0logs Do you mean sticky posts are not displayed in Visual Builder? Did you try to replicate the same issue on master?

**Comment by timayhelen** [comment]
@Anny85 If that is the issue, can you fix it in this PR so we can move it to Dev Review?

**Comment by Anny85** [comment]
@timayhelen Yes, I'm just not sure what the real issue is. It is hard to tell by just looking at screenshots. I'll try to replicate the issue with sticky posts.

**Comment by lots0logs** [comment]
@Anny85 I actually hadnt realized it was sticky posts until you mentioned it. I checked it and found that It is indeed the sticky posts that are missing when the Blog Module is rendered in the VB.

**Comment by timayhelen** [comment]
@Anny85 It looks like code from the code module is being rendered as normal text. I think we can just strip out all content from code modules in the blog module content area:

![screen shot 2016-09-27 at 11 49 46 am](https://cloud.githubusercontent.com/assets/3333028/18887356/998a1e76-84a8-11e6-8ddb-b63950aee4d7.png)

**Comment by uportnykh** [comment]
@timayhelen I've fixed it.

**Comment by SlavaET** [comment]
Looking for a solution to not strip Divi shortcodes from the Blog/Slider modules.

**Comment by SlavaET** [comment]
Done. Shortcodes no longer truncated from the content of the Blog and Post Slider modules, they'll be rendered correctly and will not affect the layout of other elements on the same page.
