### ISSUE TITLE
Layout/Style :: Variation number disappears when admin label changed

### ISSUE THREAD

**Issue by danmossop** [elegantthemes/Divi-Beta#5]
### Problem:

When a split test is created, the variation number is shown in a circle to the right of the variant. However, if the admin label for the variant is changed, the number / circle is no longer displayed for that variant. 

### Steps To Reproduce:
1. Create a new page and start a split test, selecting the first section as both the target and goal.
2. Note that the two variants have (1) and (2) beside them.
3. Change the admin label for variant 1. 
4. Note that (1) is no longer displayed beside variant 1. The (2) is still displayed beside variant 2, but will go away if it's admin label is also changed.

### Additional Information:

Changing other settings doesn't seem to affect it - only the admin label causes this (not tested extensively).

Testing on Windows 8.1 with Chrome.

![split-test-section-numbers-disappear](https://cloud.githubusercontent.com/assets/17969935/13907938/26271cea-ef4d-11e5-84ff-a9f393f14107.png)

**Comment by SlavaET** [comment]
Fixed.
**Note**: the issue can be reproduced only if you update the label from Module settings Modal. If you rename the section via right click menu, then it works fine.
