### ISSUE TITLE
Contact Form Appearance

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#500]
It looks like the contact form module's default appearance has changed in recent updates. The text area is not 100% width, as mentioned in this post:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=594467

It happens in our own demos as well:

http://elegantthemes.com/preview/Divi/agency/

**Comment by uportnykh** [comment]
All newly created forms should work fine now. 

Customers will need to open contact form settings and hit save to fix the issue with existing modules settings.

**Comment by abhi-sharm** [comment]
Hi @uportnykh , this has been merged in latest version? and if customer updates to 3.0.14 , it will work fine for them ? or even after updating they need to click on save button to fix the issue ? One customer wants to confirm as they have almost 200 sites where they are using Divi form.

**Comment by uportnykh** [comment]
Hi. It is fixed in the latest version. Yes, they would need to hit save to fix the issue with existing forms.
