### ISSUE TITLE
Inline Editor :: TinyMCE's Options For Editing HTML Tables Not Available

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#501]
### Problem:
Its currently possible to edit the contents of table cells and to increase the table's height. It doesnt allow you to increase the table's width. Also the other options that MCE provides when actively editing a table are not available (not sure if its possible, but if it is then we should do it)

**Comment by kary4** [comment]
Not sure if I should create separate issue.. anyway, ET Shortcodes  buttons are not available under inline options.
![1](https://cloud.githubusercontent.com/assets/3352130/18748080/58500344-80d9-11e6-869b-b4f07561d614.png)

**Comment by SlavaET** [comment]
@kary4 please create separate ticket, since it's a different issue and not related to the Inline Editor.

**Comment by kary4** [comment]
@SlavaET Will do, thanks!

**Comment by Jronk** [comment]
This change is introducing a potentially broken looking UI into our elegant and pristine inline editor. I think if we want to do this right, we need to fully take over the UI its trying to present when editing a table, like we've done with everything else so far.
![inline-editor-inline-table-editing](https://cloud.githubusercontent.com/assets/1163441/18936842/c029953c-859f-11e6-8e7f-cdd7876f573b.gif)

**Comment by Jronk** [comment]
@timayhelen what do you think?

**Comment by lots0logs** [comment]
@Jronk Good catch! ![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/18937198/af6aba32-85b3-11e6-91cb-924d99869765.gif)

**Comment by timayhelen** [comment]
Yeah, let's just hide it for now. We can look into adding into our editor later.

**Comment by SlavaET** [comment]
Done. I made this controls hidden, but it's still possible to edit the content of table and drag the width/height of columns using inline editor.
