### ISSUE TITLE
Hidden TinyMCE Area Adds Unwanted Height To Empty Text Areas

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#504]
Each editable text area has a height of 3px added to it. When a text field is left blank, it adds extra height to the module. Do we need to have a hard-coded height of 3px, or can we just make it 0px?

![screen shot 2016-09-19 at 4 34 53 pm](https://cloud.githubusercontent.com/assets/3333028/18652514/e7d84eb2-7e87-11e6-9e02-81ce186d4e9c.png)

**Comment by SlavaET** [comment]
@timayhelen it was added to make it possible editing of empty fields. If we set it to 0 ( or we can simply not output anything ) then it won't be possible to type in the title field if it's empty.

**Comment by timayhelen** [comment]
Can we lower it to 1px, or will that make it more difficult to access?

**Comment by SlavaET** [comment]
yes, it'll be extremely difficult to access, 3px is the minimal height which is usable ( based on my experiments ). But I'm thinking of different option now - set the height to 1px and extend it on hover so it'll be possible to click inside editable area. 
I'll check that.

**Comment by timayhelen** [comment]
@SlavaET Ok, I guess it's a pretty low priority issue.

**Comment by SlavaET** [comment]
Found the way to reduce the height to `0px` and keep it accessible.
