### ISSUE TITLE
Row/Section Drop Animations Aren't Smooth

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#507]
When a row or section is dropped, there should be a smooth animation that fades/slides in just like modules. However, the animation seems to be interrupted and it's not very smooth. I think there is a base height applied that prevent the start of the animation from rendering correctly. 

![row-smooth](https://cloud.githubusercontent.com/assets/3333028/18655029/50d8464e-7e9a-11e6-844e-19d4b321edd4.gif)

**Comment by SlavaET** [comment]
Fixed. Also fixed the issue when moved module appears in previous location for a split second.

**Comment by timayhelen** [comment]
@SlavaET I notice something weird with the animations in this branch. It appears that when you move one section, it causes sections below it to "animate" in as well. Only the row/section being dropped should slide/fade in.

![row](https://cloud.githubusercontent.com/assets/3333028/18798442/7133a13c-8187-11e6-88cd-a64bbe389a7c.gif)

I also noticed some issues with rows and sections disappearing when you drag them. I am not sure if it's related to changes made in this PR though. Try loading the Homepage Basic layout and performing these actions:

![disappear](https://cloud.githubusercontent.com/assets/3333028/18798568/002584b4-8188-11e6-8d4d-bb797e11ec98.gif)

**Comment by timayhelen** [comment]
Also, it looks like if you move a module from one column to another, modules below the moved module in the original column re-animate:

![animate](https://cloud.githubusercontent.com/assets/3333028/18798891/9260a40c-8189-11e6-93a9-0e9f4cd34f45.gif)

**Comment by SlavaET** [comment]
@timayhelen I closed the previous PR and submitted a new PR with the fix which should not have the issues you mentioned, please check this - https://github.com/elegantthemes/submodule-builder/issues/1235
