### ISSUE TITLE
Legacy Contact Forms Don't Show Up In Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#509]
Contact form modules that were created before we added the "custom form fields" system don't show up correctly in the visual builder since they don't technically contain any child module items. Once the module is opened and saved in the BB, the form fields appear.

**Comment by timayhelen** [comment]
I still get a blank contact form. Try loading the "Contact Us" pre-made layout in the VB, which includes the old shortcode:

![screen shot 2016-09-22 at 12 01 43 pm](https://cloud.githubusercontent.com/assets/3333028/18762147/7510cdb4-80bc-11e6-9685-2361611562cd.png)

**Comment by SlavaET** [comment]
@timayhelen hm, it works for me. I merged the latest master into my branch, can you please check it again?

**Comment by uportnykh** [comment]
It seems to work fine for me as well.

**Comment by timayhelen** [comment]
I must not have successfully pulled recent changes. It seems to work for me now.
