### ISSUE TITLE
Add Tooltips To All Buttons

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#51]
I think we should add Tooltips everywhere, perhaps with a custom style. They would also include shortkey command when applicable.

**Comment by DeerMtn** [comment]
**1st** thing I noticed Nick - I feel lost as none of the front end icons/buttons have tooltips and I'm having to click on _everything_ to find out what it does... thumbs up on this one!

**Comment by andyhqtran** [comment]
ref #178

**Comment by timayhelen** [comment]
@andyhqtran We should add tooltips for module hover buttons.

- [ ] Move
- [ ] Edit
- [ ] Duplicate
- [ ] Save To Library
- [ ] Delete

- [ ] Change Columns

- [ ] Add Module
- [ ] Add Row
- [ ] Add Section

**Comment by andyhqtran** [comment]
@timayhelen I left some notes on the issues I was having on it but I was able to figure it out. Ready for review!
