### ISSUE TITLE
Plugin compatibility :: NextGen Gallery

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#510]
### Problem:

When I try to activate the plugin I get this error message:
```
Fatal error: Class 'ET_Builder_Element' not found in /home/content/62/7957362/html/newsite/wp-content/themes/Divi/includes/builder/functions.php on line 1223
```
I

### Additional Information:
I updated the theme myself.
All plugins are deactivated except for the support one.
I cannot reproduce the issue locally.

Website:
http://newsite.horizonstoragesheds.com/
Daygc0FS-bBo8iIfV

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=21&t=593950

**Comment by SlavaET** [comment]
@kary4 there is something wrong on his website, I cannot access the NextGen plugin settings even if Twenty Sixteen theme activated on his website, it fails with a different error though.

**Comment by SlavaET** [comment]
btw, line 1223 of `/includes/builder/functions.php` file only fires on front-end, because that function attached to `wp_footer` hook, so I assume there is an error in loading. Reinstall Wordpress maybe? :)

**Comment by kary4** [comment]
@SlavaET Thanks for checking. I think I checked the plugin with default wordpress theme. Strange, it really does not work :)  Okay, I'll let you know how it goes.
