### ISSUE TITLE
Blog Module :: Inconsistent Behavior With Sticky Posts

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#511]
### Problem:

>Our blog has a sticky post that the blog module insists on loading in addition to the specified number of posts. For example, if set to load 2 posts, it loads the stick post plus 2 more posts, for a total of 3. However, using the visual builder, any change to the settings for the module makes the sticky post disappear for the rest of the editing session. Then after exiting the visual builder, the sticky posts is displayed as before.
>
>1. I would like the behavior of the blog module in the visual builder to reflect the behavior of the live site.
>
>2. I would like to have an option in the blog module to ignore sticky posts.

**Comment by SlavaET** [comment]
@lots0logs can you reproduce this issue locally?
I tried, but no luck. For me it looks the same in FB and Front end. Also sticky post doesn't affect the number of posts in Blog module, if I set 2 - I see 2 posts including sticky, not 2 posts + sticky post.

**Comment by lots0logs** [comment]
@SlavaET Possibly related: #499

**Comment by timayhelen** [comment]
According to Yuriy it's not possible to fix this unfortunately.
