### ISSUE TITLE
Side navigation :: js error

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#516]
### Problem:

Uncaught TypeError: Cannot read property 'top' of undefined in custom.js line 820

### Steps To Reproduce:
1.  Enable side navigation
2.  Open VB
3.  Move your mouse over the section 
4. Try to scroll

`et_pb_scroll_` class disappear when you hover over the section

**Comment by Jronk** [comment]
Note, https://github.com/elegantthemes/submodule-builder/issues/1213 fixes the js error, however there is a enhancement/bug still needed which is that sections can be added/duplicated etc, and the side nav needs to be updated accordingly. New issue created for this : https://github.com/elegantthemes/Divi-Beta/issues/518
