### ISSUE TITLE
Slider Module :: CSS Parallax option causing enlarging images twice

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#517]
### Problem:

It seems this issue only with CSS Parallax option. The True Parallax works fine.

**Comment by timayhelen** [comment]
Images are set to background-size: cover, so they will extend the full width and height of the browser. Users can use true parallax mode if this isn't what they want.

**Comment by dm-chechik** [comment]
@timayhelen Thanks
