### ISSUE TITLE
FB :: Update page dot/side nav when sections added/removed

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#518]
### Problem:

When page dot navigation is in use in FB, you could add/remove sections, and the side nav does not get updated. For example, you could have 3 sections to begin with, and the side/dot nav would have 3 dots, but then add 4 new sections, there would still be 3 dots in the dot nav rather than 7.

**Comment by lots0logs** [comment]
I'm getting a bunch of errors in the console when using the dot navigation (clicking on the dots).

![2016-09-26_08-51-41-pm](https://cloud.githubusercontent.com/assets/4675662/18857633/3bf7d69a-842b-11e6-8eda-85c54a67d726.png)

**Comment by fikrirasyid** [comment]
@lots0logs can you share the layout you're using and screencast of how you did it? I tried replicating it but I can't replicate it so far:

![518-no-error-found](https://cloud.githubusercontent.com/assets/916442/18870680/035c95c6-84dc-11e6-8ddc-e05cd052c2ff.gif)

**Comment by timayhelen** [comment]
@fikrirasyid I have had this error before too. It's unrelated to the dot navigation most likely. Probably something to do with the header.

**Comment by lots0logs** [comment]
@fikrirasyid Its the Homepage Extended layout. I will test it again on a fresh copy of the repo just to rule out this being due to cache or user error (like being on the wrong branch perhaps haha)

**Comment by timayhelen** [comment]
@lots0logs It's unrelated, so open a new issue if you figure out what causes the error.
