### ISSUE TITLE
Builder Labels :: Not Visible

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#521]
### Problem:

Some users have reported that while in FB if they refresh the page and open any element settings, the labels doesn't appear:

https://drive.google.com/file/d/0B8PjD3Z_XQvuTFktZXVmVzcyeHM/view?usp=sharing

This video is from one of our customers, I think you guys will have to download it since it's in webm format.

**Comment by SlavaET** [comment]
I cannot reproduce this issue, I noticed it sometimes a while back when I was on Windows, but it's a random thing and I couldn't constantly reproduce it and it fixes itself when I resized the browser or try to inspect element to see what's going on. Probably some Chrome extension causes it. 
Also, it happened to me not only in Builder, but on other websites as well, so I'm pretty sure it's a Chrome related thing.
I haven't seen this issue on OS X at all.
@eduard-ungureanu can you please ask the customer to check the following:
- make sure he's on latest Chrome;
- check it in clean Chrome browser without extensions;
- check it in different browser ( FireFox for example ).

**Comment by eduard-ungureanu** [comment]
@SlavaET I know it's totally random issue, but I think it is still happening. I did ask the customer to check it's environment, I will update this as soon as I get a respond from him.

**Comment by timayhelen** [comment]
@eduard-ungureanu Please re-open this if you ever get more information on the issue.
