### ISSUE TITLE
 Divi visual editor doesn't display module padding

### ISSUE THREAD

**Issue by andreisnoopy** [elegantthemes/Divi-Beta#523]
A client asks if this feature is a bug or this is how it should work. I will quote him 
"When hovering over the borders of rows and modules, the Divi visual editor displays padding as a shaded area.

It does NOT display padding when hovering over the border of modules, though."

**Comment by timayhelen** [comment]
We have a different issue open for this. It will be added soon, maybe in the next ~2 versions.
