### ISSUE TITLE
Blog Grid Pagination Displayed Incorrectly In Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#527]
When adding a new Blog modules in Grid mode. the pagination often appears incorrectly. In this example I have the Wp Page-navi plugin installed. 

When you add a new blog module to a 1 column row, and only 2 posts are displayed, the pagination falls into the empty column:

![screen shot 2016-09-22 at 6 30 23 pm](https://cloud.githubusercontent.com/assets/3333028/18771325/d93bbb06-80f2-11e6-9417-f52bff1da058.png)

With sufficient posts the pagination does not fall onto the side as shown above, but it does not extend the full width of the row as it should. It gets bunched up onto one side:

![screen shot 2016-09-22 at 6 33 04 pm](https://cloud.githubusercontent.com/assets/3333028/18771344/03e510fa-80f3-11e6-994d-c33efdfea4d5.png)

It should look like this in both situations, as it does on the front-end:

![screen shot 2016-09-22 at 6 33 32 pm](https://cloud.githubusercontent.com/assets/3333028/18771348/1458cb8e-80f3-11e6-8c10-8c48b78f3aef.png)

**Comment by lots0logs** [comment]
@fikrirasyid The issue is still present when using Extra:

![2016-09-26_09-12-28-pm](https://cloud.githubusercontent.com/assets/4675662/18858087/296d3890-842f-11e6-8698-8f7d01768f29.png)

**Comment by timayhelen** [comment]
I think we can worry about Extra in a different PR. Currently WP Page Navi is completely unstyled in Extra.
