### ISSUE TITLE
Scroll doesn't work in Visual Builder when you edit a module

### ISSUE THREAD

**Issue by andreisnoopy** [elegantthemes/Divi-Beta#530]
### Steps To Reproduce:
1.  Create a text module (or any module with text)
2. Click on the text field to insert/remove a text
3. Try to scroll

**Comment by timayhelen** [comment]
@andreisnoopy I can't replicate this. Can you post a screencast?

**Comment by andreisnoopy** [comment]
I just updated to 3.0.8 and couldn't reproduce it no more. I will check with the client and see if he update and if the issue is still there. I will reply here after I recive an answer
