### ISSUE TITLE
Email Optin :: Doesn't work

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#531]
### Problem:

The Email Optin doesn't work on Windows 7, Firefox and IE 11, but it does work on Chrome:

The reason FF on Windows 7 show this error when the button is clicked:

<img width="960" alt="screen shot 2016-09-23 at 12 46 56 pm" src="https://cloud.githubusercontent.com/assets/1719735/18781852/41793aa6-818c-11e6-9589-568b9a341766.png">

The same form work on any other system / operating system no matter what browser is used.

**Comment by Anny85** [comment]
@eduard-ungureanu Are you sure the customer is using the latest version. I fixed it here: https://github.com/elegantthemes/submodule-builder/pull/1170

**Comment by eduard-ungureanu** [comment]
@Anny85 : that was a noob mistake, he is using the 3.0.2 version, I did ask the customer to update to the latest version. I'm sorry! We can close this!
