### ISSUE TITLE
Add Option To Completely Disable Google Maps

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#532]
Follow up of https://github.com/elegantthemes/Divi-Beta/issues/453#issuecomment-247219304. Rationale:

- In countries which bans Google services, VB wouldn't work
- If user choose to use plugin which uses Google Maps and enqueue its own Google Maps API script, things went wrong

**Comment by fikrirasyid** [comment]
This issue requires these three PRs to be merged:

- Divi: https://github.com/elegantthemes/Divi/pull/2555
- builder: https://github.com/elegantthemes/submodule-builder/pull/1224
- epanel: https://github.com/elegantthemes/submodule-epanel/pull/39

cc: @lots0logs

**Comment by lots0logs** [comment]
@fikrirasyid Please see my note on the Divi PR regarding the copy. Also note that I made a typo so it should begin with the following:

>Disable this option to remove **the** Google Maps API script

**Comment by fikrirasyid** [comment]
@lots0logs I've updated both PRs to incorporate your feedback:

- https://github.com/elegantthemes/Divi/pull/2555/commits/d688a8f132773a0527b493801552616eae1e443b
- https://github.com/elegantthemes/submodule-builder/pull/1224/commits/f9948b44e146c72b89be008e3915872d05364392

**Comment by timayhelen** [comment]
@fikrirasyid Just realized we need to add this option to Extra and the Divi Builder plugin, otherwise the warning will always appear.

**Comment by Jronk** [comment]
Ill add the option to Extra a the plugin

**Comment by fikrirasyid** [comment]
@timayhelen ah, you're right :|

@Jronk thanks! let us know once you've pushed the update to Extra and Divi Builder

**Comment by Jronk** [comment]
- [X] Added to Extra: https://github.com/elegantthemes/Extra/commit/80c277871f89c517be65e4bb203451a319e8c311
- [ ] Issue for it to be added to builder plugin, as the setting needs a lot more work to get implemented: https://github.com/elegantthemes/divi-builder/issues/541
