### ISSUE TITLE
Theme Customizer :: Change the row left / right padding

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#533]
### Problem:

When you go to Theme Customizer > Mobile Styles > and change the row height, it also change the default row left / right padding. 

### Steps To Reproduce:
1.  create a new page
2. import the layout (attached)
3. go to Theme Customizer > Mobile Styles
4. Change the default row height
5. the row's padding left / right will get lost.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: mac book pro

**Operating System**: OS Sierra

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuZ1doem5YYl9rMjQ/view?usp=sharing

**Link To Download Layout JSON File**:
[WPC Layout.json.zip](https://github.com/elegantthemes/Divi-Beta/files/489798/WPC.Layout.json.zip)

**Comment by uportnykh** [comment]
I could replicate the issue with Specialty Section Rows only. It works fine with normal rows.

**Comment by eduard-ungureanu** [comment]
@uportnykh I did tested again with the latest version with divi and with normal section it looks like the issue was resolved!
