### ISSUE TITLE
Adding custom exit button if admin bar is disabled

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#535]
### Problem:

This is quite interesting: https://elegantthemes.slack.com/archives/support/p1474479896000315. At this moment, exit to page or to backend builder relies to admin bar. Some people choose to disable admin bar. This causes an absence of exit link. We could probably detect for admin bar existence and adding custom exit link (possibly the exit door icon) if there's no admin bar.

![exit button](https://cloud.githubusercontent.com/assets/916442/18804414/b1ebd92c-8224-11e6-8cec-44fee2878c44.jpg)

**Comment by SlavaET** [comment]
@timayhelen Do we still need this button? if yes - how this button should look like and where to place it?
