### ISSUE TITLE
Visual Builder :: Save button doesn't work on visual builder

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#536]
### Problem:

I can't understand why the layout cannot be saved using Save button in divi 3.0.8, but it works good in the previous (3.0.7) version. Here is the error message:
```
TypeError: e is null
```
from the bundle.js file.

Website:
http://toilettage-montpellier.fr/?et_fb=1

### Additional Information:
I cannot reproduce the issue locally.
Right now there are two divi versions installed (divi - 3.0.8  and divi-test - 3.0.7). You can see it works in 3.0.7.

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=596879

**Comment by timayhelen** [comment]
Looks like people are saying it's due to Disabled Modules on the page. When they removed the disabled modules, saving worked again.

**Comment by timayhelen** [comment]
I tested on localhost and was able to save the page with a disabled module, but the module gets stripped from the page.

**Comment by timayhelen** [comment]
Ah it looks like modules that are disabled in all 3 locations don't appear in the Visual Builder, but they are still accessible in the BB. I can't re-create the error mentioned above.

**Comment by timayhelen** [comment]
Looks like the error occurs when you try to save a page with a disabled Section. Disabled modules work fine, but saving a page that contains a disabled section in the VB will cause the error.

**Comment by fikrirasyid** [comment]
@timayhelen what is the expected behaviour of disabled section? The latest version of Divi completely hide disabled section. Last time I remember, we only lowered down the opacity. causes the disabled module end up removed if this issue is fixed.
