### ISSUE TITLE
Fullwidth Menu :: Impossible to reach settings panel

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#538]
### Problem:

When Fullwidth menu in the top of the page there is now way to click on Module Settings panel. It is under the fixed main menu.

![image](https://cloud.githubusercontent.com/assets/20072036/18809445/f5e83aa8-8283-11e6-9c93-649d0d5095e4.png)

**Comment by lots0logs** [comment]
@dm-chechik I cannot reproduce this on the latest master. Its likely that it was fixed recently. We can reopen this if the issue persists in the next update version.
