### ISSUE TITLE
Plugin compatibility :: Paid Member Subscriptions :: Problem with custom fields

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#540]
### Problem:

It's a paid plugin, so unfortunately can't reproduce the issue. Here is the plugin page:
Paid Member Subscriptions

To get more info please refer to this ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=593533

**Comment by lots0logs** [comment]
@kary4 The issue with custom fields being deleted has already been fixed. Please asked them to ensure they are using the latest version and to let us know if the issue persists.

**Comment by uportnykh** [comment]
@lots0logs Actually we couldn't replicate the issue with custom fields being deleted, so we can try to replicate the issue with the plugin.

**Comment by lots0logs** [comment]
@uportnykh It looks like its working now. At least that's what the customer reported on the ticket. I'll let you decide if we still need to look into it :smiley:

**Comment by uportnykh** [comment]
I think we can close it then. Please, let us know if you some other clients will be having an issue with custom fields.
