### ISSUE TITLE
Plugin Compatibility :: Nested Calls To the_content() Are Not Performed Safely

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#545]
### Problem:
>Hi Dustin,
>
>Thank you for providing the Divi theme for further investigation. After evaluating the theme, it appears that the theme breaks WordPress' the_content filter process when certain modules (such as the "Blog" module) are used on a page.
>
>WordPress does not currently support nested filter calls of a currently-running filter (e.g. applying the_content filters within a function hooked into the_content). Since shortcodes (such as those used by the Divi theme) are processed in the the_content filter, applying the the_content filter within the shortcode handler steamrolls the already-running filter process, stopping all other functions hooked into that filter from running.
>
>To avoid this, the existing filter state needs to be temporarily saved before calling a function that applies the the_content filter (e.g. the_content(), the_excerpt(), etc.) from within a shortcode handler and then restored once the nested filter call has finished.
>
>Take a look at apply_filters() code for more details on its inner workings, and see here for details on an example of backing up the filter state (https://github.com/websharks/wp-snippets/pull/2) in another shortcode handler that was inadvertently stopping plugins hooked into the the_content filter from running.
>
>Thanks,

**Comment by fikrirasyid** [comment]
@lots0logs what is the context of this? Who reviewed it and why it happened? I'm not sure what causes this in the first place :thinking_face:

**Comment by fikrirasyid** [comment]
@lots0logs is it related to https://github.com/elegantthemes/Divi-Beta/issues/522#issuecomment-249395897?

**Comment by lots0logs** [comment]
@fikrirasyid No its not related to that one. Its an email from the developer of the Simple Lightbox plugin. They have received reports of compatibility issues and requested a copy of Divi to investigate. I provided them with a copy last week. They sent their findings today (which I copy/pasted above). That's all I know at this point. Though their findings sound legitimate so I think we need to look into it.

**Comment by lots0logs** [comment]
I will ask them for complete details on the exact issue in question and post back here as soon as they respond.

**Comment by fikrirasyid** [comment]
@lots0logs alright. I assume the plugin you're referencing is this, isn't it? https://wordpress.org/plugins/simple-lightbox/

Can you share me links to the thread where people complained about this? I'll take a look and start investigation for our side.

**Comment by lots0logs** [comment]
The reports were made to the plugin developer. The only thing I can find in our forum is related to a conflict with magnific popup (though surely that's not what this is)

**Comment by fikrirasyid** [comment]
Ah, that one out of the blue issue with no specific way to replicate it :facepalm:

**Comment by SlavaET** [comment]
@fikrirasyid keep in mind this ticket while you're looking into this issue - https://github.com/elegantthemes/Divi-Beta/issues/459

**Comment by fikrirasyid** [comment]
@SlavaET thanks for the hats up.

**Comment by fikrirasyid** [comment]
@lots0logs it appears that I couldn't catch any issue at all. Based on the description:

> After evaluating the theme, it appears that the theme breaks WordPress' the_content filter process when certain modules (such as the "Blog" module) are used on a page.

I assume that the issue would be around:

- page with module which uses the_content and simple plugin throws error
- simple plugin doesn't work in page builder

I tried various settings to make it throws error but none happens. I'll postpone this until clear steps to reproduce the issue have been provided.

**Comment by lots0logs** [comment]
@fikrirasyid 
>Hi,
>
>Here is an example of a report from a user: https://github.com/archetyped/slb-addons/issues/47
>
>Here are steps to reproduce the issue in Divi:
>
>Standard Functionality
>
>1. Install/Activate Simple Lightbox (https://wordpress.org/plugins/simple-lightbox/) plugin.
>
>* Note: the issue can be reproduced with a custom function that hooks into the_content (example (https://github.com/archetyped/simple-lightbox/issues/419#issuecomment-132779127) ), but using an existing plugin may be simpler.
>
>Create new page and edit with Divi's builder. 
>Add new Row. 
>Add Text module to the new row and insert a linked image from the media library, save page, and exit builder. 
>Clicking image link should display image in a lightbox.
>
>Reproducing Issue
>
>1. Open Divi builder and add a new Row. 
>2. Add Blog module to new row, save page, and exit builder (module defaults are fine). 
>3. Clicking on image link in previously-created Text module will now open image directly. 
>4. Removing the Blog module from the page allows the image link to be opened in a lightbox once again.
>
>Please let me know if you have any additional questions.
>

**Comment by SlavaET** [comment]
Just a note. We need to make sure this fix doesn't break compatibility with Yoast SEO plugin.

**Comment by fikrirasyid** [comment]
@SlavaET thanks for the heads up. I've checked how YOAST works on https://github.com/elegantthemes/submodule-builder/issues/1251 branch and it appears that (based on the AJAX call and its response) the plugin works as intended. FB works as expected too (ensuring that the issue which has been fixed at https://github.com/elegantthemes/Divi-Beta/issues/459 isn't reappeared)

**Comment by timayhelen** [comment]
It looks like content inside of Fullwidth Post Sliders is being handled differently that content inside of the Blog Module. 

When you choose to display "the_content" in the blog module, it strips out ET shortcodes but leaves in normal HTMl like H2, P, BR, etc. In the Post Slider, however, these become encoded:

![screen shot 2016-09-29 at 12 07 38 pm](https://cloud.githubusercontent.com/assets/3333028/18968323/56a1d23e-863d-11e6-8147-815534be51e7.png)

**Comment by uportnykh** [comment]
@timayhelen I've fixed it
