### ISSUE TITLE
Disabled Modules/Rows/Sections Break Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#548]
If a disabled module/row/section is on the page, it breaks the builder. The following error occurs when you attempt most actions, such as deleting a module:

![screen shot 2016-09-27 at 12 14 07 pm](https://cloud.githubusercontent.com/assets/3333028/18888211/34cfdd00-84ac-11e6-8130-96544be0e9e0.png)

**_You must save the page and refresh after disabling something to cause the cause the error._** 

Also, it appears that once the page has been saved, disabled rows & sections completely disappear. The current UI convention is to reduce their opacity. I think it may be related to the previous bug, since these disabled rows/sections are not rendering at all and likely causing the chain of errors the proceed. 

- [ ] Fix issue where disabled modules/rows/section break the builder.
- [ ] Render disabled modules/sections/rows with reduced opacity. This is how it works when you first disable something, but once you save and re-fresh the items do not appear it all. Could be related to issue #1.

**Comment by lots0logs** [comment]
@timayhelen Might be related: https://github.com/elegantthemes/Divi-Beta/issues/536#issuecomment-249372889

**Comment by timayhelen** [comment]
I can't replicate it now. I dono what happened, lol.
