### ISSUE TITLE
Global Modules Settings Modal background issue

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#55]
### Problem:
Background color of expand and dock buttons in Settings modal is incorrect for Global modules:
![image](https://cloud.githubusercontent.com/assets/3446682/17786587/52bc928c-65a7-11e6-902c-5ff21c686dc0.png)

### Steps To Reproduce:
1. Open Global module's settings
2. Check the header of Settings modal

**Comment by timayhelen** [comment]
@Anny85 This changes all buttons in the modal the green. That isn't what we want.

**Comment by Anny85** [comment]
@timayhelen hmm, let me take a look...

**Comment by timayhelen** [comment]
@Anny85 I pushed a fix.

**Comment by Anny85** [comment]
@timayhelen Ok, great
