### ISSUE TITLE
FB :: Overlaping icons issue

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#550]
### Problem:

![1](https://cloud.githubusercontent.com/assets/3352130/18893713/b998a3ee-8517-11e6-92dd-ffc6996a688f.png)
1. To replicate the issue add a row, define custom width to 370px (under row module settings).
2. Next add CTA module and define padding: 0; under cta custom css settings (main element).
3. Now enable Front End Builder and you'll see the problem.

Screen cast:
http://youtu.be/E3uDF1rpc6A?hd=1

**Comment by lots0logs** [comment]
@SlavaET I checked it with 3.0.12 and it has improved but let's see if we can improve it further.

![2016-10- 5_09-13-39-pm](https://cloud.githubusercontent.com/assets/4675662/19138346/d7005c2c-8b40-11e6-8c73-820a1c637f4b.png)

**Comment by SlavaET** [comment]
I found a way to improve the accessibility of short Module Settings popover within the narrow rows:
![popover-access](https://cloud.githubusercontent.com/assets/3446682/19682836/43711582-9ad1-11e6-9634-4cfff20c4f32.gif)

So, when you hover over the visible part of Settings Popover, then Row Settings will disappear and it'll be possible to access all the buttons. It works under the following conditions:
- Parent Row width < 520px;

**AND**

- The module is first and is `short` **or** The difference between the Row top and Module Top is less than 100px.

It should cover the most ( if not all ) the cases when Row Settings overflows the Module settings popover

@timayhelen what do you think about such an approach? Does it look ok to you?
@lots0logs I also fixed the issue with code module you mentioned here - https://github.com/elegantthemes/Divi-Beta/issues/298#issuecomment-251733778

**Comment by timayhelen** [comment]
I think we should think of a different solution, or make this solution a bit more targeted. I think this will happen a lot when it might not be necessary, and the behavior is also a bit unexpected. I would prefer a solution that doesn't change the hovering conventions that we already have in place.

**Comment by SlavaET** [comment]
Found a different solution:
![popover-access-2](https://cloud.githubusercontent.com/assets/3446682/19799185/1d71d644-9d17-11e6-97ac-047bb4dbf3ef.gif)

It dynamically checks whether the Row Settings popover covers the Module Settings popover or Add New Module button and adjust their position using the `margin-left`
@timayhelen does this solution look better?

**Comment by timayhelen** [comment]
@SlavaET I think we might want to love the buttons down instead of moving them to the right. It creates some weird situations when using other column structures. For example, here you can't access the first two module options:

![corrected](https://cloud.githubusercontent.com/assets/3333028/19818880/af7b35fa-9d06-11e6-8fbb-d629ecb6c4ec.gif)
