### ISSUE TITLE
Right click causes previous modal to open.

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#551]
### Problem:
If you open any modal that uses `modal/index.jsx`, click on a `tooltip-modal`, and then right click outside of the modal, 2 modals pop up.

### Steps To Reproduce:
1. Open History Modal
2. Open Portability Tooltip Modal
3. Right click outside modal.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Macbook Pro 15" Retina

**Operating System**: macOS

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
![image](https://cloud.githubusercontent.com/assets/6789067/18894095/c0dbc14c-84c5-11e6-865a-a9fc6cf20b3f.png)

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Looks like it actually opens up the modal for the item you right click on.
