### ISSUE TITLE
Roboto Light Front Doesn't Work In Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#552]
If you assign Roboto Light in the Visual Builder, the following error occurs:

> http://fonts.googleapis.com/css?family=Roboto+Light:100 Failed to load resource: the server responded with a status of 400 (Bad Request)

Once you save and go to the front-end, however, it works fine. We seem to enqueue the font differently on the front-end than we do in the Visual Builder, possibly because Roboto Light is actually just a low font-weight of Roboto.

**Comment by SlavaET** [comment]
@timayhelen fixed. I also found and fixed following issues in the Inline Editor and tinyMCE:
- inline editor content saves all the tinyMCE metadata;
- inline editor doesn't save correctly font names which contains more than one word ( `Amatic SC` for example ). So if you set the font, save page, reload VB, save page again, then you'll see that font is not applied on front-end;
- VB doesn't enqueue required inline fonts on module load. So if module was saved with custom fonts, then you refresh the VB you'll see that google fonts are not applied.

Below is an example of content edited using inline editor ( when the page loaded on front-end ).
Master Branch:
```
<span style="font-family: &quot;Amatic SC&quot;;" data-mce-style="font-family: 'Amatic SC';">some</span>
```
My branch with the fix:
```<span style="font-family: 'Amatic SC';">some</span>```
