### ISSUE TITLE
Theme Customizer :: Does not work in Multisite

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#558]
### Problem:

Can anyone check why divi theme customizer/module customizer does not work under multisite installation here http://kunden.ksk-agentur.de
It just shows white page and nothing else.
Screen cast:
http://youtu.be/foRmFLTw2dU?hd=1

Unfortunately I cannot reproduce the issue locally. It works good on my local server.
Ask me for support token if needed.

**Comment by lots0logs** [comment]
@kary4 Please see my message on Slack :smiley:
