### ISSUE TITLE
Code module :: Custom HTML

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#559]
### Steps To Reproduce:
1.  Add this code in code module in VB
`<div class="sub_header"><span><h2>Our Mission</h2></span></div>`

2.  Save
3. Open actual front end

Result

`<div class="sub_header"><span><br><h2>Our Mission</h2><p></p></span></div>`

**Comment by lots0logs** [comment]
@andrey-agp That isnt valid HTML. `<span>` elements cannot have block-level elements as children.

**Comment by andrey-agp** [comment]
@lots0logs Thanks. Yes it works with this code
`<div class="sub_header"><h2><span>Our Mission</span></h2></div>`
