### ISSUE TITLE
Full Width Sections Color Picker Alpha Slider Bug

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#56]
### Problem:

When you add a fullwidth module like header or menu, the color picker doesn't display correctly:

![test divi](https://cloud.githubusercontent.com/assets/16414613/17721208/667b10a6-6420-11e6-9679-b2d7406d1a6e.png)

### Steps To Reproduce:
1. Create a fullwidth section.
2. Add a fullwidth header or fullwidth menu modules.
3. Try using the color picker.

**Comment by fikrirasyid** [comment]
@timayhelen can you checked this on https://github.com/elegantthemes/submodule-builder/pull/945? I've checked it on https://github.com/elegantthemes/submodule-builder/pull/945 and it looks fixed on that branch.

**Comment by SlavaET** [comment]
It seems to work fine in the latest `1848-front-end-builder branch`
