### ISSUE TITLE
FB :: It is not clear to which unit applies the settings panel

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#560]
### Problem:

I've recorder the screencast showing the problem. It's all Blurb Modules.
http://screencast-o-matic.com/watch/cDQUIBjTX3

**Comment by timayhelen** [comment]
I don't think there is much we can do about this unfortunately. The alternative is to allow the module buttons to overlap the row buttons, which I think is a worse tradeoff.
