### ISSUE TITLE
Multi Site :: Domain Mapping

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#561]
### Problem:

Several users reported that using the Domain Mapping from WPMU dev plugin, prevent the front end builder to properly work.

### Steps To Reproduce:
1.  have a multi install wordpress
2. map each of your sub site using the above plugin 
3. activate the visual builder from one sub domain 
4. everything works until the sub site it get redirected to the mapping domain.

**Comment by uportnykh** [comment]
@eduard-ungureanu We can't replicate it. Can you send me the user's token via Slack?

**Comment by eduard-ungureanu** [comment]
@uportnykh sorry for the long delay, but I never get back from the client with the requested token, is it possible to reopen this topic, since I see other customer with the same issue and I will request a token.

**Comment by lots0logs** [comment]
@eduard-ungureanu We can reopen it when you receive the token from the other customer :wink:

**Comment by eduard-ungureanu** [comment]
@uportnykh , @lots0logs I finally get a response from the client. he is using the "official mapping plugin" which strange enough it says that it's not supported and maintained anymore, even if the plugin is present in the WordPress code:

https://codex.wordpress.org/Create_A_Network

and this is the plugin:
https://wordpress.org/plugins/wordpress-mu-domain-mapping/

Client keeps saying that the plugin is maintained, in the support forum by the Automatic team. Right now I'm waiting for he's token!

Thank you in advance
Best Regards.
