### ISSUE TITLE
Theme effects do not work in Visual Builder

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#563]
### Problem:

If you open a page inside FB the theme effects like fixed header shrinking or parallax do not work.
The parallax effect is working while you creating new section however after saving and reloading the page parallax effect dissapears.

**Comment by lots0logs** [comment]
@Anny85 Please see [my review](https://github.com/elegantthemes/Divi/pull/2572#pullrequestreview-2500782) on the PR. Thanks!

**Comment by timayhelen** [comment]
- [ ] When Vertical Navigation and Centered Inline Logo are enabled, the navigation jumps as you scroll down:

![vertical-nav](https://cloud.githubusercontent.com/assets/3333028/19049942/55c0df32-8961-11e6-8b18-906c26a59138.gif)

- [ ] Hide Navigation Before Scroll does not work in the VB.
