### ISSUE TITLE
Select module using arrow on add module tooltip

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#565]
### Problem:
I think it'd be really helpful if we can select module using arrow when selecting module on add module tooltip. The most possible scenario for this being useful is:

1. click add module button
2. it is automatically focused on filter input text
3. Keyword is being typed, and list of module is updated (shrunken)
4. Instead of picking up keypad or mouse and click the remaining modules like we do now, we can simply a) click arrow down to select the remaining module then click enter to select, b) or even directly click enter to select if there is only one module remains.

**Comment by timayhelen** [comment]
I like the idea of the first item on the list being selected automatically, so you can type in "Text" and press Enter to add a text module.

**Comment by fikrirasyid** [comment]
@timayhelen yeah, it is really desktop - like experience which feels really intuitive (҂'̀⌣'́)9

**Comment by lots0logs** [comment]
@fikrirasyid Whenever you type `tab` into the search field it narrows the results to `pricing table` and `tab` but pricing table is highlighted (ideally the tab would be highlighted instead). Not sure if there are any other cases where this might occur. Can we do anything about it?

**Comment by timayhelen** [comment]
@lots0logs @fikrirasyid I think we can address this in a different ticket, but I don't think it will be easy. We would need to integrate a legitimate search system. Right now we just match a string of text and exclude all items that don't include that text. Items remain listed in alphabetical order.

**Comment by lots0logs** [comment]
@timayhelen In that case all it needs is some style luv from you and then its good to go :+1:

**Comment by timayhelen** [comment]
@lots0logs Yeah I have been thinking about that...it's hard to make it look right for the Add New Section modal. I might remove styles completely from there.

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen yeah, it's a simple string matching search. It'd be nice to make it works in more contextual way, but I think it'd be more appropriate to be done on another ticket.

**Comment by timayhelen** [comment]
@fikrirasyid I think we should change this UX a bit. I think it's a great feature, but I also think that 99% of people will not know it exists. So for the most part, people will be opening up tooltips and they will just see that the first item on the list is a slightly different color and not know why. It's also a bit confusing when you are hovering over items on the list to select them with your mouse. It makes it look like two items are selected:

![screen shot 2016-10-20 at 2 07 48 pm](https://cloud.githubusercontent.com/assets/3333028/19578011/9e6f1be8-96ce-11e6-93d9-0952f207eeda.png)

So proposed that we keep the functionality, but make it a little less obvious by: 

1. Only apply the "selected" class when a) an arrow key has been pressed or b) when the search bar has been used. So when you first open the tooltip, nothing appears to be selected.
2. I think we should only allow one thing to appear to be "selected." So if you use the arrow keys to browser though some items, then you decide to move your mouse and selected something instead, when your mouse hover over the first item the "selected" class from the arrow keys is removed.  If you start using the arrow keys again, it gets added back, and if you start to move your mouse again to select something it gets removed again.

**Comment by fikrirasyid** [comment]
@timayhelen you're right. It shouldn't be visible by default (it should only be visible after key press / filtering) and there should only one select state exist. I'll have it updated.

**Comment by fikrirasyid** [comment]
@timayhelen I've incorporated your feedbacks at https://github.com/elegantthemes/submodule-builder/issues/1321. The experience of selecting module using hover and keyboard's arrow (which is less obvious now) has been unified:

![unified hover keyboard experience](https://cloud.githubusercontent.com/assets/916442/19589499/a46845ec-9796-11e6-812d-1b7c09f9f0a9.gif)

Here's what happens:

1. When add new tooltip is clicked, no item is selected
2. Hover as usual
3. If in the middle of hover you start to move using keyboard, it'll continue from the last item you hovered
4. If you filter, the first result is automatically selected so you can directly hit enter to select it.
