### ISSUE TITLE
Fullscreen menu remains open

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#566]
### Problem:

The issue appeаrs only under Firefox. If you go to any page from Fullscreen menu and click Back browser button the previous page will be shown with opened Fullscreen menu.

**Comment by Anny85** [comment]
@dm-chechik I couldn't replicate it in Firefox 48 on Mac and Windows. Can you check it on the demo site? https://www.elegantthemes.com/preview/Divi/fullwidth-menu/

**Comment by dm-chechik** [comment]
@Anny85 You should check Fullscreen menu not Fullwidth :)
