### ISSUE TITLE
Component custom css fields do not accept svg code

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#568]
### Problem:

The custom css fields do not accept css with svg values. For example this one

`background-image:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 1080 100" enable-background="new 0 0 1080 100" preserveAspectRatio="none"><polygon class="ps-head-triangle" points="0,0 1080,100 0,100" style="fill:rgba(0,0,0,1)"></polygon></svg>');`

The FB shows the chnages however after saving svg part is truncated.

**Comment by Jronk** [comment]
See PR review

**Comment by uportnykh** [comment]
I've fixed all issues
