### ISSUE TITLE
Visual Builder strips "\" from any text

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#569]
### Problem:

If for example you need to enter a widows file path something like: `C:\LB\Column_Form.xlsx` the visual buildler will strip the \ character leaving the path to be `C:LBColumn_Form.xlsx`, even if the path is wrap in `<code></code>`.

https://drive.google.com/file/d/0B8PjD3Z_XQvuZXl6RDBpb3ZxbHc/view?usp=sharing

**Comment by timayhelen** [comment]
@Anny85 This works for textarea content areas, like Text modules, but it doesn't work for normal inputs, such as Slider Titles.

**Comment by Anny85** [comment]
@timayhelen WordPress doesn't seem to allow us to use `\` in shortcode attributes values. So I'm afraid there's nothing we can do to fix it.

**Comment by eduard-ungureanu** [comment]
@Anny85 : the strange part is that if it is used when I create the page, and publish the page the `\` character shows, the problem is that if I do other changes to the page and update the page, the `\` is stripped out!

**Comment by Anny85** [comment]
@eduard-ungureanu I've fixed the issue with `\` character, used in shortcode content, so it fixes the issue that can be seen in the video you mentioned above. But it turns out that we can't fix it, if `\` is used in shortcode attribute ( Slider Titles etc. )

**Comment by eduard-ungureanu** [comment]
@Anny85 cool, that's great news!
Regarding using `\` in Slider Title, I don't really see who would use that. The client from where I get this, was using `\` to mark a file path like: `C:\desktop\file_name.png`
