### ISSUE TITLE
Font :: Lato Light doesn't load

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#570]
### Problem:

![screenshot_4](https://cloud.githubusercontent.com/assets/9657712/19031380/b9ce59fa-8975-11e6-9bca-7a73782900ca.png)

### Steps To Reproduce:
1.  Add Text module with text
2.  Select Lato light and check console
3. 
4.

**Comment by timayhelen** [comment]
This has been fixed already.
