### ISSUE TITLE
Display issues of the visual builder on Safari 8

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#571]
### Problem:

![bs_macyos_safari_8 0](https://cloud.githubusercontent.com/assets/16414613/19036269/b7ad49e2-8966-11e6-8a8d-51bdafb27ded.jpg)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
MAC
**Operating System**:
OS x Yosemite 
**Browser**:
Safari 8
**Screen Resolution**:
1600 x 721

**Comment by Anny85** [comment]
@timayhelen Flex doesn't work in Safari 8, it works fine in Safari 9 and 10 though.
http://caniuse.com/#feat=flexbox

Do you think we should replace flex with basic CSS code to fix it?

**Comment by timayhelen** [comment]
@Anny85 Let's not worry about it. We should instruct users to use a modern browser.
