### ISSUE TITLE
Text Module :: Line Height

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#573]
### Problem:

Using Visual Builder, add a text module, and set the line-height to be any value express in px. Then moving from the Visual Builder to Divi Builder, check the line-height of that particular text module, it will set to be 3px.

### Steps To Reproduce:
1.  add a text module
2. set it's line height to be something like 30px for desktop and 20px for mobile
3. leave the visual builder and enter to divi builder and check the line height, it will be set to be 3px.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:
Customers Screencast: http://recordit.co/k8HMdAeVbS

I did also being able to replicate this on 2 different servers using the latest version of Divi 3.0.10.

**Comment by Anny85** [comment]
@eduard-ungureanu Can you still replicate the issue?

**Comment by timayhelen** [comment]
@Anny85 I am able to replicate it using the steps he mentioned. 

1. Open VB
2. Add a text module
3. Set line height to 30px
4. Save
5. Check value in BB

**Comment by timayhelen** [comment]
It's actually this old issue that Slava has proposed a fix for. I am not sure if the fix is still relevant though since we never got around to reviewing it: https://github.com/elegantthemes/submodule-builder/issues/355

**Comment by Anny85** [comment]
I see. I'll check it out.

**Comment by eduard-ungureanu** [comment]
@Anny85 : yes I still can replicate it in the last version of Divi!

**Comment by lots0logs** [comment]
@Anny85 While testing this branch I noticed that the HTML that is output on the page (when viewed normally) is different depending on whether it was last saved in the VB or BB. In this specific case it doesnt cause any visible differences to the text  (on desktop view..will explain below) but really the end result should be the same regardless of which builder was used to save the page.

Following the steps to reproduce the issue provided by @timayhelen [here](https://github.com/elegantthemes/Divi-Beta/issues/573#issuecomment-251730250), the resulting HTML (from saving the page with the VB) was:
```html
<div class="et_pb_text et_pb_module et_pb_bg_layout_light et_pb_text_align_left  et_pb_text_0">
				
<p>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;<span>Fixed the issue with incorrect range settings in BB, when value is entered manually</span></span></span></span></span></span></p>

			</div>
```
After saving the page in the BB the HTML output correctly as:
```html
<div class="et_pb_text et_pb_module et_pb_bg_layout_light et_pb_text_align_left  et_pb_text_0">
				
<p>Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually.&nbsp;Fixed the issue with incorrect range settings in BB, when value is entered manually</p>

			</div>
```
Regardless of which builder is used to save the page, when you specify a custom value for Tablets it does not get applied. Instead the value specified for mobile is what ultimately applies to tablets.

**Comment by Anny85** [comment]
@lots0logs We can't replicate the issue with different resulting HTML. I don't think this fix can cause such issues. Can you create a new issue for it and provide the exact content you put into the Text Module?
