### ISSUE TITLE
Content refreshing on heartbeat when it shouldn't be

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#575]
### Problem:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=600939

There are 2 problems:

A. The heartbeat external modification checker should only be for builder, and should not be working during non builder.
B. The heartbeat was detecting a external modification on a new post/page, (which was actually just the first auto-save) and then trying to update the content to: ''.
### Steps To Reproduce:

Scenario A:
1. Add new page
2. Add content especially with several line breaks between paragraphs
3. Add a title to the page, then blur focus of the title field
4. Wait approx up to 30 seconds and the content will botch
![heartbeat-botch-scenario-a](https://cloud.githubusercontent.com/assets/1163441/19087552/4498516a-8a27-11e6-9422-6bccbefe90dd.gif)

Scenario B:
1. Add new page
2. Turn on builder
3. Click load from library
4. Load "Product Features"
5. Add a title to the page, then blur focus of the title field
6. Wait approx up to 30 seconds and the content and builder will botch
![heartbeat-botch-scenario-b](https://cloud.githubusercontent.com/assets/1163441/19087586/65a1a10e-8a27-11e6-9781-dded31320ab8.gif)

**Comment by Jronk** [comment]
reopening to keep working on the https://github.com/elegantthemes/submodule-builder/issues/1267 solution

**Comment by Jronk** [comment]
https://github.com/elegantthemes/submodule-builder/pull/1267 is now ready

**Comment by lots0logs** [comment]
@Jronk Works great in my testing. Though I think that once customers see the feature in action they will naturally expect that it works both ways (If BB saves the page then the FB would update). Not sure if this was already discussed so just thought I would mention it :grimacing:

**Comment by timayhelen** [comment]
@Jronk Is that something we can add?

**Comment by Jronk** [comment]
yes, I already paved the way for this, and since I am also working on https://github.com/elegantthemes/Divi-Beta/issues/349, I am trying to connect those dots to make it work both ways. What I am afraid of, is customers getting too cozy with this. I feel comfortable offering this feature under the basic use case that it is preventing a mistake (like modifying content and saving via FB, then saving the BB, causing BB to stomp the FB save). The main reason I dont want to put this particular feature on much of a pedestal is the 30 sec lag of the sync, for the heartbeat duration, which is plenty of time for you to still make the aforementioned mistake and cause a stomp. So, to clarify, im down for this feature, and making it work both ways, but the only way to truly make it a polished and rock like feature would be to decrease the heartbeat delay, like down to 3-5 seconds, and implement a actual lock on one while using the other, so that during unsaved changes in FB, the BB gets a overlay and modal saying its locked, and vise versa when BB is in use with unsaved changes the FB gets overlay'ed with modal saying editing is occurring in BB.

**Comment by Jronk** [comment]
![autosave flowchart](https://cloud.githubusercontent.com/assets/1163441/20019438/8ab0a808-a289-11e6-93af-27d24562acba.png)

**Comment by Jronk** [comment]
See #349
