### ISSUE TITLE
FB :: Unwanted Modal's Tab Switching Shortcut Behaviour

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#576]
### Problem:

Pressing <kbd>Tab</kbd> to switch between modal's tabs causes inability to move between padding / margin's inputs:

![tabs shortcut issue](https://cloud.githubusercontent.com/assets/916442/19096422/7468d5a0-8ac6-11e6-9d8c-d0e094d872ad.jpg)

I personally feel disoriented when I'm at one of the padding inputs and pressing tabs moves me to other tabs instead of moving the cursor to the next input. I think it needs additional key to be triggered,  probably <kbd>option</kbd> + <kbd>tab</kbd>

**Comment by timayhelen** [comment]
@fikrirasyid Can we make it so that tab goes to the next input whenever you are currently clicked into an input? If you aren't currently typing inside of an input, then tab will bring you to the next tab.
