### ISSUE TITLE
Implement ETBuilderComponent Class To Reduce Boilerplate Code In Components

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#58]
[2491-auto-bind-this-for-component-class-methods](https://github.com/elegantthemes/submodule-builder/tree/2491-auto-bind-this-for-component-class-methods)
### React.createClass() -> ES6 Conversions Remaining
- [x] select-fonticon.jsx  (1 usage found)
- [x] select-fontstyle.jsx  (1 usage found)
- [x] select-option.jsx  (1 usage found)
- [x] select-yesno.jsx  (1 usage found)
- [ ] textarea.jsx  (1 usage found)
- [ ] tinymce.jsx  (1 usage found)
- [ ] upload.jsx  (1 usage found)
- [ ] upload-gallery.jsx  (1 usage found)
- [ ] TinyMCE.js  (1 usage found)
- [ ] right-click-item.jsx  (1 usage found)
- [ ] right-click.jsx  (1 usage found)
### Peer Reviews

Details to come...

**Comment by lots0logs** [comment]
Related: #57
