### ISSUE TITLE
Divi 4 - Static CSS Cache Generation Issue with Custom Post Types

### ISSUE THREAD

**Issue by marsronny** [elegantthemes/Divi-Beta#58]
<img width="1352" alt="Bildschirmfoto 2024-03-19 um 12 37 12" src="https://github.com/elegantthemes/Divi-Beta/assets/67509236/efc21463-d1eb-42e5-96ca-d16ad3f5a93c">
<img width="1133" alt="Bildschirmfoto 2024-03-19 um 12 39 00" src="https://github.com/elegantthemes/Divi-Beta/assets/67509236/01f2cec8-4ce9-4928-8cba-32908928c6a0">

The founder of Divi Pixel says "it's a Divi thing" that the Static CSS Cache Generation causes layout issues.
I'm not an expert nor programmer but I'm desperately looking for a solution for this layout issue that I'm facing for already 5 months. 
It occasionally happens when changing something in the layout or just editing anything on the website. It just happens with the Divi Pixel Popup Maker which seems to use Custom Post Types (CPT).

Divi Pixel Support and the ET Divi Support are not able to fix this issue.

I'm willing to provide more information if needed and I'm sorry for that unprofessional bug report.

Clearing the Divi Static CSS Cache temporarily fixes the problem but after using the search or changing anything on the Divi site, lets the issue return.

**Comment by VladET** [comment]
@marsronny Apologies for the delay. I reached out to you via email through our Support system. Let's connect there.
