### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#581]
### Problem:

Can anyone take a look the following websites. It's not possible to update divi here:

http://tabernanorteysur.es

www.bonoturisticocordoba.com

There is no any updates notification. Right now it's divi 3.0.5. installed. Ask me for a token if you need. 
### Additional Information:

**Divi theme folder is not renamed**:

**Style.css file looks good**:

**Latest wordpress version**:

I have no idea what else I can check.

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=591010&start=20

**Comment by abhi-sharm** [comment]
I have seen couple of tickets like this especially after Divi 3.0 , this is one more ticket where customer used to get the notifications in past but they are not getting notification after they updated to a newer version manually.  I have the token if needed  https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=596421&start=10

**Comment by lots0logs** [comment]
@abhi-sharm That customer is running PHP 5.3. Ask them to request the latest PHP from their hosting provider. It will resolve the issue for now.

**Comment by uportnykh** [comment]
@abhi-sharm You can send me the token and FTP login details, I'll take a closer look. Please, ask him to email you FTP login details, instead of using PMs.

**Comment by abhi-sharm** [comment]
@lots0logs : Asked the customer to update PHP , thanks for pointing out , i should have checked that part already.

@uportnykh : I have asked them if the issue persists even after updating PHP, they can send the ftp details to my email id , i will forward to you as soon as i receive, For now sending the token on slack

**Comment by abhi-sharm** [comment]
@lots0logs , @uportnykh  - It worked for them after updating PHP. Thanks

**Comment by kary4** [comment]
Here is a new problem with updates, though it's Extra theme, but I think the issue might be related. Let me know if I should open an issue under Extra repository. Here http://www.secret-ingredient.ru/  it's wordpress 5.6.25 version, correct theme folder name and style.css file. Update notifications still don't appear. Ask me for a token if you need.

**Comment by lots0logs** [comment]
@kary4 Could you send me the token? Thanks.

**Comment by uportnykh** [comment]
@lots0logs I'm looking into it

**Comment by kary4** [comment]
Can we also check this website: http://www.investtech.com.br
It's the same problem.
