### ISSUE TITLE
Button background styles in the customizer are now overriding module buttons styles

### ISSUE THREAD

**Issue by uportnykh** [elegantthemes/Divi-Beta#583]

**Comment by lots0logs** [comment]
@uportnykh The background color for module buttons doesn't show in the VB. The other button styles work properly. All of them seem to work properly on the frontend website (including the background color).

![2016-10- 5_12-20-50-pm](https://cloud.githubusercontent.com/assets/4675662/19124012/ee049d4c-8af6-11e6-9740-6b17784d0477.png)
