### ISSUE TITLE
BB :: Global module saving when it shouldn't

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#584]
### Problem:

I noticed that there is a logic problem with saving global module, its thinking a module is global when it isn't firing a pointless ajax save call that gets ignored/bailed on the server.

### Steps To Reproduce:
1.  Create some layout
2. add a normal text module
3. clone the text module
4. notice the ajax call, and more importantly missing the post_id POST arg

### Code steps that are occuring
1. `pasteAfter()` called, which calls: 
```
// Update global module
this.updateGlobalModule();
```
then..
2. in `updateGlobalModule`:
```
if ( ! ET_PageBuilder_Layout.is_global( this.model ) ) {
```
passes, when it should not. Notice this logic says "not is global", which makes `et_pb_update_global_template` get called.
then...
3. in `et_pb_update_global_template()`, it looks for 
```
post_id = global_module_view.model.get( 'et_pb_global_module' ),
```
but `post_id` will be undefined
4. the ajax call to action: `et_pb_update_layout`, will be processed by `et_pb_update_layout()` in `core.php`.

it checks for:
```
if ( '' !== $post_id ) {
```
which is addressing the last minute non-saving of the module, but then the ajax call was pointless. when the `if ( '' !== post_id ) {` could have been checked prior to the ajax call. For example:
```
		function et_pb_update_global_template( global_module_cid ) {
			var global_module_view           = ET_PageBuilder_Layout.getView( global_module_cid ),
				post_id                      = global_module_view.model.get( 'et_pb_global_module' ),
				layout_type                  = global_module_view.model.get( 'type' );
				layout_type_updated          = 'row_inner' === layout_type ? 'row' : layout_type,
				template_shortcode           = ET_PageBuilder_App.generateCompleteShortcode( global_module_cid, layout_type_updated, 'ignore_global' );

				if ( 'row_inner' === layout_type ) {
					template_shortcode = template_shortcode.replace( /et_pb_row_inner/g, 'et_pb_row' );
					template_shortcode = template_shortcode.replace( /et_pb_column_inner/g, 'et_pb_column' );
				}

			if ( _.isUndefined( post_id ) ) {
				return false;
			}

			$.ajax( {
				type: "POST",
				url: et_pb_options.ajaxurl,
				data:
				{
					action : 'et_pb_update_layout',
					et_admin_load_nonce : et_pb_options.et_admin_load_nonce,
					et_layout_content : template_shortcode,
					et_template_post_id : post_id,
				}
			} );
		}
```

**Comment by SlavaET** [comment]
It was working that way from the beginning when we introduced the global modules and this logic wasn't updated in 3.0. So probably we should move this issue from `Divi-Beta` to `Divi`.

We can fix it with High Priority right now of course, just wanted to mention that it's not the 3.0 bug.

**Comment by Jronk** [comment]
@SlavaET thanks for taking care of this, I know it has been around for a while, but a new addition coming to FB and BB is relying on the WP heartbeat, which is a sensitive thing for weak-sauce servers out there, so when I noticed this ajax abuse going on and wanted to shore it up. I want to free up as much resources as we can to squeeze in all the real and needed ajax calls we want/need to be making. So, thanks!
