### ISSUE TITLE
Blog module :: Caption Shortcode Does Not Work Correctly

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#586]
### Problem:

Wordpress Caption shortcode does not work correctly in the latest divi version, but it works good in older one. Please check the screen cast below:
http://youtu.be/w3q-0OYAvlI?hd=1

### Steps To Reproduce:
1.  Add the following shortcode (replace IMG URL) to a post page using text module:
```
[caption id="attachment_6" align="alignright" width="300"]<img src="http://localhost/wp-content/uploads/2010/07/800px-Great_Wave_off_Kanagawa2-300x205.jpg" alt="Kanagawa" title="The Great Wave" width="300" height="205" class="size-medium wp-image-6" /> The Great Wave[/caption]
```
2. Then open a page and add a blog module that includes the post where you added the changes in the previous step.
3. Preview the page.

I was able to reproduce the issue locally.

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=601052

**Comment by lots0logs** [comment]
@Anny85 I found some problems with this solution: 
![2016-10-12_03-26-51-pm](https://cloud.githubusercontent.com/assets/4675662/19326576/b9fe6f92-9090-11e6-930e-760b2ec2fd35.png)

![screencapture-et-falgout-us-divi-1476304065619](https://cloud.githubusercontent.com/assets/4675662/19326583/c1cdadc8-9090-11e6-84d2-cdcef27d56cc.jpg)

**Comment by Anny85** [comment]
@lots0logs I've fixed it
