### ISSUE TITLE
Fullwidth Slider :: Background shifts when True Parallax is enabled

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#587]
### Problem:

The problem appears in the second, third, etc. slide. It's difficult to explain however I've recorded the screencast. 
http://screencast-o-matic.com/watch/cD6h3njvId

**Comment by lots0logs** [comment]
@dm-chechik What is the URL to that page?

**Comment by dm-chechik** [comment]
@lots0logs Dustin, you can check the issue on the customer site http://www.realfeel.com.au/

**Comment by lots0logs** [comment]
@dm-chechik Please ask the customer to update to the latest version and let us know if the issue persists.

**Comment by dm-chechik** [comment]
@lots0logs I've checked on my local installation under 3.0.14. The issue persists
