### ISSUE TITLE
Add Copy/Paste Styles feature

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#589]

**Comment by SlavaET** [comment]
- Added Copy/Paste style into Right click menu
- Added Copy/Paste style shortcuts:

<kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>C</kbd> - Copy styles

<kbd>Alt</kbd> + <kbd>Super</kbd> + <kbd>V</kbd> - Paste styles

**Comment by lots0logs** [comment]
@timayhelen The two key combos for the shortcuts are pretty inconvenient to press. I think it's more natural if key combos flow from left to right. So in this case, it'd be <kbd>Super</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd>  What do you think?

**Comment by timayhelen** [comment]
@lots0logs It's opposite on Mac. Alt - Cmd - C is the natural direction.

**Comment by lots0logs** [comment]
:facepalm: ...you win! lol :wink:
