### ISSUE TITLE
Save Changes prompt alignment issues

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#590]
### Problem:

![image](https://cloud.githubusercontent.com/assets/3446682/19143314/e9247a1c-8bc4-11e6-8daf-f397a4b74a12.png)

### Steps To Reproduce:
1. Open page in VB;
2. Make any change;
3. Click `Exit Visual Builder` button in Admin Bar;
4. Check the header of opened modal.

**Comment by timayhelen** [comment]
@SlavaET do you have core running on the latest master? The modal doesn't look right.

**Comment by SlavaET** [comment]
Ah, totally forgot to update the core.
