### ISSUE TITLE
Undo Doesn't Update Global Modules

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#596]
Let's say you have a Global Section on the page with 4 blurb modules. If you delete any of the blurbs, it automatically updates the global module in the database even if you don't save the page. If you delete something by mistake, and then Undo the change, the item gets put back put the global item is not updated in the database. So if you accidentally delete something in a global module there is no way to get it back.

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated your feedback at https://github.com/elegantthemes/submodule-builder/pull/1316/commits/a90cffc8a7aeac89bdb927ae607dbc754ec2b34a
