### ISSUE TITLE
Font Color not working in IE

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#597]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=601754&p=3315958&hilit=visual+builder#p3315958

We should check the Inline Editor and Module options.

**Comment by SlavaET** [comment]
I tested Font Options in IE11 and Edge browser and I found several issues in the Color Picker from Inline editor. Other color options from modules work fine and I didn't notice any issues. This is what I found:
1) Edge Browser. Color is not changing if you select some text and try to set the `hex` color using the Inline Editor. `rgba` colors work fine, also it works fine with `hex` values if you do not select any text and just place the cursor inside the editor area:
![edge-color-issue](https://cloud.githubusercontent.com/assets/3446682/19432795/d5c2a804-947f-11e6-87ed-d082d9ea4e92.gif)

2) IE11 Browser. Several issues there:
- js Warning appears in console if you open the Color Picker from Inline Editor
- Color picker doesn't work after you closed it and open again in different place
![ie11-color-issue](https://cloud.githubusercontent.com/assets/3446682/19433164/6d714830-9481-11e6-9c4d-97b3ef2a6be7.gif)

I fixed the above issues in my PR.
