### ISSUE TITLE
FB :: Right Click menu doesn't work correctly on Rows inside Specialty Sections

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#602]
### Problem:

Right Click menu doesn't display correct items if you click on Row inside the Specialty section or on any module inside that row:
![specialty-right-click](https://cloud.githubusercontent.com/assets/3446682/19187561/ee6890a0-8cad-11e6-9b73-0cad3cc10f22.gif)

### Steps To Reproduce:
1. Open Visual Builder on page with specialty section containing a row with some modules;
2. Right click on the Row inside specialty Section;
3. Right click on the Module inside the Row from step no. 2.

**Comment by timayhelen** [comment]
@SlavaET This seems to be working for me now. Does it still not work for you?

**Comment by SlavaET** [comment]
Yeah, seems to work fine in the latest master
