### ISSUE TITLE
Inability to use the global modules on multi language sites

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#606]
### Problem:

I think we should consider the ability to use Global Modules on multi language sites. For example with WPML plugin. Right now you should create different Global Module for each language. It's inconvenient

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/Divi #2585](https://github.com/elegantthemes/Divi/issues/2585) via [**ZenHub**](https://www.zenhub.com/)
