### ISSUE TITLE
Sliders Don't Resize Height In Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#607]
On the front end, if you have a slider with slides of two different heights, the smaller of the two slides inherits the height of the tallest slide. This way all slides have a uniform height and there is no jumping when flipping through each slide. This doesn't happen in the VB, however.

**Comment by SlavaET** [comment]
@timayhelen I was able to reproduce this issue only in Post Slider and Fullwidth Post Slider modules. Fixed it there.

**Comment by lots0logs** [comment]
@SlavaET I'm still seeing the issue on the post slider module (non-fullwidth):

![2016-10-21_14-39](https://cloud.githubusercontent.com/assets/4675662/19609396/86e662fa-979c-11e6-9c62-14d0748e5ebc.gif)

**Comment by SlavaET** [comment]
@lots0logs can you please export and share the layout of that page? I cannot reproduce it locally.

**Comment by timayhelen** [comment]
@lots0logs @SlavaET It actually occurs on the front end as well. It looks like slides that are placed into non 1 column rows do not have their height synced. I am not sure why, but you can see it in our live demo:

https://www.elegantthemes.com/preview/Divi/slider/

I think it would be better to have sliders in smaller columns work the same way as they do in fullwidth and 1 column rows.

**Comment by SlavaET** [comment]
Fixed.

**Comment by lots0logs** [comment]
@SlavaET The slide content isn't properly positioned for all slides (except the one with the largest height). This happens in the VB and on the frontend page. 

![2016-10-24_02-02-35-pm](https://cloud.githubusercontent.com/assets/4675662/19659916/71978f42-99f3-11e6-8749-3bcc8c6197a1.png)

I also noticed something strange in the VB:
![2016-10-24 14-05](https://cloud.githubusercontent.com/assets/4675662/19660054/048b4a28-99f4-11e6-85cf-533d825097fc.gif)

Notice the white space between the section's border and the slide background. I'm not sure why it appears but if you scroll while that whitespace is there then the issue occurs as shown in the screencast. If I switch to the other slide in the slider the white space goes away and the issue doesn't occur.

**Comment by SlavaET** [comment]
@lots0logs these 2 issues are not related to the Slider Resizing fix actually :)
Anyway, I fixed them both in my PR. Here are some comments:
1) ```The slide content isn't properly positioned for all slides (except the one with the largest height). This happens in the VB and on the frontend page.```
I fixed it using the `display: table;` and `vertical-align: middle;` properties. It works perfectly to center the content inside the slider and it works in all the modern browsers ( even in IE8 ). But we're changing the `display` property for the content div inside sliders and defeault alignment which may affect some custom CSS which our customers may use for slider. @timayhelen what do you think? Is it fine to add this fix and change the sliders content default alignment?
2) ```Parallax issue in slider```. I was able to reproduce this issue on both VB and Frontend when CSS parallax used for the slider. Fixed it.

**Comment by lots0logs** [comment]
I think the change to `display: table;` will be fine. I did some googling to see if there could be any side-affects that I hadn't considered and couldn't find anything sooo, LGTM! :+1:
