### ISSUE TITLE
Help Modal

### ISSUE THREAD

**Issue by andyhqtran** [elegantthemes/Divi-Beta#608]
#### Keyboard Shortcut (#449)
- [ ] Open Modal - Hold down <kbd>Super</kbd> for 3 second opens up modal
- [ ] Close Modal - Press <kbd>ESC</kbd>
#### Notes
- [ ] Video should contain icon that indicates it can pop out.
- [x] Video should pop out and be able to snap to corners of the page with an adjustable opacity.
- [x] Modal should have a close button in the header and footer.
- [ ] Modal can stay open while other modals are active.
- [ ] Modal should reuse the same component.

**Comment by fikrirasyid** [comment]
We actually already have help shortcut, it is <kbd>/</kbd> and  <kbd>?</kbd>. However it is intentionally disabled on current master as we haven't finished all the help list. See: https://github.com/elegantthemes/submodule-builder/blob/master/frontend-builder/app/components/et-builder-root.jsx#L1235 Removing the comment block will re-enable this shortcut.

cc: @timayhelen.

**Comment by andyhqtran** [comment]
@Jronk this still needs to be looked at to see why the video resizing isn't updating properly.

**Comment by andyhqtran** [comment]
I will be taking a second tackle at this. @Jronk I'll keep you posted if I can find the solution.
