### ISSUE TITLE
Unable to edit modules in Zoomed Out Mode

### ISSUE THREAD

**Issue by bpitts82** [elegantthemes/Divi-Beta#61]
### Problem:

In zoomed out mode I added a new layout and cleared current layout using the bottom menu.  Upon doing this, I lost the ability to add new modules and go into the settings of existing modules.  

### Steps To Reproduce:
1.  Started with page template and then opened bottom editor - switched to zoom out mode
2.  Added new layout and cleared current layout (added team layout from default layouts)
3.  Closed bottom editor
4.  No editing functions were available (only able to change margins and text)
5.  Couldn't add any new modules or go into the settings of existing modules

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:  iMac

**Operating System**: OSX

**Browser**: Safari

**Screen Resolution**: iMac (5120 x 2880)

**Screenshots**: 
<img width="865" alt="screen shot 2016-08-18 at 8 23 02 pm" src="https://cloud.githubusercontent.com/assets/3269673/17794911/a035f182-6581-11e6-994b-971dc62fd5a1.png">

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Thanks, I have opened a new issue about this that better addresses what needs to be done: 

https://github.com/elegantthemes/Divi-Beta/issues/62

This actually started as a design choice, since the zoomed out mode would have affected the settings modal and made it impossible to edit modules. This is no longer the case actually, so we can just add those buttons back.
