### ISSUE TITLE
Added remaining VB's module shortcuts

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#610]
This is faux issue for VB's module shortcuts listed on https://github.com/elegantthemes/Divi-Beta/issues/449. This faux issue is added for easier status tracking.

For more info, see: ~~https://github.com/elegantthemes/submodule-builder/pull/1292~~.

Update: this is the correct PR: https://github.com/elegantthemes/submodule-builder/pull/1302

**Comment by timayhelen** [comment]
@fikrirasyid I notice that when I try to increase row and section padding using r + up/down or s + up/down, the page scrolls up and down. This is because the up and down arrow keys typically trigger page scroll on most browser. Can we disable this when r or s is being held down?

**Comment by fikrirasyid** [comment]
@timayhelen did you press the <kbd>⬆️</kbd>/<kbd>⬇️</kbd> or <kbd>r</kbd>/<kbd>s</kbd> first? In my test, if you press the <kbd>r</kbd>/<kbd>s</kbd> first, the moment you press the up/down arrows, the page scroll is already disabled. Things would be different if the up/down is pressed first. 

Disabling page scroll when <kbd>r</kbd> or <kbd>s</kbd>being held down wouldn't avoid the first scroll when being done tho; Typically, held down is detected by how long the keypress is done (700ms or longer). After the long keypress is detected, the scroll can be avoided. But before the long keypress is detected, the scroll will still happen, possibly one or two jumps-ish.

**Comment by fikrirasyid** [comment]
@timayhelen I'm curious: do your layout is longer than the screen's height? I might look into different things because my layout is longer than the screen's height 🤔

**Comment by timayhelen** [comment]
@fikrirasyid I pressed R and S first. I even tried holding down R for 2 seconds and then pressing the down arrow. It still scrolls the page.

**Comment by fikrirasyid** [comment]
@timayhelen noted. I'm currently taking a look at it.

**Comment by timayhelen** [comment]
@fikrirasyid Another thing, we shouldn't allow padding values to go negative. If you press Alt + S + Arrow after it reaches 0px padding, it continues into the negatives. 
![screen shot 2016-10-10 at 5 40 55 pm](https://cloud.githubusercontent.com/assets/3333028/19255247/cabd804c-8f10-11e6-8f4a-e0bb5b0436b0.png)

**Comment by fikrirasyid** [comment]
@timayhelen noted. I'll have it fixed as well 👍

**Comment by fikrirasyid** [comment]
@timayhelen before you try changing the row's height at https://github.com/elegantthemes/Divi-Beta/issues/610#issuecomment-252781911, did you previously press command button? I discovered another issue with how keyup & keydown perform. This might / might not be related to the issue you mentioned

**Comment by timayhelen** [comment]
@fikrirasyid I didn't do anything else. Just loaded the builder, hoevered over something, held down R and then press arrow keys.

**Comment by fikrirasyid** [comment]
Noted. Thanks for clarifying it. It isn't related then.

**Comment by fikrirasyid** [comment]
@timayhelen can you take a look at `449-add-power-user-features-3.1` branch and see whether the unwanted scroll and negative padding issue have been fixed? If the issue remains, can you take a screencast of it? Thanks.

Note: as I've explained on Slack at https://elegantthemes.slack.com/archives/development/p1476182454000026, I mistakenly merged this branch to `master`, so this PR is no longer used since it can't be un-merged. The correct PR for this issue is now located at https://github.com/elegantthemes/submodule-builder/pull/1302. The branch name is: `449-add-power-user-features-3.1`

**Comment by timayhelen** [comment]
@fikrirasyid It still causes the page to scroll down for me. Also, it looks like you Ctrl + R / Cmd + R no longer works to refresh the page in this branch.

**Comment by fikrirasyid** [comment]
Can you make a screencast of it? i'm suspecting particular kind of scroll involving front end's js, but It'd be very helping to have it clarified

Get Outlook for iOS




On Wed, Oct 12, 2016 at 1:27 AM +0700, "Nick Roach" <notifications@github.com> wrote:












@fikrirasyid It still causes the page to scroll down for me. Also, it looks like you Ctrl + R / Cmd + R no longer works to refresh the page in this branch.

**Comment by fikrirasyid** [comment]
@timayhelen weird, it totally doesn't happening on me :|

Anyway, have you updated to Sierra?

**Comment by timayhelen** [comment]
@fikrirasyid No I haven't upgrade yet. I will try. 

Can you fix the issue with Cmd + R / Ctrl + R not refreshing the page?

**Comment by timayhelen** [comment]
I also notice that if I open and closed a settings modal, and then press R + Down the page does not scroll.

**Comment by fikrirasyid** [comment]
@timayhelen i haven't updated to sierra as well, I thought the issue exists on sierra only since I don't find this behaviour on el capitan 🤔 

Sure, I'll have it fixed as well.

**Comment by timayhelen** [comment]
@fikrirasyid Well, updating to series didn't help regardless, lol.

**Comment by fikrirasyid** [comment]
@timayhelen it was wild guess tho 😅

**Comment by fikrirasyid** [comment]
@timayhelen I've fixed the <kbd>super</kbd> + <kbd>s</kbd> and the unwanted scroll upon modifying section/row's padding using shortcut issues. To check the patch, you need to switch builder and Divi to these branches:

- Divi PR branch: `449-add-power-user-features-3.1`. See: https://github.com/elegantthemes/Divi/pull/2588
- Builder PR branch: `449-add-power-user-features-3.1`. See: https://github.com/elegantthemes/submodule-builder/pull/1302

The issue caused by SmoothScroll, the library we used to automatically add smooth scrolling effect if its option is activated via ePanel, which tracks the use of arrow keys to initiate the smooth scrolling. It mistaken `r` + `up/right/down/left` and `s` + `up/right/down/left` as `up/right/down/left` which should initiate its smooth scrolling effect. To fix this:

1. Add custom interface for SmoothScroll library to easily activate / deactivate custom keyDown event
2. When the `r` + `up/right/down/left` and `s` + `up/right/down/left` combination is pressed, disable SmoothScroll's keydown event. After the padding has been successfully modified, re-init SmoothScroll's keydown event.

**Comment by timayhelen** [comment]
@fikrirasyid Now r + up/down/left/right and s + up/down/left/right doesn't work when Smooth Scrolling is disabled. It checks for ET_SmoothScroll, but this variable is undefined when the smooth scroll js file is not loaded.

**Comment by fikrirasyid** [comment]
@timayhelen I should've thought and added the variable checks earlier :facepalm:

I've pushed a patch and fixed the issue at the both Divi's `449-add-power-user-features-3.1` and submodule-builder's `449-add-power-user-features-3.1` branches.

**Comment by fikrirasyid** [comment]
@Jronk I've refactored the way shortcut's add new row / section works. It has been significantly simplified and only use one action to get things done. Anyway now that I've looked deep into the code, I remember several things that makes it the way it was (I missed several things during our discussion at Slack).

 This is how it works previously:

1. The idea is to reuse as much component and store's method so if there's a change to the method, shortcut automatically used it as well (we don't end up maintaining two different "ways" for adding row/section)
2. To use component's methods, we need to get component's object. This is the tricky part: there's no way to get component's object. There is `getShortcodeObjAtAddress()`, but it gets layout's object, not the component object.

To overcome no. 2, hence the "global flag" mechanism was added. Basically:

1. Add new row shortcut is called
2. Toggle "addNewRow" flag to the VB
3. Last hovered row gets rerendered. Noticing that there is `addNewRow`'s flag, the component pushes an action which contains the component's object
4. Triggering all methods needed to add new row. This takes two loops back and forth from store, rerendering component, calls action again, fires store, and render the outcome.

This works as expected, but violates the unidirectional nature of flux architecture. Thus, we refactored it. Right now:

1. We have store methods for adding new row and section. These methods merged all necessary functions for adding new row / section
2. Now adding new row / section via shortcut is as simple as calling actions, triggers store, updates the main layout object, and re-rendering the UI
3. There is one down side tho: whenever a change is added to the way we added row / section, recheck how add new row/section's shortcut works, whether it needs to be adjusted or not.

**Comment by Jronk** [comment]
@fikrirasyid regarding the last #3 (the downside), if we instead move all/most of this logic and function calls: https://github.com/elegantthemes/submodule-builder/pull/1302/files#diff-3d118346b9153b174ee444572afed18dR4192  in to a function of its own, then no matter how you arrive (via shortcut or "add new"  button, then the same function will get called to do all the work.

**Comment by fikrirasyid** [comment]
@Jronk that would be tricky because that is actually three user-based actions packed into one. Let me walk you through it:

```
/** 
 *  ========> This happens when user clicks the (+) button
 */
if (action.moduleSlug === 'et_fb_specialty') {
  const hoveredSectionAddress = action.module.props.address;
  const $hoveredSectionAddNewButtonDOM = jQuery(`div[data-address="${hoveredSectionAddress}"] .et-fb-section-button-wrap--add button`);
  const addNewSpecialtySectionButtonPosition = $hoveredSectionAddNewButtonDOM.offset();

  if (isObject(addNewSpecialtySectionButtonPosition)) {
    addNewSpecialtySectionButtonPosition.element = $hoveredSectionAddNewButtonDOM.parent();
  }

  setButtonPosition(addNewSpecialtySectionButtonPosition);
}
setActiveModule(action.module);
setActiveModuleLock(action.module);
var is_parent = isUndefined(action.module) ? true : false;
setModuleAddAfter(action.module, is_parent);
setModuleAdd(true, action.module);

/** 
 *  ========> This happens when user clicks the what kind of section to be added on the tooltip
 */
const shortcutAddNewSectionCallback = function() {
  const sectionNoun = action.moduleSlug === 'et_fb_fullwidth' ? 'fullwidth_section' : 'section';
  History.add(
    _shortcode_obj,
    ETBuilderStore.getPageSettings(),
    { verb: 'added', noun: sectionNoun }
  );
};

setTimeout(function(){
  if ( 'et_fb_specialty' === action.moduleSlug ) {
    setModuleAdd( true, 'specialty_section' );
    ETBuilderStore.emitModuleAdd();
  } else {
    insertNewModule( action.moduleSlug, undefined, undefined, shortcutAddNewSectionCallback );
    ETBuilderStore.emitModuleAdd();
  }
}, 0);
```

I think merging these into different function to be used when user adds section via UI wouldn't be possible since it contains two separate actions.
