### ISSUE TITLE
Saved Layouts do not retain the Custom CSS content

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#611]
### Problem:

Layouts saved into the library do not retain custom css.

### Steps To Reproduce:
1.  Create any page layout
2. Add some css to the layout Custom CSS field
3. Save layout into the library
4. Create new page and load saved layout
5. The custom css field will be empty.

**Comment by timayhelen** [comment]
Are you referring to the custom CSS in Page Settings? This is saved as post meta and unfortunately it's not currently part of the JSON export since it's not part of the post content.
