### ISSUE TITLE
Saved Modal Position Can Be Outside Viewport

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#613]
Currently when you save the page, the current Modal state is saved. The next time you open up the builder, it remember the size and position of the modal and whether or not it was snapped or fullscreen.

The problem is, if the browser window changes size then the position of the modal can actually appear outside the viewport. 

1. Make your browser full screen and place the modal all the way to the right side of the browser. 
2. Save the page. 
3. Close the VB and re-size your browser window to be 50% of the width of the screen. 
4. Open up the VB again and try to edit a module. The settings modal can't be located because it exists outside the viewport. 

We need to detect if the modal is going to be outside the viewport, and if it is, bring it back inside with ~100px of space between the modal and the edge of the browser.

**Comment by timayhelen** [comment]
@SlavaET Looks like the problem still occurs if you "expand" modal to full screen using the expand icon. If you expand the modal at a large browser width and save the page, and then you reduce the browser width and open a modal setting, the modal will be expanded to it's previous height and width. 

I think this is more of a flaw in how the "expanded" modal state is being saved. We don't want to save the actually height and width of the modal, but instead save the fact that it has been "expanded." Then when the modal is opened, it is opened to its normal dynamic height and width.

**Comment by SlavaET** [comment]
@timayhelen fixed.

**Comment by timayhelen** [comment]
@SlavaET This branch actually breaks "Modal Snap" when the modal is snapped to the right side of the screen. Snap the modal to the right, save the page, and then refresh and open the modal. 

Looks like the check that prevents the modal from leaving the viewport & being too close to the edge conflicts with the modal snap right.

**Comment by SlavaET** [comment]
@timayhelen fixed.
Also fixed one more issue - when you save the very big modal and then open it on small screen it'll overflow the viewport.
