### ISSUE TITLE
 Incompatibility with WP Offload S3 Plugin

### ISSUE THREAD

**Issue by andreisnoopy** [elegantthemes/Divi-Beta#614]
One client reports some incompatibility with this plugin : https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=601530

**Comment by lots0logs** [comment]
@andreisnoopy Please let the customer know that Divi adheres to the [Standards For Good Coding](https://make.wordpress.org/core/handbook/coding-standards/) as defined by the makers of WordPress. All images uploaded via the Divi Builder are processed via the WordPress media library so the plugin developer's assumption is incorrect. Also....

```
Unfortunately there is no ETA on a solution that I can provide at this time. Though I can assure you that issues are addressed as quickly as possible based on our development teams current workload and the severity of the issue when compared to the severity of other open issues. 

Please let me know if you have any further questions. 

Best Regards,
```

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/Divi #2586](https://github.com/elegantthemes/Divi/issues/2586) via [**ZenHub**](https://www.zenhub.com/)
