### ISSUE TITLE
Database error shows up, when a post / page is saved on fresh install

### ISSUE THREAD

**Issue by uportnykh** [elegantthemes/Divi-Beta#617]
```WordPress database error Table 'wordpress.wp_et_divi_ab_testing_stats' doesn't exist for query DELETE FROM wp_et_divi_ab_testing_stats WHERE test_id = 2397```

**Comment by uportnykh** [comment]
I'm not sure how to replicate the issue, but I have lots of these errors in my log file, so it is definitely worth adding a check.

**Comment by lots0logs** [comment]
@uportnykh Please see my comment on the PR. Thanks :smiley:
