### ISSUE TITLE
Disable "Double Click To Open Module Settings" When Clicking Module Buttons

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#619]
Often times I find myself clicking he duplicate icon 3-4 times to quickly duplicate a module several times. Since we added "double click to open module settings," however, this will open the module settings while duplicating, which is annoying. I think we should prevent modal settings from opening if you double click on any of the module buttons (except the gear icon that is used from opening module settings normally).

**Comment by timayhelen** [comment]
@uportnykh This works for module buttons, but not Section or Row buttons.

**Comment by uportnykh** [comment]
@timayhelen ah, right. I've fixed it.
