### ISSUE TITLE
Slider Module :: Slide Image Position Isn't Adjusted When Slide Becomes Visible (in VB)

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#624]
### Problem:

![2016-10-11_07-57-58-pm](https://cloud.githubusercontent.com/assets/4675662/19293823/3b3b22e8-8fed-11e6-96c7-4290230e6a31.png)

**Comment by fikrirasyid** [comment]
@lots0logs is there any specific step that need to be done to replicate the issue? I've rechecked this on both slider and fullwidth slider module and it works as expected:

![624-misalign-image](https://cloud.githubusercontent.com/assets/916442/19346432/6f5021ba-916d-11e6-9b1e-ebdf4e6151cf.gif)

The only possible scenario I can think of the issue to happen is:

1. The slide image is hosted elsewhere / not local
2. Somehow the image is loaded longer that it should be
3. Thus the slide image position is configured before the image is even loaded, thus the incorrect vertical align positioning

**Comment by lots0logs** [comment]
@fikrirasyid It looks like it only happens when the slider appears outside of the viewport when the page initially loads (so put the slider at the bottom of the page)

**Comment by fikrirasyid** [comment]
@lots0logs I tried putting the slider on the bottom of the layout, but it still works as expected tho:

![624-pr](https://cloud.githubusercontent.com/assets/916442/19373115/b6ade082-91eb-11e6-9c48-dcbaf515e05a.gif)

Can you share the layout you're using which replicates this issue? This is the layout I'm using:
[624-test.json.zip](https://github.com/elegantthemes/Divi-Beta/files/528520/624-test.json.zip)

**Comment by lots0logs** [comment]
@fikrirasyid Use the Homepage Extended (Premade Layout), save the page, reload the page, and then scroll to the bottom to the slider. You should see the issue :smiley:

**Comment by timayhelen** [comment]
@fikrirasyid This only occurs:

1. When you first load a layout. If you save the page a refresh, the image will appear correctly.
2. Only for the first slide in a slider, because sliding to the next slide seems to trigger the JS that centers the image. 

So just load the "homepage extended" layout and scroll down to the blue slider in the middle of the page.

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen I can replicate the issue now using the steps @lots0logs mentioned above. It appears to be related to https://github.com/elegantthemes/Divi-Beta/issues/624#issuecomment-253480568 tho; if you change the slide image to local image, the issue doesn't appear.

I'll find a fix for this.
