### ISSUE TITLE
Encoded Spaces Removed From URL's In VB

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#628]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=604257

**Comment by SlavaET** [comment]
Looks like this issue is fixed in following PR - https://github.com/elegantthemes/submodule-builder/pull/1282
@uportnykh can you please verify? I checked and it seems to be fixed because you changed the way we sanitize the values, therefore encoded characters no longer stripped from the strings.
