### ISSUE TITLE
Blog Module :: HTML5 Video Posts Are Rendered Differently Inside The VB

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#629]
### Problem:
In the VB, the blog module renders Video Posts that use HTML5 videos differently than what actually shows up on the page itself. 

Also, let's see if we can do anything about oembed videos not using the same overlay as the HTML5 videos. If we can get them to look more consistent that would be great.

### Steps To Reproduce:
1. Create a video post using an HTML5 video.
2. In the VB, setup a Blog Module to display the post.
3. Save the page and compare the VB view to the actual page.

#### On the page:
![2016-10-12_02-54-06-pm](https://cloud.githubusercontent.com/assets/4675662/19325638/af1742ba-908c-11e6-842b-b917a1b7192b.png)

#### In the VB:
![2016-10-12_02-53-47-pm](https://cloud.githubusercontent.com/assets/4675662/19325651/bf864eac-908c-11e6-89f4-c0fb3998c60b.png)

**Comment by lots0logs** [comment]
@fikrirasyid LGTM, but what about this:
>Also, let's see if we can do anything about oembed videos not using the same overlay as the HTML5 videos. If we can get them to look more consistent that would be great.

**Comment by fikrirasyid** [comment]
@lots0logs either oEmbed or self-hosted video which are used as main video in blog module's video format post are actually don't use any overlay image at all. It behaves differently than Extra's post modules which use featured image as video format's video overlay.

![629 feedback](https://cloud.githubusercontent.com/assets/916442/19405665/67f0400c-92a4-11e6-887e-9f511f21d383.jpg)

I'm not sure: is this behaviour (not having featured image as video overlay) intentional on blog module? If it is intentional, I don't think we should add it. @timayhelen what do you think about it?

**Comment by fikrirasyid** [comment]
@lots0logs any update on this?

**Comment by lots0logs** [comment]
I was waiting for input from @timayhelen actually :grimacing:

**Comment by timayhelen** [comment]
@fikrirasyid I think using Featured Images (if available) as an overlay would be nice. Let's add it.

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen I've added video overlay at https://github.com/elegantthemes/submodule-builder/commit/4d48f563c3165ecc52103a3739b64ca68d927c6c. Basically if a post uses video format and has a featured image, the featured image will be used as video's overlay cover.

![has-no-overlay](https://cloud.githubusercontent.com/assets/916442/19552728/53c2c01a-96db-11e6-83e5-fe230da13987.jpg)

**Comment by lots0logs** [comment]
@fikrirasyid It'd be nice if we could achieve some level of consistency (though not sure if its possible)

![screencapture-et-falgout-us-divi-1476998966099](https://cloud.githubusercontent.com/assets/4675662/19578756/c22900ee-96e2-11e6-9886-78dabeb75588.png)

@timayhelen What do you think?

**Comment by timayhelen** [comment]
@fikrirasyid Ideally we would use the overlay for all video types, and trigger the video to play when the overlay is clicked if possible.

**Comment by fikrirasyid** [comment]
@lots0logs can you elaborate more on what you mean by more consistency? If a post has no featured image, it'll fallback to its original video player. I don't think there's a way to modify original video player. 

Based on the screenshot above, all post which has featured image appear to be consistent except for the vimeo based post. Is that what you mean?  I tried importing the layout you give but I couldn't import the featured image of the video format post you attach above, I assume you imported it from localhost?

***

@timayhelen noted. I actually remember we're doing the same thing for Extra long time ago: https://github.com/elegantthemes/Extra/issues/414#issuecomment-155903874

**Comment by fikrirasyid** [comment]
@timayhelen Ah, I was missing a part of your reply. I was reacting to this:

> trigger the video to play when the overlay is clicked if possible.

Regarding this:

>  Ideally we would use the overlay for all video types

If no featured image found, which image that needs to be used as overlay?

**Comment by timayhelen** [comment]
@fikrirasyid We only use a thumbnail when featured images are defined. I think I was confused by your screenshot because it made it seem like features images were not used for Youtube and Vimeo videos, but it looks like those were examples of videos without featured images?

**Comment by fikrirasyid** [comment]
@timayhelen ah I see. Basically at `master` now there's no overlay for all videos at all. At this PR, overlay is added for blog module's video format either it is self-hosted, or hosted on 3rd party service if the post has featured image.

So at the time being, If there's no featured image, the post's video will have no overlay.

**Comment by fikrirasyid** [comment]
@timayhelen I've incorporated your feedback. Clicking video overlay now automatically plays the video.

![clicking overlay now auto plays the video](https://cloud.githubusercontent.com/assets/916442/19600751/8e92014c-97d0-11e6-8ac2-fc09736e489a.gif)

**Comment by timayhelen** [comment]
This doesn't seem to work for me. I get some strange results. I tested a blog module with 2 video posts, both with featured images. One was a youtube video and one was a self-hosted MP4. 

This is the result:

![blog](https://cloud.githubusercontent.com/assets/3333028/19610370/14b1f38a-9791-11e6-88bb-c8a9bdc710f3.gif)
