### ISSUE TITLE
Video Posts :: Thumbnail Video Player Doesn't Work When Video URL Is Added To Content Without Shortcode

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#630]
### Problem:
When using HTML5 videos for video posts, no thumbnail video player is shown for the post in post listings unless you wrap the video URL inside of the `[video]` shortcode.

### Steps To Reproduce:
1. Create a video post and put the video URL directly in the content.
2. Create another video post and use the `[video]` shortcode to put the video in the content.
3. View the two posts in a post listing (Category/Archive or Blog Module)

#### With video shortcode:
![2016-10-12_02-54-06-pm](https://cloud.githubusercontent.com/assets/4675662/19325922/ef081736-908d-11e6-9372-af08716fcecf.png)

#### Without video shortcode:
![2016-10-12_03-10-19-pm](https://cloud.githubusercontent.com/assets/4675662/19325938/095f659e-908e-11e6-80c5-f25df2472bfa.png)

**Comment by Anny85** [comment]
I've fixed it here: https://github.com/elegantthemes/submodule-builder/commit/468afec4b1782a09132d41acbfc99830ed593c32
