### ISSUE TITLE
VB Exit Modal :: Position The Modal Close To The Top Of The Viewport

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#631]
### Problem:
When using the native alert dialog in browsers to show a message on the `beforeunload` event, the dialog appears at the top of the viewport. I think the reason for that is because more often than not, the user's focus is in that area. For example, if navigating using the back and forward buttons you are already looking at the top of your screen and your mouse cursor is also positioned there so showing the modal close to the top makes things flow more naturally/smoothly.

**Comment by timayhelen** [comment]
I would prefer to keep it centered so that all of our modals look the same and appear in the same location.
