### ISSUE TITLE
Woocommerce :: check out page :: header in center layout

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#633]
### Problem:

If by default, the layout requires to have a tall header, which will not change size when scrolling, when in the woocommerce check out page, if no details are filled in the form, and try to submit the ordering, woocommerce will show the fileds that need to be filled out, the problem is it will scroll to those fields, but not in the right position.

Here is a customers page:
<img width="960" alt="screen shot 2016-10-13 at 11 10 28 am" src="https://cloud.githubusercontent.com/assets/1719735/19341354/c3537074-9135-11e6-8980-a0f90bda561b.png">

**Comment by SlavaET** [comment]
Fixed. Likely Woocommerce triggers an event in case of error and we can adjust scrolling at this point.
