### ISSUE TITLE
Configuration panel can hide when you move from wide to small screens.

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#635]
### Problem:

Easy solution just zoom out! I'm reporting this anyway:
https://www.youtube.com/watch?v=tJUl2bUcZxM

**Comment by lots0logs** [comment]
@FaycalBoutam We can only guarantee the layouts/styles when they are viewed with **normal** zoom (100%). That goes for all of our products.

**Comment by timayhelen** [comment]
The bug isn't related to zooming. He means that once the modal is lost, you have to zoom out to find it. 

But this is actually a bug that has already been fixed: https://github.com/elegantthemes/Divi-Beta/issues/613

**Comment by lots0logs** [comment]
:doh: :sweat_smile:

**Comment by FaycalBoutam** [comment]
Oh I didn't think about the case of resizing the browser window. I just thought about when you switch from large to small screen (customer's case). Looks like the next update will include the fix. Thanks for the info.
