### ISSUE TITLE
FB :: Refactor "Add New {thing}"

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#636]
### Problem:

The implementation of "Add new {section/row/module}" uses an action, that upon the next rendering, sends another action, which upon next render triggers another action resulting in the final render. This approach is not following the "flux way" nor react way either. Any 1 action, should result in at most a render, and not directly trigger another action. Instead of setting "flags" that are looked for in the future renders that would be triggering a subsequent render, all that needs to be accomplished in the store via whatever modular functions necessary to accomplish the one action.

The commit message here: https://github.com/elegantthemes/submodule-builder/pull/1302/commits/03e72a904ecaad2d07be32a61d0b4e4eb48d1425 documents it quite well.

Here is what we have now:
1. You do something that fires an action
2. somewhere in the store some magical “flag” is set
3. now, somewhere in the codebase, something is looking for that magical “flag"

in 2. and 3., you have no idea of knowing what that "flag" is

you only know 1, you have to nit pick through every single thing looking for every var set in that 1 action to see if its a flag used elsewhere or not

its like looking for a needle in a haystack, without knowing what the needle even is

**Comment by SlavaET** [comment]
@Jronk I'm not sure that understand which "flag" you're talking about but adding module doesn't set any magical flags as far as I understand. It works as follows:
1) You click the Add New button and it fires the `button_click` action with required parameters;
2) In the Store we handle the button click action and emit the `MODULE_ADD_EVENT`. Also:
 - we set the last clicked button position;
 - we set the module where button was clicked;
 - do some cleanup stuff like closing opened modals, etc.

3) In the root we're listening for the `MODULE_ADD_EVENT` and activate the 'Tooltip Modal Component';
4) in the 'Tooltip Modal Component' we retrieve the "last clicked button position" and "the module where button was clicked" and render the Tooltip Modal. These 2 things are stored as variables in Store the same way we store the `Active Module` and some other things and they're not triggering any actions.

I think when @fikrirasyid said ```Thus, the act of `adding new section` requires several
`ETBuilderActions` back and forth.``` he means the interaction of user with our app when adding new section. Like click add section button - 1st action, choose the Section Type - 2nd action, choose the Row Type - 3rd action, etc. But these actions are not triggering each other, they're triggered by user in process of adding the Section and every action actually leads to a render. @fikrirasyid correct me if I wrong.

**Comment by fikrirasyid** [comment]
@SlavaET this is related to how add new row/section works in VB's shortcut: https://github.com/elegantthemes/submodule-builder/pull/1302/commits/a4790033b2c2d03deb7401d626a522746889fe9b. Basically adding row/section involves several steps in VB's GUI. Mimicking this actions in shortcut requires a flag so we can emulate these steps and reusing as much method as possible. It turns out not a good idea tho.

We actually have adjusted and merged it. https://github.com/elegantthemes/submodule-builder/pull/1302. I think we can close this issue now. cc: @Jronk. Sorry for the confusion :|

**Comment by Jronk** [comment]
Here are examples of the "magic flag" Im talking about:

if row has `props.newRowLayout` fires action: `ETBuilderActions.rowColumnChange`
which will/can add a column prop: `props.autoAddModule` which will in turn fire `ETBuilderActions.cleanNewModuleAttrs`

if a module has the prop `just_created` it will fire action: `ETBuilderActions.cleanNewModuleAttrs`

**Comment by SlavaET** [comment]
@Jronk ah, got it. Thank you for details.
