### ISSUE TITLE
Can't edit pages with the FB on NGINX servers.

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#637]
### Problem:

This problem occurs with two customers, you can use the Visual Builder to create new pages just fine, however once you publish the page it's not possible to load the Visual Builder any more (unless you save the page as draft). The two customers are using NGINX as web-server.

Here you can see a video screen for the problem uploaded by the customer and the token to the site:
https://github.com/elegantthemes/Divi/issues/2592

### Steps To Reproduce:
1.  Just try to edit any published page with the Visual Builder.

**Comment by lots0logs** [comment]
@FaycalBoutam I sent you a message on Slack.
