### ISSUE TITLE
Header Style :: Vertical :: Right

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#639]
### Problem:
The sub menu link in this case, cannot be accessed, because the sub menu will disappear as soon as the mouse cursor will leave the menu area!

Example: http://dev.niwo.eu/

**Comment by SlavaET** [comment]
@eduard-ungureanu I can access the sub menu items on website you posted. So you still see the issue there? Can you please record a screencast?

**Comment by timayhelen** [comment]
@eduard-ungureanu It seems to work for me as well. Please re-open this issue if the problem still exists and provide additional details.

**Comment by eduard-ungureanu** [comment]
Hi @SlavaET and @timayhelen!

I see the client did change to the default header format, but here is a screencast from my end, when the Header is in Vertical Layout, and the position is set to be on the right:

https://drive.google.com/file/d/0B8PjD3Z_XQvuNXUtZWFyX240LVk/view?usp=sharing
