### ISSUE TITLE
Enable Dragging When Hovering Over Any Non-Text Element Of Module/Row/Section

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#64]
Ideally users should be able initiate Drag & Drop by dragging on any part of the module/row/section, not just by using the drag icon. The only caveat would be that dragging should be disabled when hovering over editable text.

**Comment by timayhelen** [comment]
@uportnykh We should change cursor to move when hovering over any non-TinyMCE editable area. After Slava's recent update, almost all text is now editable btw.

**Comment by timayhelen** [comment]
@uportnykh  I went ahead and made the change.

**Comment by uportnykh** [comment]
@timayhelen Ok, great!
