### ISSUE TITLE
Website background color

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#640]
### Problem:

When setting a custom background color in Theme Customizer > General Settings > Layout Settings, but don't enable the Boxed Layout, the custom background color will not be visible, because in style.css we have this rule:
```
#main-content {
	background-color: #fff;
}
```

a simple fix will also need to set the background color to be white, if we have the `custom-background` css class applied to body.

```
.custom-background #main-content {
	background: transparent;
}
```

Will fix this.

**Comment by timayhelen** [comment]
@eduard-ungureanu It's actually do the Section background colors. The main content BG color will only show up if a section background is set to a transparent color, or if the "use transparent background color" option is enabled.

**Comment by lots0logs** [comment]
I think this is actually a duplicate of elegantthemes/Divi#1739 (which I have confirmed to be a bug).

**Comment by eduard-ungureanu** [comment]
@timayhelen even if I set the section background color to be transparent, still doesn't work as it should!

@lots0logs yes it looks like it's the same issue when using either custom background image, or custom background color!
