### ISSUE TITLE
Inner Shadow Settings on Regular Sections not working 

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#641]
### Problem:

Inner shadow Settings does not seems to have any effect in regular sections 

Under the "Additional Information" section below, it would be especially helpful if you could include a video screencast of the issue occurring along with a link to download the Divi Builder layout you were working on in the screencast. You can export the layout using the Divi Portability System and paste a link to where we can download the .JSON file.

### Steps To Reproduce:
1.  Create a new section 
2. In section settings set some background color
3. Enable Inner shadow setting 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
@abhi-sharm The option seems to work fine for me. I tested in the BB and VB. Can you please check again? Feel free to re-open this ticket if you have additional information about this issue.
