### ISSUE TITLE
Broken icons when using other roles than admin

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#643]
### Problem:

![screenshot_16](https://cloud.githubusercontent.com/assets/9657712/19480542/8fb6ca6e-956c-11e6-98eb-b1facd372932.png)

### Steps To Reproduce:
1. Create a new user with Contributor role
2. Open VB and try to add the module
3. 
4.

**Comment by SlavaET** [comment]
Note: the fix is in the `submodule-core` directory.

**Comment by lots0logs** [comment]
This issue is being addressed on the same PR as #644 so lets track it there.
