### ISSUE TITLE
The Modal Close :: broken style when using other roles than admin

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#644]
### Problem:

![screenshot_18](https://cloud.githubusercontent.com/assets/9657712/19480807/9cb61b88-956d-11e6-9d62-8d62175f3f9a.png)

### Steps To Reproduce:
1.  Create a new user with Contributor role
2.  Open VB and make any change
3.  Click `Exit Visual Builder` button in Admin Bar

The modal appears at the bottom of the page

**Comment by SlavaET** [comment]
Note: the fix is in the `submodule-core` directory.

**Comment by lots0logs** [comment]
@SlavaET Please see my comment on PR. Thanks.
