### ISSUE TITLE
The src attribute for images has a value of "false" in some cases

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#646]
### Problem:

This results in an extra request to the server upon every re-render (http://somesite.com/false) which of course returns 404 (which is why the browser keeps trying again to retrive the image).  The issue occurs when there is no featured image applied to a post being displayed in the module. I've only confirmed the issue on the Fullwidth Portfolio Module, but we should check all modules where this could potentially be occurring (Reg. Portfolio, Post Slider, Blog, etc).

### Steps To Reproduce:
1.  Configure a Fullwidth Portfolio Module so that it will display at least one project which has no featured image.
2. While in the VB, open your browser console.
2. Cycle through the responsive view modes a few times.
3. Check your browser console. 

### Additional Information:

![2016-10-18_11-38-41-am](https://cloud.githubusercontent.com/assets/4675662/19487477/957d0d76-9528-11e6-92a4-680e1ff906a8.png)

**Comment by lots0logs** [comment]
@fikrirasyid @Jronk Please see my comment on the PR. Thanks!

**Comment by fikrirasyid** [comment]
@lots0logs @Jronk replied at https://github.com/elegantthemes/submodule-builder/pull/1327#issuecomment-255279454

**Comment by lots0logs** [comment]
@fikrirasyid See my reply on the PR. Thanks :smiley:

**Comment by fikrirasyid** [comment]
@lots0logs I've replied it at https://github.com/elegantthemes/submodule-builder/pull/1327#issuecomment-255322166
