### ISSUE TITLE
Fullwidth Menu Doesn't Go Fullwidth

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#647]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=605198&p=33336031)

```
Create a Fullwidth section with:
a. A Fullwidth Header
b. A Fullwidth Menu
c. A Background video or image on the section.
```

You will notice that the fullwidth menu no longer goes fullwidth.

**Comment by SlavaET** [comment]
Fixed. 
**Note:** I was able to reproduce the issue only when Parallax is enabled for section.
