### ISSUE TITLE
BB :: Add ? shortcut to Backend Builder

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#648]
As @timayhelen mentioned at https://github.com/elegantthemes/Divi-Beta/issues/449#issuecomment-254665222

> @fikrirasyid Can you add the "?" modal to the backend builder as well? We should trigger the normal BB modal (the large one) and list all of the hotkeys in a similar style to the VB.

**Comment by lots0logs** [comment]
@fikrirasyid Let's use the same font weight and colors as the VB. Also, I think we need to only handle keyboard events when the cursor is hovered over the builder since we don't own the page (meaning who knows what kind of plugins or theme features we might be operating alongside of)

**Comment by timayhelen** [comment]
@lots0logs Font styles should match the BB, not the VB. I am going to make one minor adjustment, but I think it looks pretty good. Fikri pulled the header styles from the Fullwidth Header module and the text styles are inheriting the correct colors and sizes.

**Comment by lots0logs** [comment]
@timayhelen Here's how it looks on my end:

![2016-10-20_06-00-42-pm](https://cloud.githubusercontent.com/assets/4675662/19580963/417a4022-96ef-11e6-8de9-92f8284163b4.png)

________________________________

![2016-10-20_06-02-25-pm](https://cloud.githubusercontent.com/assets/4675662/19580983/66a067c8-96ef-11e6-8aa4-e9f25f1f5379.png)

**Comment by fikrirasyid** [comment]
@lots0logs @lots0logs since there's no specific UI guide for it, what I did:

1. Reused BB's modal system and UI as much as possible
2. Used fullwidth header's subtitle styling
3. Used FB's styling for <kbd /> and keys and description indentation

Thus:

1. FB's styling for <kbd /> and keys + description indentation
2. Everything else should match BB's styling

Basically it exactly like what @timayhelen mentioned at https://github.com/elegantthemes/Divi-Beta/issues/648#issuecomment-255205237

**Comment by fikrirasyid** [comment]
Regarding this: 

>  I think we need to only handle keyboard events when the cursor is hovered over the builder since we don't own the page 

Your argument makes sense but I feel that it is not intuitive for help shortcut to depend on cursor to work. If to trigger a help via shortcut requires a hover toward builder, it makes more sense to click a button on a builder to trigger the modal instead (something we haven't had).

Furthermore, I haven't found a plugin which utilizes keyboard shortcut that could possibly conflicted with. I might be wrong on this tho, CMIIW. Plus, on both BB and VB, the way keyboard shortcuts work are:

1. shortcut that should work no matter what. Ex: cmd + s for publishing
2. shortcut that should only work if NO input, textarea, or contentEditable area being `:focus`-ed. Most of our shortcuts are this type.

For `shortcut that should only work if NO :focus state found`, there are two kinds of them:

1. shortcut that should work if module/row/section are being hovered, i.e. copy module
2. shortcut that should just work, i.e. help / show shortcut list

It is pretty safe, I think.

**Comment by timayhelen** [comment]
@lots0logs We want the modal styles in the BB to be consistent, so it doesn't make sense for one modal to be changed to the VB style.
