### ISSUE TITLE
Countdown Module not displaying properly

### ISSUE THREAD

**Issue by bpitts82** [elegantthemes/Divi-Beta#65]
### Problem:

Module Countdown Timer isn't functioning properly when added to sidebar. 

### Steps To Reproduce:
1.  Added countdown timer to sidebar and set parameters
2.  Wasn't able to view it properly during creation, after creation or after saving the page.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac

**Operating System**:  OSX

**Browser**: Safari

**Screen Resolution**: iMac (5120 x 2880)

**Screenshots**: 
<img width="329" alt="screen shot 2016-08-18 at 8 45 46 pm" src="https://cloud.githubusercontent.com/assets/3269673/17795293/182e57d0-6585-11e6-849c-b10ffe1d0828.png">

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
@bpitts82 can you elaborate more on what you mean by "added to sidebar" (Do you mean WordPress sidebar, 'sidebar' in specialty section, or anything else)? If you can provide an annotated screenshot, it would be even more useful. Thanks.

Note: Countdown timer appears to work as expected on frontend builder:

![countdown timer](https://cloud.githubusercontent.com/assets/916442/17803125/7f9bd0f2-661e-11e6-810e-58fcd9fab5dd.gif)

**Comment by timayhelen** [comment]
@fikrirasyid He may be referring to the the "sidebar" of a speciality section, which means it may be a certain column layout in a particular speciality section that causes the text overlap.

**Comment by fikrirasyid** [comment]
@timayhelen I noticed one specialty section sidebar related issue but I'm not 100% sure whether this is what @bpitts82 was experienced or not. Basically there is an issue due to missing lodash method on row inner component:

![65-countdown-sidebar-issue](https://cloud.githubusercontent.com/assets/916442/17893055/6aaa012a-696e-11e6-9cd7-c5d87cf0dc1f.jpg)

@bpitts82 can you clarify that this is what happened with you?
