### ISSUE TITLE
"Add Module" Button can't be clicked from Fullwidth Post Title

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#650]
1. Add a fullwidth section
2. Add a post title module
3. Try to click the gray (+) button to add a new module below the post title. It's not clickable. 

At first it appears that the + button is too close to the main button group, but even with a large post title module the button is not clickable. It seems to be a z-index issue.

**Comment by lots0logs** [comment]
@fikrirasyid For modules that don't have a lot of height, the settings bar and add new module button overlap. Can we improve it? 

![2016-10-20_05-41-23-pm](https://cloud.githubusercontent.com/assets/4675662/19580646/447e2d94-96ed-11e6-9d25-c16658cbf8ed.png)

**Comment by fikrirasyid** [comment]
@lots0logs I've pushed a fix which should fix it. I've explained what actually happened and I'm copying the commit message here for clarity reason:

> This actually has been prevented by height detection and adding `et-fb-module--short` and `et-fb-module--short` class + modifying its size accordingly, however there was a recent change for fullwidth module's popover position which nullify this fix: https://github.com/elegantthemes/submodule-builder/commit/f28395607c297488acdaab29fd57ef98298e9013#diff-0ba0cde0b14ab12bafde7c8cea87e8aeR403. The commit has no PR/issue opened so it is kinda hard to detect what kind of situation that makes the change are made specificly. To fix this, more specific styling for fullwidth module which has short height is added to overwrite fullwidth module popovers's recent tweak.

**Comment by timayhelen** [comment]
@fikrirasyid The changes mentioned were added to ensure that the distance between (+) buttons are the same access the board. They were all different before, so it looked quite strange. Basically when you hover hover a standard-sized modules, whether is be a normal module in a standard section, specialty section or a fullwidth module in a fullwidth section, the three (+) buttons should be equally spaced apart:

(+)

(+)

(+)

**Comment by timayhelen** [comment]
So in this PR, that consistency is lost for "small" Fullwidth modules, but that's ok.

**Comment by fikrirasyid** [comment]
@timayhelen Ah I see, I get it now. Thank you for clarifying it.

> So in this PR, that consistency is lost for "small" Fullwidth modules, but that's ok.

Yeah, I think we can make exception for short modules
