### ISSUE TITLE
Text Module :: Advanced Design :: Max width field doesn't have device icon in FB

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#652]
### Problem:

Here how this setting look from the Backend Builder
![image](https://cloud.githubusercontent.com/assets/20072036/19537333/336b8366-9658-11e6-9093-ee5516f14016.png)

In the Frontend Builder this icon do not appears
![image](https://cloud.githubusercontent.com/assets/20072036/19537382/614b37b8-9658-11e6-89e7-4d9c8b5f0f00.png)

**Comment by SlavaET** [comment]
Fixed.
Btw, It was missing not only in Text module, but in all the modules which have the Max Width option.
