### ISSUE TITLE
Can't drag modules to specialty section

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#654]
### Problem:

I think this is related to https://github.com/elegantthemes/Divi-Beta/issues/352

https://www.youtube.com/watch?v=lYzoBxRWPlE

**Comment by lots0logs** [comment]
@fikrirasyid Can we make it so that there is no dropzone shown when dragging a module over dropzones that only accept rows? It seems counterintuitive to me to show a dropzone in a place that the drop will fail because the type of element dropped isn't allowed there :thinking:

**Comment by fikrirasyid** [comment]
@lots0logs actually that is what I was trying to do but after a while I still couldn't find a way to do so thus why I end up with this fix :facepalm: I'll try to look at it again.

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated your feedback at https://github.com/elegantthemes/submodule-builder/commit/1ab81e2fec9ad70da1cc767ed0e118a9d67177eb. Dragged module now can't be incorrectly dropped at specialty section's `.et_pb_column`.
