### ISSUE TITLE
FB :: Code Module + Text Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#657]
### Problem:

There was another issue about the code module #559 but I don't think those are related so I decided to open a new issue.

The problem is when I'm using a custom html code which contains this code:
```
<a class="wpc-image-hover" href="http://www.stage1sd.schneordesign.schneordesign.com/consumer-design">
<img class="wpc-image" title="Visit Consumer" src="http://et/divi/wp-content/uploads/sites/2/2016/10/AviSchneor_portrait_600x600.jpg" alt="Consumer category" data-hover="http://www.stage1sd.schneordesign.schneordesign.com/wp-content/uploads/2016/10/AviSchneor_portrait_600x600TEST.jpg" />
</a>
```
And bellow that code module a text module, containing only a simply h4 tag, in FB I cannot edit anymore the text module settings.

The custom html code  + custom css classes will be used in a custom JS code, to change the image src on hover.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvuM21HOVhseVEyZ0E/view?usp=sharing

**Link To Download Layout JSON File**:
[Code + Text.json.zip](https://github.com/elegantthemes/Divi-Beta/files/543941/Code.Text.json.zip)

**Comment by SlavaET** [comment]
I added the fix into this PR - https://github.com/elegantthemes/submodule-builder/pull/1343
Simply moved the popover a little bit lower to improve the accessibility in short modules.

**Comment by lots0logs** [comment]
Let's track this on #550
