### ISSUE TITLE
Replace jQuery.inArray() with lodash' _.includes()

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#658]
We use lots of `jQuery.inArray()` for checking value existence in array. It'd be easier to read and cleaner if  they are being replaced by lodash' `_.includes()`. Besides, we bundle used lodash method to our `bundle.js` while `jQuery` isn't being loaded to bundle.js.

**Comment by lots0logs** [comment]
@fikrirasyid Please see my comment on PR. Thanks.

**Comment by fikrirasyid** [comment]
@lots0logs I've replied it at https://github.com/elegantthemes/submodule-builder/pull/1334#pullrequestreview-5505977
