### ISSUE TITLE
Extra :: Portability Tooltip :: Some Styles Are Not Right

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#659]
### Problem:
Portability tooltip shows border when it has focus. Also the choose file button isn't styled correctly.

![2016-10-21_01-15-38-pm](https://cloud.githubusercontent.com/assets/4675662/19607643/bea0b814-9790-11e6-86a1-47efe47a4a1c.png)

**Comment by lots0logs** [comment]
@SlavaET The choose file button text should be `#fff`

**Comment by timayhelen** [comment]
I will addd it.
