### ISSUE TITLE
Extra :: Tooltips :: Page Scrolls When Opening Tooltips

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#660]
### Problem:
Page scrolls when tooltip is opened.

![2016-10-21_13-24](https://cloud.githubusercontent.com/assets/4675662/19607792/d4d358a2-9791-11e6-8a4f-f08a35f0c5c4.gif)

**Comment by lots0logs** [comment]
@SlavaET The bottom of the tooltip appears behind the settings bar now:

![2016-10-24_02-34-02-pm](https://cloud.githubusercontent.com/assets/4675662/19660910/3f1b60b2-99f7-11e6-9ee0-94a9ef0dd3d0.png)

---------------------------
![2016-10-24_02-34-16-pm](https://cloud.githubusercontent.com/assets/4675662/19660916/439f0300-99f7-11e6-8064-2e4327fae352.png)

**Comment by timayhelen** [comment]
@lots0logs coincidentally I think this was fixed in @SlavaET's other PR. 

https://github.com/elegantthemes/submodule-builder/pull/1341/commits/52545d963af15f0e3c209833c6866fba72e02e4a

**Comment by lots0logs** [comment]
@timayhelen I confirmed that it is indeed fixed by the PR. However the position of the tooltip is still too low. It now appear in front of the settings bar but in the same position as shown in the screenshots above.

**Comment by timayhelen** [comment]
@lots0logs @SlavaET  Yeah it does look like the positioning if off a bit.

**Comment by timayhelen** [comment]
(edited) @lots0logs Actually I just checked master and it seems to be positioned that way in Divi as well. I think it has always been that way, so let's just keep it for now.
