### ISSUE TITLE
Visual Builder Spinner of Death after cloning site

### ISSUE THREAD

**Issue by mshigekawa** [elegantthemes/Divi-Beta#669]
### Problem:

When cloning a Divi site using WPMU Cloner, the Visual Builder keeps spinning and never loads on the target (cloned site). The Visual Builder however loads successfully on the original source site. I didn't experience this issue when cloning sites using previous versions of Divi (before 3.0.15).

Console Output: 
TypeError: Cannot read property 'edit_module' of undefined(…)

### Steps To Reproduce:
1.  Clone Divi site using WPMU Cloner
2.  Enable Visual Builder on cloned site
3.  Spinner keeps spinning and never loads Visual Builder

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Operating System**:
macOS Sierra

**Browser**:
Chrome (latest)

**Screenshot or Screencast**:
![screen shot 2016-10-22 at 7 13 19 pm](https://cloud.githubusercontent.com/assets/21282923/19623737/1c00d6a0-988c-11e6-9c81-f32b16abc5aa.png)

**Divi Theme Version**:
Version 3.0.15 

**Link To Download Layout JSON File**:
https://ufile.io/7995

**Comment by lots0logs** [comment]
Hi @mshigekawa, there are very few plugins available that actually clone an entire site properly. By properly, I mean in a way that results in a fully functioning copy of the original site. I recommend trying the [Duplicator](https://wordpress.org/plugins/duplicator/) plugin instead (it's known to work well with Divi).

**Comment by mshigekawa** [comment]
RESOLVED. This issue ended up being related to WPMU Hummingbird (forgot I had recently installed this at the same time I updated to DIVI 3.0.15) which minified scripts related to the DIVI Visual Builder thus breaking the Visual Builder after cloning a site. 

See: https://premium.wpmudev.org/forums/topic/hummingbird-breaks-divi-visual-builder-when-cloning-site?replies=1#post-1162926
