### ISSUE TITLE
Plugin compatibility :: WPML :: Not able to add or modify a page trough WP-Admin

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#670]
### Problem:

In this website http://www.azrepair.eu  WPML does not work with divi. In the log file it says:
[22-Oct-2016 08:11:15 UTC] PHP Notice: Trying to get property of non-object in /customers/a/d/6/azrepair.eu/httpd.www/wp-content/themes/Divi/functions.php on line 8425
[22-Oct-2016 08:11:15 UTC] PHP Notice: Trying to get property of non-object in /customers/a/d/6/azrepair.eu/httpd.www/wp-content/themes/Divi/functions.php on line 8425

Can anyone check what the problem is? I can't localize the issue. 
Ask me for a token if you need.

Ticket:  https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=608151

**Comment by SlavaET** [comment]
@kary4 can you please post the steps to reproduce the issue? I checked on localhost and it works fine on my end.

**Comment by kary4** [comment]
@SlavaET So, you are right, I can't reproduce the issue locally. That's why I mentioned it happens only on the clients website, sorry for the confusion. I just don't know what else could I check to localize the issue.

**Comment by SlavaET** [comment]
@kary4 please send me the token via Slack - I'll take a look.

**Comment by kary4** [comment]
@SlavaET as usual, his support plugin now deactivated :) I asked for a token..
