### ISSUE TITLE
Divi Timeout Error

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#671]
### Problem:

Can anyone take a look please, I'm out of ideas why Divi Builder Timeout message still appears here:
https://theworklodge.com
- All plugins are deactivated;
- php memory is set to 768M;
- Installed new divi version by myself;

Ask me for a token.
Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=190&t=608512&p=3351899#p3351899

**Comment by SlavaET** [comment]
@kary4 I see you suggested to increase the `WP_MEMORY_LIMIT` in the `wp-config.php` file, but it won't work if `memory_limit` set to low value in the `php.ini`. So another thing to try is to check the `memory_limit` in the `php.ini` file and try setting it to 128 or 256

**Comment by kary4** [comment]
@SlavaET Yes, I don't believe the information in wp-config.php file :) So, I actually added 
```
<?php phpinfo();?>
```
to the footer.php file to check the real memory_limit value. It's really set to 768. Or do you think phpinfo() function gets the value from the wp-config file? 
Anyway, I'll ask him to add the value also to the php.ini,
Thank you.

**Comment by SlavaET** [comment]
@kary4 you can send me the token in Slack - I'll take a look.

**Comment by kary4** [comment]
@SlavaET It seems he disabled the support plugin :( I'll update you later, sorry.

**Comment by lots0logs** [comment]
We can reopen this later if needed.
