### ISSUE TITLE
Slider Module :: Mobile Phone Preview :: Heading Font Size Doesn't Match The Default Shown In Module Settings

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#676]
### Problem:

![2016-10-25_11-41-32-am](https://cloud.githubusercontent.com/assets/4675662/19695342/6ee4bc56-9aa8-11e6-9d91-2cc977aa69fc.png)

### Steps To Reproduce:
1.  Use the Homepage Extended Layout
2. Switch to Mobile Phone Preview 
3. Open the settings for the first slide.
4. Switch to the Design tab and look at the font-size.

**Comment by timayhelen** [comment]
I don't think this is something that is fixable, at least not easily or practically. Let's leave it as is for now.
