### ISSUE TITLE
Update package.json dependencies

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#678]
### Problem:

**submodule-builder:** 
branch: `678-update-package-deps`
Overall: 84 -> 88
DEPENDENCIES ANALYSIS: 89 -> 98
CODE ANALYSIS: 78 -> 78
https://www.bithound.io/github/elegantthemes/submodule-builder/master
https://www.bithound.io/github/elegantthemes/submodule-builder/678-update-package-deps

**Divi:** 
branch: `678-update-package-deps`
Overall: 84 -> 92
DEPENDENCIES ANALYSIS: 94 -> 99
CODE ANALYSIS: 74 -> 85
https://www.bithound.io/github/elegantthemes/Divi/master
https://www.bithound.io/github/elegantthemes/Divi/678-update-package-deps

**Comment by lots0logs** [comment]
Works well for me. No problems, no errors, nothing interesting to report :success:
