### ISSUE TITLE
FB :: Toolset Layouts plugin cooperation 

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#680]
### Problem:

Looks like the FB is not fully compatible with this 3rd party plugin. The customer get a response from their support them:

> Our Developer needs the cooperation of the DIVI developers on this.
> 
> Practically when Divi invokes the builder in the front end, the application takes over the rendering, and it is the Divi builder rendering the whole page, rather than being added to the page with extra markup or an extra layer as other builders do.
> 
> Practically this means that it is not Layouts that is not able to render what it’s done with Divi builder, but it’s Divi builder that it’s not able to render what it’s supposed to render with Layouts, in fact anything you add to the page with the Builder, when Layouts is invoked (of course when the editor is inactive) is rendered normally, without any problem.
> 
> This means that when a resource is assigned to Layouts, it is possible to edit it with Divi Builder only with the backend editor and not with the frontend editor.
> 
> To sum up: Layouts can render Divi Editor controls and Divi Editor made content, while Divi Editor cannot render content produced with Layouts, but it can add any content to Layouts and Layouts will render it, so there is something to fix in Divi rather than in Layouts.
> 
> What we would like to do now is get some specific data from the Developers of the DIVI.
> This is a longer process and it can help if you open a Ticket in their Support forum, pointing out the issue. This would give greater "weight" on the issue and could help to speed up the process of cooperation in-between our and their Developers.

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/Divi #2607](https://github.com/elegantthemes/Divi/issues/2607) via [**ZenHub**](https://www.zenhub.com/)
