### ISSUE TITLE
Border Width Error

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#682]
If you try to adjust a custom border with size, it triggers responsive editing mode and doesn't work correctly. 

1. Edit a blurb module. 
2. Enable "Use Custom Border"
3. Attempt to adjust the border width. 

![border](https://cloud.githubusercontent.com/assets/3333028/19778432/97487392-9c31-11e6-88e4-3a378a2bb2fe.gif)

**Comment by SlavaET** [comment]
@timayhelen can you still reproduce this error? I checked in the latest master and it works fine.

**Comment by timayhelen** [comment]
@SlavaET Yeah it seems to be working fine. Weird.
