### ISSUE TITLE
Detect Failed Save & Launch Failure Modal

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#683]
Would it be possible to detect JS and HTTP errors when performing a save in the Visual Builder? We still have a lot of people that can't save, and what's worse is that it's not always apparent that saving is failing. Usually there is an error involved with the admin ajax request, and if we could detect that when saving and launch a custom error message that would be great. We could launch the standard failure modal, or launch something a bit more specific.

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1622

**Comment by timayhelen** [comment]
I think we could launch the builder failure modal, with a few custom messages. A good one to add would be to detect if mod_substitute is being used, and if the SubstituteMaxLineLength is less that 10M. Then we can suggest that people increase it:

```
<IfModule mod_substitute.c>
SubstituteMaxLineLength 10M
</IfModule>
```

We might also add a suggest to check application firewall settings, such as mod security, since this seems to be a common issue as well.

**Comment by timayhelen** [comment]
I would like to implement the following notice whenever someone saves and that save fails. 

![screen shot 2017-01-24 at 5 12 30 pm](https://cloud.githubusercontent.com/assets/3333028/22273902/4dceb088-e258-11e6-8af3-647e4a03ecc7.png)


The text should read:

> An error has occurred while saving your page. Various problems can cause a save to fail, such as a lack of server resources, firewall blockages, plugin conflicts or server misconfigurations. You can try saving again by clicking **Try Again**, or you can download a backup of your unsaved page by clicking **Download Back**. Backups can be restored using the portability system while next editing your page.

> Contacting your host and asking them to increase the following PHP variables may help: _memory_limit, max_execution_time, upload_max_filesize, post_max_size, max_input_time, max_input_vars_. In addition, auditing your firewall error log (such as ModSecurity) may reveal false positives that are preventing saves from completing.

> Finally, it is recommend that you temporarily disable all WordPress plugins and browser extensions and try to save again to determine if something is causing a conflict.

**Comment by timayhelen** [comment]
@fikrirasyid I am concerned that this, for the most part, wont catch failed saves due to the reasons that most of our customers are experiencing failed saves. For the most part, the save fails due to two reasons:

1. A firewall, such as ModSecurity, is blocking the admin-ajax.php save request. It's unclear why, but it could be due to certain shortcode content in the request triggering a filter. 
2. Lack of server resources, such as a lack of memory or certain request-size limits. 

If a firewall is blocking the save request, I think it might also block the comparison request since it is retrieving similar data. Or does it not work that way?

Similarly, if there is a request limit involved that is blocking admin-ajax.php from sending a certain amount of data, wouldn't that same limit apply to the comparison request?

I wonder if there is an additional method we can use to detect a failed save. Is there a way to catch errors from the console on the admin-ajax.php save request?

**Comment by lots0logs** [comment]
@fikrirasyid The failures we want to catch with this modal all return http error-level status codes on the AJAX request so it shouldnt be necessary to compare the content. Unless I'm missing something here?

**Comment by fikrirasyid** [comment]
@timayhelen @lots0logs the idea of this modal should be able to cover what you're concerning but I'm not 100% sure because I'm still unable to replicate the issue consistently. Basically:

1. VB sent data to backend
2. backend return data to VB in form of simple JSON object
3. VB expects this returned data to have element `save_verification = true`.
4. Unless this specific element is found, the modal notification is triggered

Thus, if:

1. The saved value is different from what is being send, throw modal
2. The saving process failed due to server issue, no verification value being returned, throw modal
3. Basically this works like the loading notification modal: if VB isn't initiated after couple of second for any reason, the modal will kick in

**Comment by timayhelen** [comment]
@fikrirasyid It sounds like it should work then, since the modal is thrown when there is no response. Let's move this through QA @lots0logs

**Comment by timayhelen** [comment]
Looks like the failed save modal always fires for me, even when the save is successful. Also, the modal fires immediately before the save has completed. You will notice the save spinner is still spinning when the modal fires:

![save](https://cloud.githubusercontent.com/assets/3333028/22314874/4dc28572-e318-11e6-8a84-11df03c0340b.gif)

I also noticed a bug with having multiple instances of our core modal. It looks like if one modal fires, and then you close it, and then a different modal fires, the modal will not be sizes or centered correctly. 

![modal](https://cloud.githubusercontent.com/assets/3333028/22314927/9480aed0-e318-11e6-929c-8ba470be526f.gif)

**Comment by lots0logs** [comment]
I can confirm @timayhelen's findings. Something else I noticed is that when you click Download Backup you get the chrome "Are you sure" dialog. You must click "Leave" to complete the download. That will be confusing/scary for users. However, I am pretty sure its not an issue directly related to this PR as it occurs on the live demo when exporting a layout as well. @timayhelen :notsureif: we want to fix it within the scope of this PR or create a new issue for it? 

![2017-01-25_06-39-00-pm](https://cloud.githubusercontent.com/assets/4675662/22315689/f1a16e82-e32d-11e6-86bf-6dc6fb898855.png)

**Comment by timayhelen** [comment]
@lots0logs Yeah we can look at it in another ticket. I am not sure if there is a way to avoid it though.

**Comment by fikrirasyid** [comment]
@lots0logs can you take a look at it again? I noticed a typo which probably caused the issue and I've pushed a fix for it

**Comment by timayhelen** [comment]
@fikrirasyid It seems to work for me, but can you address the modal issue as well?

**Comment by fikrirasyid** [comment]
@timayhelen do you mean this modal issue? 

> I also noticed a bug with having multiple instances of our core modal. It looks like if one modal fires, and then you close it, and then a different modal fires, the modal will not be sized or centered correctly.

**Comment by timayhelen** [comment]
@fikrirasyid Yeah

**Comment by fikrirasyid** [comment]
@timayhelen @lots0logs can you take a look at it again? I'm still unable to create a naturally broken builder, but @lots0logs suggestion to emulate the error by throwing various response code and applying `die()` is quite close to the real-life error and it ables to catch several edge-cases as well.

What I did was basically added the following error code at the beginning of `et_fb_ajax_save()`, causing it throwing error response:

```
	// header("HTTP/1.1 100");
	// header("HTTP/1.1 101");
	// header("HTTP/1.1 200");
	// header("HTTP/1.1 400");
	// header("HTTP/1.1 404");
	// header("HTTP/1.1 500");
	// wp_send_json_error();
	// var_dump( 'pseudo error thrown by PHP' );
	// Break WP by throwing random string

	// die();
```

Several edge-cases that are updated:

- anticipating proper response which contains error code
- anticipating improper response causing by PHP error
- anticipating 200 response which returns `null` (this surprisingly causes lots of error)
- fixing modal behaviour; removing existing modal if there's any before initiating other unsaved notification modal, causing the modal behaves properly on window resize:

*Note: I intentionally break the AJAX response to emulate the unsaved notification window*

![improved-unsaved-modal-behaviour](https://cloud.githubusercontent.com/assets/916442/22319827/e46534d4-e3b8-11e6-8a9d-33dc88bcdbde.gif)

**Comment by timayhelen** [comment]
@fikrirasyid Cool it seems to work for me. I tried just deleting admin-ajax.php to make it fail, haha. Is there additional testing we can do to ensure that there are not any false positives that might cause the modal to fire when the save has not actually failed? I am not really sure how to best QA this. @lots0logs any ideas?

**Comment by timayhelen** [comment]
@fikrirasyid I am still seeing the issue with firing two different modals that are different sizes. The modal that is fired second has the incorrect height and position.

**Comment by fikrirasyid** [comment]
@timayhelen 

> I tried just deleting admin-ajax.php

this is pretty hardcore 😂 

I haven't found further edge-case 🤔 

***

Regarding this:

> I am still seeing the issue with firing two different modals that are different sizes. The modal that is fired second has the incorrect height and position.

Can you mention the steps you took to cause it? On the latest commit, all existing modal should be removed before new modal is appended. Theoretically, it shouldn't happen

**Comment by lots0logs** [comment]
@timayhelen The closest we can get to the actual errors is to use the method I suggested to @fikrirasyid on Slack earlier. Basically choose one of the `header(..)` lines from his [previous comment](https://github.com/elegantthemes/Divi-Beta/issues/683#issuecomment-275304354) and add it at difference places within the callback function that handles the save, followed by `die()`. So for example:
```php
header("HTTP/1.1 500");
die();
```
You can find the callback function `et_fb_ajax_save()` in the builder's `functions.php` file.

**Comment by fikrirasyid** [comment]
@timayhelen I've rechecked the second modal size issue and it appears as expected 🤔  can you mention the steps needed to replicate it? screenshot will definitely help as well.

**Comment by timayhelen** [comment]
You can refer to the gif in my initial comment. It still happens for me:

![9480aed0-e318-11e6-929c-8ba470be526f](https://cloud.githubusercontent.com/assets/3333028/22323686/6182f826-e359-11e6-8f68-6bc2e2f66d75.gif)

**Comment by lots0logs** [comment]
Weird. It never happened for me. I tested this with Divi and with the plugin :thinking:

**Comment by fikrirasyid** [comment]
@timayhelen @lots0logs I've fixed it via https://github.com/elegantthemes/submodule-builder/commit/db9c55a3096f42d68aa24c395dc4df23976dc959 (thanks for the steps to replicate it on Slack):

![683-modal-issue](https://cloud.githubusercontent.com/assets/916442/22324201/78359f16-e3da-11e6-957b-8ba8624b6842.gif)

**Comment by timayhelen** [comment]
Looks good!

**Comment by timayhelen** [comment]
Closing this since it will go through QA as part of the builder sync and auto-save branch.
