### ISSUE TITLE
Cannot read property 'replace' of undefined(…)

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#684]
We have a person complaining about saving not working. This error is occurring while using the builder, though it us unclear how or when:

`bundle.js?ver=3.0.16:8 Uncaught TypeError: Cannot read property 'replace' of undefined(…)`

Any ideas what might be going wrong?

**Comment by timayhelen** [comment]
The customer has provided the shortcode output for the page and the full error:

[Divi One Page - Saving Error with Visual Builder.txt](https://github.com/elegantthemes/Divi-Beta/files/558929/Divi.One.Page.-.Saving.Error.with.Visual.Builder.txt)

**Comment by FDiskas** [comment]
:white_medium_small_square: +1 Me to
