### ISSUE TITLE
VB :: Module settings window stays on the same tab

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#688]
### Problem:

Module settings window stays on the same tab as a child element after saving settings.
For example if you add a new or edit existing Bar Counter and make some changes on Advanced Design tab, after saving changes the parent Bar Counter settings windows stays on Advanced Design tab as well.
The issue exists on all modules where there is a possibility to create child elements (Sliders, Toogles, Bar counters and so on).
Also the issue exists in Divi Builder as well.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1590

**Comment by timayhelen** [comment]
Yeah, I think it would be better to automatically place users in the "Genera" tab whenever they return to the main settings modal from a module child item settings modal.

**Comment by lots0logs** [comment]
@lceberg Please see my review. Thanks! :smiley:

**Comment by lceberg** [comment]
@lots0logs I addressed your feedback. 👍
