### ISSUE TITLE
Launching Theme Customizer + Visual Builder

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#69]
Currently if you have the Visual Builder enabled, and you use the WordPress admin bar to activate the Theme Customizer, the Theme Customizer will load with the visual builder enabled. We shouldn't allow this.

**Comment by timayhelen** [comment]
@SlavaET This fix seems to remove builder CSS from the page. When I load up the page in the customizer, lots of styles are broken.

**Comment by SlavaET** [comment]
@timayhelen can you please explain which CSS you're talking about? I tested and all the css works as expected and styles look good.

**Comment by timayhelen** [comment]
@SlavaET Any CSS created by the builder that gets added to <style type="text/css" id="et-builder-advanced-style">

**Comment by SlavaET** [comment]
Ah, I see. Fixed.
