### ISSUE TITLE
Possible issue with Gallery module in the VB

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#692]
Looks like the VB isn't showing the correct cropped versions of the images in some cases, based on this user's screenshot:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=604039

**Comment by fikrirasyid** [comment]
@timayhelen I've tried to replicate the issue but it appears as expected. I'll ask for user token to further investigate the issue
