### ISSUE TITLE
VB :: Countdown Timer :: Header Font Size doesn't working

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#693]
### Problem:

There is no way to set module header font size.
Also the issue exists in Divi Builder as well.

**Comment by fikrirasyid** [comment]
@dm-chechik can you take a look at it again at latest master? I tried to replicate the issue but It appears to work as expected:

![693-master](https://cloud.githubusercontent.com/assets/916442/20345052/0b4e413a-ac28-11e6-9e9f-08c711e95f2e.gif)
