### ISSUE TITLE
VB :: Filterable Portfolio :: Wrong number of filters

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#695]
### Problem:

It seems VB renders more filters in edit mode.
The issue exists in Divi Builder as well.
Here are filters in edit mode
![image](https://cloud.githubusercontent.com/assets/20072036/19840104/da83703c-9eff-11e6-9ced-7132ea29b0e7.png)

And here are filters on a front page
![image](https://cloud.githubusercontent.com/assets/20072036/19840113/0bb48c2c-9f00-11e6-91ed-a53884e11273.png)
### Steps To Reproduce:

Here are projects to categories assignments
![image](https://cloud.githubusercontent.com/assets/20072036/19840118/380ea80c-9f00-11e6-89b4-bafbb9a40587.png)

Here is the categories tree structure
![image](https://cloud.githubusercontent.com/assets/20072036/19840123/5be00eba-9f00-11e6-9456-9be752188f8e.png)

**Comment by timayhelen** [comment]
@fikrirasyid When I add a filterable portfolio module in this PR, no items show up until I save and refresh the page. 

![bug](https://cloud.githubusercontent.com/assets/3333028/20320992/bbe35cca-ab28-11e6-8ca0-2e724a74cf2b.gif)

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed a fix for it at https://github.com/elegantthemes/submodule-builder/commit/771dc21bd4e30f9aca65eaa529784c2a88cdf845. The issue actually happens at `master` as well. It occurs due to the previous intentional behaviour of only pulling the first computed attribute and ignore the rest computed attributes (Filterable Portfolio has two computed attributes since https://github.com/elegantthemes/submodule-builder/pull/1430). See https://github.com/elegantthemes/submodule-builder/commit/f7a518ea424a60e7447a6e8e2cdf7cc6883c2066#diff-3d118346b9153b174ee444572afed18dR1513: 

```
// initiate the ajax update of the module. Not necessary to send all the fields, send just one to trigger the update
handleAjaxComputedPropertyUpdate({props: new_module}, computedFields[0].name, callback);
```

![695-i2](https://cloud.githubusercontent.com/assets/916442/20344558/d2a01856-ac25-11e6-8ae2-d72a065077d1.gif)

@SlavaET https://github.com/elegantthemes/submodule-builder/commit/771dc21bd4e30f9aca65eaa529784c2a88cdf845 modifies the change you made at https://github.com/elegantthemes/submodule-builder/commit/f7a518ea424a60e7447a6e8e2cdf7cc6883c2066. Can you take a look at it and see just in case I'm missing something? Thanks.

**Comment by SlavaET** [comment]
@fikrirasyid it seems your fix doesn't bring back the js error in history which I fixed a while back.

**Comment by fikrirasyid** [comment]
@slavaET thank you for confirming it 👍

**Comment by lots0logs** [comment]
@fikrirasyid The module appears to "flicker" when selecting/deselecting categories (probably because its re-rendering for both ajax callbacks):

![2016-11-16 11-05](https://cloud.githubusercontent.com/assets/4675662/20357319/1654e95c-abed-11e6-94f5-254b1068aaa8.gif)

**Comment by fikrirasyid** [comment]
@lots0logs can you share the following information:

- Divi's latest commit SHA
- submodule-builder commit SHA
- Layout you use on the page
- List of active plugin you use
- Do you check this on localhost, or live site?

I tried to replicate the flickering issue, but it works as expected. Both ajax call arrives at the (almost) same time and there's no flicker at all:

![695-flicker](https://cloud.githubusercontent.com/assets/916442/20369914/5b907274-ac8e-11e6-853b-bd62726266c7.gif)

my setups are:


- Divi's latest commit SHA: 55b92f17af611be554c0c7e2c5da38b1e6722d4b
- submodule-builder commit SHA: 771dc21bd4e30f9aca65eaa529784c2a88cdf845
- Layout you use on the page: Porfolio Grid (preloaded layout)
- List of active plugin you use: AJAX Thumbnail Rebuild, Duplicate Post, Switch Theme on Admin Bar, WooCommerce, WordPress Importer
- Do you check this on localhost, or live site? Localhost (MAMP)

**Comment by lots0logs** [comment]
@fikrirasyid I tested it on my sandbox site (its a real site). I think that we cannot count on the ajax requests coming back at almost exactly the same time. In the real-world that won't always be the case. I will test the branch again just to confirm that I didnt make a mistake and checkout the wrong branch...

**Comment by fikrirasyid** [comment]
@lots0logs I've tried testing the issue on my sandbox site at http://wordpress-8622-57086-151808.cloudwaysapps.com/portfolio-grid/ but it only happens once per ten attempts; it is quite rare that the returned AJAX call has significant delay on my test site 🤔  can you share more details like what I've asked above so I can reliably replicate the issue? It's quite hard to fix the issue without able to replicate it first.

**Comment by lots0logs** [comment]
@fikrirasyid I provided all the details you asked for. I think you read my comment too quickly? :thinking:

**Comment by fikrirasyid** [comment]
@lots0logs somehow the updated content doesn't appear on the page I was opening :facepalm: thanks for the details, I'll try replicating the issue

**Comment by fikrirasyid** [comment]
@lots0logs anyway, how much project `post type` posts that you have?

**Comment by lots0logs** [comment]
Oh okay! I have over 20 projects in all categories. Also, not sure if it matters but I tested the fullwidth (non-grid) layout for the module.

**Comment by fikrirasyid** [comment]
@lots0logs alright, thank you for confirming it. Looks like the issue can be replicated if the server side process is tricked to be heavier than it is now 🤔

**Comment by fikrirasyid** [comment]
@lots0logs I've fixed the unwanted flickering issue via https://github.com/elegantthemes/submodule-builder/commit/1717f07a3b7285baf721f35ef4eba24a193a6dfc (see the commit message regarding what is being changed). Can you take a look at it? To be safe, please check how other module options which has `computed_affects` works as well. I've checked it and it looks good, but it'd be safer if it is being checked by different person.

**Comment by lots0logs** [comment]
@fikrirasyid It no longer flashes when enabling/disabling a single category. However, there's a new issue and also another issue that remains from before. 

1. No posts are shown when the module is first added to the layout.
2. It still flashes if you enable/disable multiple categories consecutively.

Both issues can be seen in this gif:

![2016-11-17 16-06](https://cloud.githubusercontent.com/assets/4675662/20409777/82aa74d4-ace0-11e6-907c-0d2a02e0937d.gif)

Perhaps we could retrieve the first N posts from all categories when the module is first loaded and cache them so we can reuse them later? :thinking:

**Comment by fikrirasyid** [comment]
@lots0logs I can replicate the second point you mentioned, but I can't replicate the first one. Adding new filterable portfolio automatically shown posts from all categories by default. Is there anything specific that needs to be added (I've tried it on blank page and currently edited page)? Here's how it looks:

![695-new](https://cloud.githubusercontent.com/assets/916442/20451261/ef983294-ae29-11e6-9f02-061b3c70577e.gif)

**Comment by fikrirasyid** [comment]
@lots0logs I've pushed https://github.com/elegantthemes/submodule-builder/pull/1430/commits/1fd56c737b124518efe26f7e8fdffde0ab1f78ba which should fix the flickering issue (details about the issue and how it is being fixed can be seen on the commit message).

I still can't replicate `No posts are shown when the module is first added to the layout.` tho. It works as expected:

![add-new-filterable-portfolio](https://cloud.githubusercontent.com/assets/916442/20454310/8c67a8b2-ae6f-11e6-96d8-11485c2a553c.gif)

Can you re-check it on the updated `695-vb-filterable-portfolio-wrong-number-of-filters`?

**Comment by timayhelen** [comment]
@fikrirasyid Something quite strange happened to me after switching to this branch. All my my Project categories were deleted. I am not sure how it's possible, but I am worried that it might be related to something in the branch. 

![screen shot 2016-11-21 at 3 44 12 pm](https://cloud.githubusercontent.com/assets/3333028/20505386/5dd68944-b001-11e6-97b6-9d43e7a2c324.png)
