### ISSUE TITLE
Yoast SEO cannot "see" text after update.

### ISSUE THREAD

**Issue by rtwintp** [elegantthemes/Divi-Beta#7]
### Problem:
After updating Divi to 2.6.9, Yoast SEO is reporting "The text contains 1 words." (sic) This compounds the extant incompatibility of Divi with perhaps the most popular WordPress SEO plugin, which already cannot "see" images or outbound links within pages built with the Divi Builder.

### Steps To Reproduce:
1.
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
***Note:*** *Will be fixed by elegantthemes/Divi#1805 & elegantthemes/Divi#1830*

**Comment by rtwintp** [comment]
This appears still to be an issue after updating to Version: 2.6.9.1.

**Comment by lots0logs** [comment]
The fix has not been merged yet. It should make it in the next round :smile:

**Comment by rtwintp** [comment]
Thank you! Sorry for my impatience. ;-)
