### ISSUE TITLE
Implement changes?

### ISSUE THREAD

**Issue by Augustin56** [elegantthemes/Divi-Beta#70]
### Problem:

Okay.  I'm a newbie for version 3.0.  It's pretty intuitive.  I'm trying to edit a page I have open, and have done so easily.  I found the Save button at the bottom, but when I pull the page up again, the changes are gone.  And how do I get out of edit mode back to a normal screen any user would see?

### Steps To Reproduce:
1.  Bring up a page.
2.  Click on Enable Visual Builder.
3. Make some edits.
4. Save
5. Close the page and bring it back up again.  Changes are gone!

### Additional Information:

I even tried doing a Save, then bringing the page back up in the normal Wordpress Divi editor and doing an Update.  No dice.  I'm sure there must be a way, but it's not intuitive, if it is.  

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Can you try right clicking in Chrome and choosing "Inspect Element" right before you click the save button? Next click "save" and see if any messages appear in the "Console" tab. Please past the messages here if anything shows up.

**Comment by DeerMtn** [comment]
How does one exit the front end visual editor?

**Comment by SlavaET** [comment]
@Augustin56 do you still have issues in the latest version of Divi Beta?
