### ISSUE TITLE
VB :: Toggle Module in Open State Does not Preview Well

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#700]
### Problem:

For toggle module in visual builder even if we select the state as open it is not visible as open in preview so we can not see the live editing of the content , it does not affect the working of the module after saving and seeing it on live site , May be considered as enhancement for future.

### Steps To Reproduce:
1.  Add a toggle module
2. Make toggle state as open
3. try to see live preview of toggle content

**Comment by SlavaET** [comment]
It was fixed already.
