### ISSUE TITLE
VB :: Login Module :: There is no chance to see customizations of input fields and button inside builder

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#701]
### Problem:

When you editing the Login Module there is no Username, Password and Button because you logged in. I think the Module should show the fields and button while editing (customizing).

**Comment by lots0logs** [comment]
@SlavaET Can we do this for the BB's Live Preview Mode as well?

**Comment by SlavaET** [comment]
@lots0logs done.

**Comment by lots0logs** [comment]
@SlavaET Hmm...still the same as before in the BB Live Preview.

**Comment by SlavaET** [comment]
@lots0logs sorry, I applied it to preview in Customizer, not to BB preview. 
Fixed in BB preview as well.

**Comment by timayhelen** [comment]
@SlavaET I noticed that the position of the form fields are different in the VB and BB:

![screen shot 2016-11-30 at 3 14 46 pm](https://cloud.githubusercontent.com/assets/3333028/20775436/ca0c3aea-b70f-11e6-9eef-63ef5661e873.png)

![screen shot 2016-11-30 at 3 14 50 pm](https://cloud.githubusercontent.com/assets/3333028/20775439/cc2b77fa-b70f-11e6-9b9f-db23e97a3004.png)

**Comment by SlavaET** [comment]
@timayhelen please clear cache of your browser and check again. Looks like updated styles are not loaded. It works on my end:
![image](https://cloud.githubusercontent.com/assets/3446682/20781652/a4ff69ee-b7ae-11e6-9a09-b2875409b1d9.png)

**Comment by lots0logs** [comment]
@SlavaET I'm seeing the same thing as Nick:

![2016-12- 1_01-16-55-pm](https://cloud.githubusercontent.com/assets/4675662/20808539/95995554-b7c8-11e6-8033-d24ec1d1f7d1.png)
_____________________________________

![2016-12- 1_01-16-06-pm](https://cloud.githubusercontent.com/assets/4675662/20808546/9c866cda-b7c8-11e6-8a8a-357838cf15aa.png)

**Comment by SlavaET** [comment]
@lots0logs please make sure you see the css code as on my screenshot. If you don't see that code, then old version of css file cached in your browser. 
Try to hard refresh the page several times ( I see the same results as on your screenshot when I first added the code, but hard refresh helped )

**Comment by timayhelen** [comment]
@SlavaET It seems to be working for me now.
