### ISSUE TITLE
Countdown Timer :: Design : Number font settings applying to Label as well

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#705]
### Problem:
Here is a screencast: http://screencast-o-matic.com/watch/cD6wosjdpj

The main problem is the font style (bold, underline, uppercase and italic), there is no way to overwrite these from the **Label** font style if they are set for **Number**.

**Comment by fikrirasyid** [comment]
I've fixed this at https://github.com/elegantthemes/submodule-builder/issues/1440 which is submitted for https://github.com/elegantthemes/Divi-Beta/issues/694. Thus, let's close this issue and centralize the number font style issues at https://github.com/elegantthemes/submodule-builder/issues/1440
