### ISSUE TITLE
Email Optin :: Design : Button Icon Placement

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#709]
### Problem:

Here is a screencast: http://screencast-o-matic.com/watch/cDXVXxjKY5

**Left vs. right:**

<img width="978" alt="capture" src="https://cloud.githubusercontent.com/assets/1061516/19888584/1f516a32-a038-11e6-859f-6065ae6ee65f.PNG">

**Comment by timayhelen** [comment]
@fikrirasyid There are various issues with custom button styles in other modules in this PR. 

- [ ] When a button is switched to "left" icon, the icon does not appear at all unless you select a custom icon:

![button1](https://cloud.githubusercontent.com/assets/3333028/20370634/86f85e06-ac14-11e6-8690-b8716ed71b30.gif)

- [ ] After selecting a custom icon it appears, but then the left padding of the button becomes uneven. There is not enough padding on the left side:

![screen shot 2016-11-16 at 3 51 59 pm](https://cloud.githubusercontent.com/assets/3333028/20370648/9f01f0d4-ac14-11e6-90d5-156b977771d2.png)

- [ ] Left aligned icons are also way too close to the button text when compared to master:

![screen shot 2016-11-16 at 3 52 35 pm](https://cloud.githubusercontent.com/assets/3333028/20370666/bcf5f810-ac14-11e6-90f5-9c8943d70121.png)

**Comment by fikrirasyid** [comment]
@timayhelen have you re-run `grunt` on `/Divi` dir? It has been handled but it requires `.css` update. Take a look at these buttons below:

Left Icon | Right Icon
--------- | -----------
Default icon + On Hover | Default icon + On Hover
Custom Icon + On Hover | Custom Icon + On Hover
Default icon + Always Visible | Default icon + Always Visible
Custom Icon + Always Visible | Custom Icon + Always Visible

![709-button](https://cloud.githubusercontent.com/assets/916442/20370883/ac6ed1c2-ac93-11e6-9396-2e83b0e1ef49.gif)

Thus actually three issues you mentioned above have been fixed 🤔

**Comment by timayhelen** [comment]
@fikrirasyid Looks like you are right, never mind!

**Comment by fikrirasyid** [comment]
@timayhelen glad to hear it working as expected (҂'̀⌣'́)9
