### ISSUE TITLE
VB :: Filterable Portfolio Module : Projects not showing up at first

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#710]
### Problem:

Here is a screencast: http://screencast-o-matic.com/watch/cDXVlijKrL

As soon as you change the Layout type it displays correctly.

**Comment by fikrirasyid** [comment]
This issue has been fixed at https://github.com/elegantthemes/submodule-builder/issues/1430 which is submitted for https://github.com/elegantthemes/Divi-Beta/issues/695
