### ISSUE TITLE
VB :: Filterable Portfolio Module : Include Categories changes do not reflect

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#711]
### Problem:

Here is a screencast: http://screencast-o-matic.com/watch/cDXVl2jK3e

As soon as you save and exit the visual builder it works.

**Comment by fikrirasyid** [comment]
This is duplicate of https://github.com/elegantthemes/Divi-Beta/issues/695. I've submitted a PR for it at https://github.com/elegantthemes/submodule-builder/issues/1430
