### ISSUE TITLE
Post Slider Module :: Shortcodes Displayed On Frontend Page

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#716]
### Problem:

As of 3.0.17, the post slider module (and possibly other post-based modules) display shortcodes on the front end page. The issue does not occur inside the VB, it only occurs on the page itself. 

http://et.falgout.us/divi/divi-builder-post-2/

### Additional Information
Issue occurs when the post being displayed in the slider is the same as the post the slider appears on.

**Comment by SlavaET** [comment]
This issue appears only in `Post Slider` and `Fullwidth Post Slider` and in case post contains one of the following modules:
- Blog
- Portfolio
- Post slider
- Fullwidth Post Slider

To avoid infinite loops we shouldn't render the shortcode of the post in case it contains one of the above modules, but this mechanism didn't work correctly in Post Sliders. I fixed it in my PR and now we're back to original behavior - if post contains one of the above modules we do not output the content of such a post inside the Post Slider ( as well as in the Blog module ).

**Comment by lots0logs** [comment]
@SlavaET Is it possible to simply exclude the shortcodes for post-based modules from the content that we render inside of post based modules?

**Comment by SlavaET** [comment]
@lots0logs can you please explain? I'm not sure that understand your idea

**Comment by lots0logs** [comment]
I mean something like the `et_pb_strip_shortcodes()` function @uportnykh created but only strip the shortcodes for post based modules and keep the others as they are. Does that make sense? If a code example would help let me know...

**Comment by SlavaET** [comment]
I think I understand now. Basically we should truncate only the shortcodes I mentioned in my previous message and keep the rest.

**Comment by lots0logs** [comment]
Yes exactly. I mean if its possible. I'm pretty sure it is. What do you think?

**Comment by SlavaET** [comment]
@lots0logs done. Please check now.

**Comment by lots0logs** [comment]
@SlavaET Awesome :+1:  There's just one thing I noticed: take a look at the category view compared to the blog module view, notice the post meta:

[Category Page](http://et.falgout.us/divi/category/caption-test/)
[Blog Module](http://et.falgout.us/divi/)

**Comment by SlavaET** [comment]
@lots0logs I only see the difference in date format and comments count, but these are configurable parameters. Is it the issue you're talking about?

**Comment by lots0logs** [comment]
@SlavaET No, sorry. I mean how the post meta info for the post that is displayed in the post slider appears on category pages (so the result is that you see two post meta info elements on the category pages). The post meta from the post slider is not shown by the Blog Module. It only happens on category/archive pages.

**Comment by SlavaET** [comment]
@lots0logs ah, I see. But it's unrelated to the original issue and it looks more like an improvement for index pages. Probably we should open a new issue for that which is not high priority I assume.
