### ISSUE TITLE
VB :: Toggle Module :: Open and Close state on mouse hover

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#718]
### Problem:

If you click on open/close button inside VB the state isn't change while mouse hover the module. As soon as you move mouse from the module the state will change.
The issue exists in Divi Builder as well.

The screencast here -> http://screencast-o-matic.com/watch/cDXnrTj7mt

**Comment by lots0logs** [comment]
This was fixed in elegantthemes/submodule-builder#1409
