### ISSUE TITLE
VB :: Video Slider :: Display Image Overlays on Main Video 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#719]
### Problem:

The setting doesn't show overlays inside builder.
In Divi Builder the issue exists as well.
![image](https://cloud.githubusercontent.com/assets/20072036/19950369/0a3fec96-a168-11e6-81a5-08771d78fee2.png)

**Comment by lots0logs** [comment]
@SlavaET The overlays are working for OEmbed videos but not for HTML5 videos. We recently implemented overlays for HTML5 videos for the Video Post Format when posts are displayed in post listings and Blog Module so we should do the same in this case.

**Comment by SlavaET** [comment]
@lots0logs can you please explain a bit? I'm not sure that understand how you can insert the HTML5 video into the Video Slider. It allows adding video from the Media Library or from the 3rd party source like YouTube. Probably I'm missing something 🤔

**Comment by lots0logs** [comment]
@SlavaET Sorry I should have posted a screenshot with that to make it more clear :sweat_smile: 

Here is a screencast. The first video is an OEmbed Video. The second video is HTML5 video. Notice how the second one doesn't have an overlay image with play icon in the center.

![2016-11-13 23-33](https://cloud.githubusercontent.com/assets/4675662/20254429/08d291c0-a9fa-11e6-8d1b-ea5fdd61db7e.gif)

**Comment by SlavaET** [comment]
@lots0logs hm, as far as I understand correctly you get see this issue when you're using the uploaded video which we render as HTML5 element. I tested with both YouTube video link and with uploaded MP4 video and overlays seems to work fine on my end:

![video-slider](https://cloud.githubusercontent.com/assets/3446682/20254723/42629446-aa61-11e6-9568-09ec6846417d.gif)


Can you try clearing the cache and check again?
