### ISSUE TITLE
Gallery :: Inconsistent Slider After Automatic Animation is toggled

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#72]
### Problem:

In Gallery module, if a module is set to slider layout then automatic animation is turned on then later is turned off, the layout becomes inconsistent:

![gallery auto slide leftover](https://cloud.githubusercontent.com/assets/916442/17795951/eced2896-65e6-11e6-8054-6820144b20f6.gif)

### Steps To Reproduce:
1 Add gallery module
2. Set to slider layout
3. Turn on `automatic animation`. 
4. Turn off `automatic animation`
5. Try navigating between slide item using < and > icon

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
Fixed. Also fixed one more issue found during the fixing - adding new gallery from the Visual Builder thrown js error and broke the page.

**Comment by timayhelen** [comment]
@SlavaET Looks like there is also an issue with adjust the automatic slider transition speed. Sometimes when adjusting it, it breaks the animation and the transition between slides becomes glitchy. It may have to do with typing 1,0,0,0 and have split seconds of "1" as the transition speed. 

![slider](https://cloud.githubusercontent.com/assets/3333028/17889504/673eaac4-68e5-11e6-99c4-54fbf3458e2a.gif)

**Comment by SlavaET** [comment]
@timayhelen fixed.
