### ISSUE TITLE
Theme Customizer :: Background Images

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#720]
### Problem:

While the background images looks nice and sharp on desktop, no matter what view port size is, on mobile devices such as iPhone (5s, 6, 6+) and Samsung (S5, S6 and S7) the image looks stretched out which result in bad image quality.

### Steps To Reproduce:
1.  download this image: http://leemusicproduction.com/wp-content/uploads/2016/10/COVER-SIMPLU-nou-nout-jpg.jpg
2.  set as background image in Theme customizer
3. check on any mobile device

**Comment by lots0logs** [comment]
Sections are much taller when viewed on mobile devices. The height of the section affects the display of the background image. This is not a bug. Its simply how CSS background images work.
