### ISSUE TITLE
VB :: Add From Library :: Incorrect displaying of items with long names

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#725]
### Problem:

Items with long names are not displaying correctly.
![image](https://cloud.githubusercontent.com/assets/20072036/20041040/f530e616-a473-11e6-8907-d9c2b4309eef.png)

**Comment by lots0logs** [comment]
@fikrirasyid Could we use CSS whitespace & ellipsis properties here so that its clear when the entire name is not visible?

**Comment by fikrirasyid** [comment]
@lots0logs do you mean instead of doing this:

```
This is very long
title name and 
~~sometimes it gets~~ --> invisible
~~cut by max-height~~ --> invisible
```

We should display it like this instead:

```
This is very long
title name and...
```

This is looks solid actually. I'll find a way to do it

**Comment by lots0logs** [comment]
@fikrirasyid Yes. Exactly. This is what I had in mind btw: https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated the ellipsis properties at https://github.com/elegantthemes/submodule-builder/commit/670ea0521452b7a20b1e03e2511d34a4cf9520eb. There are several things that need to be noted tho: It forces the item to have one line only:

![screen shot 2016-11-22 at 4 40 52 am](https://cloud.githubusercontent.com/assets/916442/20501911/635d00a6-b06e-11e6-9f1c-0dd340f6e35d.png)

I personally think that this looks good tho.

**Comment by lots0logs** [comment]
@fikrirasyid 
>There are **several** things that need to be noted tho

I only see one thing :confused:  lol

**Comment by lots0logs** [comment]
I kind of think there isn't enough padding applied to each item but since its not in the scope of this PR I'll let @timayhelen make the call on that :wink:

**Comment by fikrirasyid** [comment]
@lots0logs I initially had several things to be written, but as I wrote I realized that there was only one thing that really mattered so I erased the list but forgot to change the `pronoun` 😅
