### ISSUE TITLE
VB :: Role Editor :: Settings Types issues

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#726]
### Problem:

There are some issues with Settings Type settings.

Disabled **Edit Colors**
In VB I can see some color settings under Design tab and in custom styles for button.
Also I can change color in inline editor.

Disabled **Edit Fonts**
Not sure however I can edit font in custom styles for button.
Also I can change font in inline editor.

Disabled **Edit Content**
Seems the setting is not working at all. I can edit text inside any module.

The issues exists in Divi Builder as well. 

### Attached PRs
https://github.com/elegantthemes/submodule-builder/issues/1554

**Comment by SlavaET** [comment]
Fixed.
The only issue I cannot reproduce:
>Disabled Edit Content
Seems the setting is not working at all. I can edit text inside any module.

@dm-chechik can you please check it in the latest version of Builder? It seems to work as expected and I cannot edit content when `Edit Content` is disabled in Role Editor.

**Comment by SlavaET** [comment]
@lots0logs done. Please check again.

**Comment by lots0logs** [comment]
@SlavaET When Fonts are disabled in the role editor, it removes **everything** except the admin label in the General Tab and **everything** except colors in the Design Tab. Vise-versa when Colors are disabled.

**Comment by SlavaET** [comment]
@lots0logs fixed.

**Comment by lots0logs** [comment]
@SlavaET Hmm..now when fonts are disabled it removes both the font and color options from the modules.

**Comment by SlavaET** [comment]
@lots0logs which color options you're talking about? If you're talking about `font color` options, then it's expected, because these options are categorized as `font` options so they become hidden when you disable font editing. All other color options are not affected. It's the same in BB.

**Comment by lots0logs** [comment]
@SlavaET Hmm..now that you mention it, I'm not sure. I can't remember :sweat_smile: . I'll check it again and let you know!
