### ISSUE TITLE
VB :: Blog Module :: Body Font settings are also applied to the header and meta text

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#730]
### Problem:

![screen](https://cloud.githubusercontent.com/assets/20072036/20064954/706320e8-a51d-11e6-976d-4445677bd29f.gif)
The issue exists in Divi Builder as well.

**Comment by lots0logs** [comment]
This is being discussed on elegantthemes/divi-builder#633
