### ISSUE TITLE
VB :: Blurb Module :: Body Font settings are also applied to the header and blurb icon 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#731]
### Problem:

![screen](https://cloud.githubusercontent.com/assets/20072036/20065976/16d2ce3a-a521-11e6-955f-1071757e8c8a.gif)
The issue exists in Divi Builder as well.

**Comment by lots0logs** [comment]
This is being discussed on elegantthemes/divi-builder#633

**Comment by timayhelen** [comment]
We should prevent this from affecting the icon.

**Comment by fikrirasyid** [comment]
I've submitted https://github.com/elegantthemes/submodule-builder/issues/1420 which should fix the body's font style italic affects icon issue.

Related to header - body font style relationship issue, I notice that there is an issue that need to discussed and fixed holistically. Thus I reviewed the issue and opened https://github.com/elegantthemes/Divi-Beta/issues/758 for it.
