### ISSUE TITLE
Call To Action :: Body Font affect Title

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#735]
### Problem:

![animation](https://cloud.githubusercontent.com/assets/9657712/20099474/ce9f77d6-a5e2-11e6-95c1-139bbfbd44dd.gif)

Same issue in the Divi Builder plugin

**Comment by dm-chechik** [comment]
Also font is applied to the button

**Comment by dm-chechik** [comment]
The same with Body Letter Spacing option.
