### ISSUE TITLE
VB :: Column vertical margins are absent at tablet/mobile layout

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#737]
### Problem:

The margins are absent at tablet/maobile layout
![image](https://cloud.githubusercontent.com/assets/20072036/20121580/6f5dac2a-a623-11e6-86c3-daeb55f261cd.png)

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/divi-builder #775](https://github.com/elegantthemes/divi-builder/issues/775) via [**ZenHub**](https://www.zenhub.com/)
