### ISSUE TITLE
W3C :: Element style not allowed as child of element body in this context.

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#738]
### Problem:

The issue is that the `et-builder-advanced-style` and `et-builder-page-custom-style` are loaded in the `<body>` I think those should be loaded in the header

https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.elegantthemes.com%2Fpreview%2FDivi%2F

<img width="960" alt="screen shot 2016-11-09 at 10 29 42 am" src="https://cloud.githubusercontent.com/assets/1719735/20131642/73907388-a667-11e6-8b7f-9a1613f32610.png">

**Comment by lots0logs** [comment]
This was discussed in the past. That error is a false positive.

**Comment by eduard-ungureanu** [comment]
@lots0logs I see that those two `<style>` tags are children elements of the `<body>` shouldn't those be in the `<head>`? I just want to make sure we are on the same page on this one:

<img width="960" alt="screen shot 2016-11-14 at 1 14 17 pm" src="https://cloud.githubusercontent.com/assets/1719735/20262788/6d63f2e2-aa6c-11e6-89fd-15275ebb9f26.png">
