### ISSUE TITLE
Move 1 Column Text Module Resulted in Module Disappearing

### ISSUE THREAD

**Issue by bpitts82** [elegantthemes/Divi-Beta#74]
### Problem:

Moved 1 Column (minus sidebar) text module around page and then dropped it back in it's original spot and it disappeared.  

### Steps To Reproduce:
1.  Made minor adjustment to text module width on left side
2.  Moved text module around page with mouse hold
3.  Intended to drop text module back in original placement
4.  Text module disappeared

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac

**Operating System**: OSX

**Browser**: Safari

**Screen Resolution**: 5120 x 2880

**Screenshots**: 
<img width="1304" alt="screen shot 2016-08-18 at 9 37 42 pm" src="https://cloud.githubusercontent.com/assets/3269673/17796192/e61c7396-658c-11e6-866d-ab1f2bfc1da4.png">

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@bpitts82 I can't seem to replicate it. Can you please check whether you can reproduce this issue in the latest version of Divi Beta? We added a lot of improvement and fixes for drag and drop functionality and looks like this issue was fixed already.

**Comment by bpitts82** [comment]
All set now.

Thank you,
--
Brandon Pitts
