### ISSUE TITLE
nofollow attribute stripped from links in footer credits

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#740]
### Problem:
Not sure if this is new with Divi 3 or not, but when rel="nofollow" is added to a link element in 
Theme Customizer ==> Footer ==> Bottom Bar ==> Edit Footer Credits,   
it is stripped from the link on save.

### Steps To Reproduce:
1.  
2. 
3. 
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
We use a whitelist system for allowable code, so we need to ad the rel attribute to the list.

**Comment by SlavaET** [comment]
**Note:** the fix requires 2 branches:
- `Divi` - https://github.com/elegantthemes/Divi/issues/2631
- `submodule-core` - https://github.com/elegantthemes/submodule-core/issues/45

**Comment by lots0logs** [comment]
@timayhelen While were're here, I think we should change the `<p>` tag to a `<div>` tag. We're seeing a lot of forum tickets with footer problems caused by invalid HTML structure due to the fact that we are wrapping the contents of footer credits option in a paragraph tag.

**Comment by timayhelen** [comment]
@lots0logs @SlavaET Sure that sounds fine to me.

**Comment by SlavaET** [comment]
@lots0logs done.
