### ISSUE TITLE
Divi Builder :: Blog Module :: Sticky post

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#744]
### Problem:

In the most recent of Divi the sticky post option is ignored by the Blog Module, I have over 15 blog post and only one is set to be sticky. The expected behavior will be that the sticky post will be shown on the first page of the blog module, but it doesn't.

Could this be related to https://github.com/elegantthemes/Divi-Beta/issues/511?

**Comment by lots0logs** [comment]
As per Codex, sticky posts only affect the home page when it is set to display posts. Currently the blog module does not support handling sticky posts specially so it will behave how WordPress behaves by default.
