### ISSUE TITLE
Blog Module :: Offset number issue

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#747]
### Problem:

When the offset number is set to 1 the blog module removes two posts instead of just one. **This only occurs on VB mode, the front end looks fine.**

![22](https://cloud.githubusercontent.com/assets/16414613/20239920/c41a95ba-a903-11e6-99a4-5515aa9f9f26.gif)

**Comment by SlavaET** [comment]
@FaycalBoutam I cannot reproduce this issue in the latest master. Can you please check whether you still see the issue or not?
