### ISSUE TITLE
Multisite Testing :: Beta Tester Plug in not responding for update

### ISSUE THREAD

**Issue by trueink** [elegantthemes/Divi-Beta#75]
### Problem:
Testing on a Multisite Network :: Beta Tester Plug in not responding for update.  Not sure if the beta was meant for multisite.

### Steps To Reproduce:
1. Created new site in multisite network
2. updated everything including wordpress 4.6
3. Installed new / fresh Divi theme downloaded from ET
4. Assigned theme to newly created network site and activated theme
5. installed beta tester plug in and activated
6. in network admin > dashboard > updates tried the suggested "check again" multiple times with no success.
7. Changed the version of Divi to 2.9.1 and tried the "check again" button several more times.  No response.

**Comment by timayhelen** [comment]
Sorry about that. The plugin doesn't actually add any special update functionality, that is contained in the theme. So if update notifications work for you normally, then this one should show up eventually. I am going to close this for now so we can keep this repo for Divi 3.0 related issues, but we will follow up with this internally.

**Comment by cyborge** [comment]
The issue mentioned in this post persists. I too have a Wordpress 4.6 Multisite with Divi and the Beta Tester plugin installed and activated. No updates are available even after modifying the styles.css.
