### ISSUE TITLE
VB :: Builder unsaved changes dialog does not always displayed

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#751]
### Problem:

I'm not sure this is the normal behavior. However if I trying to close a browser tab or click to the **Go to back** browser button I see the standard WP browser dialog **Do you want to leave this site?** instead of builder **You Have Unsaved Changes** dialog.
The issue exists in Divi Builder as well.
![screen](https://cloud.githubusercontent.com/assets/20072036/20246727/8c7aafa2-a9ce-11e6-8715-361c451e8506.gif)

**Comment by timayhelen** [comment]
This is normal behavior. We were not able to trigger the modal unless something on the page was being clicked. Browser back buttons were outside our scope of control.
