### ISSUE TITLE
Slider Module :: CSS Parallax Effect issue 

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#752]
### Problem:

When **Use Parallax effect** option is enabled the slider background is displayed incorrectly.
![screen](https://cloud.githubusercontent.com/assets/20072036/20247350/fbc8c054-a9da-11e6-8d42-8228aa5c7120.gif)

**Link To Download Layout JSON File**:
https://www.dropbox.com/s/d5quw6q14gp6xi6/slider-module-css-parallax.zip?dl=0

**Comment by SlavaET** [comment]
I fixed this issue in the following PR - https://github.com/elegantthemes/Divi-Beta/issues/607
