### ISSUE TITLE
Tabs Module :: Transparent line under the active tab

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#754]
### Problem:

The 1px transparent line appears under the active tab.
The issue exist in Divi Builder as well.
![image](https://cloud.githubusercontent.com/assets/20072036/20248533/3172355c-a9f7-11e6-9368-51d6e91aec63.png)

**Link To Download Layout JSON File**:
https://www.dropbox.com/s/2lja4y07u4019k6/tabs-line.json?dl=0

**Comment by lots0logs** [comment]
Let's track this on #756
