### ISSUE TITLE
Post Title Module :: Background color option 

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#755]
### Problem:

I'm not sure what is this option do (design tab -> Background color)? You can add a bg color from General tab -> Use Text Background Color.

![divi builder demo just another wordpress site](https://cloud.githubusercontent.com/assets/16414613/20248784/3a756a52-a9e3-11e6-91d1-3f6f181a2229.png)

**Comment by fikrirasyid** [comment]
@FaycalBoutam both of the options work. Background option changes the `.et_pb_post_title` background while text background option changes the `.et_pb_post_title .et_pb_title_container` background. You need to remember to change the opacity of `background color` option tho:

![755-master](https://cloud.githubusercontent.com/assets/916442/20369502/db85b3a2-ac8b-11e6-82f7-da2266e88056.gif)
