### ISSUE TITLE
Tabs Module :: Individual tab background does not fit to the whole tab area

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#756]
### Problem:

The issue exists in Divi Builder as well.
![image](https://cloud.githubusercontent.com/assets/20072036/20248842/72ba3c02-a9fd-11e6-88a5-5dc84bf2abbb.png)

**Comment by lots0logs** [comment]
@SlavaET If you apply `background-color` in the Custom CSS tab for one of the tabs, it does not override the color that is configured in the tab's Advanced Design Settings (styles in custom css tab should always override styles from advanced design settings).

**Comment by SlavaET** [comment]
@lots0logs fixed. I changed several selectors in the Tab module and Tab item to make it work correctly, so it may possibly bring some issues with custom css for our customers. But now our options work correctly.

**Comment by lots0logs** [comment]
@SlavaET The selectors for the individual tab content elements don't look right:

|Field|Currently|Should Be|
|:---|:---|:---|
|Before|.et_pb_tab_0:before|.et_pb_tabs_0 .et_pb_tab_0:before|
|Main Element|.et_pb_tabs div.et_pb_tab_0.et_pb_tab|.et_pb_tabs_0 .et_pb_tab_0|
|After|.et_pb_tab_0:after|.et_pb_tabs_0 .et_pb_tab_0:after|

Basically with how they are now, adding custom styles to one tab would affect the tab at that index position in all tab modules on the page.

**Comment by SlavaET** [comment]
@lots0logs are you sure? Did you check that?
Every single tab on a page ( as well as every single slide, pricing table, toggle, etc ) has its unique index and the situation you described is impossible unless you modify the Divi code and change the mechanism which calculates the module indexes 😉

**Comment by lots0logs** [comment]
@SlavaET No I didn't test it specifically. Though if its like you are saying then the selectors we are showing to the user in the builder are not actually the selectors being used (in which case that needs to be fixed). I'll test it more on Monday and let you know...

**Comment by SlavaET** [comment]
@lots0logs hm, selectors from the `Currently` column in your table look right and we actually use them.

**Comment by lots0logs** [comment]
@SlavaET Okay, in that case how does this selector not affect every Tabs Module on the page? 
```
.et_pb_tabs div.et_pb_tab_0.et_pb_tab
```
Should it not start with `.et_pb_tabs_0` so that it affects only the module it is supposed to?

**Comment by SlavaET** [comment]
@lots0logs every tab on a page has unique order class no matter where it's located and there is no possibility that we have 2 tabs with `et_pb_tab_0` class on a page. Unless you add this class manually somehow.
![image](https://cloud.githubusercontent.com/assets/3446682/20514313/60192edc-b0b5-11e6-8b7f-d3ae846b1e7b.png)

**Comment by lots0logs** [comment]
I was thinking that the number started over at 0 inside each module..omg 

![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/20514469/ab66cbb0-b051-11e6-9c76-630b50ddf2f2.gif)

sorry! :sweat_smile:

**Comment by timayhelen** [comment]
@SlavaET This causes various issues with the tab's design.

1. The tabs text no longer lines up correctly. 

2. The active tab text bounces up when activated. 

![screen shot 2016-11-22 at 11 40 51 am](https://cloud.githubusercontent.com/assets/3333028/20539090/b9c474a8-b0a8-11e6-8ae2-8efa28a55e72.png)

The negative margin isn't a good solution in this case since it makes things uneven.

**Comment by SlavaET** [comment]
@timayhelen fixed. Please check it now.

**Comment by timayhelen** [comment]
@SlavaET It looks like background colors and images for the overall tab module and individual tab items do not fill the whole tab area:

![screen shot 2016-11-23 at 4 30 11 pm](https://cloud.githubusercontent.com/assets/3333028/20582908/2de8ef84-b19a-11e6-8a3f-7794c9871314.png)

I think that's what the original post was about. Can we make it fill the whole area?

**Comment by SlavaET** [comment]
@timayhelen hm, it works correctly on my end:
![tabs-bg](https://cloud.githubusercontent.com/assets/3446682/20587807/91b923b2-b23a-11e6-8dfd-c8dfebd4da92.gif)


Can you please export the layout of that page I'll check that.

**Comment by lots0logs** [comment]
Works fine for me. 

***Note:*** Testing this branch with the VB requires pulling from the latest `master` of `submodule-builder`
