### ISSUE TITLE
Text Module :: Header font options do nothing.

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#763]
### Problem:

Not sure why that option is added in the first place. I tried to add an H2 tag but the header font options don't work on it:

![divi builder demo just another wordpress site](https://cloud.githubusercontent.com/assets/16414613/20323040/284dc842-ab73-11e6-9846-919f2dc2daad.png)

**Comment by timayhelen** [comment]
I think it only works for H1 tags, which is by design since we don't want to have one settings change the size of all header types.

**Comment by FaycalBoutam** [comment]
@timayhelen We could add a setting for each tag, at least to the text module.
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=618183&p=3412642
