### ISSUE TITLE
VB :: Incompatibility with Page in Widget plugin

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#768]
### Problem:

The FB won't start on pages where **Page in Widget** widget is used.

### Steps To Reproduce:
1. Place a **Page in Widget** widget into the footer for example
2. Select any page which will be displayed inside the widget
3. Try to enable Visual Builder

**Comment by lots0logs** [comment]
@dm-chechik Explain to the customer that we cannot guarantee compatibility with 3rd-party plugins. Also advise them on how they can accomplish what it is they use that widget for using Divi's built-in features.
