### ISSUE TITLE
Optin module :: Mailchimp Does Not Work

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#770]
### Problem:
Optin module does not work again. I apply API and enable Regenerate MailChimp Lists but it does not load mailchimp lists in Optin module, or still loads old information. It does not work correctly on my local machine but on customer's website it does not work at all here:
http://meteoricrevenue.com/

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=616607

Please ask me for a token if you need.

**Comment by lots0logs** [comment]
@kary4 Currently the Mailchimp integration requires the `curl_init()` function to be available on the server. Ask the customer to check with their host to see if that function is available.

**Comment by kary4** [comment]
@lots0logs Thank you, will do and let you know the result.

**Comment by kary4** [comment]
@lots0logs The answer is that: All curl_init functions are available per the host.

Actually I was able to reproduce the problem locally, not sure if it's something specific for the customer..

**Comment by lots0logs** [comment]
@kary4 Could you get a token from the customer and send it to me on Slack? Thanks!

**Comment by kary4** [comment]
Sure, just asked.
