### ISSUE TITLE
VB :: Strange builder settings button behavior

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#775]
### Problem:

I accidentally discovered the strange behavior of the button.
![screen](https://cloud.githubusercontent.com/assets/20072036/20397996/b0449ff2-acfc-11e6-8336-2db001202606.gif)

**Comment by fikrirasyid** [comment]
@dm-checknik can you elaborate more on how to replicate the issue? I've tried to replicate the issue based on your attached gif alone on latest `master` by doing the following:

1. Install + configuring Bloom
2. Install + configuring Monarch
3. Replicating the layout content (tabs + accordion module)
4. Replicating the exact same steps as displayed on the animated gif above

 but it looks as expected:

![775-master](https://cloud.githubusercontent.com/assets/916442/20454943/8b9dbbc6-ae81-11e6-80bf-d473b84a7382.gif)

**Comment by dm-chechik** [comment]
@fikrirasyid It seems this is a temporary issue. I can't reproduce it too. Just tried in incognito window.
Sorry :) Anyway if I'll notice the same behavior I'll let you know

**Comment by fikrirasyid** [comment]
@dm-checknik alright, I'll close this issue for the time being then. If you're able to replicate the issue, feel free to re-open it :)
