### ISSUE TITLE
VB :: Debug log output

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#778]
### Problem:
When loading the VB on a page where the Homepage Extended layout has been applied, the following is output to the debug log:
```
[17-Nov-2016 22:21:58 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[17-Nov-2016 22:21:58 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[17-Nov-2016 22:22:00 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
[17-Nov-2016 22:22:00 UTC] PHP Notice:  Array to string conversion in /srv/et.falgout.us/wp-includes/shortcodes.php on line 326
```
It does not occur when loading the page itself on the frontend.

**Comment by SlavaET** [comment]
@lots0logs can you please check whether you see this error if you remove the Portfolio Module from the page? If yes - do you have any projects made with Builder? What's the content of such a projects?
I tested different combinations, but cannot reproduce this error.

**Comment by lots0logs** [comment]
@SlavaET Yeah I have a few projects that are using the Project Extended Layout actually.

**Comment by SlavaET** [comment]
@lots0logs hm, still no result.
Can you check whether this error occurs on any other page with Fullwidth Portfolio?

**Comment by lots0logs** [comment]
@SlavaET It's late here :sleepy:  I created a login for you on my sandbox site. You should have received the password on your gmail. You can use WPIDE plugin to view the debug log. If you dont get around to it then I will check on it when I wake up :smiley:

**Comment by SlavaET** [comment]
@lots0logs I checked on your test website and cannot reproduce it.
Looks like the issue is related to specific content of your projects ( which I have no access to ) or maybe you got this error on the specific branch?

**Comment by lots0logs** [comment]
@SlavaET You have full access: http://et.falgout.us/divi (the errors only show up when the page is loaded in the VB)

**Comment by SlavaET** [comment]
@lots0logs weird, I cannot activate the Visual Builder on this website 😄  
![image](https://cloud.githubusercontent.com/assets/3446682/20427435/1995ede2-adae-11e6-9c5a-77a20dc926f3.png)

**Comment by lots0logs** [comment]
@SlavaET I'm still seeing this in the logs on my server every time I load the builder on the homepage (which uses the Homepage Extended premade layout). Not sure why you couldnt load the builder last time you tried. Its possible that I forgot to reset the git branches after doing QA testing that day. Could you check it again? Thanks.

**Comment by SlavaET** [comment]
Figured out the root cause and fixed the issue, finally.
Steps to reproduce the issue:
1) Enable `Grab First Image` option in ePanel settings;
2) Create a `project` without Featured image and enable Divi Builder on that project;
3) Load Visual Builder on any page;
4) Check the debug.log.

@lots0logs As for the issue with VB loading on your website. Something wrong with the user you created for me, looks like my user doesn't have role assigned and it causes the error, how did you create that user? This is what `wp_get_current_user()` returns for my user ( I removed the sensitive information, check the `roles` array ) :
```
WP_User Object
(
    [data] => stdClass Object
        (
            [ID] => 47
            [user_login] => ***REMOVED***
            [user_pass] => ***REMOVED***
            [user_nicename] => ***REMOVED***
            [user_email] => ***REMOVED***
            [user_url] => 
            [user_registered] => 2016-11-18 08:55:32
            [user_activation_key] => 
            [user_status] => 0
            [display_name] => ***REMOVED***
            [spam] => 0
            [deleted] => 0
        )

    [ID] => 47
    [caps] => Array
        (
        )

    [cap_key] => et_88_capabilities
    [roles] => Array
        (
        )

    [allcaps] => Array
        (
        )

    [filter] => 
)
```

**Comment by lots0logs** [comment]
@SlavaET Your user is a SuperAdmin..I think for super admins, capabilities check will always return true, no?

**Comment by SlavaET** [comment]
@lots0logs we check user roles, not the capabilities. Since we limit the functionality for users based on their roles ( even custom ones ). So we cannot rely on capabilities and need to know the user Role. I added my comment to this ticket - https://github.com/elegantthemes/Divi/issues/2627

**Comment by lots0logs** [comment]
@SlavaET What I mean is that there is nothing wrong with your user account. It was set up just like any normal account and then granted SuperAdmin rights. I think the reason you have had trouble is because of the branches that my test site's Divi repo has been on whenever you tried it :sweat_smile:  Anyway, looks like you figured out the issue for this ticket so no need to worry about doing testing on my site (for this issue anyway :stuck_out_tongue_winking_eye: )
