### ISSUE TITLE
VB :: Module Settings Modals :: Custom CSS :: Help Icon Not Visible & Clicking It Results In JS Error

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#779]
### Problem:

The help icons are not visible when hovering over the names of the fields in the Custom CSS tab of modules' settings. If you click where the icon should appear, the following JS Error shows up in the console:
```
Uncaught TypeError: this.props.onClickHelp is not a function
```

### Additional Information:
![2016-11-17_04-35-38-pm](https://cloud.githubusercontent.com/assets/4675662/20410780/6331813e-ace4-11e6-9cf2-6bf051767bbc.png)

**Comment by SlavaET** [comment]
Fixed. The same issue was with advanced settings.
With my PR for the CSS options we'll display the selectors, for advanced options we won't render that button at all.

**Comment by lots0logs** [comment]
@SlavaET The selectors shouldn't drop to the next line. Also, when you click outside of the field the selector should fadeout automatically. @timayhelen Do you have anything to add regarding this?

![2016-11-18 12-26](https://cloud.githubusercontent.com/assets/4675662/20441614/dbd8ac9c-ad8a-11e6-8d3b-40aba831c9b7.gif)

**Comment by SlavaET** [comment]
@lots0logs we can make it look the same way as in BB, but it's slightly different design used for these fields in BB, so I made it to look consistent with help text in other options in VB.
Also, in some cases it still will drop to the next line because of the selector's length ( check the audio module for example ).

**Comment by lots0logs** [comment]
@SlavaET :indeed: that is the question! @timayhelen ?

**Comment by timayhelen** [comment]
@lots0logs @SlavaET I think we can use Slava's solution for now.
