### ISSUE TITLE
Divi Builder :: Post Title

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#780]
### Problem:

If a post title, module it is placed on a single project, and it is set to show the categories, it will not show those. I guess that's because the module is looking for post categories, and not for custom taxonomies.

**Comment by SlavaET** [comment]
@eduard-ungureanu yes, it doesn't work with custom taxonomies:

![image](https://cloud.githubusercontent.com/assets/3446682/20476577/db3f9e80-affb-11e6-99a5-cb347442002b.png)

**Comment by eduard-ungureanu** [comment]
@SlavaET thank you, any plans to add this to also be working with Projects post type for example?!
