### ISSUE TITLE
Divi visual page builder not loading after installing SSL

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#781]
### Problem:

The issue comes from the customer.
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=617795
After installing SSL on his server the VB is not loading

**Comment by lots0logs** [comment]
@dm-chechik This is most likely an issue with the customer's content not being ready for the site to be flipped to SSL connections. There are plugins available to help correct mixed content issues. Recommend a few to the customer.

**Comment by dm-chechik** [comment]
@lots0logs I've checked the WP backend. Customer has already SSL plugin and the "Correct mixed content" option is enabled. At first glance everything is configured correctly.

**Comment by lots0logs** [comment]
@dm-chechik If there is mixed content being served on the page, its not something that Divi has any control over. Divi's assets will be served over SSL provided that SSL has been setup properly. The main thing is to ensure that both URLs in Settings>>General are `https://`. If the customer has plugins adding resources with regular `http` or has `http` resources loaded within their content they'll have to resolve that problem in order for everything to work properly with SSL connections.
