### ISSUE TITLE
VB :: Gallery module disappears

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#784]
### Problem:

It's hard to explain. Please have a look to the screen cast
![screen](https://cloud.githubusercontent.com/assets/20072036/20459100/4d5ebe3c-aec7-11e6-8713-a866fc138791.gif)
The same in Divi Biulder.

**Comment by lots0logs** [comment]
@SlavaET On this branch, I can't drag the Gallery anywhere:

![2016-11-28 19-56](https://cloud.githubusercontent.com/assets/4675662/20693589/13bc5ce0-b5a5-11e6-92b4-22d14ace2349.gif)

**Comment by SlavaET** [comment]
@lots0logs I don't think it's related to my changes. I can see the same issue in master and not only with Gallery module. I've submitted a new issue for that - https://github.com/elegantthemes/Divi-Beta/issues/815

**Comment by timayhelen** [comment]
@SlavaET There are still issues with this if you keep moving and duplicating and deleting the gallery. 

![gallery](https://cloud.githubusercontent.com/assets/3333028/20899017/7705a81e-badd-11e6-83a4-2196244b96e1.gif)

**Comment by SlavaET** [comment]
@timayhelen fixed.
