### ISSUE TITLE
Theme Customizer :: General Settings Background :: Does Not Work Correctly

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#785]
### Problem:

If you go to the Theme Customizer > General Settings > Background and define a background image it does not works on some pages. I'm still not sure if it depends on if divi builder is enabled/disabled.
Screen cast:
http://youtu.be/GJNgjf0Ia60?hd=1

**Comment by lots0logs** [comment]
@kary4 When the Divi Builder is used for a page the background must be set in the builder. There is an open issue already in the Divi repo for the background on non-divi builder pages/post.
