### ISSUE TITLE
Module Background Important has no effect

### ISSUE THREAD

**Issue by indikatordesign** [elegantthemes/Divi-Beta#790]
### Problem:

The important declaration for background inside modules has no effect.

```
'background' => array(
	'css' => array(
		'main' => "{$this->main_css_element}",
		'important' => 'all',
	),
	'settings' => array(
		'color' => 'alpha',
	),
),
```

The output should be something like this:

`.element { background-color: #0c71c3 !important; }`

But it is represented without "!important".

**Comment by fikrirasyid** [comment]
@comitzuu To make sure that we're on the same page, can you elaborate which module that you're referring to on this issue? Thanks :)

**Comment by comitzuu** [comment]
It refers to any module to which it is applied. The CSS output should be provided with a "!important", as it is also applied for padding and margin.

However, this is not the case. You can see it for example in the "ET_Builder_Module_Tabs_Item". It also does not affect customer module customizations. You must then create unnecessary fields to avoid this..

**Comment by fikrirasyid** [comment]
@comitzuu thank you for pointing that out! I've verified the issue and I've submitted the patch for it. Once the patch passes the review process, it should be merged to the next release of Divi.

**Comment by indikatordesign** [comment]
@fikrirasyid thank you and best regards

**Comment by fikrirasyid** [comment]
@indikatordesign I'm reopening this issue. Please let the issue open, we'll close it when the patch has been merged to master 👍

**Comment by indikatordesign** [comment]
Oh.. Ok, sorry..
