### ISSUE TITLE
WooCommerce filters have no effect

### ISSUE THREAD

**Issue by indikatordesign** [elegantthemes/Divi-Beta#791]
### Problem:

WooCommerce provides filters to configure related- and upsell-products. These have no effect when used with Divi. With the standard-theme, they work as expected.

filter: woocommerce_upsell_display_args

filter: woocommerce_output_related_products_args

```
$args = array(

	'posts_per_page' => 3,
	'columns' 	 => 1,
	'orderby' 	 => 'DESC'

);
```

**Comment by fikrirasyid** [comment]
@indikatordesign can you paste the complete code of how you hooked the filter and the screenshot of the expected result so we can correctly replicate the issue? Thanks.

**Comment by indikatordesign** [comment]
You can insert this snippet into the functions.php and get the following output in the standard theme (Twentysixteen). In this case, simply ignore the passed arguments and re-define them:

```
add_filter( 'woocommerce_output_related_products_args', function( $args )
{

	$args = array(
		'posts_per_page' => 12,
		'columns' 	 => 5,
		'orderby' 	 => 'DESC',
	);

	return $args;

});
```
![-1](https://cloud.githubusercontent.com/assets/6696178/20701742/ea9548d4-b614-11e6-9425-1f960e433faa.jpg)
You only need to adjust the width of the li elements. As you can see, 12 products are distributed cleanly to 5 columns in a descending order.

If you add exactly the same snippet into the functions.php of Divi, it has no effect at all.
![-2](https://cloud.githubusercontent.com/assets/6696178/20702058/66b466ce-b616-11e6-8b55-f347cc69299a.jpg)

The same happens with the upsell products. Here you can use the following snippet, which has no effect:

```
add_filter( 'woocommerce_upsell_display_args', function()
{

	$args = array(
		'posts_per_page' => 12,
		'columns' 	 	 => 5,
		'orderby' 	 	 => 'DESC',
	);

	return $args;

});
```

**Comment by indikatordesign** [comment]
And if you try to output it directly with something like this:
```
$class = 'my-class';

$args  = array(

	'posts_per_page' => 6,
	'columns' 	 => 3,
	'orderby' 	 => 'DESC',

);

echo sprintf( '<div class="woo-related %1$s">', $class );

	woocommerce_related_products( $args );

echo '</div>';
```
You get the following result:
![-3](https://cloud.githubusercontent.com/assets/6696178/20702896/e7c870c2-b619-11e6-9b31-5b7e40ca8398.jpg)

For upsell products you have here again the same behavior:

```
echo sprintf( '<div class="woo-upsell %1$s">', $class );

	woocommerce_upsell_display( 6, 3, 'DESC'  );

echo '</div>';
```

**Comment by fikrirasyid** [comment]
@indikatordesign I've submitted a patch for this issue and the patch is currently under review. I can confirm that `woocommerce_output_related_products_args` filter doesn't work on Divi's single product page (which the patch will fix). However:

1. Upsell product is actually works on Divi. Have you configured the upsell product on the editor? This is how the upsell area looks like on Divi: 

![screen shot 2016-11-30 at 10 50 41 pm](https://cloud.githubusercontent.com/assets/916442/20759415/75d1c7b6-b74f-11e6-8b1b-eb7bacccda35.png)

These upsell products automatically appear after the up-sells info is configured:

![screen shot 2016-11-30 at 10 51 01 pm](https://cloud.githubusercontent.com/assets/916442/20759443/8b4c8ad6-b74f-11e6-91e4-70107acb3aff.png)

**Comment by indikatordesign** [comment]
@fikrirasyid I have adjusted the upsell products correctly. The following picture shows the result I get from:

```
'posts_per_page' => 3,
'columns' => 1,
```

![1](https://cloud.githubusercontent.com/assets/6696178/20760390/36132ed2-b720-11e6-8ed8-cccf8d0f2a7d.jpg)

I also tried it in the Extra-Theme. There it is displayed correctly.

**Comment by fikrirasyid** [comment]
@indikatordesign what you explained at https://github.com/elegantthemes/Divi-Beta/issues/791#issuecomment-263916334 isn't a bug: it works correctly. if the `column` argument is set to `3`, the `3rd, 6th, 9th, 12th, etc` will not have a margin because it supposed to be the last item on the row:

![791-1](https://cloud.githubusercontent.com/assets/916442/20786085/72313ec0-b7d6-11e6-8d6e-7ef8e072ca63.jpg)

As a comparison, if your wrapper can contains 4 items, you should set the column into `4`:

![791-2](https://cloud.githubusercontent.com/assets/916442/20786114/b005be4c-b7d6-11e6-990d-fed8e929d08d.jpg)

If the product items wrapper can contain `4` items but you set the column to `3`, this is what logically will happen:

![791-3](https://cloud.githubusercontent.com/assets/916442/20786152/edaab9fa-b7d6-11e6-9b34-5e79b5cf0a4f.jpg)

**Comment by indikatordesign** [comment]
@fikrirasyid Yes you're right. It shows the columns properly, only the CSS does not work properly with these settings .. To make it easier for customers to implement their own ideas, it would be good if the CSS settings go in the direction as they represent these results here:

```
.woocommerce ul.products li.product,
.woocommerce-page ul.products li.product {
    width: 25%;                /*represents a 4 column setting for default*/
    display: inline;
    float: left;
    margin: 0 0 1.3em;         /*just a little margin at the bottom*/
    padding: .3%;              /*a small padding for a distance between the items*/
}

.et_full_width_page.woocommerce-page ul.products li.product:nth-child(4n+1),
.et_left_sidebar.woocommerce-page ul.products li.product:nth-child(3n+1),
.et_right_sidebar.woocommerce-page ul.products li.product:nth-child(3n+1){
   clear: none;
}
```

This allows the 4 standard columns to be imitated only, but each customer can easily change the settings, without much intervention in the CSS settings. Only the width has to be adapted for different results and maybe some little padding adjustments:

width: 25%;

![1](https://cloud.githubusercontent.com/assets/6696178/20787451/214d2ff2-b7ac-11e6-8f31-abdf04b7e52d.jpg)

width: 33.33%;

![2](https://cloud.githubusercontent.com/assets/6696178/20787503/7139aaf4-b7ac-11e6-80c8-cd267539a611.jpg)

width: 20%;

![3](https://cloud.githubusercontent.com/assets/6696178/20787531/936183c2-b7ac-11e6-9535-6ad3dda09de9.jpg)

A corresponding solution for both would be great: for upsell-products and related-products..

**Comment by fikrirasyid** [comment]
@indikatordesign thank you for your suggestion. I'll discuss it with our designer but I personally see that Divi is *intentionally* designed for 3 (has-sidebar) and 4 (full-width) product columns so what you suggested would fall into user's customization. So the chance for adding stylesheet that we don't natively design is small.

It's like adding WooCommerce stylesheet to WordPress' core stylesheet. WordPress isn't designed to be online shop, that is why it doesn't have built in online shop styling. But if you as user wanted it, it is possible and feel free to add customization to it.

**Comment by indikatordesign** [comment]
This is funny.. In extra theme it works out-of-the-box as I described it here.. So it should not really be a big problem, cause it is also based on WordPress.. Please, try your very best and thank you for your effort :)

**Comment by fikrirasyid** [comment]
@indikatordesign can you elaborate what do you mean by it works out-of-the-box in Extra (I might be missing something)? I checked it on Extra and it works similarly like Divi, it's either 3 or 4 columns. Extra even has stricter rule: it completely ignores the column setting and enforce 3 columns in desktop if it has sidebar and 4 columns if it is full-width page with no sidebar.

![column-5](https://cloud.githubusercontent.com/assets/916442/20791467/c1fd973c-b7ef-11e6-96b7-32ec0a6c4b7d.jpg)

> So it should not really be a big problem, cause it is also based on WordPress

Simply adding stylesheet isn't a huge technical problem, but we're quite opinionated in terms of design decision to avoid unpleasant UX. It's quite similar to the reason why regular section in Divi Builder only has 4 columns (so far) regardless customer request to add 6 or even 8 columns. We think 6 - 8 columns is too small and not readable thus we don't natively support it. It doesn't mean user can't customize the builder to their content's heart tho. You can customize it as you see fit If you want to. However, we don't natively support it thus we don't add it by default :)

> Please, try your very best and thank you for your effort :)

I'll try communicating this issue to our designer 👍

**Comment by indikatordesign** [comment]
> it completely ignores the column setting and enforce 3 columns

That's pretty fine.. Please note the following in the context of the request for change:

> This allows the 4 standard columns to be **imitated** only

It is absolutely fine to ignore the colums by CSS. With the proposed changes, only "posts_per_page" has an effect and the columns are handled alone across the width per CSS. In this case, the customer must adapt it according to his needs, but he only needs to make changes to the width of the li-elements, like you can do in the Extra-Theme. Try it yourself. You only have to change the width in the extra theme and the elements take the number of columns that correspond to their width (33.33% = 3 columns, 20% = 5 columns and so on).

With my suggestions for change this would be possible in Divi, too. The customers only need to  changes the "posts_per_page" and determines the columns alone over the width in CSS, without pictures directly connected, while the others has a gap as you can see in my screenshot..

**Comment by indikatordesign** [comment]
@fikrirasyid - when do you release the patch for woocommerce_output_related_products_args ?

**Comment by fikrirasyid** [comment]
@indikatordesign we don't have any ETA for this moment, but I can see it's been progressing in our review process (every patch is reviewed by three different aspect & team). It has been queued and progressed but I can't guarantee when it'll be released. 

If you need it ASAP, I can provide the fix for you + instruction to quick-patch it. We cannot 100% guarantee it since it is still in review process on our side tho.

**Comment by wenjonsommers** [comment]
I would like to change the amount of upsells to 5... Is this option coming soon?

**Comment by lots0logs** [comment]
Hi @wenjonsommers, I'm afraid there is not currently an option in the theme to control the number of upsells displayed. However, it can be customized using a child theme. If you could, please open a ticket in the forum and our support team will be happy to advise you on how to do it :smiley:
