### ISSUE TITLE
Plugin compatibility :: WooCommerce Products Per Page :: Does Not Work

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#792]
### Problem:

Divi does not works with this plugin activated: 
https://en-gb.wordpress.org/plugins/woocommerce-products-per-page/

So, when you try to select Number of products in a category page it still loads the default number that comes from the theme options settings.

I was able to reproduce the issue on my local machine.

Ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=619938

**Comment by lots0logs** [comment]
@kary4 Advise the customer that the theme includes an option specifically for controlling the number of products per page on product archives. There is no need to use a plugin. Be sure to mention our policy on supporting 3rd-party plugins as well.
