### ISSUE TITLE
Plugin compatibility :: Wc vendors pro :: Does Not Work

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#794]
### Problem:
Wc vendors pro plugin does not work in Divi. It's payed plugin, so unfortunately I can't check it myself.
You can get more info here:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=619364

The plugin page:
https://www.wcvendors.com/product/wc-vendors-pro/

**Comment by lots0logs** [comment]
@kary4 Let the customer know that we cannot guarantee support for 3rd-party plugins and that they will need to contact the plugin developer for assistance. I've looked into that particular plugin recently and the problem is not caused by Divi.
