### ISSUE TITLE
Post Slider :: Featured Image Position

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#796]
### Problem:

When setting the option for the Image Placement: to be either top or bottom, the image shows in the wrong position: 

Image Placement: TOP
![screenshot 2016-11-24 16 07 57](https://cloud.githubusercontent.com/assets/1719735/20601375/0175135c-b261-11e6-98b3-eff1d133878b.png)

Image Placement: BOTTOM
![screenshot 2016-11-24 16 09 05](https://cloud.githubusercontent.com/assets/1719735/20601390/11a7ed62-b261-11e6-8898-2b971dbc2d81.png)

**Comment by SlavaET** [comment]
This issue should be fixed in scope of the following PR - https://github.com/elegantthemes/Divi-Beta/issues/762
