### ISSUE TITLE
Button :: Incorrect padding on hover

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#797]
### Problem:

![screenshot_3](https://cloud.githubusercontent.com/assets/9657712/20602860/42d2fce2-b289-11e6-970b-13c1667d34e2.png)

### Steps To Reproduce:
1.  Open Theme Customizer >Buttons > set "Add Button Icon" option to "no"
2.  Create Button module and select custom icon in Advanced Design Settings

**Comment by fikrirasyid** [comment]
Patch for this issue consists of two PRs:

- Divi: https://github.com/elegantthemes/Divi/pull/2642
- submodule-builder: https://github.com/elegantthemes/submodule-builder/pull/1483

**Comment by timayhelen** [comment]
@fikrirasyid I switched to both branches, ran npm start and grunt, cleared my cache and used Incognito but I still see the issue:

![screen shot 2016-11-29 at 3 38 47 pm](https://cloud.githubusercontent.com/assets/3333028/20733735/ed93b5c2-b649-11e6-9c65-769ae43c2b20.png)

**Comment by fikrirasyid** [comment]
@timayhelen can you share the layout you're using?

**Comment by lots0logs** [comment]
@timayhelen For some reason I've had to run `npm build` on all branches I QA tested today for the changes to actually show up.

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen can you pull latest `797-button-incorrect-padding-hover` branch at `Divi` and `submodule-builder` then test it again? @timayhelen's layout test shows me that the branch doesn't anticipate the following situation:

- customizer's `Add Button Icon` is set to `No`
- button's `Add Button Icon` is set to `Yes`
- button's `Only show icon on hover for Button` is set to `No`

I've fixed the issue. It looks as expected now:

![797-powered-up](https://cloud.githubusercontent.com/assets/916442/20736669/92601402-b6da-11e6-9b69-a97e35368a49.gif)

**Comment by Jronk** [comment]
See my comment on PR https://github.com/elegantthemes/submodule-builder/pull/1483#pullrequestreview-10879414

**Comment by fikrirasyid** [comment]
@Jronk I've replied it at https://github.com/elegantthemes/submodule-builder/pull/1483#discussion_r90374509. I've pushed changes as well, you need to pull both Divi and submodule-builder's branches to preview the change.
