### ISSUE TITLE
Page Load :: Very noticeable page load delay with variations of a Fullwidth Header in fullscreen mode.

### ISSUE THREAD

**Issue by kolleen** [elegantthemes/Divi-Beta#8]
### Problem:
This isn't necessarily a bug, but it does make take Divi backwards in smoothness. I loaded up the Beta and couldn't wait to get my hands on the A/B Testing. Set up a header with a few headlines and let it roll.

The page loads and then the first section "pops" into place. It makes the page load seem awkward and not nearly as sexy as the regular page load within Divi. 

### Steps To Reproduce:
1. Go to my build site: http://www.designbykolleen.com/
2.
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Mac Desktop

**Operating System**: 10.8.5

**Browser**: Firefox

**Screen Resolution**: 

**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
It happens when you're using cache plugins. Unfortunately the only way to load the variations in this case is via Ajax and it may cause the delays which can be noticeable in some cases. The best thing we can do there is to display the Fullscreen placeholder maybe with loading animation, but I'm not sure that it'll look better.
As a solution you can disable your cache plugin for the time of Split testing and it'll be loaded without delays.
@timayhelen do we need to improve the placeholders to display loading animation or something?

**Comment by lots0logs** [comment]
@SlavaET IMO, a placeholder would look better than the current behavior.

**Comment by kolleen** [comment]
Okay, I left it up for you to see the behavior. I'm going to remove the split testing since it's not as important as site speed until I move to a better host.

**Comment by SheriLossing** [comment]
I am having the same issue, maybe, if I am understanding the original description correctly. I am using no plugins, other than the two to install/update for the beta version, and with my fullwidth header the image loads larger, then 'pops' into place/shrinks. http://fa4.690.myftpupload.com/

**Comment by SlavaET** [comment]
@SheriLossing it's not the same issue. Original issue is that the section is empty on load and then the content pop up with some delay. In your case it's delay in resizing of the header image and is not related to the split testing.

**Comment by SheriLossing** [comment]
@SlavaET Do you want me to 'open an issue/ticket' for this?

**Comment by SlavaET** [comment]
@SheriLossing yes, please and it will be great if you record a screencast of the issue.

**Comment by timayhelen** [comment]
Let's table this for now, as I am not sure if a pre-loader would the most desirable solution. Let's see what users think.
