### ISSUE TITLE
Warning Field (UI Element)

### ISSUE THREAD

**Issue by dtcblyth** [elegantthemes/Divi-Beta#8]
### Problem:
In D4 we could add a **warning field** (or UI element) to `get_fields()`. Are there plans to implement the **warning field** in D5? 

I use **warning fields** extensively in some modules. I often display them conditionally. They really help inform the user of things that might not be immediately obvious. I’ve found that most users don’t read documentation, or even the "description" text above the fields. Putting important information in the **warning fields** really helps reduce support requests.

In D4 **warning fields**could in include HTML and inline CSS, which made them very useful.

Example:
```
$field['my_warning'] = array(
  'message'     =>  $warning,
  'tab_slug'    => 'general',
  'toggle_slug' => 'my_toggle',
  'type'        => 'warning',
  'value'       =>  true,
  'display_if'  =>  true,
);
```
### Examples:
<img width="399" alt="Screenshot 2023-03-18 at 7 42 31 AM" src="https://user-images.githubusercontent.com/59285096/226072595-2ad250bc-562c-4627-a800-66fbde606ab9.png">
<img width="399" alt="Screenshot 2023-03-18 at 7 42 12 AM" src="https://user-images.githubusercontent.com/59285096/226072601-e133f455-eb21-436d-bc25-8a090c75836e.png">
<img width="537" alt="Screenshot 2023-03-18 at 7 39 20 AM" src="https://user-images.githubusercontent.com/59285096/226072602-101bb41d-0f62-4af3-8b7d-cf7209106218.png">
<img width="396" alt="Screenshot 2023-03-18 at 7 42 50 AM" src="https://user-images.githubusercontent.com/59285096/226072604-2a761283-b977-4fe5-9c38-210861339ce2.png">

**Comment by fikrirasyid** [comment]
@dtcblyth this has been [addressed in dev beta 02](https://dividevdocs.com/blog/release-dev-beta-2/#new-warning--field-library-component). Documentation: https://dividevdocs.com/docs/builder-api/js/field-library/warning/#divifield-library
