### ISSUE TITLE
Difficult to Edit 1px divider in Visual Builder

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#80]
### Problem:

In visual builder, the little toolbar disappears to quickly when trying to edit tiny objects like a 1px divider.  Can't get the mouse to the toolbar before it fades.

### Steps To Reproduce:
1. Add a 1px divider in a section.
2. try to edit the divider module in visual editor
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
PC
**Operating System**:
Windows
**Browser**:
Chrome Version 52.0.2743.116 m
**Screen Resolution**:
1366x768
**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by websbyjd** [comment]
Discovered the same issue when trying to edit blurb module if only title and icon are used with icon left.  Tool bar fades before you can get to it.

**Comment by fikrirasyid** [comment]
@websbyjd We've submitted a patch for this and it is currently under review process. Once it passes review process, it should be merged on the next beta release. Thank you for reporting the issue 😄 

Here's how the patch looks like:

![divi-beta-80](https://cloud.githubusercontent.com/assets/916442/17965864/f38e29a0-6ae8-11e6-965d-3afdf3c04b72.gif)
