### ISSUE TITLE
WP 4.7 :: Custom CSS :: Evaluate Custom CSS field on Dashboard > Divi > Theme Options

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#800]
### Problem:

Divi has Custom CSS field at `Dashboard > Divi > Theme Options > General` tab:

<img width="1249" alt="screen shot 2016-11-25 at 2 30 26 pm" src="https://cloud.githubusercontent.com/assets/916442/20617428/bc5f3980-b31b-11e6-8a75-3d0b162d9491.png">

WordPress Customizer now has additional CSS field by default:

![custom-css-wp-37](https://cloud.githubusercontent.com/assets/916442/20617440/dbbe304c-b31b-11e6-8331-e27d68a164d7.gif)

We might want to evaluate the existence of `Custom CSS` field on theme options, since it is redundant now with WordPress' native additional CSS field.

**Comment by SlavaET** [comment]
What if we sync this WP option with our ePanel option? So users will be able to modify theme custom css from Customizer or ePanel.
I didn't check how it works yet, just an idea.

**Comment by timayhelen** [comment]
@SlavaET Yeah that would be nice, and then we can phase out epanl CSS after the next few major releases.

**Comment by SlavaET** [comment]
Done.
It works as follows in my PR.
- We use WP system to output custom CSS on frontend starting from WP 4.7. Fallback to our legacy system otherwise;
- We keep in sync Custom CSS option with ePanel CSS option. We sync them once in new version of theme and then update both of them when user modified it from any place;
- We still store all the Custom CSS in theme options to support backward compatibility with old versions of WP and old version of theme. So if user will add/update custom CSS using Customizer in WP 4.7 and then downgraded to WP 4.6, then all the custom CSS will appear in ePanel; 
- This fix is applicable to all our themes which have Custom CSS option in ePanel.

**Comment by lots0logs** [comment]
@SlavaET After enabling this branch the content of the custom CSS field in epanel is empty. Also nothing shows in Customizer custom CSS except for the default CSS comment. Changing branch back to `master` makes the custom css that existed before show up in epanel custom CSS field again.

**Comment by SlavaET** [comment]
@lots0logs do you see any errors in `debug.log` ? I cannot reproduce this issue.

**Comment by lots0logs** [comment]
@SlavaET I will test it again and let you know. Just to confirm, you tested it with existing content in epanel custom CSS (saved prior to testing the new branch), right?

**Comment by SlavaET** [comment]
@lots0logs yes. I tested different variations:
- content added to ePanel prior to upgrade of wp
- content added to ePanel prior to upgrade of theme
- content added to wp prior to upgrade of theme
- content added to both wp and ePanel prior to upgrade of wp, prior to upgrade of theme.
- downgrade of theme or/and wp after content added to customizer and/or ePanel
- some more combinations I could think of :)

**Comment by lots0logs** [comment]
@SlavaET I'm getting the same result as before. The custom CSS field in ePanel is empty when on this branch (and so is the one in customizer). Could it have something to do with multisite?

**Comment by SlavaET** [comment]
Yeah, it may work differently on multisite. I'll check that. Is it possible to perform some tests on your server tomorrow? :smile:

**Comment by lots0logs** [comment]
@SlavaET Sure, you can anytime. Just let me know when :+1:  ...hmm..4.7 gets released tomorrow I think :grimacing:
