### ISSUE TITLE
WP 4.7 :: Customizer :: Added Partial Edit Shortcut Button Support

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#801]
### Problem:

WordPress' default themes has this useful customizer shortcut edit button in WordPress 4.7 RC1:

![partial-edit-shortcut-button](https://cloud.githubusercontent.com/assets/916442/20627547/5c009736-b353-11e6-9dd3-6d9e7f3e54ba.gif)

The same button can't be found on WordPress 4.6:

![screen shot 2016-11-25 at 9 08 47 pm](https://cloud.githubusercontent.com/assets/916442/20627560/6ea8b256-b353-11e6-9e15-78648887aa5a.png)

Divi at WP 4.7 doesn't display this button as well. I think it'll be useful if we added support for this feature on Divi.

The caveat is I couldn't find any decent reference about this feature. All I need to know so far is:

- The feature is called `edit shortcut button`, or `partial edit shortcut button`
- Here's WordPress trac for Customizer component for 4.7: https://core.trac.wordpress.org/query?status=closed&group=resolution&component=Customize&milestone=4.7
- This feature being discussed on WordPress trac: https://core.trac.wordpress.org/ticket/38532

### Steps To Reproduce:
1.  Update to WordPress 4.7 RC-1
2. Make sure that you're current active theme is WordPress' default themes (TwentySeventeen or TwentySixteen, for example)
3. Open `Dashboard > Appearance > Customize`
4. Done testing the edit shortcut button? Try switching theme to `Divi`

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Comment by uportnykh** [comment]
I've added selective refresh support for widgets.

It is also possible to add partial edit shortcut to any element in the theme: https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentyeleven/inc/theme-options.php#L509-L524

**Comment by fikrirasyid** [comment]
@uportnykh I've checked https://github.com/elegantthemes/Divi/pull/2639 and it is working well adding partial edit shortcut for widget. Anyway, can we do the same for nav, header logo, and footer? It seems logical for doing so. This is how partial edit shortcut looks like on TwentySixteen. The links look really contextual and useful:

![screen shot 2016-11-29 at 6 53 31 am](https://cloud.githubusercontent.com/assets/916442/20691069/043ce7e2-b601-11e6-9c24-09384a9998bb.png)

![screen shot 2016-11-29 at 6 53 37 am](https://cloud.githubusercontent.com/assets/916442/20691076/0c1ec8ea-b601-11e6-800b-09888ca90316.png)

**Comment by uportnykh** [comment]
Yes, we just need to come up with the full list of settings we want to integrate partial edit for.

/cc @timayhelen

**Comment by timayhelen** [comment]
@uportnykh Let's add 

1. Header - This will appear inside of the header and will simply open up the main "Header & Navigation" menu. It can be placed to the left of the logo. 
2. Footer - This will open the main "Footer" menu and can be placed in the top left of the footer area. 
3. Footer Widgets - This will open the "Footer > Widgets" menu and can be placed to the top left of the first footer widget, below the main Footer edit link. 
4. Bottom Bar - This will open the Footer > Bottom Bar menu and will be placed to the left of the bottom bar credits text. 
5. Footer Elements - This will open the " Footer > Footer Elements" menu and should be placed to the left of the social icons in the footer bottom bar. 
6. General Settings - This will open the General Settings menu and can be placed in the top left of the main body area below the fixed header. The Header and General Settings icons should be vertically aligned.

**Comment by timayhelen** [comment]
Looks like it's not possible to assign editing shortcuts to panels. Let's just merge widget support for now.
