### ISSUE TITLE
WP 4.7 :: Customizer :: Misaligned Close Customizer Button

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#802]
### Problem:

Subtle, but this happens. Close customizer button on Divi theme appears to be little bit misaligned:

![screen shot 2016-11-25 at 9 26 12 pm](https://cloud.githubusercontent.com/assets/916442/20627944/d3e97fae-b355-11e6-96e2-79a1e8fc3616.png)

As comparison, this is how the button appears on TwentySixteen theme:

![screen shot 2016-11-25 at 9 27 12 pm](https://cloud.githubusercontent.com/assets/916442/20627963/f3ebd8f6-b355-11e6-84c5-a0b5d675ec7f.png)

### Steps To Reproduce:
1.  Update to WP 4.7 RC1
2. Activate Divi, open customizer then see the alignment of the close button.
3. Activate TwentySixteen, open customizer then see the alignment of the close button.

### Additional Information:
**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Comment by lots0logs** [comment]
@SlavaET This change fixes the alignment for 4.7 but breaks it for previous versions.

**Comment by SlavaET** [comment]
@lots0logs fixed.
I closed my previous PR in `submodule-core` and opened a new PR in `submodule-builder` instead.
So the fix requires following PRs:
1) `Divi` - https://github.com/elegantthemes/Divi/issues/2641
2) `submodule-builder` - https://github.com/elegantthemes/submodule-builder/issues/1488

**Comment by timayhelen** [comment]
@SlavaET These fixes weren't necessary. We just needed to remove our custom CSS entirely:

https://github.com/elegantthemes/Divi/commit/6e5460d9c09c775c44aaa56f5440ed2dae627da1
https://github.com/elegantthemes/submodule-core/commit/5578274677a90965c39f34bded1bb489617c3593

I also fixed an unrelated z-index issue that resulted in a hidden border bottom.
