### ISSUE TITLE
WP 4.7 :: VB :: Cannot load predefined layouts

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#803]
### Problem:

Loading pre-defined layout always fails. Here's how it looks:

![cannot-load-predefined-layout](https://cloud.githubusercontent.com/assets/916442/20628752/69ecf2de-b35a-11e6-9439-21b9f986d59f.gif)

### Steps To Reproduce:
1. Make sure that no cache stored by opening console tab on dev tools, then type `localStorage.clear()` then hit enter
2. Create new page, activate BB, save, then view in visual builder
3. Try adding predefined layouts.

Note: if you're not clearing your `localStorage` first, sometimes the load predefined layout works.

### Additional Information:
**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Comment by uportnykh** [comment]
I can't replicate it. I'm using the latest dev version of WordPress though, so it might have to do with it.

**Comment by SlavaET** [comment]
I can reproduce the issue with the latest dev version of WP, but I get the following errors. 
In browser console:
![image](https://cloud.githubusercontent.com/assets/3446682/20657229/7c184d86-b55e-11e6-837e-f170cc2113b2.png)

in debug.log:
```PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes) in /Applications/MAMP/htdocs/wordpress/wp-includes/shortcodes.php on line 378```

This error appears only in Divi theme. It works fine in plugin.

**Comment by SlavaET** [comment]
Turned out I found different 2 issues which are not related to WP 4.7 actually.
1) It's related to blog module which contains posts with blog module and it creates infinite loop which breaks the library loading.
2) Divi Builder always set the memory_limit to 128mb even if current limit is higher

I'll open a new ticket for that.

@fikrirasyid I cannot reproduce the issue you described either.

**Comment by fikrirasyid** [comment]
@SlavaET @uportnykh I pulled latest `master` on both `Divi` and `submodule-builder` and now I can't replicate this issue as well. I'll close this issue then.
