### ISSUE TITLE
VB :: Blog module breaks the loading of library layouts if contains posts with blog module inside

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#805]
### Problem:
I get the following errors when using the Visual Builder. 
In browser console:
![image](https://cloud.githubusercontent.com/assets/3446682/20657229/7c184d86-b55e-11e6-837e-f170cc2113b2.png)

in debug.log:
```PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65552 bytes) in /Applications/MAMP/htdocs/wordpress/wp-includes/shortcodes.php on line 378```

**Additional info:**
There are 2 issues actually:
1) It's related to blog module which contains posts with blog module and it creates infinite loop which breaks the library loading.
2) Divi Builder always set the memory_limit to 128mb even if current limit is higher

The errors appear only in Divi theme. It works fine in plugin.

### Steps To Reproduce:
1. Create a post with Blog module with default settings
2. Load the VB
3. Check console
4. Check debug log ( the error in debug log may not appear in some cases )

**Comment by timayhelen** [comment]
@SlavaET I still get weird issues when Blog Modules contain posts with Blog Modules. 

For example, add a Blog Module set to Fullwidth and Show Content. In That Blog Module, make sure the first post contains a Blog Module that is also set to Fullwidth and Show Content. 

The layout gets jumbled and I also see remnants of the blog shortcode output in the blog content:

![screen shot 2016-11-30 at 1 36 25 pm](https://cloud.githubusercontent.com/assets/3333028/20772373/0b5b2992-b702-11e6-9ed3-7863319b7a87.png)

**Comment by SlavaET** [comment]
@timayhelen fixed.
