### ISSUE TITLE
Image Module :: Animation does not work under IE

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#806]
### Problem:

I've faced the similar problem on other customer sites, however the issues do not appear constantly.
This is another customer site where I can successfully reproduce the problem -> http://foelelsenaffaxe.dk/lokalsamfund/haslev/

**Comment by lots0logs** [comment]
@dm-chechik The issue is caused by the Google Maps plugin they have installed. Here is the error that gets thrown in Internet Explorer:

![2016-12- 2_07-12-11-pm](https://cloud.githubusercontent.com/assets/4675662/20855518/78a93300-b8c3-11e6-9c3a-48dfaec83e12.png)
