### ISSUE TITLE
Modals :: Footer Buttons Glitchy During Opening Animation

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#809]
### Problem:

To see the issue, focus on the left side of the modal footer in the following screencast:

![2016-11-28 21-33](https://cloud.githubusercontent.com/assets/4675662/20695575/b96b4626-b5b2-11e6-9cb2-0729eb2d73d2.gif)

**Comment by timayhelen** [comment]
I think the only way to avoid this would be to add a background color to the button group to make the white gabs less noticable. We can use the dark gray-blue that we use throughout the VB, such as in the "upload" button in this screenshot.

**Comment by lceberg** [comment]
As @timayhelen suggested changing the button group background to grey makes the flickering hardly noticeable.

Additionally I added a 1px negative margin to the buttons to prevent the bottom line flickering when the color below the button matches the button color (see the purple button in the screencast).

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1567
