### ISSUE TITLE
Modal Snap Triggers Responsive Preview, But It Doesn't Get Untriggered

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#811]
1. Open up a settings modal. 
2. Snap it to the left. 
3. Increase the width of the snapped modal so that it triggers the tablet preview mode. 
4. Unsnap the modal. 

You will notice that the content remains in tablet preview mode. It should go back to whatever mode was enabled before snapping the modal.

**Comment by timayhelen** [comment]
@SlavaET This works when you click the modal snap button to un-snap, but it doesn't work when you drag the modal off the edge to un-snap.

**Comment by SlavaET** [comment]
@timayhelen fixed.

**Comment by Jronk** [comment]
@SlavaET please see my PR review

**Comment by SlavaET** [comment]
@Jronk fixed.
