### ISSUE TITLE
Divi Builder :: Slider Image :: Don't show on mobile

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#813]
### Problem:

When using the slider image, everything works on desktop, but on mobile, the image simply doesn't show up.
[raemarieinteriors-product-page.zip](https://github.com/elegantthemes/Divi-Beta/files/620615/raemarieinteriors-product-page.zip)

I did attached a custom layout, which shows the issue with the Slider Image.

**Comment by SlavaET** [comment]
I fixed it in scope of this issue - https://github.com/elegantthemes/Divi-Beta/issues/762
