### ISSUE TITLE
Plugin Compatibility :: Yoast SEO Premium :: Builder Fails To Load When Plugin Is Active

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#814]
### Problem:

**See:** elegantthemes/Extra#1477

### Additional Information:

**Ref:** Yoast/wordpress-seo#5427
**Ref:** Yoast/wordpress-seo#5475

**Comment by timayhelen** [comment]
@SlavaET I think you created this function originally. Does it look good to you?

**Comment by lots0logs** [comment]
@timayhelen No it was actually @SlavaET that created it. I wanted to wait to receive a copy of the plugin (sent our contact at Yoast an email yesterday) so that I can confirm the issue is resolved by this change (though I'm confident it will be).

**Comment by SlavaET** [comment]
The changes look good to me as long as it works with free version of yoast.
