### ISSUE TITLE
VB :: impossible to move module in some cases

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#815]
### Problem:

In some cases drag and drop functionality doesn't work correctly, for example - create a new 1 column row, add there Portfolio module, then create a new 2 columns row and then try to move the Portfolio module from 1 column row to a different place:

![move-modules-issue](https://cloud.githubusercontent.com/assets/3446682/20742426/32f12842-b6fa-11e6-98f0-b4b16808b374.gif)

But it starts working after you change the column structure of the 1 column row.

### Steps To Reproduce:
1. Add a new 1 column row with the Portfolio ( or gallery ) inside
2. Add another row with 2 column ( or any other columns structure, it doesn't matter ) 
3. Try moving the Module from the row created on step 1 into any place.

**Comment by SlavaET** [comment]
Fixed. My PR also should improve VB drag and drop user experience in general.

**Comment by lots0logs** [comment]
@SlavaET The drop zones are too sensitive. It's difficult to get the desired dropzone to stay visible long enough to do the drop. This is an issue on master as well but Is there anything we can do to improve it?

![2016-12-02 19-31](https://cloud.githubusercontent.com/assets/4675662/20855740/c0edbb74-b8c6-11e6-8186-e82f286f3d9c.gif)

**Comment by SlavaET** [comment]
@lots0logs please check the latest version, I improved it and it's not so sensitive anymore.

**Comment by timayhelen** [comment]
@SlavaET Ah dragging sections is so much better now!
