### ISSUE TITLE
Button :: Button with external URL and rel="nofollow"

### ISSUE THREAD

**Issue by ilianiv** [elegantthemes/Divi-Beta#817]
### Problem:

How can I create button that acts like link with rel="nofollow"? I really need this feature because of SEO nature of the project. Maybe a checkbox for `nofollow` in Button Module Settings will help 💡.

### Steps To Reproduce:
1. Open Button Module Settings
2. No input control for `nofollow`

### Additional Information:

**Divi version**: 3.0

## Attached PR
- https://github.com/elegantthemes/submodule-core/pull/52
- https://github.com/elegantthemes/submodule-builder/pull/1677

**Comment by ilianiv** [comment]
For maximum flexibility you may add dropdown with all valid `rel` values:

- alternate
- author
- bookmark
- external
- help
- license
- next
- nofollow
- noreferrer
- noopener
- prev
- search
- tag

**Comment by timayhelen** [comment]
Let's add a new option to the button module.

**Comment by lots0logs** [comment]
@lceberg Please see my review. Thanks!

**Comment by lots0logs** [comment]
@lceberg Looks like there's a typo (my fault) :grimacing:

**Comment by lceberg** [comment]
Latest commits fixes this .. and another typo. 😄

**Comment by lots0logs** [comment]
@lceberg The `<br>` is being stripped from the output when I test these branches. At first glance I don't see what's causing it :thinking:

**Comment by lceberg** [comment]
@lots0logs can you check that once more in incognito or after clearing local storage ?

Here is how it looks on my side while being on the two branches (tested on all browsers):
![button-rel-description](https://cloud.githubusercontent.com/assets/1928328/22734370/18f31c12-edfe-11e6-8deb-35c2b332dcea.png)

**Comment by timayhelen** [comment]
@lceberg I think we should add this option to the bottom of the list of settings in the modal, right above "disable on." It's quite obstructive due to how long the list is and it wont be a very common setting to use. 

We might want to consider pruning the list to only the most necessary rel attributes as well.

**Comment by lots0logs** [comment]
@timayhelen I thought the same but decided to let you decide :grin:  I think using CSS columns for multi-checkbox input options would be a huge improvement :thinking:

**Comment by lceberg** [comment]
The checkboxes are now placed above the "Disable on" option. I'm not sure what would be the most used rel attributes but the list is reduced to bookmark, external, nofollow, noreferrer and noopener.

@timayhelen @ilianiv please let me know what you think.

**Comment by ilianiv** [comment]
Thank you for adding this feature.
