### ISSUE TITLE
Post-Based Modules :: Shortcodes Should Never Be Included In Excerpts

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#819]
### Problem:

**See:** https://github.com/elegantthemes/Divi-Beta/issues/762#issuecomment-262035607

**Comment by SlavaET** [comment]
Fixed. Now shortcodes will be rendered correctly. We have filters, so our shortcodes will not be included into the excerpt, but if user has some 3rd party shortcodes, then we'll render them. 
Also, users may add shortcodes into the manual Excerpt field and these shortcodes will be rendered as well.

@lots0logs @timayhelen please let me know if my solution is wrong and we don't need to render shortcodes, but to simply truncate them from all the excerpts.

**Comment by lots0logs** [comment]
@SlavaET While I'm not against rendering shortcodes in excerpts, I'm :notsureif: we want to be altering a default behavior of WP Core like this. I do think that this is something many customers would love. However, there will be cases where this behavior is not desirable (I'm sure). So if we do this, I think it needs to have an on/off switch in the theme options and in the applicable modules' options. @timayhelen what do you think?

**Comment by SlavaET** [comment]
@lots0logs why do you think it goes against the default WP core behavior?
Default `the_excerpt()` function renders shortcodes as well as `the_content()` because both of them processed through the `the_content` filter. So it's default behavior for WP to render shortcodes from the Excerpt. We just replicate the same thing with our automatically created excerpts.

**Comment by lots0logs** [comment]
@SlavaET 

From https://developer.wordpress.org/reference/functions/the_excerpt
>An auto-generated excerpt will also have all shortcodes and tags removed. It is trimmed down to a word-boundary and the default length is 55 words. For languages in which words are (or can be) described with single characters (ie. East-Asian languages) the word-boundary is actually the character.

**Comment by SlavaET** [comment]
@lots0logs yeah, you're right they truncate the shortcodes from auto generated excerpts, but not from the explicitly defined excerpts.

**Comment by lots0logs** [comment]
@SlavaET Please see my review comment on the PR. Thanks!

**Comment by SlavaET** [comment]
@lots0logs done.
