### ISSUE TITLE
Slider :: Background Video does't work when being added 

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#82]
### Problem:

Background video and video related options that are being added to slider item doesn't work. These are the options in `Slider > Slider Item` that don't work:

- [x] Background Video MP4
- [x] Background Video Webm
- [x] Background Video Width
- [x] Background Video Height
- [x] Pause Video

### Steps To Reproduce:
1. Added slider and configured its slider item
2. Try adding background video and modifying the options listed above. You'll see that the options doesn't correctly displayed on sidebar

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Screenshots**:

**Comment by timayhelen** [comment]
@SlavaET I am still experiencing issues in this branch. If I a try to add a video background to a slide, it does not render correctly until I save and refresh:

<img width="1440" alt="screen shot 2016-08-28 at 11 47 44 am" src="https://cloud.githubusercontent.com/assets/3333028/18035944/6ec153da-6d15-11e6-9dd3-33ba247493db.png">

**Comment by SlavaET** [comment]
@timayhelen please check now.

**Comment by timayhelen** [comment]
@SlavaET I still see issues with video sizing. It looks fine when saved, when it's off when configuring the slider's video background:

<img width="1265" alt="screen shot 2016-08-29 at 1 48 28 am" src="https://cloud.githubusercontent.com/assets/3333028/18046039/c9f97b68-6d8a-11e6-9306-ee494701df4b.png">

**Comment by SlavaET** [comment]
@timayhelen please check it now. I hope I covered all the cases this time.
