### ISSUE TITLE
BB :: Code Module :: Escaped HTML is Unescaped After Saving Module Once

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#820]
### Steps To Reproduce:
1.  Add a new code module with the following contents:
    ```html
    <a class="ds-hover-1" href="#" ds-title="&quot;Honey, have you seen my right shoe? I can't find it anywhere.&quot;" ds-desc="The durable sweat and heat resistant Club Valet&reg; golf labels also work great inside shoes. They will even stick to dishes and are dishwasher safe - how cool is that!"><img src="https://golf-label.com/wp-content/uploads/2016/05/lostshoe.png" alt="Golf shoe with a club valet golf label"></a>
    ```
2. Save module settings
3. Reopen module settings 
4. You will find the following:
    ```html
    <a class="ds-hover-1" href="#" ds-title=""Honey, have you seen my right shoe? I can't find it anywhere."" ds-desc="The durable sweat and heat resistant Club Valet® golf labels also work great inside shoes. They will even stick to dishes and are dishwasher safe - how cool is that!"><img src="https://golf-label.com/wp-content/uploads/2016/05/lostshoe.png" alt="Golf shoe with a club valet golf label"></a>
    ```

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1583

**Comment by SlavaET** [comment]
@lots0logs what's the point of adding escaped characters there? 
Our Code module escapes all the content and then WP unescapes it when shortcode rendered on front-end, so we do not preserve the escaped characters anywhere.
Also, in this particular case what's the point of adding double quote character inside the double quotes? This is not a valid code and it won't be rendered properly in any case.

**Comment by lots0logs** [comment]
@SlavaET The customer is using a plugin that uses HTML5 tags on elements for rendering the contents of some custom popups. Though really the exact use case is not relevant to us. What is relevant, however, is that it works fine in the default editor but it does not work in the builder.

**Comment by SlavaET** [comment]
Done. Now it's possible to save the escaped HTML in Code module and it won't be unescaped.

**Comment by lots0logs** [comment]
@SlavaET After following the steps to reproduce listed above, try activating the inline editor in the code module and then deactivate it and try to save the page. You will see that the code module will lose its contents. I kind of think that we shouldn't allow the inline editor to be used in the code module :thinking: I mean unless you think this issue and issues like it can be handled consistently?

**Comment by SlavaET** [comment]
@lots0logs I can reproduce this issue in the master branch as well, so looks like it's not related to my fix and is different issue. I'll take a look at this and will try to fix it in scope of my PR though.

**Comment by SlavaET** [comment]
@lots0logs fixed.
