### ISSUE TITLE
DnD :: Placeholder For Fullwidth Sections While Dragging Should Be Purple

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#821]
### Problem:

![2016-12-02 19-31](https://cloud.githubusercontent.com/assets/4675662/20855700/ee63f5ce-b8c5-11e6-9323-94849fc73f4f.gif)

**Comment by SlavaET** [comment]
Fixed it in the same PR where I fixed the drag and drop issues - https://github.com/elegantthemes/submodule-builder/pull/1496
