### ISSUE TITLE
Incorrect background video stop way point offeset

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#822]
### Problem:

It seems we have incorrect way point offset for sopping section background video while scrolling down.
Currently offset is set to `-50%` that indicate the top of the element is 50 percentage of the window height beyond the top of the viewport. However in cases of background video height is greater that window height the video is paused before it fully scrolled up. (i.e. the bottom section edge still visible)
The official waypoint documentation says that we can use the following code for the offset point

```
offset: function() {
    return -this.element.clientHeight
  }
```

However what if the next section will contain background video too? Especially with any sound.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1595

**Comment by lceberg** [comment]
The PR addresses the first part where the videos are being paused earlier than they should.

Having two sections with background video one after another makes an interesting case 'though (especially if they have sound, as mentioned). I believe the best way it should work in that case is (when scrolling down):
- the first video gets paused when it is fully out of the viewport
- the second video gets played when it reaches the very top of the viewport
This however would also cause smaller videos to be played just as they reach the top of the viewport.

@timayhelen do you think we should further modify the current behavior to cover this case?

**Comment by timayhelen** [comment]
@lceberg I think we can worry about the double video issue another time. It's a very small use case and I don't think anyone has every complained about it.

**Comment by lots0logs** [comment]
@lceberg I am seeing the following error in the VB with this branch:
```
Uncaught TypeError: Cannot read property 'play' of undefined
    at t.handler [as callback] (frontend-builder-scripts.js:3129)
    at t.trigger (waypoints.min.js:7)
    at i.flushTriggers (waypoints.min.js:7)
    at e.handleScroll (waypoints.min.js:7)
    at t (waypoints.min.js:7)
```

**Comment by lots0logs** [comment]
Actually, looks like that error is on `master`. I'll open a new issue for it.
