### ISSUE TITLE
PHP Notice :: Undefined offset: 0 in core.php

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#823]
@andrey-agp commented on [Thu Nov 17 2016](https://github.com/elegantthemes/Divi/issues/2627)

### Problem:

I can't reprodcue the issue on my end

> PHP notice on my local site:
> 
> PHP Notice: Undefined offset: 0 in [redacted]\wp-content\themes\Divi\includes\builder\core.php on line 288
> 
> The notice keeps showing up even with all plugins deactivated. 
> 
> The problem is in this piece of code:
> 
> $current_user = wp_get_current_user();
> $user_roles = $current_user->roles;
> $role = ! empty( $user_roles ) ? $user_roles[0] : '';
> 
> The last line assumes that the $user_roles array is zero-indexed, but that is not always the case. On this particular site the index of the first role is 15. That's certainly unusual, but not invalid. The WP_User class doesn't make any promises about the order or indexing of the WP_User::$roles array.
> 
> The fix is simple - get the first element of the array in a way that doesn't depend on it having a specific index. For example:
> 
> $role = ! empty( $user_roles ) ? reset($user_roles) : '';
> 
> Side note: 
> If I had to speculate, I'd say that the reason the role list ended up this way is that at some earlier point a plugin wanted to add some custom capabilities to a user, and it put them at the start of the WP_User::$caps array instead of the end. (As you probably already know, WP stores user-specific capabilities in the same array as user roles.) Since capability/role changes are permanent, this change persisted long after the plugin was removed.

---

@SlavaET commented on [Sun Dec 04 2016](https://github.com/elegantthemes/Divi/issues/2627#issuecomment-264771980)

There could be one more issue when `$roles` array is empty. Like this:
```
WP_User Object
(
    [data] => stdClass Object
        (
            [ID] => 47
            [user_login] => ***REMOVED***
            [user_pass] => ***REMOVED***
            [user_nicename] => ***REMOVED***
            [user_email] => ***REMOVED***
            [user_url] => 
            [user_registered] => 2016-11-18 08:55:32
            [user_activation_key] => 
            [user_status] => 0
            [display_name] => ***REMOVED***
            [spam] => 0
            [deleted] => 0
        )

    [ID] => 47
    [caps] => Array
        (
        )

    [cap_key] => et_88_capabilities
    [roles] => Array
        (
        )

    [allcaps] => Array
        (
        )

    [filter] => 
)
```
VB won't load in this case and looks like this is possible situation as well, I encountered it on Dustin test server, check the comment - https://github.com/elegantthemes/Divi-Beta/issues/778#issuecomment-264428338

**Comment by SlavaET** [comment]
Fixed. 
I was not able to reproduce the situation described, but I tested it by manually adjusting array of roles in the code.
@lots0logs to test the second issue please check this fix on your test server using the account you made for me. Make sure that:
1) VB is loading without errors and is usable ( all the controls are in place );
2) Role is determined properly and restrictions defined in Divi Roles editor work as expected. 

Sending you my password via Slack.
