### ISSUE TITLE
Video Slider :: DOMException: no supported source was found

### ISSUE THREAD

**Issue by ilianiv** [elegantthemes/Divi-Beta#825]
### Problem:

Videos in video slider do not show in some Chrome browsers.
```
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
Uncaught (in promise) DOMException: The element has no supported sources. //at play:function(){this.load(),this.media.play()}
```
occurred.

I've added both mp4 and webm version of the video.

### Additional Information:
When I try to open the video resource directly from the server (http://example.com/video.mp4) it dumps the same error (I guess I have some codecs issue) but http://example.com/video.webm works directly but not in the slider.

**Device**: PC

**Operating System**: Windows 10

**Browser**: Chrome 55.0.2883.75 m (64-bit)

**Screen Resolution**: 1920 x 1080

**Comment by lots0logs** [comment]
Hi @ilianiv , If you could, please open a support ticket in [our forum](https://www.elegantthemes.com/forum) so that our support team can take care of you. Thanks for your cooperation :smiley:
