### ISSUE TITLE
FW Header Module :: Module Settings Button Doesn't Respond To Clicks When In 1st Section On Page

### ISSUE THREAD

**Issue by thepauly** [elegantthemes/Divi-Beta#83]
### Problem:

When I hover over a fullwidth header section, the controls show up, when I move the mouse up to click the buttons they disappear when I hit #main-header. If I set #main-header to "pointer-events: none;" it works OK.

### Steps To Reproduce:
1. Add a fullwidth section
2. Add a fullwidth header module to that section
3. Enable visual builder
4. Try to edit fullwidth header module

### Additional Information:

Tested on default Divi installation with no plugins enabled.

-

**Comment by fikrirasyid** [comment]
@thepauly can you provide screencast / screenshot which shows how you encountered the issue? I've followed the steps you mentioned above but it appears that everything works as expected. Here's how it looks on my mac:

![issue 83](https://cloud.githubusercontent.com/assets/916442/17918193/1be5081c-69ed-11e6-8c54-123cc1db76ac.gif)

**Comment by thepauly** [comment]
@fikrirasyid I think the primary menu needs to have a transparent background for it to work. I'll take a screencast when I get a chance.

**Comment by thepauly** [comment]
![divi](https://cloud.githubusercontent.com/assets/4914868/17918927/8bf4aaa8-6a0c-11e6-8d22-e48c8569e2b5.gif)

url is here if you want to take a look:

http://wordpress-16322-53254-145113.cloudwaysapps.com/

**Comment by thepauly** [comment]
It works OK when the Primary Menu Bar is set to a solid colour, but any transparency causes it to break.

**Comment by fikrirasyid** [comment]
@thepauly thank you for confirming the issue. I can replicate the problem now. Divi has particular adjustment to fullwidth modules that are being placed on the first row of the layout if the primary menu has rgba color. I'm currently investigating the issue. I'll keep you updated.

**Comment by fikrirasyid** [comment]
@thepauly patch for this issue have been submitted and currently under review process. Once it passes the review process, it should be merged on the next beta release. Thank you for submitting the report 😄

**Comment by timayhelen** [comment]
@fikrirasyid The fix works on Desktop but not on mobile breakpoints.

**Comment by fikrirasyid** [comment]
@timayhelen thank you for noticing it. I've incorporated it on the PR:

![85-responsive-support](https://cloud.githubusercontent.com/assets/916442/18002947/2d3ee672-6bb5-11e6-8bff-a0aaf0e0560e.gif)

**Comment by timayhelen** [comment]
@fikrirasyid Sorry, one more thing! Looks like there needs to be an additional adjustment for the secondary navigation bar. I don't think the new offset takes this additional height into consideration, because the button are still being overlapped by the header for me when the secondary nav bar is present.

**Comment by fikrirasyid** [comment]
@timayhelen thank you for noticing it. I've incorporated your feedback at https://github.com/elegantthemes/submodule-builder/pull/985/commits/5494be7fd30a11585e65d4f1318981a2be1a46fe. Now fullwidth module which is located at the first row considers the height of the secondary navigation bar as well.

**Comment by thepauly** [comment]
Nice work. Really can't find any other bugs other that ones already added.
