### ISSUE TITLE
Countdown module :: Numbers Font Size

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#833]
### Problem:

The settings made in Advanced Design Settings are overrided by the themes default settings.

I did set the font-size like so:
- dekstop : 50px - is ok
- tablet : 30px - not ok, it is overrided by the default theme css code 64px!important
- phones: 20px - not ok, it is overrided by the defualt theme css code 32px!important.

Screenshots:

Desktop
<img width="960" alt="screen shot 2016-12-08 at 7 34 04 pm" src="https://cloud.githubusercontent.com/assets/1719735/21020585/bd43cc6e-bd7d-11e6-8e62-00ce509c439d.png">

Tablets
<img width="960" alt="screen shot 2016-12-08 at 7 34 14 pm" src="https://cloud.githubusercontent.com/assets/1719735/21020597/caeb90cc-bd7d-11e6-9efc-6d00f387910f.png">

Phones
<img width="960" alt="screen shot 2016-12-08 at 7 34 25 pm" src="https://cloud.githubusercontent.com/assets/1719735/21020604/d0c38fd6-bd7d-11e6-9d41-97292ef8a0d8.png">

**Comment by fikrirasyid** [comment]
@eduard-ungureanu https://github.com/elegantthemes/submodule-builder/pull/1345 (which is the patch for https://github.com/elegantthemes/Divi-Beta/issues/679) is actually fixes this issue as well:

![desktop](https://cloud.githubusercontent.com/assets/916442/21035037/dcf83b28-bdee-11e6-88ed-8a6b505a64e7.png)
*desktop*

![tablet](https://cloud.githubusercontent.com/assets/916442/21035038/dcf85c0c-bdee-11e6-85a7-fffc47aea23b.png)
*tablet*

![mobile](https://cloud.githubusercontent.com/assets/916442/21035039/dcf94158-bdee-11e6-8931-158a2c019c6d.png)
*phone*

The patch is quite major and fundamental tho, so it might take some time until it is merged.

**Comment by lots0logs** [comment]
Let's track this on #679
