### ISSUE TITLE
The Gallery module is causing the browser to fail (high memory usage)

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#834]
### Problem:

All you have to do is remove 4 and you'll see an increase of memory usage by Chrome:

![59](https://cloud.githubusercontent.com/assets/16414613/21066062/60e7a006-be5b-11e6-94be-403b252b4ed3.gif)

### Steps To Reproduce:
1.  Go to: https://www.elegantthemesdemo.com/?et_fb=1
2. Add the Gallery Module.
3. In **Images Number** remove the number 4 (to add 5 for example).
4. When it's removed the hole page will fail.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
PC
**Operating System**:
Win10
**Browser**:
Chrome latest

**Comment by SlavaET** [comment]
Fixed. This error was always in Gallery module. 
You can save the gallery module with `0` images number or with some string like `asdfasdf` using the BB, then try loading the page on frontend.
