### ISSUE TITLE
Contact Form :: Custom CSS :: Before

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#837]
### Problem:

Editing one of the default fields in the Contact Form, using the Custom CSS tab, prevent's the custom css to stick. For example, editing the Name field, and the :before section, after saving the module, the code is messed up

### Steps To Reproduce:
1.  add a contact form
2. edit one of the fields
3. go to custom css tab and for :before section add
```
content: "label name";
```
4. Save and publish
5. receck the field again

<img width="960" alt="screen shot 2016-12-12 at 9 51 38 am" src="https://cloud.githubusercontent.com/assets/1719735/21091792/30789a2c-c051-11e6-8045-8f7ac3148e36.png">

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1519

**Comment by fikrirasyid** [comment]
I've narrowed down this issue until I found what possibly caused it, but I still couldn't find the point where the error occurs. The issue mentioned on this ticket only occurs if *a double quote is being saved at submodule's custom CSS field*. Double quote supposedly encoded as `%22` but somehow, when the module modal is triggered, the saved `%22` is decoded as `||` which is the encoding for line-break. Thus, the issue.

Thus:

1. This issue only occurs on sub module item
2. modal properly encoded and saved double quote as `%22`
3. When being opened, modal somehow incorrectly decodes submodule's `%22` as `||`
4. `||` will be decodes as line-break by modal

Once issue no. 3 is cracked this issue should be closer to a fix. I still couldn't find where it occurs tho 🤔 

I'm still working on it. I'll let you know the progress of this issue.

**Comment by fikrirasyid** [comment]
Patch submitted: https://github.com/elegantthemes/submodule-builder/pull/1519

**Comment by timayhelen** [comment]
@fikrirasyid I noticed that this PR causes all line breaks to be stripped from code modules and I am worried that it might conflict with the PR that Slava is working on:

https://github.com/elegantthemes/Divi-Beta/issues/769

**Comment by timayhelen** [comment]
@fikrirasyid Hmm I went to create a GIF but now I can't recreate the issue.

**Comment by timayhelen** [comment]
@fikrirasyid Looks like it happens in master too. It only occurs when TinyMCE is in Visual mode, and I just happened to switch to that mode while in your branch.

**Comment by fikrirasyid** [comment]
@timayhelen regarding this:

> I am worried that it might conflict with the PR that Slava is working on:
>
> #769
> 
>  Also worried that it might cause issues with how line breaks are handled in Text modules, since they has always been a really delicate issue. Is that in the scope of this PR?

I've rechecked @SlavaET and my PRs to be sure, and I think this PR wouldn't conflicting with Slava's approach to encoding/decoding line break in code module. The main reason for that is https://github.com/elegantthemes/submodule-builder/pull/1519 only works on custom tab fields and sub module item (ie: slider, accordion, tab, contact form, etc ). Since both text and code module has no sub module item , it shouldn't be an issue.
