### ISSUE TITLE
Page Settings :: Color Palette Picker :: Current Color Select Button Missing

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#838]
### Problem:

![2016-12-12 14-37](https://cloud.githubusercontent.com/assets/4675662/21115910/e82150e8-c078-11e6-823f-62199b4fc0cd.gif)

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1514

**Comment by SlavaET** [comment]
I don't think we need a button. I just improved the behavior of palette preview so it now reflects the color changes as it should and is less confusing to the user:
![color-palette](https://cloud.githubusercontent.com/assets/3446682/21130591/da1128c8-c133-11e6-9d04-055c1d7e85ee.gif)

@lots0logs @timayhelen please let me know if it looks fine or if we need a `select color` button.

**Comment by lots0logs** [comment]
@SlavaET Hmm..I like your idea but I think it'd be better UX if this was consistent with the rest of the builder and the theme. Let's wait and see what @timayhelen thinks though...

**Comment by timayhelen** [comment]
@SlavaET I think a Select button wouldn't hurt. We could place it in-line next to the Clear button.

**Comment by SlavaET** [comment]
Done. Added `Select` button which simply closes the colorpicker.

**Comment by lots0logs** [comment]
@SlavaET Let's put the select button on the left so that its next to the input field. Also, let's do the same in the BB.

**Comment by SlavaET** [comment]
@lots0logs done.

**Comment by lots0logs** [comment]
@SlavaET The font weight for the select button should be the same as on the clear button.

![2016-12-19_02-46-50-pm](https://cloud.githubusercontent.com/assets/4675662/21328544/1b0c0602-c5fa-11e6-9d51-961dfcb7e653.png)

**Comment by SlavaET** [comment]
@lots0logs fixed.
