### ISSUE TITLE
Theme Customizer :: Buttons Style Settings :: Incorrect Button Appearance

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#843]
### Problem:

Icon Placement and Icon Hover options do not work correctly.
![screen](https://cloud.githubusercontent.com/assets/20072036/21185130/752a0158-c220-11e6-9235-a4af9223d6d1.gif)

## 📎 Attached PR

- https://github.com/elegantthemes/Divi/pull/2658

**Comment by lots0logs** [comment]
@fikrirasyid Here's what I'm seeing now:

![2016-12-16 13-57](https://cloud.githubusercontent.com/assets/4675662/21276665/1729e45a-c398-11e6-81a1-67c5472eeb76.gif)

I checked the stylesheet in chrome dev console and confirmed that the change you made in this branch was loaded.

**Comment by fikrirasyid** [comment]
@lots0logs have you run `grunt` at `/Divi`, clear cache, then refresh the page? It works correctly on my localhost:

![843-it-is-working](https://cloud.githubusercontent.com/assets/916442/21285564/9cbe65f6-c46e-11e6-8cd2-ba7b948152d0.gif)

![843-testing-how-to](https://cloud.githubusercontent.com/assets/916442/21285600/b7f6a012-c46f-11e6-9efa-e87d860689d8.jpg)

***

Anyway, did you modified button module appearance from its module modal settings as well?

**Comment by lots0logs** [comment]
@fikrirasyid I see the issue. I'm looking at buttons that appear in CTA and Slider Modules, not the Button Module. The issue still exists for other buttons (that aren't the Button Module).

**Comment by fikrirasyid** [comment]
@lots0logs can you share the screencast and the layout you're using? I've checked all other module that use button besides button module on my local testing site, and it looks as expected:

![843-proof](https://cloud.githubusercontent.com/assets/916442/21341699/594e03ea-c6c0-11e6-96bc-049ba8c42318.gif)
