### ISSUE TITLE
VB :: Visual Builder doesn't save empty Fullwidth and Regular sections

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#846]
### Problem:

All empty Fullwidth and Regular sections will be truncated and won't be saved If you save the page containing empty sections using VB.
BB saves all the empty sections correctly.

### Steps To Reproduce:
1. Load the page which contains empty Fullwidth and Regular sections in VB ( or create one in VB );
2. Save the page; 
3. Reload page;
4. Check the content of page. You will see all the empty sections were removed from page.

**Comment by SlavaET** [comment]
Looks like we made it on purpose actually. I can't remember why though 😄 
@timayhelen do we need to change it and allow saving of empty sections via VB?

**Comment by timayhelen** [comment]
@SlavaET Yeah let's allow it, unless you think there was a good reason not too. I think some people use empty sections like dividers sometimes, with custom background colors or patterns.
