### ISSUE TITLE
Video Slider :: Loading and Arrow Color Issues

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#85]
### Problem:

Video slider has two issues (note: this fields exist on its module item > general tab):

- [x] Video MP4/URL ::  transitioning from local video to 3rd party video is glitched. cannot fetch `this.props.loading` correctly thus the video dimension normalization doesn't work
- [x] Slider Arrows Color :: Changing the value doesn't affect the slider's arrow color

### Steps To Reproduce:
1. Add video slider and configure its value. Save the page
2. Open module settings > any module item which uses local video
3. Try changing the value into any YouTube video URL

For slider arrows colors:
1. Add video slider and configure its value. Save the page
2. Open module settings > any module item 
3. Try changing `Slider Arrows Color` value

### Additional Information:

**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Reference**:

**Screenshots**:

**Comment by timayhelen** [comment]
@fikrirasyid I can't seem to get the video slider module to work when adding a fresh video slider to the page in the VB. As soon as I try to add my first video sub item, the following error occurs:

<img width="721" alt="screen shot 2016-08-26 at 2 39 30 am" src="https://cloud.githubusercontent.com/assets/3333028/18001204/73ad9088-6b36-11e6-88fa-fca3d63192a0.png">

**Comment by fikrirasyid** [comment]
@timayhelen ah, looks like I missed it. I've fixed and pushed it to the PR: https://github.com/elegantthemes/submodule-builder/commit/063643fd87c616b8834bce36decc910c160783d0
