### ISSUE TITLE
Blog Module :: Some Options In Design Tab Have No Effect

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#850]
### Problem:
The **Body Font Size** option has no effect when you adjust it (in the VB and also on the frontend page). 

The **Meta Text Color** option doesn't affect links that appear in post meta. ~~Since there is no option for meta link color, the text color should be used.~~ Actually, its probably better to add an option for meta link color instead. 

The Body Letter Spacing affects the heading text (it shouldn't)

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1527

**Comment by fikrirasyid** [comment]
> The Body Letter Spacing affects the heading text (it shouldn't).

This has been reported multiple times, and this is how the state of the situation now: https://github.com/elegantthemes/Divi-Beta/issues/758

**Comment by lots0logs** [comment]
Yeah I guess it is. We will definitely revisit the situation (#758) again during 3.1 sprint. Because currently making any customization to the body settings forces you to make customization to the heading and that's :notgood: :wink: .

**Comment by SlavaET** [comment]
@lots0logs I cannot reproduce the issue with Body Font-size option. It works fine for me in VB and applied correctly on Frontend:
![body-font-size](https://cloud.githubusercontent.com/assets/3446682/21253972/75fbb190-c38c-11e6-93b2-d9dbb8deb7cd.gif)
As for the meta color option - I made it to affect the links as well, because we don't use the separate option for meta links anywhere. We use single option which affects both text and links.

**Comment by lots0logs** [comment]
@SlavaET You can check the font size on https://www.elegantthemesdemo.com I guess its fixed already in latest master?.

**Comment by SlavaET** [comment]
@lots0logs I see there is custom css added on demo site which overrides the font-size defined in Blog modules settings:
![image](https://cloud.githubusercontent.com/assets/3446682/21254701/414b255c-c391-11e6-8269-f68ce513e983.png)

It comes from Customizer CSS ( or ePanel which is the same now ).

**Comment by lots0logs** [comment]
That's not Custom CSS..more likely its from Theme Customizer options. Those options should always be overridden by module options though, no?.

**Comment by SlavaET** [comment]
@lots0logs ah, I see. I thought it's custom css, but you're right, it's from the customizer options. Looking into the issue.

**Comment by SlavaET** [comment]
Fixed.

**Comment by lots0logs** [comment]
@SlavaET :cool: what about this, did you notice it from my previous comment? (I edited it a few minutes after commenting):
>As for the meta links color, we don't actually offer the option to change the color of meta text anywhere but in the builder (no such option in Divi nor Extra). So that's not a good reason to exclude a separate option for the links here IMO.
>
>The reason I think its best to go ahead and add the option is because fixing the bug of the links not taking the same color as the text will result in an unwanted style change for some users (surely).

**Comment by SlavaET** [comment]
@lots0logs I see your point, but we have several modules with Post Meta settings like Portfolios, Post Sliders and we apply the same styles for both text and links without separation. So it'll be weird if we'll add this option to Blog module only.. That's what I meant when I said:
>we don't use the separate option for meta links anywhere

@timayhelen do you think we need a separate option for post meta links?

**Comment by timayhelen** [comment]
@lots0logs @SlavaET Let's just keep the way it is for now, I want to stay focused on fixing bugs rather than adding new features. This PR makes the module work like the rest of the modules, which is good for now.

**Comment by lots0logs** [comment]
@timayhelen Please see https://elegantthemes.slack.com/archives/D0KCFUGG6/p1483996076000393
