### ISSUE TITLE
Theme Customizer :: Background : no-repeat

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#852]
@andrey-agp commented on [Wed Dec 14 2016](https://github.com/elegantthemes/Divi/issues/2657)

### Problem:

No Repeat option is not working with Boxed Layout

### Steps To Reproduce:
1. Enable boxed layout
2. Upload background image 
3. Change Background Repeat option to "no repeat"
4.

Same issue with Background Position > Fixed

## Attached PR
- https://github.com/elegantthemes/Divi/pull/2667

**Comment by FaycalBoutam** [comment]
Also for the background position (fixed) it's not working.

**Comment by FaycalBoutam** [comment]
@lots0logs This is important. Customers who used the no-repeat or fixed options are now seeing their site's (bg image) messed up.
