### ISSUE TITLE
Primary Navigation :: Unexpected behavior on touch screens

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#853]
### Problem:

I think we should reinspect primary navigation behavior on touch screens. The problem with tier dropdown menu links. On default WP theme these links acts like that - first touch opens dropdown menu, second touch leads to the link.
If you check our Divi demo site on iPad (landscape oriented) there is no way to reach tier dropdown menu links. Also under IE/Edge (touch) the menu is not working at all. I can reach any menu link. 

### Attached PR
- https://github.com/elegantthemes/Divi/issues/2721

**Comment by SlavaET** [comment]
Done. It works as follows with my PR, if you tap on the menu item, then if the menu item has child elements:
- first tap on that menu item will open the submenu;
- second tap on that menu item will open the link;
- longer tap will open the link right away ( this event considered as click. It's default behaviour of touch devices and we do not adjust it ). This is quite tricky method and you should catch the moment before the long tap device menu is triggered.

**Comment by dm-chechik** [comment]
@SlavaET What about Fullscreen Menu (Fullscreen header style). It seems the top tier links only open and close sub menus. Is it possible to implement the same behavior?

**Comment by SlavaET** [comment]
@dm-chechik yes, it's possible, but Fullscreen menu designed to work that way, top tier menu links disabled for both Desktop and Mobile.
