### ISSUE TITLE
No Divi Builder in Firefox on Macbook Air 13"

### ISSUE THREAD

**Issue by lbjohnson01** [elegantthemes/Divi-Beta#855]
### Problem:

Apologies in advance for the scant details, but I saw this happen on a client's machine during a Divi tutorial so am unable to reproduce it myself or include screenshots. 

Firefox (not sure what exact v.) will not open up the Divi Builder either in Posts, Pages or Projects, when selected

### Steps To Reproduce:
1.  Log in to WP dashboard
2. Go to Posts (or Pages or Projects) / All 
3. Select a post
4. Select Divi Builder
5. No builder shows up
6. Repeat steps 1-5 in Chrome, and the Divi Builder will work

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Macbook Air, circa 2013-2014

**Operating System**: MacOS X

**Browser**: Firefox

**Screen Resolution**: 1400x900

**Comment by lots0logs** [comment]
Hi, if you could, please open a ticket in [our forum](https://www.elegantthemes.com/forum) so that our support team can take a look at the issue. Thanks for your cooperation :smiley:

**Comment by lbjohnson01** [comment]
I just did - thank you!

**Comment by jcdarocha** [comment]
Hi there!

Got the same problem this morning, always worked on FF, and this morning, nothing, can't edit a html box, it doesnn't pop up.
Works well on chrome.

Did you have any informations?
THX
JC
