### ISSUE TITLE
Setting Primary Navigation to "Fullwidth" in the customizer causes horizontal scroll bar

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#857]

**Comment by SlavaET** [comment]
@timayhelen I cannot reproduce the issue. Can you please post the screenshot? Probably it appears  on certain layout only

**Comment by timayhelen** [comment]
@SlavaET Looks like it only occurs when Fixed Navigation is disabled in ePanel.

**Comment by SlavaET** [comment]
@timayhelen fixed. Btw, the issue appears not only in Customizer, but on actual front-end as well.
