### ISSUE TITLE
Slider Module :: Firefox Browser

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#858]
### Problem:

Using the slider module, adding 4 slides, where the last slide only have the background image + the slide image set, it will not render in Firefox, the slide image, doesn't get the max-height property properly set, like it does in Chrome / Safari, and it simply the whole slide has 0px in height.

Please check this demo url in chrome and latest firefox version:
http://divi.wordpress-corner.com/hassenkam/

Here is the layout export:
[icons.json.zip](https://github.com/elegantthemes/Divi-Beta/files/666166/icons.json.zip)

This is how it looks in chrome:
<img width="960" alt="screen shot 2016-12-21 at 1 22 02 pm" src="https://cloud.githubusercontent.com/assets/1719735/21387483/7ddf55c2-c780-11e6-9f21-f885e8ef3f5a.png">

This is how it looks in Firefox:
<img width="960" alt="screen shot 2016-12-21 at 1 22 06 pm" src="https://cloud.githubusercontent.com/assets/1719735/21387486/80251eca-c780-11e6-8cf8-0dc717e23d79.png">

**Comment by SlavaET** [comment]
Eduard, can you please check whether this PR fixes the issue or not - https://github.com/elegantthemes/submodule-builder/pull/1531

**Comment by eduard-ungureanu** [comment]
@SlavaET yap, that fixes the issue with firefox:
<img width="960" alt="screen shot 2016-12-21 at 2 01 47 pm" src="https://cloud.githubusercontent.com/assets/1719735/21388694/12243298-c786-11e6-87b7-7b284943a546.png">

**Comment by SlavaET** [comment]
Great closing it then.
