### ISSUE TITLE
Divi Library :: Impossible to export element

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#859]
### Problem:

Impossible to export element from the library if it belongs to a category that has a parent.

### Steps To Reproduce:
1. Create a Parent category and child category in Divi Library
2. Assign library element to the child category 
3. Try to export the element
4. The export process sucks at 1%

### Attached PR
- https://github.com/elegantthemes/submodule-core/issues/50

**Comment by lots0logs** [comment]
@SlavaET Looks like the child category is exported as if it was a top-level category now. We should retain the category hierarchy for exporting items so that the result after importing them on another site is the same as the original site.

**Comment by SlavaET** [comment]
@lots0logs fixed. Categories hierarchy will be retained now.
But if you export only item ( or items ) which included into child categories and no items from parent category included into the export file, then the child-parent relation will be lost during the import.

**Comment by lots0logs** [comment]
@SlavaET Hmm..why is that? An item in a child category is also considered to be in the parent category regardless of whether it is explicitly configured that way. For example, if you have a category called Vehicles and two child categories called Cars and Trucks, when you list all Vehicles, it will include all the cars and all the trucks.

**Comment by SlavaET** [comment]
@lots0logs do you mean that it's correct to include the post in both parent and child category during the export? It's the only way we can preserve the parent-child hierarchy during the export of posts included into child categories only.
In that case filters in library will work correctly, but it still won't be quite correct and will look differently than it should. 
For example before exporting:
![image](https://cloud.githubusercontent.com/assets/3446682/21670164/3ff2948c-d33c-11e6-9aa2-099ede7a0f62.png)

And after importing these items it'll look like this:
![image](https://cloud.githubusercontent.com/assets/3446682/21670176/646d1aee-d33c-11e6-95fb-bd27fc7576bd.png)

And in the Categories list, before:
![image](https://cloud.githubusercontent.com/assets/3446682/21670190/8ce101de-d33c-11e6-963b-2143b769acc5.png)

after:
![image](https://cloud.githubusercontent.com/assets/3446682/21670196/9cd5c48a-d33c-11e6-8b22-c1f81c84897a.png)

If you think it's fine and expected, then we can do this.

**Comment by lots0logs** [comment]
@SlavaET After taking a closer look at the exported json file I see why you did it the way that you did. Ideally, when exporting layouts from one site and importing them on another site, the category structure for the layouts should be identical to that of the first site. If we cannot accomplish that without too much effort then we can just go with your proposed solution for now.

**Comment by SlavaET** [comment]
@lots0logs I found a way to preserve the full categories hierarchy even when single post from child category imported. Please check the latest version of PR.
