### ISSUE TITLE
VB :: 1/4 columns stick together in Responsive preview on hover

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#865]
### Problem:

![1-4-column-responsive](https://cloud.githubusercontent.com/assets/3446682/21497410/d9873926-cc4e-11e6-94f4-a63cca66e790.gif)

### Steps To Reproduce:
1. Create section with 1/4 1/4/ 1/4 1/4 layout in VB
2. Switch to the Tablet preview mode
3. Hover over the column

**Comment by timayhelen** [comment]
@SlavaET This doesn't work for me. I cleared cache and I am in Incognito. I am testing on the Homepage Basic layout.

**Comment by SlavaET** [comment]
I can't reproduce this issue in the latest master.
@timayhelen @lots0logs can you please check whether you still see the issue in the latest master?

**Comment by timayhelen** [comment]
This was fixed, sorry I forgot to close the issue.
