### ISSUE TITLE
Responsive Preview Mode :: Add New Row Button Not Positioned Properly

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#868]
### Problem:

This happens on tablet and mobile views:

![2016-12-28_07-33-47-am](https://cloud.githubusercontent.com/assets/4675662/21523032/2afe9066-ccd0-11e6-9d79-92fba99695df.png)

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1548

**Comment by fikrirasyid** [comment]
@lots0logs can you elaborate the steps needed to replicate the issue? I tried to replicate the issue, but all of them appears to be correct .

**Comment by lots0logs** [comment]
@fikrirasyid No special steps really. For example, go to https://www.elegantthemesdemo.com and activate the tablet mode. Then look at the add new row button (it will be partially cut off like in the screenshot above)

**Comment by fikrirasyid** [comment]
@lots0logs thanks for the clarification. I've pushed a fix for this issue (see attached PR)

**Comment by lots0logs** [comment]
@fikrirasyid I think your PR will conflict with one of @SlavaET 's (he fixed the issue with the columns moving upon hover).

**Comment by fikrirasyid** [comment]
@lots0logs can you share the link of @SlavaET's PR?

**Comment by lots0logs** [comment]
@fikrirasyid https://github.com/elegantthemes/Divi-Beta/issues/865

**Comment by fikrirasyid** [comment]
@lots0logs fixed, thank you for noticing it 👍

**Comment by timayhelen** [comment]
@fikrirasyid This worked for responsive preview modes, but not when the browser was actually sized down manually. I added the same fix for the normal @media breakpoint.
