### ISSUE TITLE
Secondary Menu appearing as right hand vertical

### ISSUE THREAD

**Issue by janeemckay** [elegantthemes/Divi-Beta#87]
### Problem:

Secondary Menu appearing as right hand vertical.

### Steps To Reproduce:
1. Theme customizer
2. Click Show Social Icons
3.
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: PC

**Operating System**: Windows 8

**Browser**: Chrome 

**Screen Resolution**:

**Screenshots**:
Before I click "Show Social Icons"
![no social icons](https://cloud.githubusercontent.com/assets/21113541/17797752/cf758128-660e-11e6-82e8-5edeea2a3bef.png)

After I click "Show Social Icons"
![social icons](https://cloud.githubusercontent.com/assets/21113541/17797764/de176fc0-660e-11e6-9e15-e2f46a58b56c.png)

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
This may be related to https://github.com/elegantthemes/Divi-Beta/issues/69

**Comment by SlavaET** [comment]
@timayhelen yeah, I think it won't be an issue after we restrict the loading of Frontend Builder inside Customizer. I checked it in my branch with the fix and cannot reproduce the issue.
