### ISSUE TITLE
Divi 3.0.26 Causing Issue With Responsive Editing

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#871]
A few users are reporting that, after upgrading to Divi 3.0.26, their customizations for Tablet and Smartphone breakpoints in the Divi Builder (using the responsive editing feature) have disappeared. After loading up each module's settings and saving the page, the customizations return. 

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=634798&p=3497970
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=634472

I am guessing that this is related to: https://github.com/elegantthemes/Divi-Beta/issues/679

**Comment by SlavaET** [comment]
weird, I tried several options and they work after update.
I tested it like this:
1) activate old version of Divi 3
2) adjust padding and font-size for all the breakpoints in Blurb module
3) save
4) activate the latest version of Divi 3
5) check output on front-end and in VB.
All the responsive options work as expected.
@timayhelen are you able to reproduce it?
