### ISSUE TITLE
Mega Menu :: 3rd level children

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#872]
### Problem:

Not sure if this is an actual issue, or this is how it suppose to work but it looks like if using the mega menu the user cannot add a 3rd level menu item, that item will show in the mega menu.

Here is an example:
<img width="960" alt="screen shot 2017-01-03 at 12 30 45 pm" src="https://cloud.githubusercontent.com/assets/1719735/21605245/7bc20ad4-d1b0-11e6-865e-47d3f9f67ce5.png">

The menu item called 4 Box Layout - full width, it should be a children of the mega menu item calle Sub Mega Menu item 1, instead it does show as a mega menu item:
<img width="960" alt="screen shot 2017-01-03 at 12 30 53 pm" src="https://cloud.githubusercontent.com/assets/1719735/21605272/a321af12-d1b0-11e6-91b1-d2d6502fa850.png">

**Comment by timayhelen** [comment]
This is working as intended
