### ISSUE TITLE
Impossible To Exit Inline Editor

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#875]
It is currently impossible to exit the inline editor after clicking into editable content in the Visual Builder. If you click ESC, or click outside the editable area, the cursor is removed and it looks like you have exited the content area. However, if you start typing your typed content appears at the beginning of the editable area. 

Larger events, such as adding new modules or opening settings modals, will allow you to successfully exit the inline editor.

![inline-editor](https://cloud.githubusercontent.com/assets/3333028/21629442/350475dc-d1dd-11e6-9be0-6de23fac8d45.gif)

I also notice that changes made to content in this way (after unsuccessfully "exiting" the inline editor and then adding content) do not create history events.

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1558

**Comment by lots0logs** [comment]
@SlavaET A couple issues:

![2017-01-04 13-58](https://cloud.githubusercontent.com/assets/4675662/21657061/3dbab426-d286-11e6-9abb-be881b2dc0d0.gif)
___________________________________________________

![2017-01-04 14-00](https://cloud.githubusercontent.com/assets/4675662/21657073/49233626-d286-11e6-8fa3-bab01e52ec07.gif)

**Comment by SlavaET** [comment]
@lots0logs fixed.

**Comment by lots0logs** [comment]
@SlavaET I'm still seeing the issue with the accordion.

**Comment by SlavaET** [comment]
@lots0logs what's wrong with the accordion? I'm not sure that understand it from your screen last. Can you please explain?

**Comment by lots0logs** [comment]
@SlavaET Yeah, (sorry). Only one accordion section should be open at any time. When you open a section the section that is currently open should close. Check it on the demo to see the correct behavior.

**Comment by SlavaET** [comment]
Got it, I was trying to see the issue with inline editor on your scrrencast 😀

**Comment by SlavaET** [comment]
@lots0logs are you sure you're checking accordion module? I checked accordion and it works fine on my end, then I checked your screencast again and it looks like you have several toggle modules on your test page instead of accordion. Can you please double-check that?

**Comment by lots0logs** [comment]
@SlavaET omg
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/21782114/e947773a-d677-11e6-8662-028b7f93fabe.gif)

**Comment by Jronk** [comment]
See PR review

**Comment by SlavaET** [comment]
@Jronk fixed.
