### ISSUE TITLE
Module options panel is inaccessible on certain layots

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#878]
### Problem:

It seems we have already fixed the same issue before. However I can't find the issue on GitHub.
The row options panel overlaps module panel if it located at the top left corner of the row and the module height is low.
![image](https://cloud.githubusercontent.com/assets/20072036/21714700/735ee246-d411-11e6-893e-f20e44bafb5f.png)

This is how the layout looks from backend editor.
![image](https://cloud.githubusercontent.com/assets/20072036/21714717/8897826c-d411-11e6-8930-a7e6c59b3ff3.png)

Can we put row options panel over the row outline?

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1577

**Comment by fikrirasyid** [comment]
@dm-chechik can you share the layout you're using? I tried to replicate the issue, but the adjustment we have made turns out to work as expected:

![878-fix-inaccessible-options-panel](https://cloud.githubusercontent.com/assets/916442/22045197/623d7e4e-dd4b-11e6-86b6-0858fba2ab91.gif)

**Comment by timayhelen** [comment]
@fikrirasyid I believe it's from this pacL

https://www.elegantthemes.com/blog/divi-resources/download-our-free-divi-layout-pack-for-modern-homepages-and-single-page-websites

**Comment by fikrirasyid** [comment]
@timayhelen it's on `Pack 1 - published` on our dropbox, isn't? I'll take a look on it.

**Comment by fikrirasyid** [comment]
Confirmed. It can be replicated using slightly modified `homepage - 2` layout:

![878-replicated-issue](https://cloud.githubusercontent.com/assets/916442/22046275/1a8ba312-dd52-11e6-999c-65164cffb612.gif)

**Comment by lots0logs** [comment]
@fikrirasyid If you set the row padding to a low value or to zero then its still very difficult to access the image module options. Though I'm not sure how we can make it any better in this case :thinking:

**Comment by fikrirasyid** [comment]
@lots0logs I've pushed a commit which makes the overlapping module popup settings to be more accessible.

![878-fixed](https://cloud.githubusercontent.com/assets/916442/22092329/7c27f214-de2f-11e6-87d3-979ca5473ace.gif)

Note: the hovered module on the gif above is the image module (heart image). You can test this issue using this following layout:

[878-fix-innacessible-options.json.zip](https://github.com/elegantthemes/Divi-Beta/files/715623/878-fix-innacessible-options.json.zip)

**Comment by lots0logs** [comment]
@fikrirasyid Its still hard to tell which module the settings bar being displayed is for. 

![2017-01-19 19-50](https://cloud.githubusercontent.com/assets/4675662/22132641/d941520a-de80-11e6-9cc0-ec051f74cbfe.gif)

Though I think this is the best we can do in cases like this one. Let's see what @timayhelen thinks...

**Comment by fikrirasyid** [comment]
@lots0logs that is inevitable case for first module on the first column of the row, especially when the height of the module is relatively equal to the row settings popup's height.

**Comment by lots0logs** [comment]
Yeah, I think this is an edge case anyway. The Blurb Module could be used instead of an image module and multiple text modules to achieve the same end result. In fact, maybe we should update this layout to use the Blurb Module. Hmmm.. :thinking: @mariomaruffi ?

**Comment by timayhelen** [comment]
@lots0logs We don't need to spend time updating old layouts.
