### ISSUE TITLE
Plugin Compatibility :: Conflict with reCAPTCHA feature from iThemes Security Pro

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#880]
### Problem:

Can anyone check the following ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=627543

The plugin does not work with divi and honestly I'm not sure if it actually should work or not.
Also, the plugin author says they try to contact with Eleganthemes.

**Comment by lots0logs** [comment]
@kary4 Messaged you on Slack :smiley:
