### ISSUE TITLE
Number Counter Module :: Adding a dot or comma to number 

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#887]
### Problem:

The animation is smooth when you add numbers only, but when adding a comma or a dot, the animation is not "smooth"

![62](https://cloud.githubusercontent.com/assets/16414613/21831296/92587aea-d79a-11e6-8029-521a95c79262.gif)

**Comment by timayhelen** [comment]
I don't think there is much we can do here, aside from stripping out all non-numerical characters. I am not sure it's a good idea though. It's technically working correctly, counting up to 19, it just does't count up decimal places.
