### ISSUE TITLE
Visual Box Layout does not show in Fullwidth Slider

### ISSUE THREAD

**Issue by yuricp** [elegantthemes/Divi-Beta#89]
### Problem:

In Visual Builder mode, each module has a menu and a visual box layout. 

![divi-beta-bug05](https://cloud.githubusercontent.com/assets/18079469/17798204/e3d5ee0c-6594-11e6-8ae0-2c42d6e47c5e.jpg)

But in the Fullwidth Slider module, only menu shows (not the box layout).

![divi-beta-bug07](https://cloud.githubusercontent.com/assets/18079469/17798231/19892d66-6595-11e6-825a-abd277473179.jpg)

**Comment by timayhelen** [comment]
This is intentional UI choice. Basically we only display outlines for parent elements (things that contain other things).

**Comment by fikrirasyid** [comment]
@yuricp module actually doesn't have outline by design. Only section and row (the green one is row) which have outline. Fullwidth doesn't have row, only `Section > Module`

**Comment by yuricp** [comment]
Thank you (Sorry my bad english)

**Comment by fikrirasyid** [comment]
@yuricp no problem :)
