### ISSUE TITLE
VB :: Fullwidth Slider :: Heading :: Padding is not the same

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#890]
### Problem:

It seems Visual Builder uses different padding for the slider heading. As a result slider heading appearance different in the VB and on frontend.
![image](https://cloud.githubusercontent.com/assets/20072036/21866656/25abcd3a-d85c-11e6-850a-d68fe762003b.png)

![image](https://cloud.githubusercontent.com/assets/20072036/21866676/3b652fe0-d85c-11e6-9092-c652d615eda2.png)

**Comment by lots0logs** [comment]
@dm-chechik Were you able to reproduce this issue? I checked it on my test site and the issue does not occur.

**Comment by timayhelen** [comment]
This is probably due to the admin bar reducing the height of the content area or something like that. I don't think it's fixable since it's not really a bug.

**Comment by lots0logs** [comment]
@timayhelen I think he is referring to the left/right padding :notsureif:

**Comment by timayhelen** [comment]
I see, looks like this is a real bug and we should figure it out: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=636226&hilit=visual+builder

**Comment by dm-chechik** [comment]
@lots0logs I've sent you my test page layout via slack
