### ISSUE TITLE
Reduce Delay Used For Recording Inline Editor Changes

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#893]
Currently when you make a change to the page using the inline editor, there is a 300ms delay before those changes are saved. So you make a change to some text content and then quickly exit the inline editor or click into a different editable area, the changes you just made are reverting. I am not sure why this delay exists, but I think it needs to be reduced. Is it safe to reduce this to 100ms?

![delay](https://cloud.githubusercontent.com/assets/3333028/21870232/27576384-d810-11e6-8960-5cf19eff3326.gif)

**Comment by SlavaET** [comment]
@timayhelen it was reduced to 100ms already, in this PR - https://github.com/elegantthemes/submodule-builder/pull/1417
So it should be 100ms in the latest master.
