### ISSUE TITLE
Draggable Padding Doesn't Work Correctly For Inner Rows

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#898]
When hovering over rows inside of specialty sections, the draggable padding indicators do not appear. After you drag padding for the first time, the indicators start to appear correctly. 

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1568

**Comment by timayhelen** [comment]
![row-padding](https://cloud.githubusercontent.com/assets/3333028/21942074/58e699ee-d980-11e6-99c2-a61a6eccfc84.gif)

**Comment by lots0logs** [comment]
@fikrirasyid Please see my review. Thanks.

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated your feedback 👍
