### ISSUE TITLE
Is It Possible To Split Up The Save Request, Or Make The Request Smaller?

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#899]
We have a lot of people who have trouble saving their changes in the Visual Builder. It's usually related to a timeout issue with the Ajax request to save, often related to the size of the request. Often times the following rule in htaccess will fix it:

```
<IfModule mod_substitute.c>
SubstituteMaxLineLength 10M
</IfModule>
```

Other times, increasing settings like these will fix it:

```
memory_limit = 125M;
max_execution_time 180
upload_max_filesize 256M
post_max_size 1024
max_input_time 600
max_input_vars 5000
```

I am wondering if it might be possible split up the saving mechanism into 2 smaller requests? Could we save half of the page at a time? Or maybe there is some other way to tackle this problem? Instructing people to edit their htaccess file isn't a good enough solution.

**Comment by lots0logs** [comment]
This will be addressed in #723

**Comment by lots0logs** [comment]
Actually let's revisit this after #723 is merged.

**Comment by Jronk** [comment]
Note, in case we do need this eventually. Our shortcode can be split by sections, and concat'ed on the server.
