### ISSUE TITLE
Cancelling split test causes advisory popups

### ISSUE THREAD

**Issue by jamesheath12** [elegantthemes/Divi-Beta#9]
### Problem:  Cancelling split testing causes popups afterwards

I turned on the split testing in a post, fiddled with it for awhile, then turned it off.  Every subsequent save of other items (like section color) causes a popup with a heading of "End split testing?".  I also don't get an active 'update' button capability if I change a different item in the page settings, like 'section background color'.

### Steps To Reproduce:
1. Turn on split testing, and set the item to monitor
2.  Turn split testing off
3.  Open the page settings again, change a section background, and save the setting
4.  Link on hover of the settings is: /wp-admin/post.php?post=31&action=edit&w3tc_note=flush_all#  (with website prefixed, but removed for this entry)

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:  Mac Mini

**Operating System**:  OSX 10.11

**Browser**:  Firefox 44.0.2

**Screen Resolution**:  1920x1200

**Screenshots**:  ![screen shot 2016-03-20 at 11 01 24 pm](https://cloud.githubusercontent.com/assets/17970652/13909814/ea7f2730-eeef-11e5-91ce-f7b7f6e8cc39.png)

Website has WP Total Cache active.  Clearing the cache doesn't resolve the issue.

-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by fikrirasyid** [comment]
Hi @jamesheath12, thank you for reporting this issue. I've found a possible fix for this issue, but there is one thing I'd like to verify about how you turn off the split testing. How did you turn off the split test? 

Did you do this (Option A):

1. Open builder settings on the top right of the builder
2. Set **Enable Split Testing** to `No`
3. Click save
4. Continue editing builder
5. The `end split test?` popup appears when you clicking anything


Or did you do this (Option B):

1. Open builder settings on the top right of the builder
2. Set **Enable Split Testing** to `No`
3. Click save, the popup disappears, 
4. Select which split testing subject you'd like to keep. 
5. Click subject you'd like to keep (the other subjects will be removed)
6. Continue editing builder
7. The `end split test?` popup appears when you clicking anything

Thank you for your clarification :)

**Comment by fikrirasyid** [comment]
@jamesheath12 we've submitted a patch for this issue and it is currently under review process. Once it passes the review process, it should be available on the next beta release. I'll keep you notified.

However, your clarification on https://github.com/elegantthemes/Divi-Beta/issues/9#issuecomment-199626513 might change the status of the patch (especially if my assumption is incorrect) :)

**Comment by jamesheath12** [comment]
The use scenario that you've added is essentially how it happened, except step 6. I didn't refresh the screen. I can change another setting, such as the color palette, save the settings, and upon saving the settings, the popup occurs. At this point, the update button for the post is disabled, as if no edits have been made. If I don't make some other content change, the update button isn't enabled.

**Comment by fikrirasyid** [comment]
@jamesheath12 thank you for your clarification. I've rechecked how the fix works and how the issue emerges based on your clarification. I think the existing patch that I've submit should've fixed your issue regardless the difference in step. 6. we'll continue the review process and hopefully this will be merged on the next beta release cycle :)
