### ISSUE TITLE
Saving content :: Tool Set Plugin

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#901]
### Problem:

One customer have reported that when using Tool Set Plugin, he will not be able to save any content. I advise him to check with the plugin author about this issue, they have investigate the issue, and it looks like this happens, only when using the image filed.

This is a topic reply from their support team:

> It took quite a while to track down what exactly was the cause, and the JS errors on the page (that you can see in your browser console when you try to save a post) are caused by a conflict which arises when you have a Types image field assigned to the post.
>
> I removed the image fields from your posts custom field group and the issue was resolved.
> 
> I was then able to reproduce the problem on a fresh install with just Types 2.2.5 and Divi 3.0.27 by adding an image field to a custom fields group assigned to standard posts.
> 
> I have escalated this so our compatibility team can investigate further. In the meantime it seems you won't be able to include custom image fields on your posts, I'm afraid.

**Comment by timayhelen** [comment]
Sounds like we can let their team handle it.
