### ISSUE TITLE
Uploading Images In The Visual Builder Doesn't Work With Domain Mapping

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#904]
It has been reported that, for sites that are using domain mapping, image uploading results in an error in the Visual Builder.

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=638477&hilit=visual+builder

**Comment by SlavaET** [comment]
@lots0logs is it possible to enable and test it on one of the live test websites? I cannot test it on localhost, that plugin doesn't seem to work for me.

**Comment by lots0logs** [comment]
@SlavaET Sure :smiley: Do you still have the credentials I sent you the other day?
