### ISSUE TITLE
Shop Module :: Products type and product category

### ISSUE THREAD

**Issue by lceberg** [elegantthemes/Divi-Beta#906]
### Problem:

Once a product category is selected, that category persists no matter which option is selected under "Type" afterwards. However, the "Include Categories" checkboxes are only visible when "Product Category" is selected.

### Steps To Reproduce:
1. Select "Product Category" under "Type" and check any of the available categories
2. Change "Type" to "Featured Products"
3. Only the featured products from the categories selected in Step 1 would be displayed

I believe a solution for this would be either to:
- ignore the checked categories when "Product Category" is not selected
- make the checkboxes visible for all types whose shortcodes support categories

@timayhelen @lots0logs can you please give feedback on which option sounds better to you ?

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1576

**Comment by timayhelen** [comment]
@lceberg Let's leave the product selection visible for all modes that support it.

**Comment by lceberg** [comment]
Turns out all the modes support it, so the PR simply removes the conditional logic on that section.

Note: Even though the checkboxes would now be always visible, "Product Category" is still a viable selection if categories are the only criteria the user wanted to use to sort their products.
