### ISSUE TITLE
VB :: Cannot Close Settings Modal After Changing A Computed Setting's Value

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#909]
### Steps To Reproduce:
1.  Add a gallery module to the page.
2. Change it from grid to fullwidth (which is a computed field)
3. Wait for gallery to render and then try to close settings modal.

### Additional Information:
* RE: https://github.com/elegantthemes/submodule-builder/commit/d1abe316a8474f2ca8e370ae992e00791926bc88

I'm sure this affects all modules that have computed settings (not just the gallery)

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1615

**Comment by timayhelen** [comment]
FYI this only occurs after you save and refresh the builder. 

- Add a gallery module to the page.
- Save the page.
- Refresh the page.
- Change it from grid to slider.
- Wait for gallery to render and then try to close settings modal.
