### ISSUE TITLE
VB :: Portability :: Exporting Layout Triggers Browser Exit Confirmation Dialog

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#910]
### Problem:

https://github.com/elegantthemes/Divi-Beta/issues/683#issuecomment-275278129

**Comment by lceberg** [comment]
I added a solution for this (check PR for description of the approach). Not sure if we have to tweak this when the modal in https://github.com/elegantthemes/Divi-Beta/issues/683 is implemented but we might use similar logic.
