### ISSUE TITLE
Sync click/drag padding changes to device view

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#913]
### Problem:
After many site builds with Divi3,  this is a feature request that I didn't see mentioned.  While working in VB, the click/drag padding change feature should be synced to the media queries of whichever view you are in from the lower left corner view links.   This would be an incredible time saver.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1799

**Comment by fikrirasyid** [comment]
@websbyjd have you tried activate the responsive mode of the padding first? This is actually exists on current version, however you need to activate the responsive mode first. So, a little background:

1. We improved the way responsive value works
2. Basically, responsive inputs values (tablet, phones) will only be used if its responsive mode is activated which is indicated by toggled on tabs
3. If responsive mode isn't activated, desktop value will be used for all breakpoints

![screen shot 2017-03-01 at 1 01 55 pm](https://cloud.githubusercontent.com/assets/916442/23447701/48cb84e2-fe7f-11e6-8d2d-c200a8d20d41.png)
**Responsive mode activated**

![screen shot 2017-03-01 at 1 01 48 pm](https://cloud.githubusercontent.com/assets/916442/23447706/502d88a2-fe7f-11e6-8700-23595fe68069.png)
**Responsive mode inactive**

Considering this behaviour, the way drag padding UI works are:

1. If responsive mode isn't activated, dragging on any breakpoint will modify desktop values:

![responsive-mode-deactivated](https://cloud.githubusercontent.com/assets/916442/23447732/7ce5256c-fe7f-11e6-9cda-af307e8c5d96.gif)

2. If responsive mode is activated, dragging on respective breakpoint will modify the value of the related input breakpoint.

![responsive-mode-activated](https://cloud.githubusercontent.com/assets/916442/23447752/9ed6da1c-fe7f-11e6-89eb-b347cf3e8387.gif)

@timayhelen what do you think on this? Should we automatically activate responsive mode if the padding is dragged on mobile breakpoint?

**Comment by lots0logs** [comment]
>Should we automatically activate responsive mode if the padding is dragged on mobile breakpoint?
+1 from me :smiley:

**Comment by fikrirasyid** [comment]
@lots0logs it feels intuitive indeed but there is one thing that kinda bothers me: activating responsive mode is intentional and I don't have any idea whether user wants to activate responsive mode or not when dragging padding UI 🤔

**Comment by lots0logs** [comment]
@fikrirasyid I think when the user is dragging padding while in responsive preview mode they expect the padding to be applied to the breakpoint they are previewing :philosoraptor:

**Comment by fikrirasyid** [comment]
@lots0logs i see, i start to see your point. Let's automatically activate responsive mode if user drags padding on mobile breakpoint.

**Comment by fikrirasyid** [comment]
@lots0logs @websbyjd I've submitted a PR which automatically activate responsive mode when padding UI is being dragged on mobile breakpoint.

![913-fixed](https://cloud.githubusercontent.com/assets/916442/23457835/1c94512e-feac-11e6-966e-38cff2232739.gif)
