### ISSUE TITLE
Dreamhost :: Builder Sync :: Text Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#915]
### Problem:

Having the same page opened in 2 tabs: in tab 1 it's the Back End Divi Builder, in tab 2 is Divi Visual Builder, changing the text orientation in back end, doesn't update the front end, while changing the same option in the Visual Builder does update the back end:

https://drive.google.com/open?id=0B8PjD3Z_XQvuaXJBaC1JXzNneDg

**Comment by timayhelen** [comment]
@eduard-ungureanu Can you check again? I have updated Divi on Dreamhost with a potential fix.

**Comment by FaycalBoutam** [comment]
I'm still seeing this issue with Dreamhost account.

**Comment by timayhelen** [comment]
@FaycalBoutam I update the theme on BllueHost. Can you try again?

**Comment by eduard-ungureanu** [comment]
@timayhelen : tested again, and now all the options works as it should both from back end > visual editor as well as visual editor > back end builder. Thank you

**Comment by FaycalBoutam** [comment]
@timayhelen It's all okay now.
