### ISSUE TITLE
Dreamhost :: Builder Sync :: Text Module :: Body font styles

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#916]
### Problem:

Changes done in the backend Builder for the body font styles of Divi Builder, doesn't get updated in the Visual Builder, while changes made in Visual Builder does get updated in the backend Builder.

https://drive.google.com/open?id=0B8PjD3Z_XQvuX2VCZXRoQU1FSlE

Update:
None of the module settings (General, Advanced, custom css) do get updated into the Visual Builder, while the same settings made in Visual Builder do get updated into the Back end Builder.

Related: https://github.com/elegantthemes/Divi-Beta/issues/915

**Comment by timayhelen** [comment]
@eduard-ungureanu Can you check again? I have updated Divi on Dreamhost with a potential fix.

**Comment by eduard-ungureanu** [comment]
@timayhelen now everything works perfectly regarding the text module!
