### ISSUE TITLE
Siteground :: Builder Sync :: Does Not Enable Divi Builder

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#917]
### Problem:

You have to enable divi builder in two opened browser's tabs. If you have one tab divi builder disabled and in another tab divi builder is enabled then you'll lost builder layout. In a short, it does not enable/disable divi builder. 

Screen cast:
http://youtu.be/oRz8wPJ_JME?hd=1

**Comment by eduard-ungureanu** [comment]
Same issue on dreamhost - although not sure, if this should also enabled the Backend Builder.

**Comment by timayhelen** [comment]
I think this is ok for now.
