### ISSUE TITLE
Dreamhost :: Builder Sync :: Blurb Module Settings

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#918]
### Problem:

None of the Blurb Module's settings does get updated on the Visual Builder, while the changes made in Visual Builder do get updated into the Back End Builder.

https://drive.google.com/open?id=0B8PjD3Z_XQvuMWs0TS13cDZZa1E

**Comment by timayhelen** [comment]
@eduard-ungureanu Can you check again? I have updated Divi on Dreamhost with a potential fix.

**Comment by eduard-ungureanu** [comment]
@timayhelen the fix is working properly now!
