### ISSUE TITLE
Dreamhost :: Builder Sync :: CTA Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#919]
### Problem:

None of the settings, done in the Backend Builder does update the Visual Builder, while the settings done in Visual Builder do get updated in the Backend Builder.

**Comment by timayhelen** [comment]
@eduard-ungureanu Can you check again? I have updated Divi on Dreamhost with a potential fix.

**Comment by eduard-ungureanu** [comment]
@timayhelen test the CTA module, and it works now, thank you!
