### ISSUE TITLE
VB when initiated from the front end adds a full width header prior to editing

### ISSUE THREAD

**Issue by elegantmarketplace** [elegantthemes/Divi-Beta#92]
### Problem:

VB when initiated from the front end adds a full width header prior to editing. ON refresh with no save, additional section remains both in back and front

### Steps To Reproduce:
1. See video 

https://www.dropbox.com/s/hduzwcc78rx78kw/adds%20another%20full%20width%20header%20when%20VB%20is%20engaged%20from%20both%20front%20end%20and%20back%20office.mp4?dl=0

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Lenovo 23" 16mb ram 1tb memory PC**:

**Operating System**:
Windows 10

**Chrome**:

**HD**:

**Video*:
As link above - I am using a child theme. 

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
Do you have any plugins installed? We are not able to replicate this. It would also be helpful to export the layout you are testing post it for download here. Thanks!

**Comment by elegantmarketplace** [comment]
No Plugins and I think it is user error as I did not realise there were two headers in the page one for mobile and one for desktop- I can see though how someone could get confused - (feel like a novice user now :/) Json attached. 
[Double_Header_for_mobile_and_Desktop.zip](https://github.com/elegantthemes/Divi-Beta/files/426719/Double_Header_for_mobile_and_Desktop.zip)
.
