### ISSUE TITLE
Dreamhost :: Builder Sync :: Updating layouts

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#920]
### Problem:

Adding modules / changing layout in Backend builder doesn't get updated the Visual Builder, while the same process but done in Visual Builder does update the Backend Builder:
https://drive.google.com/open?id=0B8PjD3Z_XQvuNjZydjZGYk1FVHM

**Comment by timayhelen** [comment]
@eduard-ungureanu Can you check again? I have updated Divi on Dreamhost with a potential fix.

**Comment by eduard-ungureanu** [comment]
@timayhelen : the fix now works, the layout changes works in both ways!
