### ISSUE TITLE
Siteground :: Builder Sync :: Divi Builder Does Not Work

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#921]
### Problem:

This problem might be related to:
https://github.com/elegantthemes/Divi-Beta/issues/917

And probably if we fix the above issue then this issue will be fixed as well, but I think in some situations this problem can appear again. 

### Steps To Reproduce:
1.  Create new page > Publish the page.
2. Preview the page in a new tab > Enable Visual Builder.
3. Go back to the first tab (back end default wordpress editor, the page you created in the first step) and Update the page.
4. Go to the 2nd tab (Visual Builder) > Save the changes. 
5. Exit Visual Builder > Enable Visual Builder > Edit Page.

You can see the problem in the screen shot below. 
![1artwork richard slechta - mozilla firefox](https://cloud.githubusercontent.com/assets/3352130/22691981/e73d6ebc-ed4d-11e6-8e3d-0779e79b0355.jpg)

Also, to avoid any confusion please check the screen cast here:
http://youtu.be/A8qNsnl-gQM?hd=1

Test page:
http://elegantthemessiteground.com/wp-admin/post.php?post=186&action=edit

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1734

**Comment by timayhelen** [comment]
This bug already exists in master, but we should try to fix it since it may be more prevalent now that people will be using the sync feature.
