### ISSUE TITLE
Divi Builder Timeout When Enabling Visual Builder Without Saving The Page

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#923]
### Problem:

One the VB is activated you have to Update the page. You can't open Visual Builder right away. You'll see No Result Found.

Screen cast:
http://youtu.be/NK1e3VnvBI4?hd=1

**Comment by timayhelen** [comment]
This occurs in the latest master as well. It happens when you enabled the Divi Builder and then click "use visual builder" without saving the page. 

1. Create a new page. 
2. Save the page. 
3. Enable the Divi Builder. 
4. Without saving, click "use visual builder."

**Comment by kary4** [comment]
I'm not sure if I should open a new ticket for the following problem:

1. Get the Divi Builder Timeout error via the steps you explained above.
2. Go back to BB save everything.
3. Go to VB and refresh the browser. I do expect it should update everything and you should see Divi builder. But it still displays No Result Fond. You have to close the tab at all and open it again.

Screen cast:
http://youtu.be/VrhI3jmKtFU?hd=1

Though I think this cannot be fixed because the No Result Found page have different URL..

**Comment by fikrirasyid** [comment]
This has been fixed on latest master, particularly on this PR: https://github.com/elegantthemes/submodule-builder/pull/1703
