### ISSUE TITLE
Siteground :: Builder Sync :: Divi Builder Layout Saves Even I Don't Save The Layout

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#924]
### Problem:
Divi builder saves on its own. I did not mean to keep divi builder activated. 

### Steps To Reproduce:
1.  Create and publish new page.
2. Enable Divi Builder and click Visual Builder.
3. Click Edit Page.
4. Refresh the browser's window.

It should be default wordpress editor, because you did not add any changes. But you'll see the Divi Builder is saved.

Screen cast:
http://youtu.be/7KPznRywJ8E?hd=1

**Comment by timayhelen** [comment]
This is unrelated actually. Clicking "Use Visual Builder" has always saved the page.
