### ISSUE TITLE
Siteground :: Builder Sync :: It Always Asks Me To Restore/Save Changes Even I add Nothing

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#925]
### Problem:
It's a bit annoying and confusing when you add nothing and it still want's to save something (even I saved changes).

### Steps To Reproduce:
1.  Create and Publish new page.
2. Activated Divi builder.
3. Open Visual Builder.
3. You'll see the Restore Popup window. Restore the changes.
4. Click Edit Page > Save changes. 
5. Now repeat steps 3-4.

Screen cast:
http://youtu.be/v03F9wSLyIU?hd=1

**Comment by timayhelen** [comment]
I am experiencing this as well, when clicking Use Visual Builder from inside the Backend Builder. It asks me to restore an auto save almost every time, even after I just saved the page.

**Comment by timayhelen** [comment]
This is possibly related to https://github.com/elegantthemes/Divi-Beta/issues/929

**Comment by timayhelen** [comment]
I am closing this is favor of https://github.com/elegantthemes/Divi-Beta/issues/929
