### ISSUE TITLE
Divi Builder Sync :: Visual Builder Is Launched Automatically When Previewing A Page

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#927]
1. Create a new page. 
2. Publish the page without enabling the Divi Builder.
3. Preview the page. 

The page will display the Divi Builder Failure modal, even though the Divi Builder is not enabled and we are only trying to preview the page. 

Upon further inspection, it appears that when you "Preview" a page, it tries to launch the Visual Builder. The builder then fails to load because there is no builder content. We should not be launching the Visual Builder automatically when previewing changes. 

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1713

**Comment by lots0logs** [comment]
@Jronk I actually couldn't reproduce the issue while following the steps @timayhelen provided on `575-fix-heartbeat-content-smashing-wip`. Nor could I reproduce it on `927-visual-builder-is-launched-automatically-when-previewing-a-page`. However, I noticed that if the Divi Builder is active and you click to preview the page it loads the visual builder. This happens on both branches.

**Comment by timayhelen** [comment]
@Jronk Yeah, it still launches the Visual Builder when previewing if the Divi Builder is enabled.
