### ISSUE TITLE
Impossible To Disable The Divi Builder When Restore Page Is Empty

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#933]
It's currently impossible to disable the Divi Builder once it has been enabled in this branch. 

1. Create a new page. 
2. Enable the Divi Builder. 
3. Load a layout.
4. Save the page. 
5. Refresh the page. 
6. Click "Use Default Editor" 
7. Save The Page. 

The Divi Builder + the previous layout you saved will be restored instead of saving the page with the Divi Builder disabled. 

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1850

**Comment by timayhelen** [comment]
Never mind this is not related to Divi Builder sync.

**Comment by fikrirasyid** [comment]
@timayhelen can you still replicate this issue? I've tested this on `master` and it appears that this issue is no longer exist:

![933-issue](https://cloud.githubusercontent.com/assets/916442/23491137/f89adeae-ff2e-11e6-9896-fea0b1f34497.gif)

**Comment by timayhelen** [comment]
@fikrirasyid It still happens, you just need to go one step further than you did in your GIF to see the problem (you need to save and refresh to see that the builder is still active)

1. Create a new page. 
2. Enable the Divi Builder
3. Publish The Page. 
4. Disable The Divi Builder
5. Save The Page. 
6. Refresh to see that the builder is still active. It can't be disabled.

**Comment by fikrirasyid** [comment]
@timayhelen I think I can replicate it now. The reason why it can't be replicated earlier is that I filled the title field. If i filled the title field then save it, it can be disabled as expected. However if the title field is empty, the issue reported on this ticket can be replicated.

I'll look into this.
