### ISSUE TITLE
Dreamhost :: Builder Sync :: Bar Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#936]
### Problem:

Adding a Bar module in BackEnd Builder updates the Visual Builder, the problem is trying to edit the Bar Module on Visual Builder doesn't work anymore.

Adding a Bar Module in Visual Builder, can be edited in Visual Builder, it does also update the BackEnd Builder.

https://drive.google.com/open?id=0B8PjD3Z_XQvuUGo2NU9CVk5YRlE

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1721

**Comment by FaycalBoutam** [comment]
Same with BlueHost.
