### ISSUE TITLE
Dreamhost :: Builder Sync :: Button Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#937]
### Problem:

Adding the button module in VB doesn't update the BB, also the custom styles applied to the button module in VB doesn't update the Styles in BB. In this case if the Button Module is opened in BB to check the styles if those are applied, upon saving will reset the styles on VB.

Also there should be an option to choose the color of the icon on hover. 

Ussage case:
- the icon has the same color as the text on normal state
- the icon is set to show also for normal state
- on hover the background color is the color for the text in normal state
- the icon is not visible when hover.

https://drive.google.com/open?id=0B8PjD3Z_XQvuX2N0MXNZaE9OOUE

https://drive.google.com/open?id=0B8PjD3Z_XQvuZnNSdUVrdGw5MVE

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1733

**Comment by timayhelen** [comment]
It looks like a button module with no button text doesn't show up when synced from the BB. It is supposed to display default text, which works when you add a blank button directly to the Visual Builder.

**Comment by fikrirasyid** [comment]
The issue where custom styling don't get synced is essentially the same issue as what happened on https://github.com/elegantthemes/Divi-Beta/issues/944. I've submitted https://github.com/elegantthemes/submodule-builder/pull/1731 to fix it. I'm still investigating the non syncing button issue
