### ISSUE TITLE
Dreamhost :: Builder Sync :: Adding row

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#938]
### Problem:

Adding row from Library in BB generate Js error, while repeating the same process in VB works, and it also updates the BB.

https://drive.google.com/open?id=0B8PjD3Z_XQvueXA1TWo2UXdCZnc

**Comment by fikrirasyid** [comment]
This is duplicate of https://github.com/elegantthemes/Divi-Beta/issues/955 which has been fixed on latest `575-fix-heartbeat-content-smashing-wip`
