### ISSUE TITLE
Color picker with elements near top of screen - can't close

### ISSUE THREAD

**Issue by Mizagorn** [elegantthemes/Divi-Beta#94]
### Problem:

Selecting text near top of screen and pulling up the color picker results in the top portion of the color picker being hidden.  You can select a color (from the bottom half of the modal), but there is no way to close it.

### Steps To Reproduce:
1. Create new page with text module.
2. Logged in as admin, on page, select text within module that is at top of page.
3.  Try to change color.
4. Clicking within single line paragraph text moves the color picker appropriately, but no way to close it.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Desktop

**Operating System**: Windows 10

**Browser**: Current Chrome.

**Screen Resolution**:  HD 1920x1080

**Screenshots**:

http://divibeta.mizagorn.com/wp-content/uploads/2016/08/color-picker.jpg

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
This has been fixed in 3.0.5.
