### ISSUE TITLE
BlueHost :: Undefined in custom padding/margin fields

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#940]
### Steps To Reproduce:
1. Load the case study premade layout. 
2. Open the configuration panel of the first row.

![1](https://cloud.githubusercontent.com/assets/16414613/22735834/72e34dce-edf3-11e6-9b70-7a2977f971f4.png)

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1722

**Comment by timayhelen** [comment]
This applies to all "column padding" settings, which are found in the Design tab of all rows.
