### ISSUE TITLE
Dreamhost :: Builder Sync :: Placing divider in VB

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#941]
### Problem:

Placing a divider in VB generates Js errors resulting in unresponsive VB.

https://drive.google.com/open?id=0B8PjD3Z_XQvuckJLdVhmTVBQcFU

Closing the FB and updating the page in BB with the divider, prevent the FB to properly work, when activating the FB (while the divider is present in the layout) I get this:

![screen shot 2017-02-08 at 1 55 20 pm](https://cloud.githubusercontent.com/assets/1719735/22736350/5b47df28-ee06-11e6-84ee-b2a995c3a72a.png)

Removing the Divider from the layout, FB returns to normal:
![screen shot 2017-02-08 at 1 56 48 pm](https://cloud.githubusercontent.com/assets/1719735/22736367/7b703110-ee06-11e6-86c9-955f6bf82757.png)

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1724

**Comment by timayhelen** [comment]
I was also able to generate the following error after adjusting the Divider settings in the Visual Builder:

![screen shot 2017-02-08 at 5 10 37 pm](https://cloud.githubusercontent.com/assets/3333028/22764758/90b7ed4a-ee21-11e6-9c3c-b9f294f94421.png)

**Comment by eduard-ungureanu** [comment]
@timayhelen that's exactly what happens on my end!
