### ISSUE TITLE
Siteground :: Builder Sync :: Shop Module :: Only Shortcodes Are Visible

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#943]
### Problem:

Just add some Shop modules under BB. In FB I see only shortcodes.

![1artwork richard slechta - mozilla firefox](https://cloud.githubusercontent.com/assets/3352130/22736570/cad8112e-ee0f-11e6-9001-79317c79ab41.jpg)

Screen cast:
http://youtu.be/VElj9EgJ6dA?hd=1

Test page:
http://elegantthemessiteground.com/builder-sync-20/?et_fb=1

**Comment by timayhelen** [comment]
@kary4 Is WooCommerce installed and enabled? I don't think I installed it on the test server.
