### ISSUE TITLE
Dreamhost :: Builder Sync :: Gallery Module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#945]
### Problem:

Settings applied in the VB are not updated in the BB. Also there was a strange issue with Title Font styles (see video), while settings done in BB does update the settings in VB.

https://drive.google.com/open?id=0B8PjD3Z_XQvuaW9SenFGUC1XVEk

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1723

**Comment by kary4** [comment]
Same problem here:
http://youtu.be/-nlSVZhRl2M?hd=1

**Comment by fikrirasyid** [comment]
The PR above only fixes the "settings not applied on BB" issue. Related to the "strange issue with Title Font styles", we already has https://github.com/elegantthemes/submodule-builder/pull/1718 which overlaps with that issue. 

Essentially, "strange issue with Title Font styles" can be consistently replicated on `575-fix-heartbeat-content-smashing-wip` on any module by doing the following:

1. On VB, add CTA module and fill its content. Open the module's settings modal and style the title's font style with uppercase. Leave the settings modal opened
2. Go to admin bar, right click + open in new tab the edit page (open the BB)
3. Wait for a moment until the builder data is synced
4. On BB, open the CTA settings modal then style the title's font style with bold, italic, and underline (basically check all the font style option)
5. Go back to the VB tab, wait until the page done syncing
6. After being synced, now you can see that all font style buttons are checked. Clicking the font style button won't toggle the font style. The actual module is affected, but somehow the button aren't being toggled

What actually happens are:

1. On VB, Settings modal works by (sort of) cached module data. Basically when we open settings modal, we hold the module's object in a variable
2. When VB receives the synced data from BB and update its whole layout including the currently opened settings modal, it mutates the data and makes the currently opened data confused; which one is the currently opened module?
3. Essentially, the https://github.com/elegantthemes/submodule-builder/pull/1718.

https://github.com/elegantthemes/submodule-builder/pull/1718 fixes this issue by closing the settings modal if its module's data is technically mutated.

Thus, I think the  "strange issue with Title Font styles" issue belongs there, not here.
