### ISSUE TITLE
Siteground :: Builder Sync :: Loading Animation Never Disappears

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#946]
### Problem:

When I switch between two browser's tabs (FB/BB) w/o saving the changes the loading animation never disappears.

### Steps To Reproduce:
1.  Open two browser tabs (BB/VB). Everything should be saved. 
2. Activated VB > Add some changes. 
3. Click Edit Page > Discard the changes.
4. Activate BB tab.

Screen cast:
http://youtu.be/t9699wu0GvY?hd=1

Test page:
http://elegantthemessiteground.com/wp-admin/post.php?post=262&action=edit

**Comment by fikrirasyid** [comment]
@kary4 can you clear your browser cache and check this again? I've tried to replicate this multiple times but it appears to work as expected now:

![946-fixed](https://cloud.githubusercontent.com/assets/916442/23088279/a1562b7e-f5ad-11e6-9c77-2d0cfe60acfb.gif)

**Comment by kary4** [comment]
@fikrirasyid Yes, I cannot replicate this problem anymore.
