### ISSUE TITLE
Siteground :: Builder Sync :: Auto Saves :: Loading Animation When Switching Between Tabs

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#947]
### Problem:
Loading Animation starts on its own when you switch from VB to another tab (not wordpress, just any tab). This happens after Auto Save was Restored.

### Steps To Reproduce:
1.  Restore Auto-save version in VB.
2. Switch to another Tab.
3. Switch back to VB tab.

Screen cast:
http://youtu.be/Se5rK0FQIBk?hd=1

Test page:
http://elegantthemessiteground.com/builder-sync-25/?et_fb=1

**Comment by timayhelen** [comment]
@kary4 I can't seem to reproduce this. I have updated the shared host with the latest version of the builder sync branch. Can you test again and let me know if the problem is still there?

**Comment by kary4** [comment]
@timayhelen I cannot reproduce the problem anymore. I think the fix works.

**Comment by kary4** [comment]
@timayhelen I think I was able to reproduce similar issue just now:

- Screen cast:
http://youtu.be/559B_O-NkQ8?hd=1

- Test page:
http://elegantthemessiteground.com/wp-admin/post.php?post=469&action=edit

**Comment by fikrirasyid** [comment]
@kary4 can you clear your browser cache then try this again? I've tried it multiple times but it appears that it works as expected now. This is what occurs when I follow step by step you did on http://youtu.be/559B_O-NkQ8?hd=1:

![947-has-been-fixed](https://cloud.githubusercontent.com/assets/916442/23088059/aa623e26-f5ab-11e6-939b-94af8fc850d1.gif)

I re-tried them again, but it works as expected nonetheless:

![947-has-been-fixed-2](https://cloud.githubusercontent.com/assets/916442/23088073/bbde202a-f5ab-11e6-8a4b-5b1a3007a815.gif)

**Comment by kary4** [comment]
@fikrirasyid Cannot reproduce this anymore..
