### ISSUE TITLE
Siteground :: Auto Saves :: No Warning About Auto-save Version

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#948]
### Problem:

In a short, in some cases divi does not suggest to load saved version. It just loads the auto-saved version, even I did not save the last changes.

Screen cast:
http://youtu.be/bzQFo8zaWgA?hd=1

**Comment by timayhelen** [comment]
Currently we discard auto-saves if you leave the builder intentionally. So if you click to leave, and you accept the warning and choose to leave anyway, we assume that you really don't want to save.
