### ISSUE TITLE
Trashcan - "Are you sure?"

### ISSUE THREAD

**Issue by Mizagorn** [elegantthemes/Divi-Beta#95]
### Problem:

Trashcan icon is immediate with no confirmation (Yes? No?) or visible way to undo.

**Comment by timayhelen** [comment]
Thanks for the suggestion!. We are going to leave it the way it is for two reasons:

1. I think the constant "are you sure" will end up wasting time in the long run, especially once you are familiar with the visual builder.
2. The visual builder already has a comprehensive Undo/Redo system, so if you delete something by mistake you can just undo it via the History panel :) We will be adding hotkey support as well (Ctrl+Z) just like the backend builder.
