### ISSUE TITLE
Siteground :: Builder Sync :: BB Does Not Update

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#950]
### Problem:

When you work in VB and then open BB in another tab it does not update the info. 

To reproduce the problem:
1. Create a page > add a divi module > publish the page.
2. Open VB in the same tab > Add one more module.
3. Click Edit Page (open in a new tab). You will see only one module, though it should be two modules. 

More over, when you go back to VB in syncs with BB so your second module disappears.

Screen cast:
http://youtu.be/9lnltHeM-mI?hd=1

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1714

**Comment by timayhelen** [comment]
@kary4 I can't seem to reproduce this. I have updated the shared host with the latest version of the builder sync branch. Can you test again and let me know if the problem is still there?

**Comment by kary4** [comment]
@timayhelen Yes, it's still the same. I can reproduce it. Here is a new screen cast:
http://youtu.be/ImXw6DQ4t5g?hd=1
