### ISSUE TITLE
Dreamhost :: Builder Sync :: Image module

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#951]
### Problem:

Leaving the FB the image module doesn't show the image, inspecting the source code I get this:
```
<img src(unknown) alt="”City" title="”City">
```
![screen shot 2017-02-09 at 10 54 23 am](https://cloud.githubusercontent.com/assets/1719735/22775890/49f5b7da-eeb6-11e6-9761-eb0766e071ee.png)

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1739

**Comment by Jronk** [comment]
@eduard-ungureanu I'm unable to reproduce this, can you elaborate on what you meant by:
> Leaving the FB

Also, if you can do a screencast for it, that would be great thanks.

**Comment by eduard-ungureanu** [comment]
@Jronk please check out this page: 

http://www.elegantthemesdreamhost.com/divi-beta683-builder-button/

Scroll down until you will see 2 number counters and a map module, on the left it should be the image.

**Comment by Jronk** [comment]
Ok, I see the image on the page, and its lacking a src value, so my question is what is the problem? like "Did you enter a value in VB and it didnt save the src...", or what was the steps to get to this end result?

**Comment by eduard-ungureanu** [comment]
@Jronk - the image module is properly set, the problem is once I save the page, and leave the VB the image SRC is not updated.

Here is a video with the issue, hope it helps:
https://drive.google.com/open?id=0B8PjD3Z_XQvuc2ZQaVBMY3owZGs

**Comment by Jronk** [comment]
I have tried to reproduce what you are saying, and what your video shows...

Here are the steps I see from your above video:
1. open existing page to edit in BB
2. Click on "Use Visual Builder"
3. Open settings modal for image module, verify the url is present.
4. click green checkbox to close modal
5. open page settings bar, click save, wait for save to complete
6. click "Exit Visual Builder" in admin bar
7. Once page is loaded, img "src" is blank in rendered HTML


Here are my steps, shown in my attempts to reproduce (as shown in below gif): 
1. open existing page to edit in BB
2. Click on "Use Visual Builder"
3. Open settings modal for image module, verify the url is present.
4. click green checkbox to close modal
5. open page settings bar, click save, wait for save to complete
6. click "Exit Visual Builder" in admin bar
7. Once page is loaded, check img "src" in rendered HTML (not broken)
8. click "Enable Visual Builder", then re-check step 3 (still not broken)


![dreamhost -- builder sync -- image module 951](https://cloud.githubusercontent.com/assets/1163441/22993957/d1fa33b4-f379-11e6-9967-12293f2f7a06.gif)

**Comment by Jronk** [comment]
I am testing on latest branch: `575-fix-heartbeat-content-smashing-wip`. If you are still able to reproduce this according to the above steps I laid out, can you provide me with an export of your layout?

**Comment by Jronk** [comment]
I even tried adding the "tricky" (```”City```) alt and title you had from above, and that's not causing it to fail for me either... 
![screen shot 2017-02-15 at 1 35 09 pm](https://cloud.githubusercontent.com/assets/1163441/22996500/d8275136-f383-11e6-97ee-52eefca26e00.png)

**Comment by timayhelen** [comment]
@Jrok All of this testing is being done on our shared host testing environments. You can log in and see the issue first hand instead of trying to replicate it:

https://github.com/elegantthemes/Divi/wiki/Shared-Hosting-Testing

## DreamHost

#### WordPress
* Login: http://elegantthemesdreamhost.com/wp-login.php
* Username: elegantthemesdreamhost_v2oepg
* Password: y(YbhaJCe@7L1p5t

http://www.elegantthemesdreamhost.com/divi-beta683-builder-button/

**Comment by timayhelen** [comment]
Here is the shortcode output of the broken module:

`[et_pb_section bb_built="1" admin_label="section"][et_pb_row admin_label="row" make_fullwidth="on"][et_pb_column type="1_3"][et_pb_image admin_label="Image" src="http://www.elegantthemesdreamhost.com/wp-content/uploads/skyline.jpg" alt="City of Light" title_text="City of Light" show_in_lightbox="on" use_overlay="on" overlay_icon_color="#ffffff" hover_overlay_color="rgba(131,0,233,0.54)" hover_icon="["] [/et_pb_image][/et_pb_column][et_pb_column type="1_3"][et_pb_number_counter admin_label="Number Counter" title="Hours worked" number="300" percent_sign="off" counter_color="#8300e9" title_font="Nunito|on||on|" title_font_size="31px" title_text_color="#8300e9" title_letter_spacing="2px" title_line_height="1.2em" number_font="Nunito|on|||" number_font_size="100px" number_text_color="#e09900" number_letter_spacing="32px" background_color="#f4f4f4" use_border_color="on" custom_padding="40px|0px|40px|0px"] [/et_pb_number_counter][et_pb_number_counter admin_label="Number Counter" title="Black Coffees" number="520" percent_sign="off" counter_color="#8300e9" title_font="Nunito|on||on|" title_font_size="31px" title_text_color="#8300e9" title_letter_spacing="2px" title_line_height="1.2em" number_font="Nunito|on|||" number_font_size="100px" number_text_color="#e09900" number_letter_spacing="32px" background_color="#f4f4f4" use_border_color="on" custom_padding="40px|0px|40px|0px"] [/et_pb_number_counter][/et_pb_column][et_pb_column type="1_3"][et_pb_map admin_label="Map" address="New York, NY, USA" zoom_level="17" address_lat="40.7128889120375" address_lng="-74.00643214424976"] [et_pb_map_pin title="our hq" pin_address="New York, NY, USA" pin_address_lat="40.7127837" pin_address_lng="-74.00594130000002"] Nullam tincidunt adipiscing enim. Curabitur at lacus ac velit ornare lobortis. Maecenas nec odio et ante tincidunt tempus. Donec posuere vulputate arcu. Quisque ut nisi. Pellentesque posuere. Nullam cursus lacinia erat. Vivamus quis mi. [/et_pb_map_pin] [/et_pb_map][/et_pb_column][/et_pb_row][/et_pb_section]`

**Comment by Jronk** [comment]
yeah, thanks @timayhelen don't know why I didn't notice this was one of the new shared servers (it was in the issue title i see..)

**Comment by lots0logs** [comment]
@Jronk After enabling the overlay for the image module in the VB I get this:

![2017-02-17_03-01-17-pm](https://cloud.githubusercontent.com/assets/4675662/23083143/109f1f0e-f522-11e6-8c91-f6ec0b76e010.png)

**Comment by Jronk** [comment]
@lots0logs Error has been fixed, thx
