### ISSUE TITLE
Dreamhost :: Builder Sync :: Divi Builder Time out.

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#952]
### Problem:

Out of the blue the FB shows Divi Builder Time out, previously the same page layout worked without any issue, while today is not:

![screen shot 2017-02-09 at 11 01 30 am](https://cloud.githubusercontent.com/assets/1719735/22776146/3fc41e18-eeb7-11e6-91b1-e456a6d53c2a.png)

Also leaving the FB doesn't show the map module (API key was correctly set for this domain):
![screen shot 2017-02-09 at 11 03 20 am](https://cloud.githubusercontent.com/assets/1719735/22776189/6507a7e4-eeb7-11e6-9521-64b1a351cb6d.png)

Removing the map module from the page layout (in BB), the FB starts to work again.

You can find the full layout with the map module, added in Divi Library called FB Builder Times out.

Removing the map module in BB and adding it again with the same exact address, looks like it did fix the issue with Builder Time out. Strange.

**Comment by fikrirasyid** [comment]
@eduard-ungureanu can you clear your browser cache and try it again? I've uploaded the latest update of builder sync branch and attempted to replicate the issue but it appears to work as expected.
