### ISSUE TITLE
Auto saves feature works differently under BB and VB

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#954]
### Problem:

Auto saves feature works differently under BB and VB. Potentially this may cause data loss.
In a short: 
     - BB does not suggest Auto saved copy if you click to leave, and you accept the warning and choose to leave anyway. It sounds logical.
    - However, VB suggests Auto saved version all the time. No matter if you ou accept the warning and choose to leave anyway.

Please check the following screen cast to see what exactly I mean:
http://youtu.be/Wf0DlBgEi7c?hd=1

**Comment by eduard-ungureanu** [comment]
I have a slightly different issue with the BB on Dreamhost - I get the message, but nothing is loading.

https://github.com/elegantthemes/Divi-Beta/issues/957
