### ISSUE TITLE
BlueHost :: Shortcode Trimming :: Issues with adding padding

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#956]
### Problem:

I don't see the results as they should appear on the VB. The front end works okay, and when you reload the VB page you also see the padding applied correctly, it's just not when you add it live:

![94](https://cloud.githubusercontent.com/assets/16414613/22790376/e5bfa67c-eedd-11e6-92bf-971f6581ddd5.gif)

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1715

**Comment by eduard-ungureanu** [comment]
Same thing on dreamhost

**Comment by timayhelen** [comment]
@lots0logs I think this is related to the recent slider change.

**Comment by lots0logs** [comment]
@timayhelen I can't reproduce this on latest master. Can you?

**Comment by timayhelen** [comment]
@lots0logs Yeah it happened to me. It has to do with the slider not adjusting it's height after the size of the slide changes due to the padding adjustments. The padding changes I think, but the slider's height applied via JS does not update.

**Comment by lots0logs** [comment]
@timayhelen Hmm..I followed the exact steps shown in the screencast and the issue does not occur. The slider renders as it should with proper padding. :thinking: I'll look into it further...

**Comment by FaycalBoutam** [comment]
There's a problem with the fullwidth post slider module as well. The standard post slider module works fine from my end.

**Comment by lots0logs** [comment]
Looks like it only occurs on the production `bundle.js`. Still looking into it...
