### ISSUE TITLE
Dreamhost :: Failed Save Warning :: Doesn't give the .json file

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#958]
### Problem:

Renaming the admin-ajax.php will cause the save process to fail, and the pop-up which give the option to save the layout appears, but clicking on Download Layout doesn't provide the `.json` file, tried in Chrome, Safari and Firefox.

https://drive.google.com/open?id=0B8PjD3Z_XQvuaUE2YzVlcXRreE0

**Comment by timayhelen** [comment]
This is a duplicate issue.
