### ISSUE TITLE
Question: Will I lose everything if I have no internet connection?

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#959]
### Problem:
I'm not sure how it's supposed to be working. Let's say I'm working in two tabs (BB and VB) for 30 minutes. Then I suddenly lost my internet connection. This means I can't close my tabs, because I'll be forced to discard all the changes I made. Then when I restore my internet connection I cannot restore my work progress (because a left the tabs before and accepted the warning). If I understand correctly there is no way at all to get my last saved copy. Or am I missing something?

**Comment by timayhelen** [comment]
@kary4 Ideally when you try to save, you would get the failure modal with an option to download a backup copy. Also, if your internet was intermittent then there will still be auto-saves. These are not discarded when you leave the builder via the JS warning prompt.
