### ISSUE TITLE
Provide hover (alt or hint) text on icons

### ISSUE THREAD

**Issue by Mizagorn** [elegantthemes/Divi-Beta#96]
That's about all.

In other words, when you hover over an icon, there is no hint as to what it will actually do (except for the icon itself).  This is what I would consider a great way to reduce support requests.

**Comment by timayhelen** [comment]
Thanks for the suggestion! We already have a ticket open for this, so I am going to close this one to avoid the duplicate. We are hoping to add tooltips to all buttons before release, but it may need to wait until 3.1. We will get it done though!
