### ISSUE TITLE
Question :: Should the module settings values be updated while module settings window is open in VB

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#960]
### Problem:

I've noticed the module css properties values are updated even module settings window is opened. However don't see the same on Design tab. I've tested the Blurb Module. If I reopen module settings window the settings are updated.

**Comment by timayhelen** [comment]
@dm-chechik Can you post a video of what you are referring to exactly?

**Comment by dm-chechik** [comment]
@timayhelen Please check the video. I've assigned CSS ID and CSS Class and they apeared in VB directly in the opened midule settings window.
http://screencast-o-matic.com/watch/cbnXFn6ixr
Is it normal behavior? I've noticed that sometimes it works sometimes not.

**Comment by timayhelen** [comment]
I see. This will actually no longer be relevant after Fikri's recent branch is merged that closes settings modal during sync.
