### ISSUE TITLE
BlueHost :: Builder Sync :: Blurb Module :: center / left orientation issue

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#961]
### Problem:

Text default orientation of the blurb module is different in VB (centered) and BB (left) which can cause a problem with syncing :

https://www.dropbox.com/s/0b647o4t3ufy0hi/95.gif?dl=0

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1732

**Comment by timayhelen** [comment]
Let's update the VB and change the Blurb default orientation to Left, like it is in the BB.
