### ISSUE TITLE
VB :: Inline Editor :: Creating Lists (<ul>) Is Buggy

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#964]
### Problem:

![2017-02-09 20-13](https://cloud.githubusercontent.com/assets/4675662/22811479/a6d09eb8-ef04-11e6-82ca-bede2f7dea17.gif)

## Attached PR 
- https://github.com/elegantthemes/submodule-builder/pull/1793

**Comment by fikrirasyid** [comment]
@SlavaET can you take a look at https://github.com/elegantthemes/submodule-builder/pull/1793? I think this one is a missing edge case of https://github.com/elegantthemes/Divi-Beta/issues/816 that you worked on previously.
