### ISSUE TITLE
GoDaddy :: Builder Sync :: Empty Section/Row sync not working

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#966]
### Problem:

I've noticed this trying to add Specialty Section however this occurs even with standard section
![screen](https://cloud.githubusercontent.com/assets/20072036/22856297/8abe0886-f09f-11e6-9447-f0e8533ca0ec.gif)

## Attached PRs
- https://github.com/elegantthemes/submodule-builder/pull/1728

**Comment by dm-chechik** [comment]
Another case with adding an empty row inside existing section.
![screen](https://cloud.githubusercontent.com/assets/20072036/22856337/61a60380-f0a0-11e6-9aa2-5ad5a1e99a5f.gif)

**Comment by fikrirasyid** [comment]
@dm-chechik can you clear your cache then try it again? It appears that the issue has been fixed on the latest version of the branch:

![966-fixed](https://cloud.githubusercontent.com/assets/916442/22959491/67fde5c4-f369-11e6-8096-364f42abda34.gif)

**Comment by timayhelen** [comment]
@fikrirasyid You need to create an empty row in the BB, which means a row with no columns in it. This will fail to sync correctly to the VB, causing various issues. 

1. Open up the VB and BB in two tabs. 
2. In the BB, click "Add Row"
3. Do not add a column. Just click the "x" button to close the modal.
4. You now have a row with no columns. Switch to the VB to see some strange effects. Sometimes rows around the empty row get deleted somehow. 

 (you can also click the X on the last row in a section to create an empty row)

![empty-row](https://cloud.githubusercontent.com/assets/3333028/23007993/32c77066-f3c1-11e6-9f5d-21871d84ae3b.gif)

**Comment by fikrirasyid** [comment]
@timayhelen thanks for the reproduction steps. I'm able to replicate and fix the issue at https://github.com/elegantthemes/submodule-builder/pull/1728.
