### ISSUE TITLE
GoDaddy :: Builder Sync :: Saving module as global is not syncing properly

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#967]
### Problem:

After saving module as global in BB the module does not appear as global in VB.
![screen](https://cloud.githubusercontent.com/assets/20072036/22856520/edaf90be-f0a3-11e6-8a0b-2cd7505fd769.gif)

**Comment by dm-chechik** [comment]
It seems the issue related to incorrect displaying of Global Module in VB.

**Comment by fikrirasyid** [comment]
@dm-chechik can you clear your browser cache and retest this again? I've tried multiple times to replicate the issue but it appears to work as expected (probably newer PRs fix this issue):

![967-fixed](https://cloud.githubusercontent.com/assets/916442/23066394/f6978422-f54c-11e6-8d85-2fd7430d5add.gif)

**Comment by fikrirasyid** [comment]
I notice that in latest `575-fix-heartbeat-content-smashing-wip` branch whenever a module is set as global in BB and being synced to VB, the text orientation disappears. I submitted https://github.com/elegantthemes/Divi-Beta/issues/989 for it.
