### ISSUE TITLE
GoDaddy :: Builder Sync :: Handling of session expiration

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#968]
### Problem:

I think we need to add a notice dialog of session expiration in VB editor. Right now on backend side when session expires the modal login dialog appears. I understand this is standard Wordpress feature however on frontend in VB editor there is no way to know the session has expired I just see infinite loading icon.

Just in case to check how it works now you can install [WP Login Timeout Settings](https://wordpress.org/plugins/wp-login-timeout-settings/) plugin and set timeout say to 2 minutes.

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1738

**Comment by dm-chechik** [comment]
While doing several test I've noticed the bugs related to losing content in BB editor.
When session expires the WP modal login form appears and after successful authorization the BB allows to continue editing the page however if I'll try to save the page the login page appears again and all changes are lost. The restore from backup option does not work too. Seems it stops saving after session expires.

**Comment by timayhelen** [comment]
@lots0logs After your session expires and you log back in, you can't save the builder. Subsequent saves all fail.

**Comment by lots0logs** [comment]
![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/23099314/2ce6d078-f629-11e6-8d86-ada37c652bcc.gif)

**Comment by timayhelen** [comment]
@Jronk since this deals with nonces and saving I would suggest extra scrutiny during Dev Review. Thanks!
