### ISSUE TITLE
Everything freezes

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#969]
### Problem:

In some situations BB freezes. I'm not exactly sure after which step this happens but if you follow the steps you can see in the screen cast below you'll understand what I mean.
http://youtu.be/ks27leQFBp4?hd=1

**Comment by VladET** [comment]
I got a very similar problem and I believe it has something to do with this error in the console.

<img width="827" alt="capture-1" src="https://cloud.githubusercontent.com/assets/1061516/22876296/b328ae04-f1d8-11e6-84a4-72d333327976.PNG">

<img width="1576" alt="capture-2" src="https://cloud.githubusercontent.com/assets/1061516/22876325/dcf6d454-f1d8-11e6-873d-914a2a2fc335.PNG">

**Comment by fikrirasyid** [comment]
This has been address on https://github.com/elegantthemes/submodule-builder/pull/1718. This is essentially what happened on https://github.com/elegantthemes/Divi-Beta/issues/945#issuecomment-280022610, but reversed on VB to BB. Please read the thorough explanation on https://github.com/elegantthemes/submodule-builder/pull/1718 PR description for complete explanation related to the issue.
