### ISSUE TITLE
Divi Update Failed.. Can't get Beta

### ISSUE THREAD

**Issue by NoHashKang** [elegantthemes/Divi-Beta#97]
### Problem:

I do everything necessary... Install Divi, the BETA plugin activation, authenticate my account through Divi Upgrade. I get a "New Update is Available" over the Divi theme when I go to update it says 
Update Failed: The theme is the latest version. The Divi Theme is v. 2.7.10.. I know I need 2.9
### Steps To Reproduce:
1. Download Divi
2. Download Divi Beta Activate Plugin
3. Authenticate
4. Install Everything
5. Click Update it fails

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
Hackintosh PC
i7 3770k
8GB Ram
GTX 970
3x 1440p monitors
**Operating System**:
Mac OS X 10.11.6 (15G31)
**Browser**:
Safari, Firefox Developer, Vivaldi
**Screen Resolution**:
2560 x 1440p
**Screenshots**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by timayhelen** [comment]
This just means that the update notification is cached. You have successfully updated, so feel free to start testing :)

**Comment by NoHashKang** [comment]
Hello, 

 Thanks for the fast reply, but it is still just the old Divi Builder. Don't get me wrong, I love that builder, but I want to test out the Front End one, am I doing something wrong? Do you access the Front End builder another way? It is not working for me

**Comment by NoHashKang** [comment]
![screen shot 2016-08-19 at 4 21 59 am](https://cloud.githubusercontent.com/assets/17282939/17803450/7fcc5f1a-65c4-11e6-9007-2cbd0ff496f5.png)

**Comment by Bhuvan937** [comment]
Hey there! I am facing the same problem ,my current Divi Beta Version is 2.9.9 But I really want to upgrade it to 2.9.12 and it does the same thing and I still have same old Beta Version 2.9.9.

![screen shot 2016-08-25 at 2 16 26 pm copy](https://cloud.githubusercontent.com/assets/21140201/17963296/831967cc-6ad2-11e6-8092-f0826a3c0df4.png)
