### ISSUE TITLE
Everything disappears in VB

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#971]
### Problem:

I still cannot understand what exactly you should do to reproduce the problem. Maybe it's necessary to add a global module or just save a global module, still trying to catch the exact steps. The problem is that after I go to another browser window (not another tab) and go back later nothing appears in VB.

Screen cast:
http://youtu.be/w02LJj4hDxc?hd=1

Test page:
http://elegantthemessiteground.com/page-21/?et_fb=1

Updated: It seems no matter if you use global modules or not. It just takes some time (1-5 minutes) to see the problem.

**Comment by fikrirasyid** [comment]
@kary4 can you clear your browser cache and try replicate the issue again on http://elegantthemessiteground.com/? I've updated the theme to the latest version of the builder sync branch, trying to replicate the issue but it works as expected so far.

**Comment by kary4** [comment]
@fikrirasyid Actually I was able to get similar problem once, but I have no idea how I can replicate this again :( I'll update you if I'll find out the exact steps.
