### ISSUE TITLE
Builder Sync :: Slider : Settings UI becomes unresponsive

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#973]
### Problem:

If you leave the settings modal opened in VB and go back to BB, change a setting then go back to VB the settings modal interface becomes unresponsive. 

http://screencast-o-matic.com/watch/cbnIQD6j5v

**Comment by fikrirasyid** [comment]
I think this is duplicate of https://github.com/elegantthemes/Divi-Beta/issues/974 which has been addressed on https://github.com/elegantthemes/submodule-builder/pull/1718
