### ISSUE TITLE
Builder Sync :: VB settings modal remains opened when the module has been removed from BB

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#974]
### Steps To Reproduce:

1.  Add a module in VB or BB
2. Open the module settings in VB and leave it opened
3. Go to BB and delete the module
4. Go back to VB, the settings modal is still there and you can't close it if you click X, it works if you hit ESC key.

Screencast: http://screencast-o-matic.com/watch/cbnIQw6j57

Not a big deal but maybe the modal should be destroyed if the module is removed.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1718

**Comment by fikrirasyid** [comment]
> Not a big deal but maybe the modal should be destroyed if the module is removed.

It turns out that this is a pretty big deal 😅 Please see linked issues on https://github.com/elegantthemes/submodule-builder/pull/1718

**Comment by VladET** [comment]
If you put it that way 😅
