### ISSUE TITLE
Question :: What Should Happen If You Save VB Page And Refresh The Page (Ctrl+F5)

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#977]
### Problem:

Builder Sync stops working once you save VB page and clear your browser's cache by refreshing the page (Ctrl + F5). So, in this situation you'll have two different versions of builder layout in BB and VB.

Screen cast:
http://youtu.be/xo6a5oJ55mA?hd=1

Though, it starts updating once you add some changes after refreshing the page.

**Comment by timayhelen** [comment]
I think this is such a rare occurrence that we don't need to worry about right now.
