### ISSUE TITLE
1&1 :: Builder Sync :: VB Does Not Work When You Create A New Page

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#979]
### Problem:

So, when you:
1. Create a page;
2. Activate Divi Builder;
3. Open Visual Builder in a new tab you can see VB is disabled, so it allows you to enable VB.

And related problem:
If you go back to BB, save the page, go back to VB - still nothing synchronized, even you click Enable VB. You have to refresh the page.
Screen cast:
http://youtu.be/UYEtqW2aSGs?hd=1

In another testing site it behaves differently. It just pops up Timeout Error message. More info here:
https://github.com/elegantthemes/Divi-Beta/issues/923

**Comment by fikrirasyid** [comment]
This issue has been fixed at https://github.com/elegantthemes/submodule-builder/pull/1703. Specifically on this commit: https://github.com/elegantthemes/submodule-builder/pull/1703/commits/adfab7de575da3a3b9c54989a74d5594075e81b6
