### ISSUE TITLE
Alignment issue - Divi builder title in RTL algined sited

### ISSUE THREAD

**Issue by yburshan** [elegantthemes/Divi-Beta#98]
### Problem:

Working in RTL site (Hebrew), the alignment of the Divi header title is off.

### Steps To Reproduce:
1.Create new post or page
2.select "Use Divi builder"

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: Macbook

**Operating System**: Win10 ENT

**Browser**: FF 48.0

**Screen Resolution**:

**Screenshots**:
![1 header-align-rtl](https://cloud.githubusercontent.com/assets/21120198/17803411/f9d11762-65fe-11e6-85e3-9b19ed0c9f80.png)
-

**Comment by lots0logs** [comment]
Thanks for the report. We're focusing exclusively on the VIsual Editor for this beta but I'll add this issue to our Divi repo so we can address it during the next round of bug fixes :smiley:

**Comment by lots0logs** [comment]
Issue moved to [elegantthemes/Divi #2508](https://github.com/elegantthemes/Divi/issues/2508) via [**ZenHub**](https://www.zenhub.com/)
