### ISSUE TITLE
Question :: Auto Saves :: You Lose Everything If You Accidentally Click Out Of Backup Exists Box

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#985]
### Problem:

Is it supposed that you can click out of the "A Browser Backup Exists" popup window and it disappears? In this case you cannot restore anything after you accidentally click some empty area. In my understanding you should not be able to proceed if you don't click one of the three options (Discard/Restore/Close).

Screen cast:
http://youtu.be/CkWRgNdQCNc?hd=1

**Comment by timayhelen** [comment]
I think it's ok for now.
