### ISSUE TITLE
Siteground :: No Way To Add Row In VB To The First Section

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#992]
### Problem:

When you try to add a row to the very fist section it created another row right below the first one. To see what I exactly mean please check the screen caste here:
http://youtu.be/DEZa2toTzqA?hd=1

### Steps To Reproduce:
1.  Create New Page > Enable VB > Save the page;
2. Open BV in a new Browser Tab and try to add a row in the first section.

### Additional Information:
This happens under Siteground but works good under 1 & 1 (Not sure maybe those are different Builder versions).

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1747

**Comment by fikrirasyid** [comment]
Note: this isn't hosting specific issue, it appears on my local test site as well.

**Comment by lots0logs** [comment]
@fikrirasyid The button's tooltip still says "Add New Row". That is going to be confusing to users. Let's change it to say "Choose Column Structure" instead.

**Comment by timayhelen** [comment]
@lots0logs Let's open a new ticket, I don't want the release getting held back for it.
