### ISSUE TITLE
Divi Builder Sync :: Synced content getting reverted back to last saved content

### ISSUE THREAD

**Issue by Jronk** [elegantthemes/Divi-Beta#997]
### Steps To Reproduce:
1. Pages > Add New
2. Enable the Divi Builder
3. Publish the blank page.
4. After publishing, right click “Use Visual Builder” and open it in a new tab.
5. You now have two tabs open with the blank page.
6. Go back to the BB and load the Homepage Basic layout.
7. Head over the VB tab to watch it sync.
8. Go back the BB and delete a blurb.
9 Go back to the VB and watch it sync.
10. Put a different app into focus, so you can see the VB in the background, and within about 30 seconds the content will revert back to last saved

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1749

**Comment by timayhelen** [comment]
@Jronk This causes all builders syncs from the VB -> BB to fail.
